### ISSUE TITLE
Enhance PD Upgrader

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#1015]
## Feature Request

**Describe the feature you'd like:**

There will be at most 2 times for PD leader transferation during its upgrading.
For example, if there are 3 replicas for PD and the pd-2 was their leader. It would be first leader transferation for PD-0 becoming leader and second leader transferation for pd-2 becoming leader.

Maybe we could enhance this progress which make this will only have 1 leader transferation at most.

**Comment by yylt** [comment]
Hi , are you sure The leader will be  transfered by 0 - 1 order ? 

I think when the pd-2 was their leader, The leader will be  transfered by 0 - 2 order , and i am confuesed how to make 1 transferation when the leader is pd-2

https://github.com/pingcap/tidb-operator/blob/932cc822fa098cd6c70f0460e0520623e61a952f/pkg/manager/member/pd_upgrader.go#L104

**Comment by Yisaer** [comment]
> Hi , are you sure The leader will be transfered by 0 - 1 order ?
> 
> I think when the pd-2 was their leader, The leader will be transfered by 0 - 2 order , and i am confuesed how to make 1 transferation when the leader is pd-2
> 
> https://github.com/pingcap/tidb-operator/blob/932cc822fa098cd6c70f0460e0520623e61a952f/pkg/manager/member/pd_upgrader.go#L104

You are right. The PD leader would only transferred from pd-0 to pd-2 or vice verse.
