### ISSUE TITLE
Google Cloud Shell tools may be out of date

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb-operator#102]
It might make sense to add the following command to the start of the GKE tutorial:

```
sudo gcloud components update
```

In my case this updated me from `kubectl` 1.9.7 to 1.10.7.  I didn't realize updates were available.

**Comment by tennix** [comment]
Maybe we can set k8s version when creating GKE cluster to meet our requirement.

**Comment by weekface** [comment]
can we close this issue now? @morgo @tennix
