### ISSUE TITLE
upgrade k8s code to 1.16

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#1020]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Keep up to date with the latest k8s code.

- compatibility is guaranteed by CI and stability tests (tested in k8s 1.12.x), in the future, we can add more test jobs for other Kubernetes versions (https://github.com/pingcap/tidb-operator/issues/1008)
- latest k8s e2e framework (k8s.io/kubernetes/test/e2e/framework) is well designed and can be reused in projects outside of core Kubernetes, we can leverage this framework to write our e2e tests
- easier to adopt libraries which depends on newer k8s code

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by cofyc** [comment]
- [ ] rename pingcap.com to pingcap (https://github.com/pingcap/tidb-operator/pull/1061)
  - the higher version of code-generator will use the name of this directory as the package name, so the domain cannot be used

**Comment by yylt** [comment]
the `pingcap/pd ` not use go mod manage module at v2.1.0-beta+incompatible 
pd use etcd@v0.0.0-20180530235116-2b3aa7e1d49d， but k8s@1.16 use etcd@v3.3.15 , it will conflict

**Comment by cofyc** [comment]
yes, it's a problem, we need to upgrade PD

**Comment by gregwebs** [comment]
PD should not be required to align dependencies with k8s, particularly one like etcd. We just need to reference some API code that should be abstracted over PD.
I think the problem is that we are referencing a PD package that imports many things. Instead the PD API definitions should be moved to a package with minimal dependencies.

**Comment by cofyc** [comment]
> I think the problem is that we are referencing a PD package that imports many things. Instead the PD API definitions should be moved to a package with minimal dependencies.

yes, that will be better

**Comment by aylei** [comment]
> I think the problem is that we are referencing a PD package that imports many things. Instead the PD API definitions should be moved to a package with minimal dependencies.

@gregwebs I'm working on proposing this to PD and TiDB.

@cofyc Because it takes time for PD to merge the change and release a new version, I've copied the config type definition and get rid of the `pd/server` dependency for now in #1048
