### ISSUE TITLE
Add imagePullPolicy support

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#103]
User should be able to customize the `imagePullPolicy` for every containers in operator. 

So we should add a related `imagePullPolicy` option for every `image`s in `charts/tidb-cluster/values.yaml`

**Comment by gregwebs** [comment]
I am starting to think we may want to just set it to Always. I said it was bad practice in production. However, not setting it to Always means you are relying on local docker image caching, so there is no real guarantee that you won't end up pulling a newer version of a tag once you don't have the cache somewhere. If we really want to peg an exact version we can use a digest.
