### ISSUE TITLE
Tidb-controller-manager state always CrashLoopBackOff

### ISSUE THREAD

**Issue by wangsheng123** [pingcap/tidb-operator#1034]
Tidb-controller-manage cannot start after tidb-operator is started

Kubernetes version 1.6

Tidb - operator version 1.0.1

**Comment by weekface** [comment]
@wangsheng123 What is the log output of the `tidb-controller-manager` pod?

**Comment by wangsheng123** [comment]
> @ wangsheng123`tidb-controller-manager` pod 的日志输出是什么？

Re-pull tidb-operator and run again without a problem
