### ISSUE TITLE
add dependencies chart  `local-storage` into tidb-cluster chart

### ISSUE THREAD

**Issue by yylt** [pingcap/tidb-operator#1050]
## Question

default value of storageClassName is local-storage in tidb-cluster, so should we add local-storage chart as dependencies?

local-stroage chart: 
[https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume/helm](url)

**Comment by aylei** [comment]
ping @cofyc @Yisaer

**Comment by Yisaer** [comment]
As `local-storage` is necessasy for `Operator` only in `prod`, I think there is no need to add `local-storage` as dependencies currently.

**Comment by tennix** [comment]
https://github.com/pingcap/tidb-operator/issues/1111 We will remove the local storage class name to make tidb-cluster able to deploy in any environment which has a default PV provider.

**Comment by aylei** [comment]
closed in favor of #1111 
feel free to reopen this if there is more discussions @yylt
