### ISSUE TITLE
tidb-controller-manager failed to list *v1beta1.StatefulSet because of kubernetes version changed 

### ISSUE THREAD

**Issue by XiaYinchang** [pingcap/tidb-operator#1063]
## Bug Report

**What version of Kubernetes are you using?**
v1.16.2

**What version of TiDB Operator are you using?**
v1.0.1

**What did you do?**
try to create a tidb-cluster

**What did you expect to see?**
tidb-cluster is ready

**What did you see instead?**
tidb-controller-manager outputs errors in log as following 
`# kubectl logs tidb-controller-manager-65f67db64d-zv6r5 -n storage-system --tail 10
E1028 13:01:40.569238       1 reflector.go:134] pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:95: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1028 13:01:41.571485       1 reflector.go:134] pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:95: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1028 13:01:42.573618       1 reflector.go:134] pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:95: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1028 13:01:43.575632       1 reflector.go:134] pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:95: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1028 13:01:44.577591       1 reflector.go:134] pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:95: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1028 13:01:45.579948       1 reflector.go:134] pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:95: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1028 13:01:46.582130       1 reflector.go:134] pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:95: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1028 13:01:47.584081       1 reflector.go:134] pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:95: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1028 13:01:48.586078       1 reflector.go:134] pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:95: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1028 13:01:49.588595       1 reflector.go:134] pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible/tools/cache/reflector.go:95: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
`

**The Problem**
The problem is obvious, the client-go package (version v2.0.0-alpha.0.0.20190115164855-701b91367003) used by tidb-operator is too old. 
From Kubernetes v1.16.2 , you can not find deployment and statefulset in apps/v1beta or extensions/v1beta any more and they are now can only be found in apps/v1. The client-go version should be upgraded or  just try to use apps/v1 instead of apps/v1beta and extensions/v1beta.

**Comment by tennix** [comment]
@XiaYinchang This is already fixed in https://github.com/pingcap/tidb-operator/pull/1012. And we'll release a new version soon to include this fix.

**Comment by XiaYinchang** [comment]
> @XiaYinchang This is already fixed in #1012. And we'll release a new version soon to include this fix.

OK. Thank you! Then this issue should be closed. Refer to #996, and fixed in #1012.
