### ISSUE TITLE
Install version-locked binaries in a sub-directory of the repo

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#1074]
## Feature Request

**Is your feature request related to a problem? Please describe:**

- do not touch global binaries on the local machine (e.g. developer may require bin@v2 globally, but we require bin@v1)
- deliver consistent behavior

**Describe the feature you'd like:**

Install version-locked binaries in a sub-directory of the repo, e.g. $ROOT/output/bin.

**Describe alternatives you've considered:**

install in the temporary path, but we need to install on every run

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by aylei** [comment]
What is this for? IIRC, all make targets install the output binaries in the repo path.

**Comment by cofyc** [comment]
external binaries, terraform/kind, code-generator/cmd/... binaries, etc.

**Comment by cofyc** [comment]
closed via https://github.com/pingcap/tidb-operator/pull/1144
