### ISSUE TITLE
Make default configuration installable on most platforms

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#1111]
## Feature Request

Currently, the default tidb cluster configuration is for "half-production". This makes it difficult to deploy for the first time, but also not production-ready configuration. Users have to tune the parameters in the default `values.yaml` to make it production-ready.

To overcome this dilemma, we should make the default installation available for most platforms including `minikube` and `kind`. So users can have a real quick-start experience using tidb-operator. As for production deployment, we can provide a detailed guide about the best practice and how to adjust parameters to make TiDB cluster both secure, stable and performant.

**Comment by tennix** [comment]
Managed platforms like GKE, EKS, minikube, kind all enables `DefaultStorageClass` admission controller to set a default storage class when a PVC does not specify a storage class.
ref: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaultstorageclass

**Comment by aylei** [comment]
ref: https://github.com/pingcap/tidb-operator/issues/700

**Comment by aylei** [comment]
This should be included in 1.1

**Comment by cofyc** [comment]
this will be addressed by https://github.com/pingcap/tidb-operator/issues/1111 and https://github.com/pingcap/tidb-operator/issues/1449.
and we should have an e2e job to verify it in one node cluster started by minkube or kind

**Comment by cofyc** [comment]
I'm going to add some basic e2e tests in Github Actions.
