### ISSUE TITLE
Transfer PD leader before deleting member during PD scaling in

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#1112]
Currently, during scaling in PD, tidb-operator just deletes member directly, however, if the PD being scaled in is leader, it should transfer leader first.

**Comment by DanielZhangQD** [comment]
Will be fixed by https://github.com/pingcap/tidb-operator/pull/1114

**Comment by Yisaer** [comment]
This also shoud be fixed in Operator. https://github.com/pingcap/tidb-operator/pull/1114 only fix it in webhook server.

**Comment by Yisaer** [comment]
fix in https://github.com/pingcap/tidb-operator/pull/1151
