### ISSUE TITLE
Transfer region leader before deleting store during TiKV scaling in

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#1113]
Currently, during TiKV scaling in, tidb-operator calls DeleteStore interface directly, however, it should evict region leader before calling DeleteStore.

**Comment by tennix** [comment]
Are TiKV leaders got evicted during offline? If not, I think it's better to do this in TiKV itself?

**Comment by DanielZhangQD** [comment]
Per discussion with TiKV dev, DeleteStore does not evict leaders.
Yes, it's better to do this in TiKV core, we can check with them.

**Comment by DanielZhangQD** [comment]
Confirmed with TiKV dev team again, DeleteStore will evict leaders automatically, close this issue.
