### ISSUE TITLE
terraform: support re-using an existing k8s cluster

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#1120]
## Feature Request

A user requested to be able to re-use an existing k8s cluster (and add new node pools). Outside of GKE, re-using an existing k8s cluster saves on cost.

Our terraform has a variable to use an existing VPC. However, our documentation states that this does not work.

https://pingcap.com/docs/v3.0/tidb-in-kubernetes/deploy/aws-eks/ indicates “Reusing VPC and subnets of an existing EKS cluster is not supported yet due to limitations of AWS and Terraform, so only change this option if you have to use a manually created VPC”

**Comment by aylei** [comment]
What are the costs saved? IIRC, VPC itself is free.

**Comment by gregwebs** [comment]
sorry for the poor description. It is really about re-using an existing K8s cluster.

**Comment by gregwebs** [comment]
A user is hacking at re-using their k8s cluster: https://github.com/mightyguava/tidb-operator/commit/d057339707a12a5537932c0f1aad1b5fcc880e1f

**Comment by aylei** [comment]
> https://pingcap.com/docs/v3.0/tidb-in-kubernetes/deploy/aws-eks/ indicates “Reusing VPC and subnets of an existing EKS cluster is not supported yet due to limitations of AWS and Terraform, so only change this option if you have to use a manually created VPC”

@gregwebs This statement is misleading, what we wanted to say is "you cannot reuse the vpc and subnets of an existing eks cluster to create another eks cluster". And actually reusing existing eks cluster is supported to deploy multiple tidb clusters is already supported (ref: https://pingcap.com/docs/stable/tidb-in-kubernetes/deploy/aws-eks/#manage-multiple-tidb-clusters)

**Comment by aylei** [comment]
Looks like this issue is about the poor user interface of our tf scripts and some bad statements in the document, then.

**Comment by gregwebs** [comment]
Do we have an example for re-using an existing EKS cluster though? For that example one is still creating the cluster in terraform.

**Comment by aylei** [comment]
> Do we have an example for re-using an existing EKS cluster though? For that example one is still creating the cluster in terraform.

Yes, we do not support re-using EKS cross top-level tf modules. This is by design because the `tidb-cluster` sub-module takes the `eks` object (which is the output of `eks` module) as input https://github.com/pingcap/tidb-operator/blob/b92da6d67b442b407d224c8501b5567ecdd64eae/deploy/aws/clusters.tf#L45. It is cumbersome to pass this object across top-level tf modules.

However, if there is valid requirement for re-using EKS cross modules, we could support it though some refinements.

**Comment by gregwebs** [comment]
> However, if there is valid requirement for re-using EKS cross modules, we could support it though some refinements.

It makes a lot of sense to do this since it lowers cost outside of GKE. With dedicated node pools it shouldn't disrupt the rest of the workload.
