### ISSUE TITLE
Scaling does not work with tidb:latest

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb-operator#115]
I deployed a GKE cluster using the tutorial, with one exception:

```
helm install ./charts/tidb-cluster -n tidb --namespace=tidb --set pd.storageClassName=pd-ssd,tikv.storageClassName=pd-ssd,pd.image=pingcap/pd:latest,tidb.image=pingcap/tidb:latest,tikv.image=pingcap/tikv:latest
```

This step no longer works:

```
helm upgrade tidb charts/tidb-cluster --set pd.storageClassName=pd-ssd,tikv.storageClassName=pd-ssd,tikv.replicas=5
```

The nodes are in `CrashLoopBackOff` status.

**Comment by morgo** [comment]
It looks like pd is failing.  I tried scaling just tidb:

```
helm upgrade tidb charts/tidb-cluster --set tidb.replicas=4

tocker@cloudshell:~/tidb-operator (morgan-test-213703)$ kubectl get po -n tidb
NAME                              READY     STATUS             RESTARTS   AGE
demo-monitor-865db5758b-t99g2     2/2       Running            0          44m
demo-monitor-configurator-vnxkk   0/1       Completed          0          44m
demo-pd-0                         1/1       Running            0          44m
demo-pd-1                         1/1       Running            0          43m
demo-pd-2                         0/1       CrashLoopBackOff   4          2m
demo-tidb-0                       1/1       Running            0          42m
demo-tidb-1                       1/1       Running            0          42m
demo-tidb-2                       1/1       Running            0          2m
demo-tidb-3                       1/1       Running            0          2m
demo-tikv-0                       2/2       Running            0          43m
demo-tikv-1                       2/2       Running            0          43m
demo-tikv-2                       2/2       Running            0          43m

```

**Comment by morgo** [comment]
Stack driver is showing:
```
panic: runtime error: index out of range goroutine 89 [running]: github.com/pingcap/pd/vendor/github.com/coreos/bbolt.(*DB).page(...) /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/coreos/bbolt/db.go:793 github.com/pingcap/pd/vendor/github.com/coreos/bbolt.Open(0xc42028abc0, 0x1a, 0x180, 0xc420067e10, 0x5a790e, 0xc42028abc0, 0x1a) /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/coreos/bbolt/db.go:237 +0x655 github.com/pingcap/pd/vendor/github.com/coreos/etcd/mvcc/backend.newBackend(0xc42028abc0, 0x1a, 0x5f5e100, 0x2710, 0x280000000, 0x2) /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:129 +0x9d github.com/pingcap/pd/vendor/github.com/coreos/etcd/mvcc/backend.New(0xc42028abc0, 0x1a, 0x5f5e100, 0x2710, 0x280000000, 0x0, 0x0) /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:113 +0x48 github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver.newBackend(0xc4202a8000, 0x0, 0x0) /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver/backend.go:36 +0x17d github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver.openBackend.func1(0xc42007b800, 0xc4202a8000) /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver/backend.go:56 +0x2b created by github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver.openBackend /home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/etcdserver/backend.go:55 +0x9f
```

**Comment by tennix** [comment]
You specified the docker image in the command line when installing tidb cluster, but you didn't specify it when scaling. So helm uses the default docker image in values.yaml file, that is v2.0.4. So you downgrade the tidb cluster when scaling the cluster. IIRC tidb cluster components now have version requirement when the process started, so the downgrade fails.

**Comment by morgo** [comment]
OK!  makes sense.  Thank you for diagnosing.

**Comment by tennix** [comment]
So it's better to write the customized variables to values.yaml instead of specifying it on the command line argument. But modify values.yaml is not suitable for the tutorial.

**Comment by morgo** [comment]
Yeah, that's kind of the position I'm in -- I'm writing a tutorial.  I'll just always include all customized variables. When 2.1 GAs I suspect tidb-operator will bump the version, and then I can go edit and simplify the variables.

**Comment by tennix** [comment]
Yeah, I think so.

**Comment by gregwebs** [comment]
This looks like an easy trap to fall into. I would like to avoid leading people to that from tutorials if possible. There are a few options here.
* Use something like [yq](https://github.com/kislyuk/yq) to alter the values.yaml with a CLI command.
* Use `helm --values` option to provide an override file (not sure if this helps)

From my reading of the [docs](https://github.com/helm/helm/blob/master/docs/using_helm.md#customizing-the-chart-before-installing), the behavior you are encountering almost seems buggy. I guess the issue comes down to the implicit use of values.yaml, which is now taking precedence over previous sets.
So another approach would be to to try to have an empty/null values.yaml and always specify a values file. Then if you don't specify one on upgrade you won't implicitly get a bunch of values.

**Comment by gregwebs** [comment]
How about this as a solution: we don't include any values.yaml in the chart (unless it is meant to be installed and never modified). So when I install, the command would be:

```
helm install ./charts/tidb-cluster -f ./values/tidb-cluster.yaml -n tidb --namespace=tidb 
```

Then upgrade should be straightforward

```
helm upgrade tidb charts/tidb-cluster --set tikv.replicas=5
```

**Comment by gregwebs** [comment]
This approach requires a missing values.yaml to be acceptable on upgrade. Right now we get `template: tidb-cluster/templates/tidb-service.yaml:11:16: executing "tidb-cluster/templates/tidb-service.yaml" at <.Values.tidb.service...>: can't evaluate field annotations in type interface {}`

So I think we would need to provide a values.yaml file with the structure outline in the chart. We would also need to make sure that empty values mean no change rather than setting to an empty value. And we would probably want validate that some fields are set on install.

**Comment by gregwebs** [comment]
I think the best approach as an end user is to use a wrapper script and never invoke helm directly. The wrapper script either uses --set or --values to set custom values, and the original values.yml would be unchanged. To ensure the wrapper is used, the helm chart can fail unless a value is set and give an error message to use the wrapper.

**Comment by gregwebs** [comment]
I am going to close this out: its a fundamental design flaw of helm that users have to be aware of. We are addressing it to some extent in our terraform setup.
