### ISSUE TITLE
Remove DinD related scripts

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1156]
## Feature Request

DinD has been deprecated, also, we are removing didn from the documents: https://github.com/pingcap/docs-cn/pull/2042 and replace it with kind: https://github.com/pingcap/docs-cn/blob/master/dev/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-kind.md 

The scripts are out of maintenance, we may remove them to avoid misusing

**Comment by yikeke** [comment]
When the DinD scripts are removed, do we need to modify the `kubectl apply` command [here](https://pingcap.com/docs-cn/stable/tidb-in-kubernetes/reference/configuration/storage-class/#%E6%9C%AC%E5%9C%B0-pv-%E9%85%8D%E7%BD%AE)? @aylei This command seems to use `local-dind`?

**Comment by aylei** [comment]
No, this command is for `local-volume-provisioner`, which is not affected

**Comment by yikeke** [comment]
> No, this command is for `local-volume-provisioner`, which is not affected

Got it, thanks~
