### ISSUE TITLE
e2e test for TLS support

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#1162]
## Feature Request

e2e test case for TLS support #782 #1158

**Comment by cofyc** [comment]
tls between components has been covered in https://github.com/pingcap/tidb-operator/pull/750 and https://github.com/pingcap/tidb-operator/pull/1454.
tls client test will be tracked in this specific issue: https://github.com/pingcap/tidb-operator/issues/1689
other tls features/bugs will be tracked in the following issues: https://github.com/pingcap/tidb-operator/issues/1748 https://github.com/pingcap/tidb-operator/issues/1685, etc.

closing this in favor of more specific issues opened recently.
