### ISSUE TITLE
terraform: all modules should lock provider versions too

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#1172]
## Feature Request

**Is your feature request related to a problem? Please describe:**

`hack/check–terraform.sh` will install dependencies for each module, and run validate and fmt in that module. Currently, it will install the latest providers for modules under `deploy/modules`.

gcp/tidb-operator has a problem with the latest `google`, I'm going to fix it in https://github.com/pingcap/tidb-operator/pull/1102.

```
Error: "ip_allocation_policy.0.use_ip_aliases": [REMOVED] This field is removed as of 3.0.0. If previously set to true, remove it from your config. If false, remove it.

  on main.tf line 1, in resource "google_container_cluster" "cluster":
   1: resource "google_container_cluster" "cluster" {


```

**Describe the feature you'd like:**

all modules should lock provider versions.

**Comment by DanielZhangQD** [comment]
@cofyc This should be fixed by https://github.com/pingcap/tidb-operator/pull/1206.

**Comment by cofyc** [comment]
no, only tidb-operator module has `versions.tf`,see https://github.com/pingcap/tidb-operator/tree/master/deploy/modules/gcp.

maybe we we don't need to init/validate modules in deploy/modules (check fmt only), because they are internal modules.

**Comment by DanielZhangQD** [comment]
Yes, I mean that the original issue of `Error: "ip_allocation_policy.0.use_ip_aliases"` should be fixed by #1206 and we do not have to set provider versions for the modules in `deploy/modules`.

**Comment by cofyc** [comment]
yes, `Error: "ip_allocation_policy.0.use_ip_aliases"` is fixed but not all modules under `deploy/modules` have locked versions, so in the future another issue may happen because each time `terraform init` will install the latest providers for these modules (except `gcp/tidb-operator`).

so we must either 1) lock versions for all modules under `deploy/modules` 2) don't run `init/validate` for these internal modules.

**Comment by DanielZhangQD** [comment]
For users, they only need to run `init` under `deploy/{aws, gcp, aliyun}`, they do not need to care about the other modules, so I prefer 2).
