### ISSUE TITLE
Cherry-pick hostnetwork support (#774) to release-1.0

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1201]

**Comment by cofyc** [comment]
https://github.com/pingcap/tidb-operator/pull/774
https://github.com/pingcap/tidb-operator/pull/818
https://github.com/pingcap/tidb-operator/pull/1032

**Comment by tennix** [comment]
Could we close this now?

**Comment by cofyc** [comment]
closed via https://github.com/pingcap/tidb-operator/pull/1202.
