### ISSUE TITLE
Deploy the webhook server as an AA Server to simplify deployment

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#1212]
If we use [generic-admission-server](https://github.com/openshift/generic-admission-server#deployment)(or our own AA Server) to develop our webhook server, and deploy our webhook server as an AA server, then the AA Server will act as a proxy to our webhook server.

 If we set `ValidatingWebhookConfiguration`'s [caBundle](https://github.com/kubernetes/api/blob/master/admissionregistration/v1/types.go#L529) to `nil`, the webhook controller(in kube-apiserver) will authenticate the requests to the AA Server:

![image](https://user-images.githubusercontent.com/9758/69320922-0dc9dd80-0c7d-11ea-9f28-4d720188c32b.png)

We can also tell [APIService](https://github.com/kubernetes/kube-aggregator/blob/39a1409e2e9e9ffe96d3c2b8122f25933940b4ef/pkg/apis/apiregistration/v1/types.go#L59) to disables TLS certificate verification when communicating with AA Server.

So, by default:
- develop our webhook server using [generic-admission-server](https://github.com/openshift/generic-admission-server#deployment)(or our own AA Server)
- deploy it as an AA Server and set its `InsecureSkipTLSVerify ` to `true`

If the user wants to open TLS certificate verification to AA Server, just use [cert-manager](https://github.com/jetstack/cert-manager) which will automatically provisioning and managing TLS certificates (for examples: APIService's `caBundle` and the AA Server's server.cert and server.key).

Ref:
https://kubernetes.io/blog/2018/01/extensible-admission-is-beta/
https://github.com/openshift/generic-admission-server

@tennix @Yisaer

**Comment by Yisaer** [comment]
This is helpful and worth to try.

**Comment by Yisaer** [comment]
Closed in https://github.com/pingcap/tidb-operator/pull/1288
