### ISSUE TITLE
Use env for rclone

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#1217]
## Feature Request

Rclone support [environment variable](https://rclone.org/docs/#environment-variables) to config, and we already inject the env for the backup, it's unnecessary to generate a temporary [`rclone.conf`](https://github.com/pingcap/tidb-operator/blob/f12f92cb93a8a6671b5387b82e1c786a29260869/images/backup-manager/entrypoint.sh#L4-L28). Besides, it should be more secure to use environment variables.

**Comment by tennix** [comment]
The secret credentials are now plain text in `env` which is security flaw. It should use `Secret` reference.

**Comment by onlymellb** [comment]
I agree to mount sensitive information from the secret instead of using the plain text of sensitive information on the pod. In addition, I think using rclone's configuration file is more convenient than using environment variables for local testing.

**Comment by tennix** [comment]
Yeah, it's convenient for local testing, but should be using environment variables for deploying. So we don't need to add the entrypoint script.

**Comment by gregwebs** [comment]
In the cloud the aws sdk should automatically find the credentials from us setting env_auth = true in rclone. We shouldn't set any environment variables ourselves. Unfortunately rclone is not currently doing this properly, but we can get that fixed upstream: https://github.com/rclone/rclone/issues/3753

**Comment by onlymellb** [comment]
I think using the entrypoint script to generate rclone's configuration is more flexible, many of the default values can be set or modified directly in the script without recompiling the code. It's much simpler more convenient than injecting all environment variables from the code, I know using environment variables can omit the rclone's configuration file, but what other benefits are there besides this ？

**Comment by gregwebs** [comment]
The aws sdk already finds credentials in a pre-defined way. So mostly we just need to let users use this technique and not force users in to any one technique. You can have a secret in the form of an aws credentials file. If in use you can set AWS_CREDENTIAL_PROFILES_FILE to point to it. If not in use, the aws sdk will find credentials already set in the environment by EKS.
