### ISSUE TITLE
Send `SIGQUIT` to tidb-server  to perform gracefully shutdown

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1224]
TiDB server only shutdown gracefully when receiving `SIGQUIT`: https://github.com/pingcap/tidb/issues/13369

Before this get fixed, we can work around this by simply send `SIGQUIT` in pod pre-stop-hook

**Comment by ekalinin** [comment]
> TiDB server only shutdown gracefully when receiving SIGHUP

I'm sorry, but it should be `SIGQUIT`, isn't it?

https://github.com/pingcap/tidb/blob/3ca8661b5b3b12ecdfd664a5dd090f2af859a55c/util/signal/signal_posix.go#L54

**Comment by aylei** [comment]
@ekalinin Thanks! I've updated the description.

**Comment by Yisaer** [comment]
I think `graceful shutdown` and `force shutdown` is both necessary. Maybe we could support it by configure it in `TidbCluster` ?

**Comment by aylei** [comment]
> I think `graceful shutdown` and `force shutdown` is both necessary. Maybe we could support it by configure it in `TidbCluster` ?

`force shutdown` could be implemented by the `gracefulShutdownSeconds` property that will be added to `TidbCluster`

**Comment by aylei** [comment]
Re-targeted to `v1.2.0`
