### ISSUE TITLE
Add default affinity for tidb if bin-log enabled 

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#1234]
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://github.com/pingcap/docs-cn/issues/2073

tidb is recomended to deploy into the same node with pump. Currently the affinity in our helm chart values for tidb is empty. I think it's better to set affnitiy for tidb to stay in the node with pump by default if bin-log enabled.

**Teachability, Documentation, Adoption, Migration Strategy:**

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity

**Comment by tennix** [comment]
The affinity should be set on TiDB instead of Pump. If binlog is enabled, the tidb-server should be scheduled on a node that has pump pod.

**Comment by Yisaer** [comment]
> The affinity should be set on TiDB instead of Pump. If binlog is enabled, the tidb-server should be scheduled on a node that has pump pod.

Updated.

**Comment by tennix** [comment]
I don't think we should set it in values.yaml. This logic is complicated in helm. Instead we should add documentation for this.

**Comment by Yisaer** [comment]
Maybe we could recommend the affinity both in the document and the note in the `values.yaml` if the user want to enable the binlog? @tennix
