### ISSUE TITLE
Optimize tranferring pd leader

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#1235]
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://github.com/pingcap/tidb-operator/issues/1015

Currently PD leader would be transferred between the first pd pod and the last pd pod without considering whether they were working or healthy. And each 2 upgrading would cause twice transferring pd leader during upgrading.

**Describe the feature you'd like:**

Optimizing the pd leader transferring logic. The target pd pod which is going to be transferred as pd leader should be checked whether it is avaiable. 

If the last pd pod was the leader before upgrading, I think there was at least and at most 2 times to transfer leader. I think we should decrease the frequenecy of 2 times pd leader transferring.

**Comment by shonge** [comment]
Can you describe which scene will transfer leader more than 2 times? @Yisaer
