### ISSUE TITLE
Consider adopting orphaned objects

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1246]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For advanced users, it is useful to delete `tidbcluster` with `--cascade=false` to orphan the underlying objects (e.g. statefulsets) and perform manual intervention. However, when they re-create the `tidbcluster` object, the orphaned objects won't be adopted again, which causes the resources leak when the cluster get real deletion.

**Describe the feature you'd like:**
Adopt orphaned objects that should have been managed by TidbCluster.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Yisaer** [comment]
I wonder why users would delete `tidbcluster` with `--cascade=false` ?

**Comment by aylei** [comment]
@Yisaer For example, expand the space of PVC
