### ISSUE TITLE
make backup and restore more universal

### ISSUE THREAD

**Issue by onlymellb** [pingcap/tidb-operator#1253]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The original design of backup and restore only considered the tidb cluster managed in k8s, so there are some restrictions.

- Can't backup and restore the tidb cluster outside k8s
- Can't specify a remote backup path to restore tidb cluste(only can specify a backup CR to restore tidb cluster)
- Backup and restore related resources must be created under the namespace of the backup and the restore cluster separately. Actually, this restriction is not necessary

At the same time, for convenience of use, some security and flexibility are sacrificed

**Describe the feature you'd like:**

The purpose here is mainly to make backup and recovery more versatile and solve the problems mentioned above
- Support backup and restore any accessible tidb cluster, whether inside or outside k8s.
- Support specify a remote backup path to restore any accessible tidb cluster, whether inside or outside k8s.
- Backup and restore related resources can be created in any namespace.
- Restore operation does not read secrets(remote storage access credentials) across namespaces

**Comment by gregwebs** [comment]
> Can't backup and restore the tidb cluster outside k8s
I do this with the existing backup helm chart just by setting a variable for the host to connect to.

> Restore operation does not read secrets(remote storage access credentials) across namespaces
If we have control of the namespace that the backup/restore job runs in that can help a lot with avoiding inappropriate access across namespaces.

**Comment by tennix** [comment]
We should also allow using IAM role to skip configuring secret explicitly as discussed here https://github.com/pingcap/tidb-operator/pull/1248#discussion_r351586748.

*Note:* current rclone does not support this feature [yet](https://github.com/rclone/rclone/issues/3753).
