### ISSUE TITLE
e2e: able to isolate tidb-operator for test specs

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1257]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, we deploy a tidb-operator singleton for all ginkgo specs (https://github.com/pingcap/tidb-operator/blob/f8f4418e7287d2127ccbdc4b46bbfab9776c2175/tests/e2e/e2e.go#L124). Different specs are not isolated and it is tedious to test tidb-operator in different configurations or setups.

**Describe the feature you'd like:**

~~A dedicated tidb-operator for each spec.~~

Discussed with @cofyc , a new tag `[Serial]` could support synchronized modification on tidb-operator. 

**Describe alternatives you've considered:**

Support customizing operator configuration and setup of the suite, and run multiple e2e tests in parallel with different operator configuration. This is less flexible, IMHO.

**Comment by cofyc** [comment]
Some resources are global, e.g. CRDs. We can have more jobs to test different kinds of specs. 
The current e2e job runs parallel specs in parallel. We can have another job to run serial specs (e.g. upgrade tidb-operator) serially (e.g. --ginkgo.focus='\[Serial\]').

**Comment by aylei** [comment]
> Some resources are global, e.g. CRDs. We can have more jobs to test different kinds of specs.
> The current e2e job runs parallel specs in parallel. We can have another job to run serial specs (e.g. upgrade tidb-operator) serially (e.g. --ginkgo.focus='[Serial]').

That'd be great

**Comment by cofyc** [comment]
> Some resources are global, e.g. CRDs. We can have more jobs to test different kinds of specs.
> The current e2e job runs parallel specs in parallel. We can have another job to run serial specs (e.g. upgrade tidb-operator) serially (e.g. --ginkgo.focus='[Serial]').

we have a serial job right now, this issue can be closed.
