### ISSUE TITLE
why default storageClassesName of tidb-cluster-pd and tidb-cluster-tikv are same in tidb-operator

### ISSUE THREAD

**Issue by hepyu** [pingcap/tidb-operator#1258]
I have some confused about storageClass when using tidb-operator as below：

![image](https://user-images.githubusercontent.com/3917749/69900865-acf48080-13b3-11ea-8fa8-453985d918ff.png)

The default storageClasses of tidb-cluster-pd and tidb-cluster-tikv are same, is this reasonable？This is my thinking：
if storageClasses of pd and tikv are different, this mean I could custom different storage size for pd and tikv, becasue the storage of pd is much less than tikv.

**Comment by tennix** [comment]
Yes, the default storage class for pd and tikv are all `local-storage`. Both the storage class and storage size are customizable. And we plan to omit the default storage class to let the cluster choose a default storage class https://github.com/pingcap/tidb-operator/issues/1111
