### ISSUE TITLE
Can't connect to TiDB DATABASE "access denied"

### ISSUE THREAD

**Issue by SebaKalina** [pingcap/tidb-operator#1259]
## Bug Report

**What version of Kubernetes are you using?**
Openshift : v4.2.7
Kubernetes Version: v1.14.6+76aeb0c

**What version of TiDB Operator are you using?**
I am using TiDB Operator v1.0.4.

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
Storage class : gp2

**What's the status of the TiDB cluster pods?**
tidb-cluster-discovery-d9b969465-rn2ld           1/1     Running            0          73m
tidb-cluster-monitor-5f78984db8-kk5qb            3/3    Running   0         73m
tidb-cluster-pd-0                                1/1     Running            0          73m
tidb-cluster-pd-1                                1/1     Running            1          73m
tidb-cluster-pd-2                                1/1     Running            0          73m
tidb-cluster-scheduled-backup-1575196500-9r228   0/1     Completed          5          72m
tidb-cluster-scheduled-backup-1575196680-rwtg6   0/1     Completed          0          69m
tidb-cluster-scheduled-backup-1575196740-htsqj   0/1     Completed          0          68m
tidb-cluster-tidb-0                              2/2     Running            0          71m
tidb-cluster-tidb-1                              2/2     Running            0          71m
tidb-cluster-tidb-2                              2/2     Running            0          71m
tidb-cluster-tidb-initializer-hrf2l              0/1     Completed          5          73m
tidb-cluster-tikv-0                              1/1     Running            0          72m
tidb-cluster-tikv-1                              1/1     Running            0          72m
tidb-cluster-tikv-2                              1/1     Running            0          72m

**What did you do?**
* Operator installation : 
helm inspect values pingcap/tidb-operator --version=v1.0.4 > tidb-operator/values-tidb-operator.yaml
oc apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/crd.yaml
oc create ns tidb-admin
helm install pingcap/tidb-operator --name=tidb-operator --namespace=tidb-admin --version=1.0.4 -f tidb-operator/values-tidb-operator.yaml

* TiDB cluster installation : 
oc adm policy add-scc-to-user anyuid -z tidb-cluster-monitor -n tidb
oc create secret generic tidb-secret --from-literal=root=Pa$$w0rd --from-literal=developer=Pa$$w0rd --namespace=tidb
Modify values :     
    initSql: |-
    create database app;
    GRANT ALL PRIVILEGES ON app.* TO 'developer'@'%';

helm inspect values pingcap/tidb-cluster --version=1.0.4 > tidb-operator/values-tidb-cluster.yaml
helm install pingcap/tidb-cluster --name=tidb-cluster --namespace=tidb --version=1.0.4 -f tidb-operator/values-tidb-cluster.yaml --set tidb.passwordSecretName=tidb-secret

* Connexion to TiDB DATABASE : 
kubectl -n tidb port-forward svc/tidb-cluster-tidb 4000:4000 &>/tmp/port-forward.log &
mysql -h 127.0.0.1 -P 4000 -u root -p
<type password>

**What did you expect to see?**
Connect to TIDB DB

**What did you see instead?**
ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)

**Comment by aylei** [comment]
Hi @SebaKalina , did you set the `.tidb.passwordSecretName` variable of tidb-cluster chart?

**Comment by SebaKalina** [comment]
Yes with the following cmd : 
* helm install pingcap/tidb-cluster --name=tidb-cluster --namespace=tidb --version=1.0.4 -f tidb-operator/values-tidb-cluster.yaml --set tidb.passwordSecretName=tidb-secret
And before that, I created the secret "tidb-secret" with the following cmd : 
* oc create secret generic tidb-secret --from-literal=root=password --from-literal=developer=password --namespace=tidb

**Comment by Yisaer** [comment]
Hi @SebaKalina , I created secret by `kubectl create secret generic tidb-secret --from-literal=root=Pa$$w0rd --namespace=tidb`.
I decode the genereted secret and found that the value for key `root` becomed `Pa6729w0rd` instead of `Pa$$w0rd` .
That's why `tidb-cluster` denied the access request.
I suggest you to check the decoded value for the generated secret and change the password with avoiding character `$`

**Comment by SebaKalina** [comment]
Thanks, it works :) !
