### ISSUE TITLE
standard API to trigger gracefully rolling-restart for each component

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1266]
## Feature Request

For users who use in-place configmap update strategy (`.enableConfigMapRollout=false`) or other special cases that requires rolling-restart of a cluster component (e.g. tidb-servers stuck in `skip-binlog` status` https://github.com/pingcap/tidb/issues/12323), a well-formed API to trigger gracefully rolling-restart is necessary.

Actually we have this ability now: modify the content of component's config and the component will be rolling-updated in favor of configuration change. However, this method is not standard and only works when configmap rollout feature is enabled. Also, the way to cancel rolling-restart is weird: user should rollback the modification of config to cancel the rolling-restart process.

Inspired the by idea taken by kubectl (https://github.com/kubernetes/kubernetes/blob/f6337c762483e60e41dd775166afd536b130455e/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/objectrestarter.go#L106), an `restartedAt` annotation of statefulset is somehow a more declarative way to perform rolling-restart. I propose to add `restartedAt` field for each component in the `TidbCluster` spec, and sync this to the annotations of statefulset of each component.

Additional considerations:

- time skew: time skew will hardly affect this feature, unless the `restartedAt` time exactly jumps back to the previous `restartedAt` time, which is only possible theoretically and easy to diagnose via `controllerrevisions`
- cancel rolling-restart: cancel rolling-restart is as simple as set the previous `restartedAt` time back to `TidbCluster` (or simply rollback the TidbCluster with the help of VCS), which is not elegant but acceptable.

cc @LinuxGit @weekface @tennix

**Comment by LinuxGit** [comment]
This is better than updating component's config. We can't be able to restart a single Pod of component gracefully this way as well?

**Comment by aylei** [comment]
@LinuxGit No, we can't, pod will not get restarted or recreated on annotation change. And the webhook requires some API operation to perform interception, so delete pod is inevitable I suppose

**Comment by tennix** [comment]
@Yisaer Is it possible to do single pod graceful restart now with webhook?

**Comment by Yisaer** [comment]
Currently webhook of  deleting pod request  for tikv/pd would gurantee the  target instance (pd/tikv) would be deleted safely ( transferring pd leader/ eviting reigion leader) from specific service account (like system:sts-controller service account) .
I think it's better to let the tidb-operator-apiserver to trigger pod restart and the webhook would ensure the whole process would be safety.

**Comment by aylei** [comment]
This could be done by set the `.spec.pd.annotations`, no additional work is needed

**Comment by aylei** [comment]
closed
