### ISSUE TITLE
run e2e process outside of the cluster

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#1274]
## Feature Request

**Is your feature request related to a problem? Please describe:**

- stability test will restart k8s nodes which may affect e2e pod

**Describe the feature you'd like:**

run e2e process outside of the cluster

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

- access k8s DNS/IPs
  - via proxy

**Comment by cofyc** [comment]
TODO

- [ ] deploy webhook as a standalone pod
- [ ] proxy to access k8s DNS/IPs

**Comment by weekface** [comment]
We can skip the k8s node which running e2e pod when restarting k8s nodes.

**Comment by cofyc** [comment]
yes, but this restriction can be eliminated and it also has other benefits:

1) easier to deploy/run (no need to wait for for the e2e pod to run and [check logs of the pod in a loop](https://github.com/pingcap/tidb-operator/blob/8714a53653428f706ae21a6a4abb725b07820f5f/hack/run-e2e.sh#L134-L152)), we can use `docker run` to run e2e process
2) easier to collect the generated reports and logs of the cluster. We can bind mount local volume with docker run `-v` flag.

**Comment by weekface** [comment]
:cool:
