### ISSUE TITLE
new custom annotation for gracefully deleting Pod

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1293]
## Feature Request

#1266

webhook could ensure a Pod getting deleted gracefully, however, client has to continuously retry until the request succeeds.

A more user-friendly API is adding a new custom annotation that marks a Pod has to be deleted, a new controller will respond to this annotation and tries to delete Pods with this annotation continuously.

cc @LinuxGit @Yisaer

**Comment by Yisaer** [comment]
merged in https://github.com/pingcap/tidb-operator/pull/1350
