### ISSUE TITLE
consider unify control-plane binaries to simplify tidb-operator deployment

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1294]
## Feature Request

This idea has been circling in my head these days, though it is not mature and many details has not been well considered, I think write it down for more discussions is a better idea.

Currently, we rely heavily on helm to deploy `tidb-operator`, which is:

- hard to test;
- tedious for ecosystem to integrate (e.g. [tidb-operator on OperatorHub](https://github.com/operator-framework/community-operators/blob/master/upstream-community-operators/tidb-operator/1.0.0/tidb-operator.1.0.0.clusterserviceversion.yaml));

I think the deployment of `tidb-operator` could be simplified to a `Deployment` with some RBAC configurations (`Role`, `RoleBinding`, `SA`), all of these resources could be included in one YAML file within 200 lines. Offering better clarity and customizability.

## How

The first issue we have to address is the complex deploy model, we could unify control-plane binaries, either at binary level or container level:

- binary level: by default, run `tidb-controller-manager` in `tidb-operator` bin, optionally to enable `tidb-scheduler`, `tidb-apiserver`, `tidb-webhook` according to command line arguments.
- container level: `tidb-operator` pod could bundle all control-plane containers.

Another issue is bootstrapping, which includes installing CRD, optionally bootstrapping `ApiService`, `CSR`, `AdmissionWebhook`, etc.

It is trivial to do self-bootstrapping in `tidb-operator` bin, command line arguments could also be provided to configure whether `tidb-operator` should perform bootstrap or skip some steps when bootstrapping.

This proposal **DO NOT** abandon helm as a package manager for tidb-operator, we could continue to provide the `tidb-operator` helm chart, but the logic in chart will be greatly simplified —— so do other package managers and users who prefers kubernetes native YAML.

**Comment by tennix** [comment]
@onlymellb had opened an issue to combine all the control plane binaries into one binary. https://github.com/pingcap/tidb-operator/issues/780

**Comment by aylei** [comment]
> @onlymellb opened an issue for combining all the control plane binaries into one binary. #780 This is like hyperkube which combines all k8s components into a single binary.

Yes, similar idea, and a more important thing is that the binary is better to have the ability to run all the component in **one process** (because they act as a whole and rarely make sense if we only run a `tidb-scheduler` process, for example) instead of run different process for each component with different argument.

**Comment by cofyc** [comment]
we should simplify our deployment but running all components in one process is not a good idea because:

1) each component has different RABC (e.g. tidb-scheduler must have same RBAC permission with kube-scheduler, but controller-manager should not)
2) webhook is a web server (server-side), not controller (client-side, don't need to process incoming API requests except optional health check)
3) webhook like kube-apiserver, don't need to do leader election
4) different types of logs will be mixed up (e.g. HTTP request logs or controller logs)

**Comment by aylei** [comment]
> we should simplify our deployment but running all components in one process is not a good idea because:
> 
> 1. each component has different RABC (e.g. tidb-scheduler must have same RBAC permission with kube-scheduler, but controller-manager should not)
> 2. webhook is a web server (server-side), not controller (client-side, don't need to process incoming API requests except optional health check)
> 3. webhook like kube-apiserver, don't need to do leader election
> 4. different types of logs will be mixed up (e.g. HTTP request logs and controller logs)

Yes, thanks for listing the constraints and actually this is exactly what I mean to do: a 'monolithic' operator process with different modules. It looks like an anti-pattern at first glance, and I'm not intend to stick on the monolithic solution. 

But I suppose it is worth to list what we will get and what we have to compromise in a monolithic so that the comparison can be done thoroughly:

We have to compromise:

1. we will bind all necessary roles to the `tidb-operator` SA;
    - why do I think this is bad but acceptable?
        - **I think** end user only cares what permissions "tidb-operator" need, despite the component
2. we will perform readiness healthz check for process, the Pod will be removed from the backends for service if probe failed;
    - why do I think this is bad but acceptable?
        - I think this is not bad actually
3. controller goroutine campaign the leader, nothing to do with other modules;
    - why do I think this is bad but acceptable?
        - I think modules do not influence each other logically
4. we have to assign a context for module log, make the log grep-friendly;
    - why do I think this is bad but acceptable?
        - I think there's no essential difference

User can get:

1. better out-of-box experience: one container to rule them all
2. less effort in day-2 operating: little worry about the version alignment and cascading failure

Also, all-in-one should not be the only solution even if we adopt it. User should have the ability to configure the binary run one module only.
