### ISSUE TITLE
Considering adjust `containerd` systemd service ulimit on EKS

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#1302]
## Question

Docker on EKS worker node may have separated `dockerd` and `containerd` systemd service, adjusting the Docker service to increase ulimit of docker systemd service is not enough (https://github.com/pingcap/tidb-operator/blob/master/deploy/modules/aws/tidb-cluster/templates/userdata.sh.tpl#L14-L19). Some users find the `containerd` service also needs to set ulimit (https://tidbcommunity.slack.com/archives/CHD0HA3LZ/p1575780218010000?thread_ts=1575775693.006100&cid=CHD0HA3LZ).

**Comment by aylei** [comment]
I thought I've met the same issue when I ran e2e test on EKS, adding `echo 'OPTIONS="--default-ulimit nofile=1024000:1024000"' >> /etc/sysconfig/docker` in the userdata solves the problem, I will do a quick verification and work out a fix if it works.
