### ISSUE TITLE
Remove actions since it's not available for legacy plans

### ISSUE THREAD

**Issue by you06** [pingcap/tidb-operator#1305]
## Question

I've noticed the talking under https://github.community/t5/GitHub-Actions/GitHub-Actions-workflows-can-t-be-executed-on-this-repository/td-p/38153. In short words, github actions are for public repositories under no legacy accounts only. Besides, the post https://twitter.com/GitHubHelp/status/1192215970254934016 shows that actions will no more available after November 13th.

I found that there still actions jobs in this repo, and they do not work anymore, what about remove them?

**Comment by weekface** [comment]
@cofyc PTAL

**Comment by cofyc** [comment]
It's ok to remove them.
