### ISSUE TITLE
e2e: operator would let sts upgrade during CheckUpgradeOrDie

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#1307]
## Bug Report

During `CheckUpgradeOrDie`, we would pend sts upgrading by setting its update partition to 1 and check whether `tikv-1` and `tidb-2` is upgraded.

However, operator may set partition to 0 at the same time and let tikv status become `Normal` from `Upgrade` during `checkManualPauseComponent` waiting duration.

This would make following condition be false forever as `tc.Status.TiKV.Phase` had already been `Normal`
```code
tikvPod.Labels[v1.ControllerRevisionHashLabelKey] == tc.Status.TiKV.StatefulSet.UpdateRevision && tc.Status.TiKV.Phase == v1alpha1.UpgradePhase
```

**Comment by aylei** [comment]
```
However, operator may set partition to 0 at the same time and let tikv status become Normal from Upgrade during checkManualPauseComponent waiting duration.
```

Why? If operator works properly, the webhook for canary release will blocking the upgrade procedure and the partition should not be set to 0. I suppose it is a bug of that webhook instead of the e2e test code

**Comment by Yisaer** [comment]
I found it is caused by webhook which I made. The e2e process logic is right.
