### ISSUE TITLE
configurator job is unstable

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#133]
I am seeing a lot of variance in the configurator job. Sometimes it completes successfully in a minute. Other times it takes much longer to the point that I assume it is failing.

@tennix identified that this separate job is not necessary in Grafana version 5.3 if we adjust update our chart configuration to work on 5.3.

**Comment by tennix** [comment]
For static provisioning dashboard in Grafana 5.x we can use Jsonnet and the [grafonnet library](https://github.com/grafana/grafonnet-lib) provided by Grafana to generate dashboard json files.

**Comment by gregwebs** [comment]
This job was removed in favor of static provisioning in #388
