### ISSUE TITLE
upgrade tidb operator affect current tidb cluster

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#1335]
## Bug Report

**What version of Kubernetes are you using?**
v1.14.8

**What version of TiDB Operator are you using?**
1.0.5

**What did you do?**
I upgraded tidb operator from 1.0.4 to 1.0.5 , then the operator rolling update tidb cluster.

I think it has risk. As user, current running cluster rolling update need to control by myself.
So, can we add a operator version spec to distinguish current cluster whether need to rollingUpdate.When cluster operator version spec is not equal to controller manager version, it can't be managed.
Even we can support different cluster use different operator versions, it let us to upgrade cluster more friendly.

**Comment by aylei** [comment]
@weekface PTAL

**Comment by cofyc** [comment]
Is it because the host network feature introduced in 1.0.4? https://github.com/pingcap/tidb-operator/pull/1202 the backward compatibility [is fixed only in 1.0.5](https://github.com/pingcap/tidb-operator/pull/1287).
I guess we should deprecate 1.0.4.

**Comment by aylei** [comment]
@cofyc Good catch, I agree we should deprecating 1.0.4 and add notes in the 1.0.5 release note about this https://github.com/pingcap/tidb-operator/blob/master/CHANGELOG.md#compatibility

**Comment by aylei** [comment]
We should add a test case to verify the upgrading compatibility, either a case in `stability-test` or an e2e case that runs only on release branch. I prefer latter.

cc @cofyc @weekface @tennix

**Comment by cofyc** [comment]
yes, the old release-1.0 does not has upgrade test in stability-test (cherry-pick PR: https://github.com/pingcap/tidb-operator/pull/1286). anyone, it's not easy to run stability test right now,  we should add an easy-to-run job to do pre-releasing checks. I'm working on this, this upgrade test can be easily re-implemented in the current e2e job. Then we can add an optional job to accepts two commits to run upgrade tests between them.

**Comment by weekface** [comment]
Do you upgrade `tidb-operator` chart or `tidb-cluster` chart, or both of them? Only upgrading `tidb-operator` chart will not trigger the rolling update. We have a test to cover this.

What is the old and new `values.yaml` files when you upgrading?

**Comment by mikechengwei** [comment]
@weekface I have enabled host mode, then change to L2 mode networker. When upgrading tidb operator ,the tidb cluster did not upgrade, it was in normal status.
And tikv nodes and pd nodes all rolling upgrade  when upgrading tidb operator.

**Comment by mikechengwei** [comment]
Did you test after multiple upgrade cluster config, for example the host config, then upgrading tidb operator .

**Comment by weekface** [comment]
Yes, i didn't test the host mode. This should be a compatibility problem.
