### ISSUE TITLE
add feature of specifying  clusterIP when  creating pd service used ClusterIp type.

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#1337]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I directly  use tikv cluster directly exclude tidb nodes,i provide a lvs ip  for my users,the lvs ip is pd service ip.
 When the cluster can't recover forever deep on helm tool, i need to execute helm reinstall command.
So I must guarantee  cluster pd service ip immutable.

**Describe the feature you'd like:**
add feature of specifying  clusterIP,when pd service use ClusterIp type.
```
services:
  - name: pd
    type: ClusterIP
    ClusterIP: 10.xx.xx.xx
```

**Describe alternatives you've considered:**
1. pd manager create service ,supporting specifying clusterIP.
2. helm charts add comment option.

**Comment by aylei** [comment]
Thanks for your reporting! Would you like to take this?

BTW, new field for `ServiceSpec` is better to be added here:

https://github.com/pingcap/tidb-operator/blob/8425f87b1b78ee7d45fe7d8b3422cbab24af79d3/pkg/apis/pingcap/v1alpha1/types.go#L342

**Comment by mikechengwei** [comment]
Ok,i will do it.

**Comment by mikechengwei** [comment]
@aylei hi,i have seen pd create service using below class : 
https://github.com/pingcap/tidb-operator/blob/8425f87b1b78ee7d45fe7d8b3422cbab24af79d3/pkg/apis/pingcap/v1alpha1/types.go#L123
It was deprecated . Is the reason why this be  deprecated because we change to use headlessService?But now we expect that the tidb operator is also a tikv operator.
Should i continue to modify based on `Services`,or changing to use  `ServiceSpec ` class?

**Comment by tennix** [comment]
This slice only contains service type and it's global. We are going to replace it with component-specific struct which contains more field.

I'm curious about in which scenario does this happen.
> When the cluster can't recover forever deep on helm tool, i need to execute helm reinstall command.

Also how do you make tikv accessible to the external world if the tikv client is not deployed inside the k8s cluster.

**Comment by mikechengwei** [comment]
@tennix I use helm tool 3.0 version.  I have used a wrong charts upgrade tidb cluster .For example,i upgrade  service from ClusterIP type  to NodePort, now helm occur deployed error . Which triggering  a helm bug  [reference ](https://github.com/helm/helm/issues/5595#issuecomment-560445169). If helm has  no deployed release , we can't rollback or upgrade to recover tidb cluster .
So ,I must reinstall my tidb cluster ,and I must keep the pd service ip immutable.

> Also how do you make tikv accessible to the external world if the tikv client is not deployed inside the k8s cluster.
My k8s cluster network use L2 mode ,so external world can access k8s network.

So I need to use ServiceSpec class ,right?

**Comment by tennix** [comment]
Okay, for the helm, we haven't tested the 3.0 version. We are migrating the helm client logic to CRD and controller. So I've no idea about this.

If you want to specify the `clusterIP` field, you should definitely use `ServiceSpec`.
Did you allow the k8s internal DNS resolvable to external world? Because we don't use pod IP directly with statefulset.

**Comment by mikechengwei** [comment]
@tennix I think it is neeed that pd service ip can be specified in tikv scene. Because we must provided an immutable pd service ip for user .

> If you want to specify the `clusterIP` field, you should definitely use `ServiceSpec`.

I need to change  following code `Services` class to `ServiceSpec`  class ,right?
https://github.com/pingcap/tidb-operator/blob/8425f87b1b78ee7d45fe7d8b3422cbab24af79d3/pkg/manager/member/pd_member_manager.go#L454

> Did you allow the k8s internal DNS resolvable to external world? Because we don't use pod IP directly with statefulset.

My k8s internal dns domain use company dns domain , and syncing it to company dns server .So,it can be resolvable.

**Comment by tennix** [comment]
You will need to extend the service spec https://github.com/pingcap/tidb-operator/blob/8425f87b1b78ee7d45fe7d8b3422cbab24af79d3/pkg/apis/pingcap/v1alpha1/types.go#L341-L351

For you DNS part, I think that is pretty cool!

**Comment by mikechengwei** [comment]
done
