### ISSUE TITLE
Improve error messages for "Failed filter with extender"

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-operator#1346]
## Feature Request

**Is your feature request related to a problem? Please describe:**

My deployment fails with this message:
```
Failed filter with extender at URL http://127.0.0.1:10262/scheduler/filter, code 500
```

But neither the logs for kube-scheduler or tidb-scheduler seem to contain any additional information that actually helps me resolve the issue.

**Describe the feature you'd like:**

This error message should be improved to provide information that can be used to resolve the problem.

[kube-scheduler.log](https://github.com/pingcap/tidb-operator/files/3970421/kube-scheduler.log)
[tidb-scheduler.log](https://github.com/pingcap/tidb-operator/files/3970422/tidb-scheduler.log)

**Comment by cofyc** [comment]
Closed via https://github.com/pingcap/tidb-operator/pull/1373. If #1373 does not address this issue, please re-open it.
