### ISSUE TITLE
terraform: CRD as the source of truth

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#1347]
## Feature Request

@kolbe frequently experiences issues with our terraform setup. I believe the main issue is all the non-infrastructure things that we are doing in terraform: running helm and kubectl

Currently the information flow is:

terraform variables -> terraform apply -> values file terraform template -> helm upgrade -> CRD

We want to move the information flow to:

values file -> helm upgrade -> CRD -> terraform variables -> terraform apply

The full workflow would be:

```
# Here we separate out cluster creation
cd k8s-cluster
terraform apply
cd ../
# Now do the TiDB setup with an existing k8s cluster
./create-tidb-env staging --cluster-from k8s-cluster
cd staging
./env helm install pingcap/tidb-cluster
./refresh-terraform-from-crd
terraform apply
```

If we want to reduce the number of user commands, we can write some simple wrapper scripts.
In the above setup, the CRD is the source of truth (derived from helm values), and the terraform is changed to match it.

**Comment by aylei** [comment]
My personal opinion is that both `terraform` and `helm` are tedious and fragile, the job about removing helm in `tidb-cluster` management is almost done, and I think the we only need external tools like `terraform` or [`aws-cdk`](https://github.com/pingcap/tidb-operator/issues/998) to provision the Kubernetes control-plane (and of course, this is optional). The node should be able to be dynamically provisioned by `ClusterAutoscaler`. `terraform` cannot cannot achieve our goal, I think it's time to start working on the long-term vision.

**Comment by gregwebs** [comment]
ClusterAutoscaler could be a good approach. But it is difficult for us to add it into a cluster since it is global in scope. If we can run one that operates only in the tidb namespaces that could work well.

In my experience terraform works fairly robustly as long as you only use it to create cloud infrastructure using the existing libraries.

With respect to helm, I agree. But it does provide functionality that we will have to ensure is replace with our own CLI. And calling the CLI from terraform would still be a bad idea.

So I think we can achieve the long-term vision with terraform but we just need to delete the part that isn't provisioning infrastructure. The only problem is that terraform wants to set the number of instances on the node pool, which complicates using an autoscaler.

**Comment by aylei** [comment]
Yes, terraform can still be an alternative for user to manage the infrastructure, what I am worried about is that it is limited to client-side coordination and fails to opt-in the automation of controller, so I doubt that it could be a general solution we recommend for users. 

Back to the issue, I agree that we should cut the helm operation from the terraform script and we may try to generate (refresh) the terraform script from the spec of custom resource.

**Comment by gregwebs** [comment]
> it is limited to client-side coordination and fails to opt-in the automation of controller, so I doubt that it could be a general solution we recommend for users.

You want something that is constantly monitoring and updating the infrastructure? The terraform approach is good for auditing changes. The constant monitoring + updating approaches that I have seen aren't very good at this. In the end everyone wants to use their existing deployment tools. But it may be possible for us to do more in k8s that everyone will accept. After removing all the tidb-operator stuff, capacity management would be the first thing to try to take away from the infrastructure provisioning.
