### ISSUE TITLE
Able to mount more than one disks for TiKV pod

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#1357]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Sometimes, it's better to store the RocksDB data and WAL logs on different disks to improve TiKV performance. See [tikv tuning docs](https://github.com/pingcap/docs/blob/d142ada331ef216b8c032509172c781cbc54c65b/v3.1/reference/performance/tune-tikv.md). But tidb-operator does not support mounting two volumes for TiKV pod.

**Describe the feature you'd like:**

Able to mount more than one disks for TiKV pod

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mikechengwei** [comment]
I am interested in implementing this feature.

**Comment by cofyc** [comment]
sorry, this is a stale issue and is replaced by https://github.com/pingcap/tidb-operator/issues/2183.
I'm working on a proposal and will send it out for the review soon. We can discuss the API and implementations details first.
I'm going to close this and we can discuss it in #2183.
