### ISSUE TITLE
terraform: ensure nobarrier is set for all SSD

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#1363]
Currently only the terraform GKE deployment ensures that nobarrier is set. We should do this as well for EKS or any other cloud environment where instance termination means SSD data is lost.

See the GKE implementation.
https://github.com/pingcap/tidb-operator/blob/master/manifests/gke/local-ssd-optimize.yaml
https://github.com/pingcap/tidb-operator/blob/master/deploy/gcp/manifests/local-ssd/overlays/terraform-local-ssd-provision.yaml

However, we may prefer to add it to the terraform user-data
https://github.com/pingcap/tidb-operator/blob/master/deploy/modules/aws/tidb-cluster/pre_userdata#L18

**Comment by tennix** [comment]
From RedHat documentation https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/storage_administration_guide/writebarrieronoff
> Additionally, the nobarrier option should never be used on storage configured on virtual machines

So I suggest benchmark this on different cloud instead of blindly adding to all environment.

**Comment by gregwebs** [comment]
According to those docs

> For devices with non-volatile, battery-backed write caches and those with write-caching disabled, you can safely disable write barriers at mount time using the -o nobarrier option for mount

Which is the point. The part about virtual machines has no citation or rationale and is wrong (when blindly applied).

Anyways, this has been benchmarked on AWS to show in some cases an enormous difference. https://www.cockroachlabs.com/blog/2018_cloud_report/
