### ISSUE TITLE
Optimize discovery advertisePeerUrl length limit 

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#1366]
## Bug Report

**What version of Kubernetes are you using?**
1.14.8

**What version of TiDB Operator are you using?**
1.0.5

**What did you do?**
Hi , in my scene, I modify pd advertisePeerUrl from `"${POD_NAME}.${PEER_SERVICE_NAME}.${NAMESPACE}.svc"` to `"${POD_NAME}.${PEER_SERVICE_NAME}.${NAMESPACE}.svc.datacloud.xxx.com"`,
It's helpful to me that k8s internal dns can sync company dns server.
Then I meet a error 
```
E1219 03:39:39.742899       1 mux.go:58] failed to discover: ssd-tidb-cluster-pd-2.ssd-tidb-cluster-pd-peer.default.svc.datacloud.17usoft.com:2380
, advertisePeerUrl format is wrong: ssd-tidb-cluster-pd-2.ssd-tidb-cluster-pd-peer.default.svc.datacloud.17usoft.com:2380
E1219 03:39:39.742916       1 mux.go:60] failed to writeError: advertisePeerUrl format is wrong: ssd-tidb-cluster-pd-2.ssd-tidb-cluster-pd-peer.default.svc.datacloud.17usoft.com:2380
```

The reason of this error is discovery nodes limit advertisePeerUrl length, I think we can optimize like the following:

```
if len(strArr) < 4 {
	return "", fmt.Errorf("advertisePeerUrl format is wrong: %s", advertisePeerUrl)
}
```

Source code is :
https://github.com/pingcap/tidb-operator/blob/35db292f812459722d39ee3b1ddc1b7a1994795a/pkg/discovery/discovery.go#L70

**What did you expect to see?**
optimize the discovery  mechanism advertisePeerUrl length  limit .

**Comment by Yisaer** [comment]
@mikechengwei Hi, did you change the `pd advertisePeerUrl` by modifying the `chart/tidb-cluster/templates/scripts/_start.pd.sh.tpl` or how ?

**Comment by mikechengwei** [comment]
yes,i modify `pd advertisePeerUrl`  config  in  chart/tidb-cluster/templates/scripts/_start.pd.sh.tpl and `--advertise-addr ` config in _start_tikv.sh.tpl file .
