### ISSUE TITLE
Pd health check need to add k8s sts check,not only cluster http url check

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#1370]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Due to discovery nodes not return args for my pd nodes one of it  for a long time , I describe my tidb cluster, failover mechanism not display my failed node.

I find that pd health check use  pdClient request pd url to get health info , maybe my failed node not get start args  cause it  not join the tidb cluster .Then client can’t get the failed node info.

So, do we need to show the failed node which not joining tidb  cluster? but the container start .

<img width="929" alt="image" src="https://user-images.githubusercontent.com/13257127/71148009-78167380-2265-11ea-9144-e5eb25a6cd53.png">

**Describe the feature you'd like:**
Status show the failed node  which not join tidb cluster.

**Describe alternatives you've considered:**
If we do the feature, I think we need to add k8s sts  check to the following code ：

https://github.com/pingcap/tidb-operator/blob/35db292f812459722d39ee3b1ddc1b7a1994795a/pkg/manager/member/pd_member_manager.go#L333

**Comment by aylei** [comment]
Good catch, would you like to take this? @mikechengwei

**Comment by mikechengwei** [comment]
yes, assign to me .
