### ISSUE TITLE
support pausing rolling-update of TidbCluster

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1381]
## Feature Request

Scenarios:

- For critical env, `pause` could be used to avoid unexpected rolling-update caused by a compatible issue of new operator version or an operation error (user fault).
- Support user to modify the spec multiple times and only apply once, or only apply at maintenance window.

Reference:

- Pause support of Deployment

**Comment by Yisaer** [comment]
Currently, we already supported this feature. #1377 moved sts webhook config in templates and exposed webhook switch in `values.yaml`. When users enabled `admissionWebhook` and statefulset hook, they can parse `tidbcluster` by adding annotations for `tidbcluster` object.

**Comment by aylei** [comment]
I suppose you are talking about the annotations (`tidb.pingcap.com/tidb-partition"`, `tidb.pingcap.com/tikv-partition`) for canary release? In some extent it meets the requirement, but it is not actually pause the all the controlling that would mutate cluster pods

**Comment by Yisaer** [comment]
@aylei  It seems that this feature requests a method like annotate `tidb.pingcap.com/pause` to `tidbcluster` to pause the upgarding without specific the canary release number.

**Comment by cofyc** [comment]
related incompatibility issues:

- https://github.com/pingcap/tidb-operator/issues/1779
- https://github.com/pingcap/tidb-operator/pull/1859
