### ISSUE TITLE
Feature request: Add ephemeral storage for TiDB pod

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#1395]
## Feature Request

Currently, TiDB does not use storage, the slow log and audit log are using temporary storage. TiDB will soon support disk based computation to avoid large dataset consuming too much memory causing OOM. https://github.com/pingcap/tidb/issues/11607

We should consider adding ephemeral storage for TiDB pod.

**Comment by aylei** [comment]
Seems duplicate with #1390
