### ISSUE TITLE
just cache the k8s native resources that need concerned

### ISSUE THREAD

**Issue by onlymellb** [pingcap/tidb-operator#1406]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently in the tidb-operator, a lot of k8s native resources are watched to the local cache, such as configmap, secret, pod, etc. When there are many such resources in the k8s cluster, this will cause the tidb-operator to consume too much memory. But in fact, the operator only pays attention to a small part of these resources. 

**Describe the feature you'd like:**

We can add SharedInformerOption to filter resources managed by tidb-operator like follow:
```go
kubeoptions := []kubeinformers.SharedInformerOption{
	kubeinformers.WithNamespace(ns),
	kubeinformers.WithTweakListOptions(
	func(listOptions *metav1.ListOptions) {
		listOptions.LabelSelector = fmt.Sprintf("%s=%s", label.ManagedByLabelKey, label.TiDBOperator)
		}),
	}
kubeInformerFactory = kubeinformers.NewSharedInformerFactoryWithOptions(kubeCli, controller.ResyncDuration, kubeoptions...)
```

https://github.com/pingcap/tidb-operator/blob/51b682016b580790d6c19a733494de91c5979bf5/cmd/controller-manager/main.go#L135-L148

**Breaking backward compatibility**
At present, most k8s native resources related to the tidb-operator have this label `app.kubernetes.io/managed-by: tidb-operator`. If this function is enabled, the `tidb-secret`(used by tidb-initializer-job) and `ceph-secret`(used by Backup)  or other resources created manually before need to be labeled `app.kubernetes.io/managed-by: tidb-operator`.

If we don't want to breaking backward compatibility, for these resources created outside of the tidb-operator,  we can obtain from the apiserver instead of the local cache.

**Comment by aylei** [comment]
@onlymellb would you take this?

**Comment by onlymellb** [comment]
@aylei Can you help to take this

**Comment by aylei** [comment]
@onlymellb no problem

**Comment by Yisaer** [comment]
@aylei Did this feature started? If not, I would like to take it.
