### ISSUE TITLE
Job name of expression in grafana is wrong

### ISSUE THREAD

**Issue by qiffang** [pingcap/tidb-operator#1420]
## Bug Report

**What version of Kubernetes are you using?**

WARN: sum(rate(tikv_thread_cpu_seconds_total{job=“tikv”}[1m])) by (instance)
WARN: avg(process_resident_memory_bytes{job=“tikv”}) by (instance)
WARN: (time() - process_start_time_seconds{job=“tidb”})
WARN: process_resident_memory_bytes{job=“tidb”}
WARN: go_memstats_heap_alloc_bytes{job=“tidb”}
WARN: rate(process_cpu_seconds_total{job=“tidb”}[1m])
WARN: process_open_fds{job=“tidb”}
WARN: rate(go_gc_duration_seconds_sum{job=“tidb”}[1m])
WARN: go_threads{job=“tidb”}
WARN: rate(go_gc_duration_seconds_count{job=“tidb”}[1m])
WARN: go_memstats_gc_cpu_fraction{job=“tidb”}
这几个

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by shonge** [comment]
Let me fix it.

**Comment by shonge** [comment]
@qiffang PTAL

**Comment by tennix** [comment]
@shonge Thank you for your PR. But changing the Grafana dashboard json file can resolve this temporarily. But some Grafana expression relies on this. A better way is changing the Prometheus scraping job. We are now using a single job named "tidb-cluster", we can separate the job by component like pd/tikv/tidb.

**Comment by shonge** [comment]
I get it, I will separate prometheus scrape 'tidb-cluster' job to pd/tikv/tidb jobs.
Let me fix it again.

**Comment by tennix** [comment]
Cool! Thank you, if you need more context and info please contact us on our community Slack.

**Comment by qiffang** [comment]
Thanks @shonge , if you have any concern， please let us known.

**Comment by tennix** [comment]
@shonge You can see how TiDB Ansible does this from here https://github.com/pingcap/tidb-ansible/blob/master/roles/prometheus/templates/prometheus.yml.j2#L110-L336 and in tidb-operator we use prometheus kubernetes service discovery https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config
