### ISSUE TITLE
Failed to run e2e test in private environment

### ISSUE THREAD

**Issue by shonge** [pingcap/tidb-operator#1433]
## Question
When I was following [CONTRIBUTING.md](https://github.com/pingcap/tidb-operator/blob/master/docs/CONTRIBUTING.md#run-e2e-tests) run e2e test on my laptop, got this err:
```
[root@localhost tidb-operator]# make e2e
./hack/e2e.sh
DOCKER_REGISTRY: localhost:5000
IMAGE_TAG: latest
CLUSTER: tidb-operator
KUBECONFIG: /root/.kube/kind-config-kind
KUBECONTEXT: kind-tidb-operator
SKIP_BUILD:
SKIP_IMAGE_BUILD:
SKIP_UP:
SKIP_DOWN:
KIND_DATA_HOSTPATH: none
KUBE_VERSION: v1.12.10
DOCKER_IO_MIRROR:
info: starting a new cluster
./hack/e2e.sh: line 192: GCR_IO_MIRROR: unbound variable
info: cluster 'tidb-operator' does not exist, skip shutting down the cluster
make: *** [e2e] Error 1

```
Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/pingcap/tidb-operator/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [TiDB Operator Readme](https://github.com/pingcap/tidb-operator)
  - [TiDB Operator Doc](https://github.com/pingcap/tidb-operator/tree/master/docs)

**Comment by cofyc** [comment]
sorry, newly-added `GCR_IO_MIRROR` should be optional, I'll fix it soon.

btw, `./hack/kind-cluster-build.sh` is not needed anymore, `hack/e2e.sh` will start a cluster internally.

`./hack/e2e.sh -h` will show some help information.

**Comment by shonge** [comment]
Use this command copy from Jenkins ci script can workaround the problem:
```
DOCKER_IO_MIRROR=https://dockerhub.azk8s.cn GCR_IO_MIRROR=https://gcr.azk8s.cn QUAY_IO_MIRROR=https://quay.azk8s.cn IMAGE_TAG=latest GINKGO_NODES=8 KUBE_VERSION=v1.17.0 REPORT_DIR=/root/e2e/ REPORT_PREFIX=v1.17.0_ ./hack/e2e.sh -- --ginkgo.skip=\[Serial\]
```
