### ISSUE TITLE
start tidb-server with `-advertise-address`

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb-operator#1439]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For let PD  to know the tidb address.
**Describe the feature you'd like:**

That need  `tidb-server` startup with `--advertise-address`, like TiKV:
```
❯ kubectl exec -it hot-new-tikv-1 -n xxx sh
/ # ps
PID   USER     TIME  COMMAND
    1 root     23d18 /tikv-server --pd=hot-new-pd:2379 --advertise-addr=hot-new-tikv-1.hot-new-tikv-peer.csn.svc:20160 --addr=0.0.0.0:20160 --status-addr=0.0
93992 root      0:00 sh
```

**Comment by tennix** [comment]
This argument should be added to the startup script of the configmap.

**Comment by aylei** [comment]
This change will trigger rolling-update of the tidb-servers if the configmap rollout strategy is RollingUpdate

What's the feature related to this change? @nolouch

**Comment by nolouch** [comment]
@aylei  PD wants to know all `TiDB` addresses, and do some proxy worker in TiDB, for example, which table the key belongs to?

**Comment by tennix** [comment]
Yes, this makes PD knows all the cluster component info. So we can retrieve the single source of true from PD for cluster status.
