### ISSUE TITLE
api: apis/pingcap/v1alpha1 compatibility unit tests

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#1440]
## Feature Request

**Describe the feature you'd like:**

Add unit tests to make sure any changes in `apis/pingcap/v1alpha1 ` does not break API compatibility.

**Describe alternatives you've considered:**

- integration tests, we can add in later PRs
- e2e tests, we can add in later PRs

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by aylei** [comment]
which version should be considered? For v1.0.x it is a little tricky because it cannot work without helm actually

**Comment by cofyc** [comment]
verify changes in the same version group (v1alpha1) should be backward compatible, the basic goal is 

- we should generate the same stateful sets for the old tidbcluster objects created in tidb-operator 1.0.

**Comment by aylei** [comment]
That'd be great
