### ISSUE TITLE
Call for examples in YAML

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1449]
## Call for examples in YAML

Currently, we have some plain CR yaml files in [example](https://github.com/pingcap/tidb-operator/tree/master/examples) directory which can be used directly in Kubernetes after tidb-operator was installed. Welcome to add more useful examples of TidbCluster or other CRs. You can follow this [doc](https://github.com/pingcap/tidb-operator/blob/master/docs/CONTRIBUTING.md#start-tidb-operator-locally-and-do-manual-tests) to do manual tests locally.

Examples:

- [Basic examples of TidbCluster and TidbMonitor](https://github.com/pingcap/tidb-operator/tree/master/examples/basic)
- [Use cert-manager to generate and renew certs](https://github.com/pingcap/tidb-operator/tree/master/examples/selfsigned-tls) 
- (WIP) [Tidb initializer](https://github.com/pingcap/tidb-operator/pull/1772/files)
- (WIP) [Tidb auto scaler](https://github.com/pingcap/tidb-operator/pull/1772/files)
- [ ] Network policy configuration examples #1946

**Comment by cofyc** [comment]
@aylei can you list out required example yamls before 1.1 GA? Then we can finish them first.

**Comment by benmaoer** [comment]
I'm very interested in it.

**Comment by cofyc** [comment]
Great! currently, we have some examples in [here](https://github.com/pingcap/tidb-operator/tree/master/examples). you can add some useful examples for TidbCluster or other CRs.
You can follow this [doc](https://github.com/pingcap/tidb-operator/blob/master/docs/CONTRIBUTING.md#start-tidb-operator-locally-and-do-manual-tests) to do manual tests locally.

**Comment by shonge** [comment]
There is the CRD list:
- [ ] TidbCluster
- [ ] Backup
- [ ] Restore
- [ ] BackupSchedule
- [ ] TidbInitializer
- [ ] TidbClusterAutoScaler
