### ISSUE TITLE
v1.1.0 release tracking issue

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1451]
## TiDB Operator 1.1 GA

milestone: https://github.com/pingcap/tidb-operator/milestone/9

## Pending issues

- Refactor helm chart to use CR https://github.com/pingcap/tidb-operator/issues/1387

## Tests

- stability test for TidbCluster managed by plain CR (need details)
- refine legacy cases after https://github.com/pingcap/tidb-operator/issues/1387 merged
- more compatibility cases (need details)

## Documentation

- Documents about managing TidbCluster via plain CR
  - TidbCluster
  - Backup
  - Restore
  - ScheduledBackup
  - TidbMonitor
  - TidbInitializer
- Documents about how to deploy components that is not yet managed in CR
- Documents for new features
  - Scale with deleted slots (asts)
  - Configuration management
  - Gracefully restart specific pod
  - Gracefully rolling restart component
  - Validation and defaulting
  - Configuring webhook (cert issue should be emphasized)
- Reference generation, generate the API reference of each CRD

**Comment by cofyc** [comment]
closing this because we don't use it to track 1.1.0 issues anymore.
