### ISSUE TITLE
New terraform scripts that use YAML as the user interface

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1470]
## Feature Request

Follow up #1347 .

Terraform could use the utility function [`yamldecode`](https://www.terraform.io/docs/configuration/functions/yamldecode.html) to understand the Custom Resource in YAML, then it should not be hard to drive the terraform logic through a YAML definition of `TidbCluster`.

The interface is assumed to be:

Existing cluster (all resources are pre-provisioned):
```
kubectl apply -f tidb-cluster.yaml
```

Existing cluster, but no dedicated nodes for TiDB cluster:
```
terraform apply -var 'spec=tidb-clsuter.yaml' -var 'eks=<my-eks-arn>'
```

No pre-provisioned resources:
```
terraform apply -var 'spec=tidb-cluster.yaml'
```

**Comment by aylei** [comment]
Because it is tedious to maintain the backward compatibility of this change, I tend to create new terraform module that use the CR YAML as the user interface. Anyone interested can participate, 
there will be a mentorship so no knowledge of terraform is required (but an account for one of the main cloud providers is required).

**Comment by gregwebs** [comment]
addresses #1347
