### ISSUE TITLE
more defaults and validations for resources

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1479]
## Feature Request

Reasonable defaults and validations are key to safe and friendly API. #1429 introduce some basic defaults and validations for the `TidbCluster` custom resource, but there are still lots of works for  `TidbCluster` and other resources, including `TidbMonitor`, `TidbInitializer`, `Backup`, `Restore`, and `BackupSchedule`.

- [ ] Defaults for TidbCluster
- [ ] Validation for TidbCluster
- [ ] Defaults for TidbMonitor
- [ ] Validation for TidbMonitor
- [ ] Defaults for Backup
- [ ] Validation for Backup
- [ ] Defaults for Restore
- [ ] Validation for Restore
- [ ] Defaults for BackupSchedule
- [ ] Validation for BackupSchedule

A typical PR may include the default/validation function(s), an unit test case and an optional e2e test case.

**Comment by Yisaer** [comment]
I think this could be split and added into the UCP.
