### ISSUE TITLE
Add cluster restore support

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#148]
The cluster may be created from a backup

**Comment by gregwebs** [comment]
Do we need to support both in the same operation or just support backup restore?

**Comment by weekface** [comment]
I think we should use a K8s `Job` to restore the backup data. Just like [fullbackup](https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-cluster/values.yaml#L186)

**Comment by gregwebs** [comment]
I think this is completed as designed now?

**Comment by weekface** [comment]
Yes, https://github.com/pingcap/tidb-operator/pull/160  already added restore support, closing
