### ISSUE TITLE
clearer message when TidbMonitor failed syncing because of the absence of referenced cluster

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1481]
## Bug Report

When I try to troubleshoot why my monitoring Pod did not get created, I could only find this clue in the log:

```
E0103 15:58:39.584097       1 tidb_monitor_controller.go:118] TidbMonitor: wuyelei/basic, sync failed, err: tidbcluster.pingcap.com "basic" not found, requeuing
```

There are several problems I suppose:

1. tidbcluster `basic` exists, why the controller cannot find it? It turns out there is no proper defaults for the namespace of the cluster, as mentioned in #1480 
2. Users need more clearer message to indicates why the Pod not get created, a status of TidbMonitor or an event could be much more friendly for users, who may not be willing to dig into a great deal of logs
3. The sync loop did not get requeue actually, the log is misleading

**Comment by Yisaer** [comment]
fixed in https://github.com/pingcap/tidb-operator/pull/1500
