### ISSUE TITLE
Deploy multiple TiDB services for different TiDB backend

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#1483]
## Feature Request

For computation isolation, users can start tidb-server with bigger cpu/memory to do AP queries and normal tidb-server to do TP queries. In order to support this in tidb-operator, we need to deploy multiple groups of tidb pods and expose multiple services for users.

**Comment by DanielZhangQD** [comment]
This will be covered in https://github.com/pingcap/tidb-operator/issues/2240.
