### ISSUE TITLE
Follow istio's service port requirements

### ISSUE THREAD

**Issue by PaulGrandperrin** [pingcap/tidb-operator#1512]
Hi,
I'm trying to configure an HTTP reverse proxy to expose the Grafana service.
This reverse proxy uses istio which requires to set a name so that it can know about the protocol used on top of TCP:
https://istio.io/docs/setup/additional-setup/requirements/

Without this, the service is unusable as-is from istio and requires us to fork the service definition and add `name: http` in it.

It would be very useful for all Istio users to have the `name` property correctly set in all exposed services.

I already opened a similar issue for the elastic operator if you want some context:
https://github.com/elastic/cloud-on-k8s/issues/2069

**What version of TiDB Operator are you using?**
checked on v1.0.6 and v1.1.0-alpha.4

**Comment by aylei** [comment]
Good catch.

BTW, is there any standard or de facto standard of service naming ? The name should be configurable if not, otherwise we just follow the standards.

**Comment by Yisaer** [comment]
AFAIK, only Istio need this config requirements. I agree with configurable port name even without considering the istio requirements.

**Comment by PaulGrandperrin** [comment]
I agree with @Yisaer but that would be nice to have a default name that works out of the box with Istio.
For instance, right now, the grafana service defines:
`name: grafana`
which could be changed to
`name: http-grafana`
to follow Istio guidelines/requirements

Anyway, thanks for your work, your operator is awesome :-)

**Comment by aylei** [comment]
Agreed, @Yisaer would you like to take this?

**Comment by Yisaer** [comment]
Sure @aylei

**Comment by Yisaer** [comment]
merged in #1521  @PaulGrandperrin
