### ISSUE TITLE
Provide a more convenient way to modify tikv data directory

### ISSUE THREAD

**Issue by cwen0** [pingcap/tidb-operator#1525]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I want to test TiKV with [Chaos Mesh](https://github.com/pingcap/chaos-mesh), IOChaos requires that the data directory of the application in the target pod should be a subdirectory of `PersistentVolumes`.  
In TiKV, the default data directory is `/var/lib/tikv` not a subdirectory of `PersistentVolumes`. 

**Describe the feature you'd like:**

1. Can we change the default data directory of tikv to "/var/lib/tikv/data" ?
2. Provide a more convenient way to modify tikv data directory.

**Teachability, Documentation, Adoption, Migration Strategy:**
 

1. For some users, they need to modify tikv data directory.
2. Sometimes, we can reuse the `PersistentVolumes` of tikv, eg: store log files in this pv

**Comment by cofyc** [comment]
IIUC, IOChaos requires the data directory of the application to be a subdirectory of PV. I think [the `subPath` feature](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) can help.

Is this urgent?

**Comment by cwen0** [comment]
For tikv or pd application, How to use `subPath` ?

**Comment by cofyc** [comment]
as I suggested, if IOChaos requires the data directory of the application to be the subdirectory of a volume, `subPath` can help.

the big problem right now is we hardcoded many volume configurations and assume only one data volume to be configured on PD/TiKV pods.
 
we can add the `subPath` field for primary storage of  PD/TiKV pods or we can use a new, extensive and backward-compatible way to configure storage-related configurations that can solve [this problem](https://github.com/pingcap/tidb-operator/issues/1357) too.

I'll keep you informed on our progress.

**Comment by benmaoer** [comment]
we need to change the default data directory of tikv to "/var/lib/tikv/data"  too.

**Comment by xialuo1990** [comment]
maked, I want support it

**Comment by cofyc** [comment]
we will support it in v1.1.1, any suggestions on CRD change are welcome!

**Comment by cofyc** [comment]
I made a mistake in my previous comments. I guess we need to provide a way to customize tikv data directory (currently is hard coded to `/var/lib/tikv`)t? 

cc @xialuo1990 are you working on this, can you propose a solution? I think this is useful.

**Comment by cofyc** [comment]
> I made a mistake in my previous comments. I guess we need to provide a way to customize tikv data directory (currently is hard coded to `/var/lib/tikv`)t?
> 
> cc @xialuo1990 are you working on this, can you propose a solution? I think this is useful.

One solution is we can add `dataSubDir` field to specify directory path related to the root directory, e.g. "/var/lib/tikv/data" will be used if `dataSubDir` is `data`.

The default value of `dataSubDir` is the empty string, the root directory of volume will be used, which is the current behavior.

**Comment by cofyc** [comment]
hi, @benmaoer, @xialuo1990 

I submitted a PR for the above solution. This is an example to change the tikv data directory to `/var/lib/tikv/data`. 

https://github.com/pingcap/tidb-operator/pull/2682
