### ISSUE TITLE
Make Service port name configurable for tidb and pd service

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#1538]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We need to make service port name configurable for tidb and pd service.  Currently, https://github.com/pingcap/tidb-operator/pull/1521 would make monitor service port name configurable. 

**Describe the feature you'd like:**

The default service port name for tidb is `mysql-tidb`. For the default pd service port name, when `enableTLS` is not enabled, it is `http-pd`. If enabled, the default service port name is `https-pd`.

**Comment by mikechengwei** [comment]
I have optimize pd service config before, so this issue can be assigned to me. @Yisaer

**Comment by Yisaer** [comment]
@mikechengwei Sure, feel free to go ahead.

**Comment by Yisaer** [comment]
@mikechengwei Hi, is this issue still WIP? Do I need reassign this issue?

**Comment by mikechengwei** [comment]
Sorry.I will finish it this week.ok?

**Comment by Yisaer** [comment]
@mikechengwei  Thanks, take your time.

**Comment by cofyc** [comment]
has it been resolved now?

**Comment by mikechengwei** [comment]
I think it have been finished.

**Comment by cofyc** [comment]
Thanks.
Closed via https://github.com/pingcap/tidb-operator/pull/1823.

**Comment by cofyc** [comment]
@mikechengwei next time, you can use [these keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references] in your PR to close issue automatically ;-)
