### ISSUE TITLE
e2e: "TiDBCluster Restarter: Testing restarting by annotations" is flaky

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#1539]
## Bug Report

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/2265/tests

```
Stacktrace
/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:619
Jan 10 06:33:08.985: Expected tidbcluster pod restarted
Unexpected error:
<*errors.StatusError | 0xc0010ff040>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "pods \"restarter-tidb-0\" not found",
Reason: "NotFound",
Details: {
Name: "restarter-tidb-0",
Group: "",
Kind: "pods",
UID: "",
Causes: nil,
RetryAfterSeconds: 0,
},
Code: 404,
},
}
pods "restarter-tidb-0" not found
occurred
/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:674
```

**Comment by cofyc** [comment]
@Yisaer do you have any ideas? I've seen this failure several times. Maybe a race in the e2e test.

**Comment by Yisaer** [comment]
@cofyc What about this problem After adding `preload-image function`? Recently I haven't seen this problem yet.

**Comment by cofyc** [comment]
not sure, we can close this if no more failures

**Comment by Yisaer** [comment]
Since we haven't this problem, this issue is closed.

**Comment by cofyc** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/2680/pipeline/79
