### ISSUE TITLE
Unable to schedule TiKV pods because of scheduling lock leaking

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1545]
## Bug Report

**What version of Kubernetes are you using?**

`N/A`

**What version of TiDB Operator are you using?**

`v1.1.0-alpha.3`

**What did you see instead?**

A pending TiKV Pod holds the scheduling lock forever, that Pod cannot be successfully scheduled because the original Node was deleted  and the local-volume it uses has vanished. Newly created TiKV Pods cannot get scheduling, with 500 error:

Before we figure why the root cause of the lock leaking, we could introduce a lock timeout in tidb-scheduler.

**Comment by Yisaer** [comment]
@aylei Do you know how to reproduce this problem?

**Comment by aylei** [comment]
@Yisaer No
