### ISSUE TITLE
stability test: Node object deletion case

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1546]
## Feature Request

**Is your feature request related to a problem? Please describe:**

#1545 is observed in a scenario that a Node is reclaimed by the cloud provider due to instance failure, this is different with node failure that keeps that Node object because after a Node object is deleted in kubernetes, Pods controlled by controllers will get re-scheduled and there may other subtle differences we have not yet noticed.

**Describe the feature you'd like:**

Add a case to delete the Node object in stability test.

**Describe alternatives you've considered:**

none.
**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by cofyc** [comment]
gke node deletion discussion: https://github.com/pingcap/tidb-operator/issues/408
