### ISSUE TITLE
Pitfall of controller-runtime/client

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1551]
## Feature Request

As we noted in https://github.com/pingcap/tidb-operator/pull/1522#issuecomment-574280758, controller-runtime/client will discover the group resources hosted by Kubernetes on initialization. If the specified resource is absent at that time, the **client will never be able to access the resource**.

This is generally okay for native resources, almost okay for CRDs under normal operations. But if the CRDs are deleted/created frequently and get a chance to be created after the client is initialized, there would be a problem.

**Comment by cofyc** [comment]
it is possible to disable the cache of group resources or force refresh them?

**Comment by aylei** [comment]
AFAIK, no. I plan to submit a PR to upstream this week.

For now, I think it is okay to use it in controller, but in e2e, extra caution is required. We may:

- Initialize `controller-runtime/client` in the spec instead of `BeforeEach` block in `serial.go`
- or simply avoid using it in serial test

**Comment by Yisaer** [comment]
Could we avoiding deleting CRD after each `serial item test` for now ?

**Comment by cofyc** [comment]
> Initialize controller-runtime/client in the spec instead of BeforeEach block in serial.go
+1
> Could we avoiding deleting CRD after each serial item test for now?
soon we'll add tests which may install different CRDs, e.g. upgrading tidb-operator
