### ISSUE TITLE
Use TidbMonitor for tidbcluster if monitor enabled

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#1558]
## Feature Request

As we already support `TidbMonitor`, we should use `TidbMonitor` instead of `monitor template` if `monitor` is enabled in `values.yaml` in `tidb-cluster` helm chart.

**Comment by longfangsong** [comment]
working on it

**Comment by Yisaer** [comment]
@longfangsong Thanks for your contribution. Feel free to ask if you have any questions.
