### ISSUE TITLE
Update tidb-lightning chart to accept tidb user/password credentials and use new tidb-lightning cli flag --tidb-password

### ISSUE THREAD

**Issue by jlerche** [pingcap/tidb-operator#1566]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When using the chart, passing in the tidb password is done in the config, which is cumbersome. A new cli flag was recently added to tidb-lightning, `--tidb-password` which allows passing in the password via the command line. The helm chart should be updated to accomodate this

**Describe the feature you'd like:**

A new section in the values to specify credentials. If specified, they should be passed to the job as environment variables. The startup script can use them if they are populated, otherwise fallback to the config

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
I think we can request the user to create a secret with a fixed key, e.g. `password`, in the doc or comments in values.yaml, config that secret in values.yaml, then we inject the password as env and run lightning with --tidb-password option with that env.

**Comment by DanielZhangQD** [comment]
The `--tidb-password` is supported from v3.0.9.
