### ISSUE TITLE
Provide API document for the new CRD based cluster management

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#1571]
## Feature Request

In 1.1, we've already migrated all the helm based cluster management to CRD. This makes it easy for users to integrate TiDB Operator to their own platform. However, we only have Golang SDK (the auto-generated client), no API documentation and other language SDK.

So we need to add API document for users to interact with tidb-operator.

**Comment by aylei** [comment]
There are lots of utility libs for this, e.g. https://github.com/ahmetb/gen-crd-api-reference-docs
