### ISSUE TITLE
helm upgrade pingcap/tidb-cluster return error

### ISSUE THREAD

**Issue by zhuboshuai** [pingcap/tidb-operator#1597]
## Bug Report

**What version of Kubernetes are you using?**
v1.16.3

**What version of TiDB Operator are you using?**
v1.0.5

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
local-storage

**What's the status of the TiDB cluster pods?**
they are running

**What did you do?**
helm upgrade pingcap/tidb-cluster

**What did you expect to see?**
return success

**What did you see instead?**
return error

**Comment by Yisaer** [comment]
Hi @zhuboshuai ,  Which version of `TiDB-Operator` you upgraded to? And please provide the error message returned from helm.

**Comment by zhuboshuai** [comment]
![image](https://user-images.githubusercontent.com/10694566/72797630-6ff28f00-3c7c-11ea-8f6d-8da3fae6c9ad.png)

**Comment by zhuboshuai** [comment]
I do this：https://pingcap.com/docs-cn/stable/tidb-in-kubernetes/initialize-cluster/
is it relevant ?

**Comment by Yisaer** [comment]
It seems some properties of `tidb initializer` are updated during `helm upgraded`. As `tidb initializer` is a `Job` in Kubernetes, it would cause error if the job would be updated.
