### ISSUE TITLE
TLS support for tidb-binlog

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#1605]
## Feature Request

When [tidb-binlog supports TLS](https://github.com/pingcap/tidb-binlog/issues/887), we also need to support this in tidb-operator.

**Comment by DanielZhangQD** [comment]
Pump & drainer already support TLS with PD, https://github.com/pingcap/tidb-binlog/issues/887 is to trace the TLS support with downstream databases.

**Comment by july2993** [comment]
> Pump & drainer already support TLS with PD, [pingcap/tidb-binlog#887](https://github.com/pingcap/tidb-binlog/issues/887) is to trace the TLS support with downstream databases.

Will not works actually, https://github.com/pingcap/tidb-binlog/pull/904 will fix this.

**Comment by shuijing198799** [comment]
https://github.com/pingcap/tidb-operator/pull/1739/files

**Comment by DanielZhangQD** [comment]
Fixed by #1739
