### ISSUE TITLE
User guide 

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#161]
For GCP MarketPlace we should have a guide following these guidelines:
https://cloud.google.com/marketplace/docs/partners/kubernetes-solutions/create-app-package#user-guide
Currently our MarketPlace guide just explains how to do a CLI install.

I think most of the what we are suppose to have is general documentation that we should have which applies to any tidb-operator deployment.

**Comment by tennix** [comment]
Yes, the specific tutorial is not enough for general purpose documentation. I'll work on this in the following week.
