### ISSUE TITLE
Integrate with Lightning for TLS support

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#1631]
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://github.com/pingcap/tidb-lightning/issues/262 is created for tidb-lightning to support TLS.
**Describe the feature you'd like:**

This feature is to trace the integration work in tidb-operator when the above enhancement is done.

**Comment by DanielZhangQD** [comment]
I think chart support is good for tidb-lightning, no need for a controller. @tennix

**Comment by tennix** [comment]
Yes, it's one-time job and using chart is good enough.

**Comment by DanielZhangQD** [comment]
Docs for Lightning:
https://docs.pingcap.com/zh/tidb/dev/tidb-lightning-backends
