### ISSUE TITLE
Integrate new BR for backup and restore with gcs storage

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#1634]
## Feature Request
blocked by https://github.com/tikv/tikv/pull/6283

**Is your feature request related to a problem? Please describe:**

Integrate new BR for backup and restore with gcs storage

TODOs:

- [ ] backup
- [ ] clean
- [ ] backupSchedule
- [ ] restore

**Describe the feature you'd like:**

Integrate new BR for backup and restore with gcs storage
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

https://pingcap.com/docs-cn/dev/how-to/maintain/backup-and-restore/br/

**Comment by shuijing198799** [comment]
this is done in pr https://github.com/pingcap/tidb-operator/pull/2267
but tikv still have a problem, this is the issue: https://github.com/tikv/tikv/issues/7625
