### ISSUE TITLE
backup-manager image needs to include BR binary

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#1635]
## Feature Request

**Is your feature request related to a problem? Please describe:**

backup-manager image needs to include BR binary
**Describe the feature you'd like:**

backup-manager image needs to include BR binary.
In addition, we have to consider the version management of BR and backup-manager image.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by LinuxGit** [comment]
I've commented on operator's release note.
https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-operator/values.yaml#L19
`tidb-backup-manager`'s version will be consistent with the tidb-operator's version.

**Comment by LinuxGit** [comment]
I've tested it AWS. I'll new PR when br's public download url is ready.
