### ISSUE TITLE
we need to emit important messages as k8s events

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#165]
* [x] https://github.com/pingcap/tidb-operator/pull/1373
* [ ] https://github.com/pingcap/tidb-operator/issues/1375

**Comment by cofyc** [comment]
this will be useful

**Comment by aylei** [comment]
@weekface What are the left works need to be done to address this issue in 1.1? Thanks!

**Comment by weekface** [comment]
This is a long-term optimized work that does not affect `1.1` release. All related work can be linked to this issue.
