### ISSUE TITLE
kubectl get backup should show backup status

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1658]
## Feature Request

**Is your feature request related to a problem? Please describe:**
```
➜  tidb-operator git:(master) ✗ kubectl get backup -A
NAMESPACE   NAME        BACKUPPATH   BACKUPSIZE   COMMITTS
tidb30001   br-backup                0
```
The `kubectl get` result of `backup` does not have a `status` column, which is inefficient.

**Describe the feature you'd like:**

Add a `status` column.

**Comment by namco1992** [comment]
@aylei @DanielZhangQD I would like to take this one. Is it adding a `status` column in `AdditionalPrinterColumns` sufficient? Do we need a field to indicate the current phase or I will just get the last condition from the `status.conditions`?

**Comment by DanielZhangQD** [comment]
> @aylei @DanielZhangQD I would like to take this one. Is adding a `status` column in `AdditionalPrinterColumns` sufficient? Do we need a field to indicate the current phase or I just get the last condition from the `status.conditions`?

@namco1992 Thanks for taking this!
I think it's OK to just get the last condition from the `status.conditions`, then we can see different status during the backup, e.g. `Scheduled`, `Running`, etc. right?

**Comment by namco1992** [comment]
@DanielZhangQD Thanks for the reply! But when the controller updates the status, it will append a new condition or update the existing condition's `LastTransitionTime`, which means that the last condition in the array is not necessarily the latest condition. I think it's ok that we take the last condition in the array, but maybe having a new field that gets updated when updating the condition is more robust? I don't think we can do a time comparison in JSONPath. Correct me if I'm wrong pls.

**Comment by DanielZhangQD** [comment]
> but maybe having a new field that gets updated when updating the condition is more robust

This sounds good. I think we can go with this and no need to take the condition anymore.
Please also help update for the Restore CR.
Thanks!
