### ISSUE TITLE
install failed on alicloud

### ISSUE THREAD

**Issue by jackxwu** [pingcap/tidb-operator#1659]
## Bug Report
```
module.tidb-operator.null_resource.setup-env (local-exec): Happy Helming!
module.bastion.alicloud_instance.bastion: Still creating... [10s elapsed]
module.tidb-operator.null_resource.setup-env: Creation complete after 13s [id=914946262093447724]
module.tidb-operator.data.helm_repository.pingcap: Refreshing state...
module.tidb-operator.helm_release.tidb-operator: Creating...
module.bastion.alicloud_instance.bastion: Still creating... [20s elapsed]
module.tidb-operator.helm_release.tidb-operator: Still creating... [10s elapsed]
module.bastion.alicloud_instance.bastion: Creation complete after 23s [id=i-bp1f0cym1zo1u08f9two]
module.tidb-operator.helm_release.tidb-operator: Still creating... [20s elapsed]
module.tidb-operator.helm_release.tidb-operator: Creation complete after 22s [id=tidb-operator]

Error: failed to execute "bash": parse error: Invalid numeric literal at line 1, column 2


  on ../modules/aliyun/tidb-operator/data.tf line 21, in data "external" "token":
  21: data "external" "token" {

```
**What version of Kubernetes are you using?**

1.14.8
**What version of TiDB Operator are you using?**

1.0.6
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

alicloud-disk
**What's the status of the TiDB cluster pods?**

failed creation
**What did you do?**

followed instructions https://pingcap.com/docs/stable/tidb-in-kubernetes/deploy/alibaba-cloud/

notice the "terraform 0.11.*" requirement is wrong. i had to use 0.12 otherwise "terraform init" would fail
**What did you expect to see?**
terraform apply is successful. 
**What did you see instead?**
Error: failed to execute "bash": parse error: Invalid numeric literal at line 1, column 2

  on ../modules/aliyun/tidb-operator/data.tf line 21, in data "external" "token":
  21: data "external" "token" {

**Comment by jackxwu** [comment]
i tested again using a aliyun cloud shell and tidb-opertor trunk head instead of 1.0.6 tag. i don't see this error anymore but i am having issues with PVC. at this time, my only question is what is the recommended version of tidb-operator should i use when deploying to aliyun?

**Comment by cofyc** [comment]
hi, 1.0.6 is the current stable and recommended version. btw, can you provide more information (e.g. logs)   about issues you had on aliyun cloud?

**Comment by jackxwu** [comment]
@cofyc i am using cloud shell and 1.0.6. 

`terraform apply` fails to finish because PVC is pending. see below

```
kc -n my-cluster get pv
NAME                     CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                           STORAGECLASS              REASON   AGE
d-bp1c1ol8upp6b8t2yoa0   100Gi      RWO            Retain           Bound    my-cluster/my-cluster-monitor   alicloud-disk-available            7m39s

kc -n my-cluster get pvc
NAME                 STATUS    VOLUME                   CAPACITY   ACCESS MODES   STORAGECLASS              AGE
my-cluster-monitor   Bound     d-bp1c1ol8upp6b8t2yoa0   100Gi      RWO            alicloud-disk-available   7m58s
pd-my-cluster-pd-0   Pending                                                      alicloud-disk             7m58s
pd-my-cluster-pd-1   Pending                                                      alicloud-disk             7m58s
pd-my-cluster-pd-2   Pending                                                      alicloud-disk             7m58s
```

**Comment by cofyc** [comment]
it's strange that by default no node selector should be used, do you configure node selector somewhere?  if possible, can you paste the full spec of pd pod, e.g. `my-cluster-pd-0 `?

**Comment by jackxwu** [comment]
something changed during the past 2 days. i did a `terraform destroy` just to start everything from scratch but i am block by the image pull error which i mentioned in another bug.

**Comment by cofyc** [comment]
> something changed during the past 2 days. i did a `terraform destroy` just to start everything from scratch but i am blocked by the image pull error which i mentioned in another bug. #1676

If I understand correctly, you don't have this issue anymore?
