### ISSUE TITLE
Certificate-based authentication for TiDB

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#1670]
## Feature Request

TiDB support [certificate-based authentication](https://pingcap.com/docs/dev/reference/security/cert-based-authentication/). This enhances the security for TiDB compared to password-based authentication. We should support this in tidb-operator for better security.

**Comment by tirsen** [comment]
FYI: This includes configuring the CA chain set and configuring the cert/key that tidb presents to the mysql clients. Btw, this may be (and likely is) different from the ca/cert/key it uses for internal TLS.

**Comment by tennix** [comment]
Yes, I think once we support user-provided certificate to tidb SQL layer, we can have this feature.

**Comment by tennix** [comment]
@weekface Is this already supported?

**Comment by weekface** [comment]
Yes, https://github.com/pingcap/tidb-operator/pull/1867 added certificate support for TiDB.
