### ISSUE TITLE
can't install on alicloud due to tiller image not available 

### ISSUE THREAD

**Issue by jackxwu** [pingcap/tidb-operator#1676]
## Bug Report

Failed to pull image "gcr.io/kubernetes-helm/tiller:v2.11.0": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**What version of Kubernetes are you using?**
1.14.8

**What version of TiDB Operator are you using?**
1.0.6

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

i follow the instructions here and used the cloud shell.

**What did you expect to see?**
terraform apply should work

**What did you see instead?**
module.tidb-operator.null_resource.setup-env (local-exec): Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

module.tidb-operator.null_resource.setup-env (local-exec): Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
module.tidb-operator.null_resource.setup-env (local-exec): To prevent this, run `helm init` with the --tiller-tls-verify flag.
module.tidb-operator.null_resource.setup-env (local-exec): For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
module.tidb-operator.null_resource.setup-env (local-exec): Happy Helming!
module.tidb-operator.null_resource.setup-env (local-exec): Error: could not find a ready tiller pod
module.tidb-operator.null_resource.setup-env (local-exec): Wait tiller ready
module.tidb-operator.null_resource.setup-env (local-exec): Error:

**Comment by jackxwu** [comment]
can you let me know where is this image location defined? i can't find it in tidb-operator code

**Comment by cofyc** [comment]
I guess it's due to that `k8s.io` is blocked by GFW. @aylei do you have any workaround solution in aliyun cloud?

**Comment by cofyc** [comment]
one possible solution I guess is to init `helm` manually by using a mirror image:

```
sudo helm init --upgrade -i registry.cn-hangzhou.aliyuncs.com/google_containers/tiller:v2.11.0
```

**Comment by jackxwu** [comment]
@cofyc i do have a mirror image that i use regularly. however in this case, it is terraform that runs the 'helm init'. if i run 'helm init' before 'terraform apply', since the k8s cluster has not been created, helm init wouldn't work. if i run 'helm init' after 'terraform apply', then my 'terraform apply', have already failed. can i re-run 'terraform apply' and except it to pick up from where it failed?

**Comment by cofyc** [comment]
yes, you can try `terraform apply` again, it should be idempotent. If it cannot recover, we should improve it.

**Comment by cofyc** [comment]
hi, @jackxwu 

@DanielZhangQD will solve this problem by specifying a tiller mirror image in https://github.com/pingcap/tidb-operator/pull/2012/files#diff-6450e6f282a472e1cc6fb35ea7019feeR32. you can try it later.
