### ISSUE TITLE
Can't use service ip to connect to tidb server while using TLS

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#1699]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2020-01-14T01:25:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
**What version of TiDB Operator are you using?**

```
release-1.1

TiDB: v3.0.8
```
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Connect tidb server using service ip:

```
mysql --ssl-verify-server-cert=true --ssl-cert=./cert --ssl-key=./key --ssl-ca=/etc/kubernetes/pki/ca.crt -h 10.96.45.84 -P 4000 -uroot -p
```

**What did you expect to see?**
succeed
**What did you see instead?**
```
ERROR 2026 (HY000): SSL connection error: The certificate is NOT trusted. The name in the certificate does not match the expected.
```

```
root@tidb-operator-control-plane:/# openssl x509 -in server-cert -noout -text | grep -A 1 "Subject Alternative Name"
            X509v3 Subject Alternative Name:
                DNS:demo-tidb-server, DNS:demo-tidb-server.demo
```

SAN only have DNS, no service ip.

**Comment by weekface** [comment]
the DNS name may alse be wrong, it should be?
```
DNS:demo-tidb, DNS:demo-tidb.demo
```

**Comment by tennix** [comment]
Is this expected? How other certificate works on k8s?

**Comment by weekface** [comment]
This SAN is used for mysql-client to verify the server cert, it is not related to k8s certificate i think.

**Comment by weekface** [comment]
Another question is: how can mysql-client connect to each tidb instance using TLS?

```
mysql -h <demo-tidb-0> -P 4000 ...
mysql -h <demo-tidb-1> -P 4000 ...
mysql -h <demo-tidb-2> -P 4000 ...
mysql -h <demo-tidb-n> -P 4000 ...
...

```

**Comment by cofyc** [comment]
I think this is because the bug here

https://github.com/pingcap/tidb-operator/blob/d314b251735693a000088d7011f9a5b2932f579f/pkg/manager/member/tidb_member_manager.go#L271-L280

wrong svc name constructed.

**Comment by tennix** [comment]
Inside k8s, I think current approach is assumed to access by service name. It may be difficult to know the service IP in advance.

**Comment by AstroProfundis** [comment]
It should be the name of `Service` for tidb server in k8s, so I think it should be `<namespace>-tidb`.

But it's not useful if the client is at some system that can not resolve hostnames inside k8s, and also for IPs. I believe the client can ignore server cert error with some argument and connect anyway. The only thing that really work is to ensure the client and server certs are signed by the same CA.

**Comment by weekface** [comment]
> Inside k8s, I think current approach is assumed to access by service name. It may be difficult to know the service IP in advance.

We can get `ClusterIP` before creating tidb server certificate.

**Comment by cofyc** [comment]
if we want to support all tidb instances ips, we need to add all of them into CSR. however, tidb instances may change, it's not realistic.

In addition to service IP/name, we can support 127.0.0.1 and localhost, the latter is required in the port forwarding scenario.

**Comment by weekface** [comment]
> if we want to support all tidb instances ips, we need to add all of them into CSR. however, tidb instances may change, it's not realistic.
> 
> In addition to service IP/name, we can support 127.0.0.1 and localhost, the latter is required in the port forwarding scenario.

Right, what about support these SANs:

- localhost, 127.0.0.1
- service domain:  `<tcName>-tidb, <tcName>-tidb.<ns>, <tcName>-tidb.<ns>.svc`
- service ip

**Comment by AstroProfundis** [comment]
AFAIK the tidb components connect to each other all with either Service names or Pod names, no direct IP connection inside the cluster (and also between controller to the cluster).

It's also not reasonable for MySQL client to directly connect to the Service IP -- it's not supposed to be accessible outside the k8s cluster. At least it should be something like a LB address.

**Comment by cofyc** [comment]
> It's also not reasonable for MySQL client to directly connect to the Service IP -- it's not supposed to be accessible outside the k8s cluster. At least it should be something like a LB address.

yes, we may need to allow users to specify extra domains in SAN.

**Comment by weekface** [comment]
> > if we want to support all tidb instances ips, we need to add all of them into CSR. however, tidb instances may change, it's not realistic.
> > In addition to service IP/name, we can support 127.0.0.1 and localhost, the latter is required in the port forwarding scenario.
> 
> Right, what about support these SANs:
> 
> * localhost, 127.0.0.1
> * service domain:  `<tcName>-tidb, <tcName>-tidb.<ns>, <tcName>-tidb.<ns>.svc`
> * service ip
> * user defined LB ip (only with the user custom certificate support?)

@cofyc @AstroProfundis @tennix PTAL

**Comment by AstroProfundis** [comment]
I don't really think it's necessary to have Service IP in the list.

When you have access to the Service IP, you should almost certainly also have access to the Service Name.

**Comment by cofyc** [comment]
> > if we want to support all tidb instances ips, we need to add all of them into CSR. however, tidb instances may change, it's not realistic.
> > In addition to service IP/name, we can support 127.0.0.1 and localhost, the latter is required in the port forwarding scenario.
> 
> Right, what about support these SANs:
> 
> * localhost, 127.0.0.1
> * service domain:  `<tcName>-tidb, <tcName>-tidb.<ns>, <tcName>-tidb.<ns>.svc`
> * service ip
> * user defined LB ip (only with the user custom certificate support?)

LGTM
btw, configuring extra IP or domains in SAN is independent with certificate management IMO. we can support it in our current k8s-based solution too.

**Comment by weekface** [comment]
We can give the user this ability, but they don't have to use service ip to connect.

The user can use: service ip, localhost, 127.0.0.1 to do testing.

**Comment by cofyc** [comment]
one drawback of service IP is that it may change after being recreated. it might not be a good idea as @AstroProfundis said. you can ask the user to use domains always if they want to access the tidb server in the cluster.

if the users have some special requirements, they can configure service IP in the extra IP lists. for example, when they have a special network configuration to allow the service IP to be accessible outside of the cluster.

**Comment by tennix** [comment]
Yes, we can allow users to specify extra IP list or domain names. And add the pre-defined SANs for tidb service.

**Comment by cofyc** [comment]
anyway, we need to support refreshing the certificate eventually and service IP in the cert can be updated automatically too.

**Comment by weekface** [comment]
So far, the preferred SANs:

- localhost, 127.0.0.1, ::1
- service domain: <tcName>-tidb, <tcName>-tidb.<ns>, <tcName>-tidb.<ns>.svc
- service ip (renew automatically with certificate)
- user defined IP or domain names

**Comment by tennix** [comment]
With tidb-operator 1.1, the tidb service is managed by the controller, and the service can be deleted and will be recreated by the controller automatically. What to do with the certificate if the service is deleted and recreated?

**Comment by weekface** [comment]
> With tidb-operator 1.1, the tidb service is managed by the controller, and the service can be deleted and will be recreated by the controller automatically. What to do with the certificate if the service is deleted and recreated?

They can't use service ip to connect before renewing the certificate.
