### ISSUE TITLE
UCP: Add toleration support for discovery deployment in tidb-cluster chart

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#1701]
## Description

Currently, when we deploy tidb cluster with helm chart, it's unable to configure toleration for discovery deployment. We should support it in helm chart.

## Score

* 50

## Mentor(s)

* [@DanielZhangQD](https://github.com/DanielZhangQD)

Contact the mentors: **#tidb-challenge-program** channel in [TiDB-Operator Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Kubernetes
* Helm

## Learning Materials

- [Kubernetes Concepts](https://kubernetes.io/docs/concepts/)
- [Helm chart basic](https://helm.sh/docs/chart_template_guide/getting_started/)

**Comment by cofyc** [comment]
closed via https://github.com/pingcap/tidb-operator/pull/1959.
