### ISSUE TITLE
Release a new version of the charts

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#1706]
## Bug Report

There are major problems in existing charts that have been fixed. But these have not been officially released in the helm charts system. It is difficult for users to use any chart version other than those that are released due to the potential for backwards incompatibility.

**Comment by gregwebs** [comment]
The issue here may be that we have coupled chart releases to tidb-operator releases. But they should have some de-coupling, particularly since tidb-operator is rarely released. The charts instead should depend on a version of tidb-operator.

**Comment by tennix** [comment]
Decoupling the chart with tidb-operator itself may make release complicated, and besides the helm chart also needs to have run stability tests.

With bugfixes in master branch chart, we should cherry-pick to release branch. And after running stability test, we can release a new version even if there is no Go code change.

**Comment by gregwebs** [comment]
Will we be able to produce a new release?

**Comment by cofyc** [comment]
release 1.1.0-beta.2 next week?

**Comment by tennix** [comment]
No, we should release 1.0.7. And for 1.1, we can release a new beta version when some TLS issues get fixed.

**Comment by cofyc** [comment]
in 1.0, there are only some cleanups since the last release v1.0.6, we can wait for some issues which affect 1.0 (including charts) to be fixed.

https://github.com/pingcap/tidb-operator/compare/v1.0.6...release-1.0

in 1.1, I'll release a new beta version soon.

**Comment by cofyc** [comment]
closed via https://github.com/pingcap/tidb-operator/pull/1789.
