### ISSUE TITLE
何时能支持helm 3.0 以上版本???

### ISSUE THREAD

**Issue by knoxville9** [pingcap/tidb-operator#1765]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/pingcap/tidb-operator/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [TiDB Operator Readme](https://github.com/pingcap/tidb-operator)
  - [TiDB Operator Doc](https://github.com/pingcap/tidb-operator/tree/master/docs)

**Comment by cofyc** [comment]
we didn't use helm3 in our testing, so there might some incompatibilities with helm 3. can you list the problems you encountered when you use our charts with helm 3? we can fix one by one.

**Comment by mikechengwei** [comment]
I use helm3 to deploy, no problem for now

**Comment by Yisaer** [comment]
Thanks @mikechengwei , It seems helm3 could support managing tidb-operator.
