### ISSUE TITLE
Specify ServiceAccount for tidb-lightning

### ISSUE THREAD

**Issue by tirsen** [pingcap/tidb-operator#1781]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Right now tidb-lightning can only run as the default service account

**Describe the feature you'd like:**
We would like to be able to run tidb-lightning as a different service account so that it can access S3 through an IAM role. Just like tidb-backup currently can:
```
# Kubernetes service account to use
serviceAccount: s3-reader
```

**Comment by DanielZhangQD** [comment]
@shuijing198799 Please make sure that both IAM role with annotations and serviceAccount work as expected.

**Comment by shuijing198799** [comment]
It wiil support specify a serviceaccount to lightning after this PR is merge https://github.com/pingcap/tidb-operator/pull/1975
