### ISSUE TITLE
PD pod unschedulable with scheduler extender

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#180]
From #170, when deploying a TiDB cluster in DinD with Local PV, even we specify `WaitForFirstConsumer` binding mode for local volume. The PV and PVC still may get bound before the pod is scheduled.

Previously we don't have scheduler extender, and all pods can be scheduled. But now when adding scheduler extender, PD pods are not allowed to schedule on the same node. So when PV and PVC are bound before pod scheduling, the pod can actually only be scheduled on the node that PV belongs to. But the HA predicate would refuse to schedule on that node, causing pod unschedulable.

This may be related to local volume scheduling [bug](https://github.com/kubernetes/kubernetes/pull/67556) which uses affinity and anti-affinity rules. It is fixed in Kubernetes v1.12.

**Comment by tennix** [comment]
This seems affect all location based persistent volumes scheduling. For example GKE regional persistent disk as in #241

**Comment by tlightsky** [comment]
i meet this issue in OSX DinD env too

**Comment by weekface** [comment]
@tlightsky Are you using `manifests/local-dind/dind-cluster-v1.10.sh` to build your DinD env?

**Comment by gregwebs** [comment]
@tlightsky what is the K8s version?

**Comment by tlightsky** [comment]
@weekface yes, i used version v1.0.0-beta.1,
then i switched to master, then clean/up again, this problem disappear

**Comment by weekface** [comment]
this should be fixed in the newer version.
