### ISSUE TITLE
Support Pump and Drainer user-defined certificates

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#1800]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Following up: https://github.com/pingcap/tidb-operator/issues/1748#issuecomment-591768552

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mightyguava** [comment]
Is this a duplicate? https://github.com/pingcap/tidb-operator/issues/1605

**Comment by weekface** [comment]
operator has support tidb-binlog user-defined certificate with #1739 , closing.
