### ISSUE TITLE
Add locking replicas ability for Auto-scaling

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#1818]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When we created TidbClusterAutoScaler for TidbCluster, there exists the problem that we should sync the current TidbCluster Replicas between the local configuration and the online cluster configuration which is not user-friendly.

For example:
1. create tidbcluster with 3 pd ,3 tikv 2 tidb.
2. create tidbclusterAutoscaler with 5max, 3 min  for tikv.
3. the tikv replicas in-cluster become 4 caused by auto-scaler
4. user updated the tikv config by local yaml or helm with previous tikv replicas (3)
5. the tikv configuration was updated, but the replicas is also changed.

**Describe the feature you'd like:**

Add `locking` in TidbClusterAutoScaler Spec. When `locking` is enabled, the target TidbCluster's Replicas would only be changed by TidbClusterAutoScaler, any manualy updating tidbcluster operation would not affect the tidbclusters replicas.

**Comment by yeya24** [comment]
Hello @Yisaer, anyone already worked on this feature? If not, I am interested in working on it. 😄

**Comment by Yisaer** [comment]
@yeya24  Thanks, take your time
