### ISSUE TITLE
UCP: Enhance tidbclusterautoscaler output information in `kubectl get`

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#1820]
## Description

Currently, when we execute `kubectl get ta`, we only see basic information about the tidbclusterautoscaler.

```bash
$ kubectl get ta   
NAME     AGE
scaler   128m
```

 We need to show more useful information, for example:

```bash
$ kubectl get ta   
NAME     AGE  TiKV  MaxReplicas   MinReplicas  TiDB  MaxReplicas   MinReplicas
scaler   128m  3         5            3          2       3              2
```

We can configure some additional print columns in our CRD manifest yaml. There are some examples in `pkg/util/crdutil.go`. You can run `hack/update-crd-groups.sh` to update our CRD manifest yaml file.

## Score

* 50

## Mentor(s)

* [@Yisaer](https://github.com/Yisaer)

Contact the mentors: **#tidb-challenge-program** channel in [TiDB-Operator Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* Kubernetes

## Learning Materials

- [Extend the Kubernetes API with CustomResourceDefinitions](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/)

**Comment by shonge** [comment]
```
[root@localhost basic]# kn t1 get ta
NAME       TIDB-MAXREPLICAS   TIDB-MINREPLICAS   TIKV-MAXREPLICAS   TIKV-MINREPLICAS
basic-autoscaler   5                  2                  5                  2
```
