### ISSUE TITLE
cannot enable tidb-server client auto-generated tls feature on the fly 

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#1828]
## Bug Report

**What version of TiDB Operator are you using?**

master

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

this is because we sync tls secrets only when the tidb sts does not exist.

https://github.com/pingcap/tidb-operator/blob/9b69f6d826d1743f4a289e4f2dfedfdaf21ba76e/pkg/manager/member/tidb_member_manager.go#L173-L201

**Comment by weekface** [comment]
duplicated with #https://github.com/pingcap/tidb-operator/issues/1804

**Comment by cofyc** [comment]
One difference is this is the problem with tidb-server tls for clients, not peer tls between components.

**Comment by cofyc** [comment]
auto-generated tls feature has been abandoned.
