### ISSUE TITLE
terraform working with helm 3

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#1829]
Helm 3 doesn't work with our terraform. Minimum changes that are needed would be in verstions.tf for helm to use 1.0.0

I am not sure if current usages of `helm init` would be backwards compatible.

Users will start experiencing this as a bug now that helm 3 is the new default. This happened to @kolbe

**Comment by mikechengwei** [comment]
I have no problems using helm3 deployment. Helm init  way and helm3 deployment  i think they are backwards compatible. 
In my opinion,we will abandon the helm deployment way and use yaml to deploy, it not need to care.
