### ISSUE TITLE
Upgrading K8s to v1.12

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#183]
Kubernetes v1.12 has been released for about 2 months. The local persistent volume scheduling bug #180 has been fixed in v1.12. We should consider upgrading to this version.

**Comment by gregwebs** [comment]
GCP is only at 1.11.2 right now :(

What does it mean to upgrade to 1.12? Can you list out the new APIs that would be used?

**Comment by tennix** [comment]
I don't think we'll use any new API when we upgrade our DinD to v1.12. We just want to make sure the scheduling issue #180 won't happen in our DinD testing environment. We can still use v1.10 or later versions.

**Comment by gregwebs** [comment]
:+1:

**Comment by gregwebs** [comment]
I am all for doing anything to make DinD more reliable
