### ISSUE TITLE
A notification mechanism is required when TiKV is restarted after 35 minutes of downtime

### ISSUE THREAD

**Issue by benmaoer** [pingcap/tidb-operator#1863]
## Feature Request

A notification mechanism is required when TiKV is restarted after 35 minutes of downtime. Now, the cluster has more TiKV instances than we needs.
Furthermore, the data of the crashed TiKV instance has lagged behind other instances. At this time, the evict-leader scheduling strategy needs to be added for the crash TiKV to avoid significant increase in response delay.

**Comment by DanielZhangQD** [comment]
@benmaoer Thanks for reporting this issue, we will evaluate this request.

**Comment by DanielZhangQD** [comment]
More events are added in https://github.com/pingcap/tidb-operator/pull/2150.
