### ISSUE TITLE
Does TiDB / PD / TiKV has a DNS cache?  If coredns crash or hangs, the maximum tolerance time of the whole TiDB cluster?

### ISSUE THREAD

**Issue by benmaoer** [pingcap/tidb-operator#1864]
## Question
Does TiDB / PD / TiKV has a DNS cache?  If coredns crash or hangs, the maximum tolerance time of the whole TiDB cluster?

**Comment by DanielZhangQD** [comment]
@benmaoer We will confirm with TiDB / PD / TiKV team and update the info here, thanks!

**Comment by Yisaer** [comment]
For PD / Tikv / PD, the address they use is the FQDN of each service. I think there's no difference between TidbCluster and other normal pods in DNS handling on Kubernetes.

**Comment by Yisaer** [comment]
I'm not sure whether I answered your question. If you have any further question about dns policy, you can reopen this issue. @benmaoer
