### ISSUE TITLE
Want Canary Deployments for tidb-operator

### ISSUE THREAD

**Issue by benmaoer** [pingcap/tidb-operator#1866]
## Feature Request
I always worry about my tidb cluster,  when I upgrading the tidb-operator. I want Canary Deployments. Maybe we can label the tidb cluster,  tidb-cluster-1 with v1.0.6 label, means this tidb cluster is controlled by v1.0.6 operator,  tidb-cluster-2 v1.0.5 label, means this tidb cluster is controlled by v1.0.5 operator, then, when we upgrade tidb-operator to v1.0.6, it only controll tidb-cluster-1, if new version has something wrong, we can rollback quickly without an accident. It's more stable.

**Comment by Yisaer** [comment]
Thanks for your suggestion. In fact, we are now trying to provide the way to make tidbcluster safer during operator upgrading. We would release the document about it soon.

**Comment by DanielZhangQD** [comment]
@benmaoer Hi, Could you please describe your request in more detail? 
What's your essential requirement? To avoid rolling updates of existing TiDB Clusters?
Do you want the canary upgrade of tidb-operator?  Actually, as a deployment, tidb-operator can be rolled back very easily.

**Comment by weekface** [comment]
@benmaoer was talking about support several tidb-operator instance in the same K8s cluster. This is a very cool feature for users.

**Comment by DanielZhangQD** [comment]
Traced in https://github.com/pingcap/tidb-operator/issues/3166.
