### ISSUE TITLE
grafana not working

### ISSUE THREAD

**Issue by tkalanick** [pingcap/tidb-operator#189]
i cloned the tidb-operator 4 days ago and followed to tutorial to launch a TiDB cluster to Google Kubernetes. i was able to run queries using a MySql client, so i think the cluster is working. however i don't see any data in my Grafana dashboard

here is what i did on my laptop:
> kubectl port-forward -n tidb svc/demo-grafana 3000:3000 
>open a browser and go to: http://localhost:3000/dashboard/db/tidb-cluster-overview?refresh=1m&orgId=1

a screen shot is attached. i have added instance names and namespace names later but it didn't seem to help.
<img width="1195" alt="screen shot 2018-11-20 at 3 33 26 pm" src="https://user-images.githubusercontent.com/45215660/48810041-f9ef4280-ecdb-11e8-9b6e-c43ffeb1155d.png">

**Comment by tkalanick** [comment]
problem seems to be caused by the data source. once i switch from "tidb-cluster" to default, data shows up.

<img width="481" alt="screen shot 2018-11-20 at 4 54 37 pm" src="https://user-images.githubusercontent.com/45215660/48811971-07f59100-ece5-11e8-84b7-ff5696f0c329.png">

**Comment by tennix** [comment]
The overview dashboard contains `system info` which is supposed to not show any metrics for tidb-operator managed tidb clusters. Did other dashboards show the metrics correctly without changing datasource? @tkalanick

**Comment by tkalanick** [comment]
nothing shows up on other dashboards.

actually the "default" data source points to "random walk", so the graph that i see is only a simulation?

**Comment by tennix** [comment]
@tkalanick This is a bug which was introduced in recent commits. We've changed the pod labels, but the Prometheus configuration still uses the old label, result in no targets to scrape. We'll fix it asap.

**Comment by boxuan666** [comment]
I have the same issue like this, and my_prometheus-config.tpl file already modified. same like #193 

there still no target in my prometheus.. why?

**Comment by tennix** [comment]
@boxuan666 You manually modified the `_prometheus-config.tpl` and run `helm upgrade`? Prometheus won't automatically reload configuration, you have to exec into prometheus container and run `kill -SIGHUP 1` to force prometheus to reload the configuration file to make the modification take effect.

**Comment by boxuan666** [comment]
@tennix  Not modified by manually. When I downloaded it, it was like this.

**Comment by tennix** [comment]
@boxuan666 So you just run `helm upgrade`? As I stated above, you should exec into prometheus container and run `kill -SIGHUP 1` to make the upgrade take effect.

**Comment by boxuan666** [comment]
@tennix 才看见你是北京的....老哥我那意思 我没改过这个`_prometheus-config.tpl`, 这个文件下载下来就是这样的. 但是我的Prometheus还是获取不到数据,我看tidb的metrics是可以暴露数据出来的

**Comment by tennix** [comment]
@boxuan666 What version did you use? As stated before https://github.com/pingcap/tidb-operator/issues/189#issuecomment-440925668 you should use charts after #193 commit. That PR fixes the bug.

**Comment by danparisi** [comment]
I think I am having the same issue. 
I deploied the cluster monitor via the CR:

`
apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: tidb-cluster
spec:
  clusters:
    - name: tidb-cluster
  storage: 5G
  persistent: true
  storageClassName: ...
  nodeSelector:
    ...
  prometheus:
    baseImage: prom/prometheus
    version: v2.11.1
  grafana:
    baseImage: grafana/grafana
    version: 6.0.1
  initializer:
    baseImage: pingcap/tidb-monitor-initializer
    version: v3.0.13
  reloader:
    baseImage: pingcap/tidb-monitor-reloader
    version: v1.0.1
  imagePullPolicy: IfNotPresent
`
