### ISSUE TITLE
backup and restore with mydumper and loader served by backup controller needs to support IAM role

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#1897]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Refer to #1884, #1861 
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
The rclone version also needs to be updated, please refer to https://github.com/pingcap/tidb-operator/pull/1817#issuecomment-592885403 and https://github.com/pingcap/tidb-cloud-backup/pull/7/files

**Comment by shuijing198799** [comment]
https://github.com/pingcap/tidb-operator/pull/1970 It is OK after merge this PR
