### ISSUE TITLE
Allow resources configuration for InitContainer in TiDB initializer job

### ISSUE THREAD

**Issue by tfulcrand** [pingcap/tidb-operator#1911]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When we run TiDB cluster with init options for TiDB component in a namespace with defined quotas, we get an error for `tidb-cluster-tidb-initializer` job object like 
```Warning  FailedCreate  3s    job-controller  Error creating: pods "tidb-cluster-tidb-initializer-cwx85" is forbidden: failed quota: karazhan-quota: must specify limits.memory,requests.cpu,requests.memory```
Investigations show us that the `initContainer` of this job has no ressources defined.

**Describe the feature you'd like:**

Allow to use the TiDB initializer job in namespace with quotas.

**Comment by DanielZhangQD** [comment]
@tfulcrand Just set `tidb.initializer.resources` in values.yaml, which is introduced in v1.0.3.

**Comment by DanielZhangQD** [comment]
@tfulcrand Did you try the above setting?

**Comment by tfulcrand** [comment]
@DanielZhangQD Yes we set `tidb.initializer.resources` in values.yaml but it dosen't fix the problem.
If you take a look of [tidb-initializer-job.yaml](https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-cluster/templates/tidb-initializer-job.yaml#L22), you can see that initContainers named `wait` has no `resources` line defined while containers named `mysql-client` has one.
We believe that this difference explains the problem. We haven't had the time to test adding this missing line yet but as soon as this is done we will offer you a fix.

**Comment by DanielZhangQD** [comment]
@tfulcrand Yes, you're right. Looking forward to your contribution, Thanks!

**Comment by tfulcrand** [comment]
@DanielZhangQD Is there something wrong with the PR ?

**Comment by cofyc** [comment]
@tfulcrand 
hi, nothing wrong with the PR, but we may miss the PR. ping us if we don't respond in time.

by the way, you can join our stack channel `#sig-tidb-operator` via [this link (https://pingcap.com/tidbslack/).

**Comment by DanielZhangQD** [comment]
@tfulcrand PR merged, sorry for the late review, thanks for your contribution!
