### ISSUE TITLE
Integrate with TiDB v3.1 for configuration parameters update

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#1920]
## Feature Request

**Is your feature request related to a problem? Please describe:**

There are configuration parameters update, e.g. add, remove, type change, default value modification, etc. for the components of TiDB v3.1.

**Describe the feature you'd like:**

TiDB Operator needs to update for the configuration changes to support TiDB v3.1.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Yisaer** [comment]
According to the document about the configuration in the reference for tidb-server / tikv-server / pd-server,  there is a few newly added configuration for these components. And the operator already has updated it. So I think there is no need for this issue or you can provide more detail?

@DanielZhangQD

**Comment by DanielZhangQD** [comment]
@Yisaer If you are sure that all the newly added parameters in TiDB v3.1 are supported, feel free to close this issue.

**Comment by Yisaer** [comment]
For tidb: #1906 
For pd: #1928 
For tikv: there is no change.
