### ISSUE TITLE
CR examples for TiDB Operator v1.1

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#1921]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We have to provide CR examples so that users do not have to write the CR from scratch:

- TidbCluster
- TidbMonitor
- TidbCluster Autoscaler

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
It's better that we provide reasonable detailed examples that users can figure out how to configure most of the fields without referring to the API doc.

**Comment by Yisaer** [comment]
Close in #1772
