### ISSUE TITLE
Guaranteed vertically scaling

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1923]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, if user vertically scales TiKV servers, the new Pod may not get running due to resources limitation, which is bad for availability.

**Describe the feature you'd like:**

Provide a mechanism to ensure guaranteed vertically scaling.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by gregwebs** [comment]
Another possible guarantee is to guarantee that at most 1 TiKV pod will fail to scale vertically, and that it will be rolled back on failure in a short time frame.

**Comment by Yisaer** [comment]
@aylei  Could you give more detail about the `vertically scale`? Does this meaning changing the `resources.requests` or the configuration in `tikv.config`?

**Comment by aylei** [comment]
change the resources requests
