### ISSUE TITLE
Backup should unify source cluster config

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1952]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When use br to backup tidb, I have to configure the source cluster in two different sections and this is error-prone:

![image](https://user-images.githubusercontent.com/18556593/76828509-1c578880-685c-11ea-8ab6-0a96c08d1c32.png)

**Describe the feature you'd like:**

Unify the source cluster config in backup cr

**Comment by DanielZhangQD** [comment]
Duplicate with https://github.com/pingcap/tidb-operator/issues/2287.
