### ISSUE TITLE
pod webhook does not work if asts controller not installed in namespace `pingcap`

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#1958]
## Bug Report

https://github.com/pingcap/tidb-operator/blob/master/pkg/webhook/pod/pods.go#L51

our code hard-coded advanced-statefulset controller namespace as `pingcap` and our CI install it in this namespace and works without a problem. but this might not be true in user environments.

**Comment by Yisaer** [comment]
good catch. I will fix it soon.
