### ISSUE TITLE
Graceful scale in for pd/tikv

### ISSUE THREAD

**Issue by xiaojingchen** [pingcap/tidb-operator#198]
current upgrade feature is graceful but the scale in without graceful. To minimize the impact of scale on tidb clusters, tidb-operator should ensure scale in is graceful like the upgrade.

**Comment by tennix** [comment]
When scaled in, the offline TiKV still serves the client request, so no extra step is needed for TiKV to do graceful scaling in. While for PD, I think you should check if removing leader member will try to transfer leader first, if it's already done by PD then no extra step is needed too.
