### ISSUE TITLE
suggestions of docs about helm

### ISSUE THREAD

**Issue by Sullivan12138** [pingcap/tidb-operator#2021]
I was reading PingCAP's guide doc about starting a k8s cluster. When I reached the `helm` part, I found that with the doc's instruction there would be an error:`Error: unknown command "init" for "helm"`. I searched Google and found that in **helm3** `helm init` has been deprecated. [https://helm.sh/docs/faq/#removal-of-tiller](https://helm.sh/docs/faq/#removal-of-tiller)
So I suggest that you may modify the doc.
![image](https://user-images.githubusercontent.com/44030194/77384404-43fca280-6dc0-11ea-9127-c479a5559c4e.png)
The doc is [here](https://pingcap.com/docs-cn/stable/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-minikube/).
Also, `helm search hub tidb-cluster -l` may not be useful. 
![image](https://user-images.githubusercontent.com/44030194/77384556-ac4b8400-6dc0-11ea-95c7-f4074eb4157f.png)
Instead, I think the command is replaced by `helm search repo tidb-cluster`, cause the `search` command has changed.
![image](https://user-images.githubusercontent.com/44030194/77384631-d3a25100-6dc0-11ea-9524-f6eee1b8c4a3.png)

**Comment by Yisaer** [comment]
Thanks for your suggestion.  In this page [使用 Helm](https://pingcap.com/docs-cn/stable/tidb-in-kubernetes/reference/tools/in-kubernetes/#%E4%BD%BF%E7%94%A8-helm) , we have already clarified the required version of helm. I think we would make it more convenient for users to know it.

**Comment by Sullivan12138** [comment]
> Thanks for your suggestion. In this page [使用 Helm](https://pingcap.com/docs-cn/stable/tidb-in-kubernetes/reference/tools/in-kubernetes/#%E4%BD%BF%E7%94%A8-helm) , we have already clarified the required version of helm. I think we would make it more convenient for users to know it.

Sorry, I didn't see the required version. But make it more convenient will be better.
