### ISSUE TITLE
A question about installing chart

### ISSUE THREAD

**Issue by Sullivan12138** [pingcap/tidb-operator#2033]
I followed the instructions in the doc in PingCAP's official web, but I got a lot of errors.
![image](https://user-images.githubusercontent.com/44030194/77569489-3ef53b80-6f05-11ea-951d-e21516945e9a.png)

![image](https://user-images.githubusercontent.com/44030194/77569453-30a71f80-6f05-11ea-8237-73c92c4b2a09.png)
I do have the values-tidb-operator.yaml, but not in /home/tidb/tidb-operator/, it's in ~/tidb/tidb-operator/. I create it in that directory because the directory /home/tidb cann't be created using common user, must be in root.
So how could I fix the question?

**Comment by cofyc** [comment]
according to errors, you must apply our CRD yaml first, `kubectl apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/v1.0.6/manifests/crd.yaml`.

**Comment by DanielZhangQD** [comment]
Please also make sure your helm version < 3.0.

**Comment by Sullivan12138** [comment]
> Please also make sure your helm version < 3.0.

It is 2.16.4.

**Comment by Sullivan12138** [comment]
> Are you using Helm and Tiller of version 2.16.x?
> It seems that something wrong with the latest versions, please downgrade both **Helm** and **Tiller** to 2.13.x and try again.
> We will figure out the version that the installation is broken.

Yes, I use the version 2.16.4. How to downgrade? Will  uninstall and install a new one be ok?

**Comment by Sullivan12138** [comment]
> Are you using Helm and Tiller of version 2.16.x?
> It seems that something wrong with the latest versions, please downgrade both **Helm** and **Tiller** to 2.13.x and try again.
> We will figure out the version that the installation is broken.

I changed the version to 2.13.1 and finally it works, thanks a lot!

**Comment by Sullivan12138** [comment]
> according to errors, you must apply our CRD yaml first, `kubectl apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/v1.0.6/manifests/crd.yaml`.

Thank you, it turns out that the probelm is about helm's version. I've solved it.

**Comment by cofyc** [comment]
Thanks for reporting this issue! I think it's time to add tests for helm 3 now.
