### ISSUE TITLE
User guide: vertically scaling TiDB

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#204]
What is the procedure to scale TiDB SQL vertically (even if it creates down-time)?

see #191 for scaling PD and TiKV vertically.

**Comment by gregwebs** [comment]
This should just work by adjusting the resource requests. However, one needs to first ensure there is available underlying capacity (e.g. provision a new and bigger node pool).

**Comment by aylei** [comment]
closed via https://github.com/pingcap/docs/pull/1468
