### ISSUE TITLE
Support customized prometheus config in tidbmonitor

### ISSUE THREAD

**Issue by yeya24** [pingcap/tidb-operator#2053]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now the prometheus config in tidbmonitor is hardcoded, and it only get the metrics from pd, tikv and tidb. It would be nice to make this config template configurable, so that we can monitor some other components like tiflash.

**Describe the feature you'd like:**

Maybe add a new field in tidbmonitor to use an external configmap

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
@yeya24 The Prometheus configs are provided by tidb-monitor-initializer, we will integrate with the monitoring of TiFlash in the near future.

**Comment by Yisaer** [comment]
In this case, I think the TidbMonitor could provide an external configmap interface that supports user to mount their own `scrape Rule`. What do you think? @yeya24

**Comment by yeya24** [comment]
@Yisaer , thanks. I think this is a more flexible way.  I also hope maybe we can use validation webhook to validate the provided configuration.

**Comment by yeya24** [comment]
Close this since duplicate with #2180
