### ISSUE TITLE
A question about monitoring cluster

### ISSUE THREAD

**Issue by Sullivan12138** [pingcap/tidb-operator#2055]
I create a tidb cluster on a remote machine, which has no GUI. How can I monitor the cluster on my own computer's Internet Browser using Grafana?

**Comment by cofyc** [comment]
hi,

You can use `kubectl portfward` to forward grafana svc to localhost.

```
kubect portforward -n <ns> svc/<tidb-cluster>-grafana -p 3000:3000
```

then open your browser to visit http://localhost:3000

Or if your  Kubernetes cluster has an ingress controller installed e.g. [ingress-nginx](https://github.com/kubernetes/ingress-nginx), you can create an [ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) for grafana service. Note that to make this work, you need to have a domain registered.

**Comment by Sullivan12138** [comment]
> kubectl port-forward -n <ns> svc/<tidb-cluster>-grafana -p 3000:3000

But my k8s cluster is on a remote server which I can only connect to it using ssh. How can I watch the  cluster on my own computer?

**Comment by Yisaer** [comment]
If I understand right, you need to deploy your monitor on your on computer?  I think the existed monitor rules can't help this.

**Comment by cofyc** [comment]
> > kubectl port-forward -n  svc/-grafana -p 3000:3000
> 
> But my k8s cluster is on a remote server which I can only connect to it using ssh. How can I watch the cluster on my own computer?

does it have a public IP? you can configure `kube-apiserver` to listen on the public IP of your remote machine (`--apiserver-advertise-address`), then you can access the k8s cluster remotely. please remember that you must update the apiserver address in your kubeconfig file.

anyway, if you want to access remote service (no matter what service in your remote machine), you must 1) expose the service itself via public IP of your remote machine (e.g. `nginx ingress`) or 2) using a proxy (e.g. `kubectl port-forward`).

**Comment by Yisaer** [comment]
If you have any question about monitoring, feel free to open this issue. @Sullivan12138
