### ISSUE TITLE
expose server CPU metrics for TiDB and TiPD

### ISSUE THREAD

**Issue by tkalanick** [pingcap/tidb-operator#208]
only "tikv_thread_cpu_seconds_total" is exposed to grafana. please add cpu metrics for TiDB and TiPD

**Comment by tennix** [comment]
TiDB and PD don't have CPU metrics by itself. The Overview dashboard gets these metrics from node-exporter. But node-exporter is not managed by tidb-operator. Usually only one node-exporter daemonset will be deployed in a Kubernetes and this is usually deployed globally by kubernetes system administrator.
If you want to see PD/TiDB CPU metrics, you can deploy [monitor addons](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/prometheus) to your kubernetes.

**Comment by tennix** [comment]
I've just confirmed with TiDB team, they'll expose CPU metrics for TiDB in tidb-server itself.

**Comment by zz-jason** [comment]
See this issue for more detail: https://github.com/pingcap/tidb/issues/8539

**Comment by gregwebs** [comment]
TiDB now exposes its own CPU measurement through prometheus. In general I recommend running netdata to look at metrics that are not specific to TiDB.
