### ISSUE TITLE
Add more event for tidbcluster

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2096]
## Feature Request

Currently, we had little method to know what happened for a specific tidbcluster. We have to find logs in Operator. I think we could use event for some case to make user easier to know what happened in their tidbcluster.

For example, we could record the event for failover / scaling.

**Comment by cofyc** [comment]
btw, we may need to record some conditions of tidb cluster objects, then we can emit events on state change (https://github.com/pingcap/tidb-operator/issues/2011).

**Comment by cofyc** [comment]
should this be added into 1.1.0 milestone?

**Comment by Yisaer** [comment]
yes
