### ISSUE TITLE
Use "Pod Topology Spread Constraints" to achieve high availability

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#2110]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We can use [topology spread constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints) to control how Pods are spread across your cluster among failure-domains such as regions, zones, nodes, and other user-defined topology domains. This can help to achieve high availability as well as efficient resource utilization.

This feature provides flexible options to distribute Pods evenly across different topology domains  to achieve high availability or cost-saving. 

In Kubernetes, directives related to “Affinity” control how Pods are scheduled - **more packed or more scattered.**

It can replace [HA](https://github.com/pingcap/tidb-operator/blob/master/pkg/scheduler/predicates/ha.go) feature in TiDB Scheduler.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by danche** [comment]
the feature of topology spread constraints is an alpha version in 1.16.  So our k8s maintainers refuse to open the feature.  We have developed a high availability strategy like topology. 
We only modified the ha.go and changed the node variable to topology key. 

We think it's useful to low k8s versions. So can we commit the code to review? @weekface

**Comment by weekface** [comment]
@danche Of course you can. I think it is useful for low k8s versions too. Feel free to open this PR.

**Comment by DanielZhangQD** [comment]
We need to support this for PD/TiDB/TiKV/TiFlash/Pump/TiCDC/DM master/DM worker.
