### ISSUE TITLE
TiDB Pod Probe doesn't work with TLS

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#2132]
TiDB Pod now has a Probe to probe TiDB Server's `/status` path. K8s Probe [cannot send](https://github.com/kubernetes/kubernetes/issues/60952) client certificate when requested. Now that TiDB Server has enabled TLS, TiDB Server has forced to verify the client certificate, so the Probe always failed to work.

```
Readiness probe failed: Get https://10.244.0.17:10080/status: remote error: tls: bad certificate
```

**Comment by tennix** [comment]
Can we use a command to do the health check? We can use local tls certificate to request port 10080.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command

**Comment by tennix** [comment]
However, tidb docker image does not contain `curl` and the builtin `wget` does not support specifying TLS certificates. So in order to use command to do health check, we may need to install curl in the tidb docker image.
