### ISSUE TITLE
Auto-scaler support tikv hot-read metric.

### ISSUE THREAD

**Issue by shonge** [pingcap/tidb-operator#2146]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For now, auto-scaler only support pod cpu metric, and scaling out tikv is follower-read pod, so I suggest auto-scaler support tikv hot-read metric to scaling out/in.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Yisaer** [comment]
This seems a good idea. We could auto scale-out tikv when the cluster encounters the hot region reading situation then we would try to schedule the hot region to the newly created tikv and split the hot region reading pressure.
