### ISSUE TITLE
Add some useful additional printer columns for TidbMonitor

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#2169]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now it uses the default columns.

```
$ kubectl get tidbmonitor
NAME    AGE
basic   23s
```

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by cofyc** [comment]
@mikechengwei 
in production, what information is useful and should be printed?

**Comment by mikechengwei** [comment]
TidbMonitor have grafana ,prometheus,reloader and additional container. Do we need to show their status like TidbCluster.
```
NAME                PD                                              STORAGE   READY   DESIRE   TIKV                                              STORAGE   READY   DESIRE   TIDB   READY   DESIRE
```

**Comment by cofyc** [comment]
maybe we can show their running status? then we can quickly check if components have problems or not

**Comment by mikechengwei** [comment]
Do you mean `ready` and `desire` info?  Tidbmonitor is running in a pod with multiple containers, i think we can't use `ready` and `desire` columns. We can use `ready` column the same as in pod columns.

**Comment by mikechengwei** [comment]
We can inherit tidbmonitor pod info.  `READY` ,  `STATUS` and  `RESTARTS` columns . What do you think?

**Comment by cofyc** [comment]
I think it will be useful.

**Comment by mikechengwei** [comment]
Ok, i can do it and do it well soon.

**Comment by cofyc** [comment]
thanks! for users who do not know technical details, they may check the status `TidbMonitor` to see if the monitor is ready or not. I guess it will be useful if we can print more information by default.
