### ISSUE TITLE
Support sidecar in tidbmonitor

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#2175]
## Feature Request

**Is your feature request related to a problem? 
None.

**Describe the feature you'd like:**
Many companies use prometheus thanos architecture,i think we need to support thanos container in tidbmonitor.

**Describe alternatives you've considered:**
Support thanos image , version,port  options in tidbmonitor.

I can do this.

**Comment by yeya24** [comment]
Is this really a feature belongs to tidb monitor? Seems this is kind of out of scope. For scalability purpose, I think we can define some additional containers field for sidecar containers, instead of having a spec specifically for thanos

**Comment by mikechengwei** [comment]
you re right , we can add a common field which use to deploy sidecar containers. Not only thanos sidecar.

**Comment by Yisaer** [comment]
> Is this really a feature belongs to tidb monitor? Seems this is kind of out of scope. For scalability purpose, I think we can define some additional containers field for sidecar containers, instead of having a spec specifically for thanos

This sounds more reasonable. I would add it into UCP.

**Comment by Yisaer** [comment]
@mikechengwei  Hi, I created this issue into UCP. Would you like to take it? 
https://github.com/pingcap/tidb-operator/issues/2177

**Comment by mikechengwei** [comment]
yes, I will do it ,thanks.

**Comment by yeya24** [comment]
I think sidecar containers are useful for TiDB cluster containers as well. We want to add some log agents for tidb/pd/tikv, it would be nice to support sidecar containers there as well. @Yisaer  WDYT?

**Comment by mikechengwei** [comment]
@yeya24 Now TIDB print log to stdout and stderr , generally we use a single process to collect the stdout log of all containers on a node, so the log agents for tidb/pd/tikv is not very useful. I think log agent is useful to collect the  application which print log to file .
But the sidecar can be given to users as a developmental capability ，users not need to modify TIDB project code.

**Comment by yeya24** [comment]
Sorry I didn't say it clearly. What I need is not a log agent, is a sidecar for collecting its stdout log and send it to the obj store like S3. Since we use Argo, so it requires a sidecar container in TiDB/PD/TiKV.

**Comment by Yisaer** [comment]
@yeya24  take your time.

https://github.com/pingcap/tidb-operator/issues/2186

**Comment by mikechengwei** [comment]
@yeya24 Let's do it together?

**Comment by yeya24** [comment]
I'd love to, but I am busy with my course work  the recent two weeks...

Anyway, I think this feature needs to be designed. Since Prometheus itself needs some configurations for such sidecar use cases. So maybe we need to ensure what kinds of argument we want to make it configurable.

**Comment by Yisaer** [comment]
@mikechengwei  If you are interested in #2186, feel free to pick up after you finish the current challenges.

**Comment by Yisaer** [comment]
> Anyway, I think this feature needs to be designed. Since Prometheus itself needs some configurations for such sidecar use cases. So maybe we need to ensure what kinds of argument we want to make it configurable.

I agreed too. I would raise the point for https://github.com/pingcap/tidb-operator/issues/2180 to 300 as it would contain the design for the external Prometheus config and explain why

**Comment by mikechengwei** [comment]
@Yisaer Ok, I will finish #2180 and #2177  firstly.
