### ISSUE TITLE
UCP: support additional sidecars for TidbMonitor

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2177]
## Description
Close https://github.com/pingcap/tidb-operator/issues/2175

We need support additional sidecars for TidbMonitor such as thanos.

## Score

* 100

## Mentor(s)

* [@yisaer](https://github.com/Yisaer)

Contact the mentors: **#tidb-challenge-program** channel in [TiDB-Operator Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills
* Golang
* Kubernetes

**Comment by mikechengwei** [comment]
assign to me ,thanks.

**Comment by Yisaer** [comment]
@mikechengwei you can follow this guide to join the UCP and pick this issue.

https://github.com/pingcap/community/blob/master/challenge-programs/challenge-program-season-2-cn.md

**Comment by yeya24** [comment]
@mikechengwei  But pay attention to that if you want to use thanos as the tidb monitor sidecar container, we also need to make some of Prometheus args modifiable. Like disabling compaction in Prometheus itself. Do you have any ideas on how to do that?

**Comment by yeya24** [comment]
> Refer to issue #2180 , we can support external config with configMap.

Yes. I think that issue should be done first

**Comment by yeya24** [comment]
@mikechengwei Hello, are you still working on this? If you don't have time to work on this then I can help

**Comment by mikechengwei** [comment]
I'm do it now.
