### ISSUE TITLE
Proposal: support resizing PD/TiKV storage limit on the fly

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#220]
As [this issue](https://github.com/pingcap/tidb-operator/issues/218) reported, TiKV node will failed to start if there is no space on the disk. There is not yet any proper solutions to prevent TiKV occupy the whole disk.

Discussed with @onlymellb , we may support resizing PD/TiKV storage limit on the fly in TiDB Operator, the coding process is:

- User edit the `capacity` in `values.yaml` and run helm upgrade
- Delete the related StatefulSet with [orphaning dependents](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#setting-the-cascading-deletion-policy). This will delete the StatefulSet but don't delete all its dependents
- Then, TiDB Operator will create the new version StatefulSet with `capacity` increased
- Modify all PVCs and change their `capacity` to new value
- Delete the old Pod one by one once the PVC has the condition `FileSystemResizePending`
- The old Pods will use a bigger capacity PV
- The new created Pod use a bigger capacity PV also

@tennix @onlymellb @xiaojingchen @gregwebs PTAL

**Comment by weekface** [comment]
@gregwebs This is only for volume expansion support for the following in-tree volume plugins: AWS-EBS, GCE-PD, Azure Disk, Azure File, Glusterfs, Cinder, Portworx, and Ceph RBD. As this [document](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/) indicated.

The local volume will have LVM supported, then it can be resized like others.

**Comment by gregwebs** [comment]
> The local volume will have LVM supported, then it can be resized like others.

Right, if there is more space available. But in a cloud deployment of TiDB there probably shouldn't be more space available: you should do an initial deploy with storage equal to the local SSD capacity. The exception to that would be if you ran multiple TiDB components (e.g. PD + TiDB) on one node, perhaps precisely for this reason, and then moved one off.

So we need to understand the behavior when the user asks for an increase in capacity that cannot be met.

**Comment by weekface** [comment]
@tkalanick Do you use `local-storage` instead of `GCE-PD`?

What are the logs of the TiKV pod?

**Comment by weekface** [comment]
> in my case the error is caused by the request limit. disk capacity is available.
> 
> tikv:
> replicas: 3
> image: pingcap/tikv:v2.1.0
> logLevel: info
> storageClassName: local-storage
> 
> imagePullPolicy: IfNotPresent
> 
> syncLog: true
> resources:
> requests:
> cpu: 15000m
> memory: 32Gi
> **storage: 64Gi**

@tkalanick Said `disk capacity is available`,  this means there **is** more space available? So, we may confirm the failed reason first. Can you provide the TiKV's logs?

**Comment by tkalanick** [comment]
@weekface it is very easy to reproduce this error. with a working cluster, modify charts/tidb-cluster/values.yaml  by expanding `tikv.resources.requests.storage` value, and then do `helm upgrade tidb charts/tidb-cluster`

you will see some tikv pod run into `CrashLoopBackOff` state. if not, delete one pod and when it recreates, it will crash. 

since it is not possible for the pod to recover from the crash state, we should at least document the fact so that people don't accidentally run `helm upgrade tidb charts/tidb-cluster` in production

**Comment by weekface** [comment]
@tkalanick Can't find the reason from the tikv logs, it looks normal. You need to check the log of the pod that was previously failed with `-p` flag:

```
$ kubectl logs -n tidb bench-tikv-0 -p
```

This may be another problem.
