### ISSUE TITLE
helm will delete old configmap first while helm upgrade

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#2202]
This will cause a Pod that has not been upgraded but restarted to crash.

**Comment by Yisaer** [comment]
I think this bugs won't happen in 1.1 version if we use CR to deploy/upgrade TidbCluster. Do we need to solve this problem?

**Comment by weekface** [comment]
Yes, it happened in `v1.0.6`, we should fix it in `releae-1.0`.
