### ISSUE TITLE
Need document using-operator to upgrade tidb 4.0

### ISSUE THREAD

**Issue by shonge** [pingcap/tidb-operator#2203]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Like this document:
https://pingcap.com/docs-cn/stable/how-to/upgrade/using-tiup/

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
@shonge Do you hit any issues to upgrade tidb cluster to v4.0 with the doc here https://pingcap.com/docs-cn/tidb-in-kubernetes/stable/upgrade-a-tidb-cluster/?
