### ISSUE TITLE
Failed to schedule tikv pod 

### ISSUE THREAD

**Issue by tkalanick** [pingcap/tidb-operator#221]
i tested a full installation with master HEAD but was not able to pass TiKV installation. container log only says "fail to schedule pod". can i find more information somewhere?

<img width="1328" alt="screen shot 2018-12-07 at 11 27 55 am" src="https://user-images.githubusercontent.com/45215660/49668514-34aee580-fa13-11e8-9597-5720b7f0beef.png">

NAME                               READY     STATUS      RESTARTS   AGE       IP          NODE
bench-monitor-7bd5478576-q2crb     2/2       Running     0          11m       10.32.2.4   gke-tidb-default-pool-7797ac69-7tx5
bench-monitor-configurator-ll7gx   0/1       Completed   0          11m       10.32.3.4   gke-tidb-default-pool-7797ac69-3xz8
bench-pd-0                         1/1       Running     0          11m       10.32.0.5   gke-tidb-default-pool-7797ac69-tbz8
bench-pd-1                         1/1       Running     0          11m       10.32.4.5   gke-tidb-default-pool-7797ac69-nqlq
bench-pd-2                         1/1       Running     0          10m       10.32.5.5   gke-tidb-default-pool-7797ac69-cmf7
bench-tidb-initializer-w9cft       1/1       Running     0          11m       10.32.6.3   gke-tidb-default-pool-7797ac69-3928
bench-tikv-0                       0/2       Pending     0          10m       <none>      <none>
bench-tikv-1                       0/2       Pending     0          10m       <none>      <none>
bench-tikv-2                       0/2       Pending     0          10m       <none>      <none>

**Comment by gregwebs** [comment]
Thanks for the report! We will take a closer look at this. Which container log are you showing?

Whey you say using master, you mean you installed charts from master?

**Comment by tkalanick** [comment]
i cloned pingcap/tidb-operator locally and did a git pull this morning. 

i started everything from scratch after a
`gcloud container clusters delete tidb`

i have a 10 nodes pool with kubernetes version: 1.11.2-gke.20,

**Comment by gregwebs** [comment]
One thing to watch out for: when you delete a K8s cluster it does not delete the underlying network storage volumes. This is mentioned in the [guide](https://github.com/pingcap/tidb-operator/blob/master/docs/operation-guide.md).

To debug this I would look at the tidb-operator logs and the PVC claims.

**Comment by tkalanick** [comment]
yes. problem seems to be unrelated to the latest change on master. i reverted to the 12/2 revision but see the same errors.

**Comment by tkalanick** [comment]
i followed the instructions to purge and delete PVs but it didn't help. after the delete, i re-ran

`helm install ./charts/tidb-cluster -n tidb --namespace=tidb --set pd.storageClassName=pd-ssd,tikv.storageClassName=pd-ssd`


but i am still getting the same errors. is there a way out of this? how do i re-build everything from scratch?

`kubectl -n tidb-admin logs tidb-scheduler-5cdb686dc8-vjzx7 -c kube-scheduler`

I1207 20:22:42.968493       1 scheduler.go:191] Failed to schedule pod: tidb/bench-pd-0
E1207 20:22:42.968583       1 factory.go:1282] Error scheduling tidb bench-pd-0: pod has unbound PersistentVolumeClaims (repeated 10 times); retrying
I1207 20:22:42.968656       1 factory.go:1375] Updating pod condition for tidb/bench-pd-0 to (PodScheduled==False)
I1207 20:22:43.972343       1 scheduler.go:191] Failed to schedule pod: tidb/bench-pd-0
E1207 20:22:43.972422       1 factory.go:1282] Error scheduling tidb bench-pd-0: pod has unbound PersistentVolumeClaims (repeated 10 times); retrying

I1207 20:28:12.192778       1 scheduler.go:191] Failed to schedule pod: tidb/bench-tikv-2
I1207 20:28:12.192941       1 factory.go:1375] Updating pod condition for tidb/bench-tikv-2 to (PodScheduled==False)
I1207 20:28:13.055938       1 scheduler.go:191] Failed to schedule pod: tidb/bench-tikv-1
I1207 20:28:13.056075       1 factory.go:1375] Updating pod condition for tidb/bench-tikv-1 to (PodScheduled==False)
I1207 20:28:13.150765       1 scheduler.go:191] Failed to schedule pod: tidb/bench-tikv-0

**Comment by gregwebs** [comment]
So it does seem to be a persistent volume claim issue. You can run `kubectl -n tidb describe pod tidb/bench-tikv-2` to see the failed claims for the pod and then `kubectl -n tidb pvc get` to see the failed pvc.

The instructions to delete the PV are for when you are deleting a K8s cluster. If your cluster was already up and you had things running, it would cause more of these problems.

In terms of a fresh restart you can of course delete the K8s cluster (or even the GCP project).
