### ISSUE TITLE
tidb-operator default image tag “latest” need “imagePullPolicy: Always”

### ISSUE THREAD

**Issue by malc0lm** [pingcap/tidb-operator#223]
My cluster deploy tidb-operator 3 month ago. But when I use helm to deploy tidb-operator again, the tidb-controller-manager pod can't start again. The log output is that "this is no auto-failover flag". Then I found I use the outdated "pingcap/tidb-operator:latest" which was pulled 3 month ago.
So I think the "latest" tag need  "imagePullPolicy: Always" config unless you specify a tag name.

**Comment by weekface** [comment]
We may use an explicit tag instead, for example: `pingcap/tidb-operator:v1.0.0-beta.0`

@tennix what do you think?

**Comment by gregwebs** [comment]
we should be using release tags in the chart values so that the pull policy doesn't have an effect.

**Comment by tennix** [comment]
Yeah, I think we should use the last release tag in chart. And update the chart every time we release a new version.

**Comment by gregwebs** [comment]
@tennix do you want me to send a PR for this?

**Comment by tennix** [comment]
Sure, thank you! @gregwebs

**Comment by tennix** [comment]
Fixed with https://github.com/pingcap/tidb-operator/pull/478
