### ISSUE TITLE
i accidentally wiped out my entire tidb namespace 

### ISSUE THREAD

**Issue by tkalanick** [pingcap/tidb-operator#224]
just to let you folks know that this is possibility. i understand it is totally my fault, that i shouldn't have included the `--namespace==tidb` in the command. 

**what happened**:
i wanted to adjust some cpu allocations, both on the controllerManager, and on TiDB, so i changed values.yaml in both `charts/tidb-cluster` and `charts/tidb-operator`

and did:

`helm upgrade tidb --namespace=tidb ./charts/tidb-cluster`
`helm upgrade tidb --namespace=tidb ./charts/tidb-operator`

**everything stopped working after that**. it appears that i have overwritten my tidb namespace. how do i prevent this from happening in a production environment? 
current status of my pods:

`kubectl -n tidb get pods`
`NAME                                       READY     STATUS    RESTARTS   AGE`
`tidb-controller-manager-7f6b796fd6-sxtj9   1/1       Running   0          15m`
`tidb-scheduler-696d67c64d-zk6f8            2/2       Running   0          15m`

`kubectl -n tidb-admin get pods`
`NAME                                       READY     STATUS    RESTARTS   AGE`
`tidb-controller-manager-7dc4bb9f46-9zv8j   1/1       Running   1          2d`
`tidb-scheduler-5cdb686dc8-vjzx7            2/2       Running   6          2d`

**Comment by gregwebs** [comment]
Thanks for reporting this, I know it can sometimes feel embarrassing. I don't know if there is a solution to this with hepm. The helm workflow is problematic. I personally think we should be looking for alternatives, but there are a lot of advantages to using a community standard.

**Comment by tkalanick** [comment]
i would want to use helm to manage my TiDB cluster during development or testing. because having a single `values.yaml` file and using one command
`helm upgrade tidb --namespace=tidb ./charts/tidb-cluster`
to update everything is convenient.

however in a production environment when millions of users or billion dollars of business are at stake, convenience is the least of my concerns. i'd rather inconvenient myself by going through 
a "canary"->"partial roll out"->"complete roll out" process on even the most insignificant parameter changes. 

in a production environment we want to limit the granularity of changes. and the ability to tryout a change on a single unit before rolling out to the rest of the system is critical. 

do you have documentations on how to build a TiDB cluster on bare metal Kubernetes? one such bare metal configuration example is 
[jmeter-kubernetes](https://github.com/kubernauts/jmeter-kubernetes). the git repo basically provides service and deployment templates for individual services. the granularity of change is therefore at the service level which i think is safer than using helm at the cluster level. on top of that, we can probably build a canary deployment process as [described here](https://medium.com/google-cloud/kubernetes-canary-deployments-for-mere-mortals-13728ce032fe)

**Comment by gregwebs** [comment]
But it seems that the jmeter example is not configurable?

I am confused by your usage of the term "bare metal". Do you mean without a helm chart? The easiest way to do that is to run `helm template --name`. This produces the raw kubernetes files which you can feed to `kubectl apply -n tidb`. If you check-in the result of that you can diff it to see exactly what is changing in your prod deployment. You could also use Kubernetes tooling to diff against what is currently running.

Let me know if that is what you are looking for.

**Comment by tkalanick** [comment]
yes. by "bare metal" i mean without a helm chart or any other third party tools. i will test out the `kubectl apply` path. thanks.
