### ISSUE TITLE
UCP: Support the noise reduction for auto-scaling

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2241]
## Description

Currently, the auto-scaling doesn't have the  noise reduction design. It means in each reconciliation in auto-scaling controller, the result would be updated into tidbcluster immediately when the result indicates to scale-out or scale-in.

Now we want to support the noise reduction for auto-scaling and design detailed is designed in following:

For `TidbClusterAutoScaler`, the status would have 3 choices: Normal / ReadyToScaleOut / ReadyToScaleIn.

1. The initialial status is `Normal`
2. If the result in the reconciliation in auto-scaling controller is lager/smaller than the current replicas, the status would become `ReadyToScaleOut`/`ReadyToScaleIn` and record the timestamp in annotation.
3. If the status is remained as `ReadyToScaleOut` / `ReadyToScaleIn` for a certain time (which could also be configured in the `TidbClusterAutoScaler` spec), the auto-scaling controller would finally updated its result in the tidbcluster.
4. When auto-scaling updated the tidbcluster or the result in the reconciliation in auto-scaling controller is equal to the current replicas, the status should become `Normal` again.

I think the PR for this issue not only contains the logic of the noise reduction but also should have a e2e case to cover it. You could look the previous logic for auto-scaling in e2e here:
https://github.com/pingcap/tidb-operator/blob/5341babebc265c79bab978211493434f47dfe0d5/tests/e2e/tidbcluster/serial.go#L653

## Score

* 2500

## Mentor(s)

* [@yisaer](https://github.com/Yisaer)

Contact the mentors: **#tidb-challenge-program** channel in [TiDB-Operator Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace
As the logic is not simple and the detail is still needed to be discussed, we are welcome for every challenger to contact the mentor if you have any questions.

## Recommended Skills
* Golang
* Kubernetes

**Comment by Yisaer** [comment]
@vincent178  Hi, Is there any progress now?

**Comment by vincent178** [comment]
@Yisaer yeah, I'm still reading the code, will reach out to you maybe tomorrow or the day after to discuss some details, thanks.

**Comment by Yisaer** [comment]
@vincent178 okay, please contact me through slack personal message if you have any problem or question. I would help you.
