### ISSUE TITLE
image can't set to statefulset

### ISSUE THREAD

**Issue by w-huaqiang** [pingcap/tidb-operator#2243]
## Question

`admin@kolla00:~/TiDB/tidb-operator$ cat aiops-cluster.yaml 
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: aiops-tidb-cluster
spec:
  version: v3.0.8
  timezone: UTC
  imagePullPolicy: IfNotPresent
  pvReclaimPolicy: Delete
  pd:
    baseImage: pingcap/pd
    replicas: 3
    requests:
      storage: "10Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    replicas: 3
    requests:
      storage: "10Gi"
    config: {}
  tidb:
    baseImage: pingcap/tidb
    replicas: 2
    service:
      type: ClusterIP
    config: {}`

error is

`reate Pod aiops-tidb-cluster-pd-0 in StatefulSet aiops-tidb-cluster-pd failed error: Pod "aiops-tidb-cluster-pd-0" is invalid: spec.containers[0].image: Required value`

I check ,there is no image set 

`admin@kolla00:~/TiDB/tidb-operator$ kubectl get statefulset aiops-tidb-cluster-pd -n tidb-aiops -o yaml|grep image
        imagePullPolicy: IfNotPresent`

**Comment by Yisaer** [comment]
Could you provide the operator version and the statefulset yaml content generated by tidb-operator

**Comment by w-huaqiang** [comment]
I install operator use helm
$ helm install tidb-operator \
--namespace tidb-admin \
--version v1.0.6 \
--set scheduler.kubeSchedulerImageName=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler \
pingcap/tidb-operator



operator version maybe 1.0.6
admin@kolla00:~/TiDB/tidb-operator$ kubectl get pod -n tidb-admin -o yaml|grep image
      image: pingcap/tidb-operator:v1.0.6
      imagePullPolicy: IfNotPresent
      image: pingcap/tidb-operator:v1.0.6
      imageID: docker-pullable://pingcap/tidb-operator@sha256:87d88143eda1b2c1f88d063b2ade9e412251320a89702ab7212724b969558c54
      image: pingcap/tidb-operator:v1.0.6
      imagePullPolicy: IfNotPresent
      image: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.15.11
      imagePullPolicy: IfNotPresent
      image: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.15.11
      imageID: docker-pullable://registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler@sha256:54be1ecc5b96c6505ccca016e6a94ef96add4e349ede40ebef8db2f30f8b00f6
      image: pingcap/tidb-operator:v1.0.6
      imageID: docker-pullable://pingcap/tidb-operator@sha256:87d88143eda1b2c1f88d063b2ade9e412251320a89702ab7212724b969558c54








admin@kolla00:~/TiDB/tidb-operator$ kubectl get statefulset/aiops-tidb-cluster-pd -o yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    pingcap.com/last-applied-configuration: '{"replicas":3,"selector":{"matchLabels":{"app.kubernetes.io/component":"pd","app.kubernetes.io/instance":"","app.kubernetes.io/managed-by":"tidb-operator","app.kubernetes.io/name":"tidb-cluster"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app.kubernetes.io/component":"pd","app.kubernetes.io/instance":"","app.kubernetes.io/managed-by":"tidb-operator","app.kubernetes.io/name":"tidb-cluster"},"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"2379","prometheus.io/scrape":"true"}},"spec":{"volumes":[{"name":"annotations","downwardAPI":{"items":[{"path":"annotations","fieldRef":{"fieldPath":"metadata.annotations"}}]}},{"name":"config","configMap":{"name":"aiops-tidb-cluster-pd","items":[{"key":"config-file","path":"pd.toml"}]}},{"name":"startup-script","configMap":{"name":"aiops-tidb-cluster-pd","items":[{"key":"startup-script","path":"pd_start_script.sh"}]}}],"containers":[{"name":"pd","command":["/bin/sh","/usr/local/bin/pd_start_script.sh"],"ports":[{"name":"server","containerPort":2380,"protocol":"TCP"},{"name":"client","containerPort":2379,"protocol":"TCP"}],"env":[{"name":"NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"PEER_SERVICE_NAME","value":"aiops-tidb-cluster-pd-peer"},{"name":"SERVICE_NAME","value":"aiops-tidb-cluster-pd"},{"name":"SET_NAME","value":"aiops-tidb-cluster-pd"},{"name":"TZ","value":"UTC"}],"resources":{},"volumeMounts":[{"name":"annotations","readOnly":true,"mountPath":"/etc/podinfo"},{"name":"config","readOnly":true,"mountPath":"/etc/pd"},{"name":"startup-script","readOnly":true,"mountPath":"/usr/local/bin"},{"name":"pd","mountPath":"/var/lib/pd"}]}],"restartPolicy":"Always"}},"volumeClaimTemplates":[{"metadata":{"name":"pd","creationTimestamp":null},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"local-storage","dataSource":null},"status":{}}],"serviceName":"aiops-tidb-cluster-pd-peer","podManagementPolicy":"Parallel","updateStrategy":{"type":"RollingUpdate","rollingUpdate":{"partition":3}}}'
  creationTimestamp: "2020-04-21T08:20:43Z"
  generation: 1
  labels:
    app.kubernetes.io/component: pd
    app.kubernetes.io/instance: ""
    app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/name: tidb-cluster
  name: aiops-tidb-cluster-pd
  namespace: default
  ownerReferences:
  - apiVersion: pingcap.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TidbCluster
    name: aiops-tidb-cluster
    uid: 4a6b31b7-fe6a-499b-9c0f-1051a35a0254
  resourceVersion: "9095301"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/aiops-tidb-cluster-pd
  uid: 8e621cce-da71-43a1-a450-044f8eb192cc
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: pd
      app.kubernetes.io/instance: ""
      app.kubernetes.io/managed-by: tidb-operator
      app.kubernetes.io/name: tidb-cluster
  serviceName: aiops-tidb-cluster-pd-peer
  template:
    metadata:
      annotations:
        pingcap.com/last-applied-configuration: '{"volumes":[{"name":"annotations","downwardAPI":{"items":[{"path":"annotations","fieldRef":{"fieldPath":"metadata.annotations"}}]}},{"name":"config","configMap":{"name":"aiops-tidb-cluster-pd","items":[{"key":"config-file","path":"pd.toml"}]}},{"name":"startup-script","configMap":{"name":"aiops-tidb-cluster-pd","items":[{"key":"startup-script","path":"pd_start_script.sh"}]}}],"containers":[{"name":"pd","command":["/bin/sh","/usr/local/bin/pd_start_script.sh"],"ports":[{"name":"server","containerPort":2380,"protocol":"TCP"},{"name":"client","containerPort":2379,"protocol":"TCP"}],"env":[{"name":"NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"PEER_SERVICE_NAME","value":"aiops-tidb-cluster-pd-peer"},{"name":"SERVICE_NAME","value":"aiops-tidb-cluster-pd"},{"name":"SET_NAME","value":"aiops-tidb-cluster-pd"},{"name":"TZ","value":"UTC"}],"resources":{},"volumeMounts":[{"name":"annotations","readOnly":true,"mountPath":"/etc/podinfo"},{"name":"config","readOnly":true,"mountPath":"/etc/pd"},{"name":"startup-script","readOnly":true,"mountPath":"/usr/local/bin"},{"name":"pd","mountPath":"/var/lib/pd"}]}],"restartPolicy":"Always"}'
        prometheus.io/path: /metrics
        prometheus.io/port: "2379"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: pd
        app.kubernetes.io/instance: ""
        app.kubernetes.io/managed-by: tidb-operator
        app.kubernetes.io/name: tidb-cluster
    spec:
      containers:
      - command:
        - /bin/sh
        - /usr/local/bin/pd_start_script.sh
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PEER_SERVICE_NAME
          value: aiops-tidb-cluster-pd-peer
        - name: SERVICE_NAME
          value: aiops-tidb-cluster-pd
        - name: SET_NAME
          value: aiops-tidb-cluster-pd
        - name: TZ
          value: UTC
        imagePullPolicy: IfNotPresent
        name: pd
        ports:
        - containerPort: 2380
          name: server
          protocol: TCP
        - containerPort: 2379
          name: client
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/podinfo
          name: annotations
          readOnly: true
        - mountPath: /etc/pd
          name: config
          readOnly: true
        - mountPath: /usr/local/bin
          name: startup-script
          readOnly: true
        - mountPath: /var/lib/pd
          name: pd
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: annotations
      - configMap:
          defaultMode: 420
          items:
          - key: config-file
            path: pd.toml
          name: aiops-tidb-cluster-pd
        name: config
      - configMap:
          defaultMode: 420
          items:
          - key: startup-script
            path: pd_start_script.sh
          name: aiops-tidb-cluster-pd
        name: startup-script
  updateStrategy:
    rollingUpdate:
      partition: 3
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: pd
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: local-storage
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  replicas: 0

**Comment by w-huaqiang** [comment]
I set both image and baseImage, but it can't work
```
spec:
  imagePullPolicy: IfNotPresent
  pd:
    baseImage: pingcap/pd
    config: {}
    image: pingcap/pd:v3.0.8
    replicas: 3
    requests:
      storage: 10Gi
  pvReclaimPolicy: Delete
  tidb:
    baseImage: pingcap/tidb
    config: {}
    image: pingcap/tidb:v3.0.8
    replicas: 2
    service:
      type: ClusterIP
    slowLogTailer:
      image: ""
  tikv:
    baseImage: pingcap/tikv
    config: {}
    image: pingcap/tikv:v3.0.8
    replicas: 3
    requests:
      storage: 10Gi
  tikvPromGateway:
    image: ""
  timezone: UTC
  version: v3.0.8
status:
  pd:
    leader:
      clientURL: ""
      health: false
      id: ""
      lastTransitionTime: null
      name: ""
    phase: Normal
    statefulSet:
      replicas: 0
  tidb: {}
  tikv: {}
```

**Comment by Yisaer** [comment]
It seems you install operator by helm, but I don't know how you install the tidbcluster. Does it also installed by helm?
I think you could follow our 1.0 doucment to install the tidbcluster：
https://pingcap.com/docs-cn/tidb-in-kubernetes/v1.0/deploy-on-general-kubernetes/

**Comment by w-huaqiang** [comment]
@Yisaer 
I refer this: `https://pingcap.com/docs-cn/tidb-in-kubernetes/stable/deploy-on-general-kubernetes/`
 I find it's `v1.1-rc`. so I follow 1.0 docoment which use helm to install tidb-cluster. it  works.

think you!
