### ISSUE TITLE
Default eks_version is too old

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-operator#2252]
## Bug Report

The default value of `eks_version` is 1.12, which will be deprecated very soon:

```
variable "eks_version" {
  description = "Kubernetes version to use for the EKS cluster."
  default     = "1.12"
}
```
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
"Kubernetes version 1.12 is now deprecated on Amazon EKS. On May 11th, 2020, Kubernetes version 1.12 will no longer be supported on Amazon EKS. On this date, you will no longer be able to create new 1.12 clusters"

We should change the default of eks_version to something newer.

**Comment by DanielZhangQD** [comment]
Fixed by https://github.com/pingcap/tidb-operator/pull/2238
