### ISSUE TITLE
tidb-controller-manager does not get new CA/certs for a newly-deployed cluster

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-operator#2253]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of TiDB Operator are you using?**

a6bbe4c4bec08003797465fd6d575f3fde41408c

**What did you do?**

I created a TidbCluster with cert-manager controlled Cluster TLS enabled. I then deleted that TidbCluster and its namespace (and all secrets associated with the TidbCluster). Then I deployed a new TidbCluster with a new CA and certificates.

The tidb-controller-manager pod cannot connect to PD:
```
E0422 04:52:32.054065       1 pd_member_manager.go:206] failed to sync TidbCluster: [tidb-cluster/kolbe-test-cluster]'s status, error: Get https://kolbe-test-cluster-pd.tidb-cluster:2379/pd/health: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "TiDB")
E0422 04:52:32.065516       1 tidb_cluster_controller.go:282] TidbCluster: tidb-cluster/kolbe-test-cluster, sync failed TidbCluster: tidb-cluster/kolbe-test-cluster's pd status sync failed, can't failover, requeuing
```

**What did you expect to see?**

I think tidb-controller-manager should be able to manage this automatically.

**What did you see instead?**

If I deleted the tidb-controller-manager pod, it was recreated with the correct secrets and it could connect successfully to the PD service.

**Comment by DanielZhangQD** [comment]
@weekface Please help check this issue, Thanks!

**Comment by weekface** [comment]
@kolbe Please supply the certificate of PD component secret and the cluster client certificate secret. It should be the content of secret `kolbe-test-cluster-pd-cluster-secret` and  secret`kolbe-test-cluster-cluster-client-secret`.

```
kubectl get secret -n tidb-cluster kolbe-test-cluster-pd-cluster-secret -oyaml
kubectl get secret -n kolbe-test-cluster-cluster-client-secret -oyaml
```

**Comment by weekface** [comment]
Do you delete the TiDB cluster and recreate it with the **SAME** cluster name? That maybe a cache problem.

**Comment by kolbe** [comment]
Yes, when I re-create the cluster it has the same as the deleted cluster.
