### ISSUE TITLE
Default db.yaml tidb sysctls are forbidden on EKS 1.14 

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-operator#2254]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**What version of TiDB Operator are you using?**

TiDB Operator Version: version.Info{GitVersion:"v1.1.0-rc.2", GitCommit:"6f42736bd0f33aed65903058f43a9005e806680a", GitTreeState:"clean", BuildDate:"2020-04-16T01:23:10Z", GoVersion:"go1.13", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

Ran terraform with `eks_version = "1.14"` and tried to deploy a TidbController using the default db.yaml.

**What did you expect to see?**

**What did you see instead?**

```
  Warning  FailedCreate  8s (x12 over 13s)  statefulset-controller  create Pod kolbe-test-cluster-tidb-0 in StatefulSet kolbe-test-cluster-tidb failed error: pods "kolbe-test-cluster-tidb-0" is forbidden: unable to validate against any pod security policy: [pod.spec.securityContext.sysctls[0]: Forbidden: unsafe sysctl "net.ipv4.tcp_keepalive_time" is not allowed pod.spec.securityContext.sysctls[1]: Forbidden: unsafe sysctl "net.ipv4.tcp_keepalive_intvl" is not allowed pod.spec.securityContext.sysctls[2]: Forbidden: unsafe sysctl "net.core.somaxconn" is not allowed]
```

**Comment by Yisaer** [comment]
Thanks for the reporting. Actually we have fixed this problem in #2238 
In the next release, this problem would be fixed.
