### ISSUE TITLE
mydumper CRD based backup doesn't work with encrypted S3 buckets

### ISSUE THREAD

**Issue by tirsen** [pingcap/tidb-operator#2270]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**What version of TiDB Operator are you using?**
TiDB Operator Version: version.Info{GitVersion:"v1.1.0-rc.2.p1", GitCommit:"f2934a010abed83433dd8a530dc7e09251edbb16", GitTreeState:"clean", BuildDate:"2020-04-16T10:58:30Z", GoVersion:"go1.13", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

I ran an adhoc CRD backup with the following yaml:

```apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: ${job}
  namespace: ${cluster}
spec:
  backupType: full
  serviceAccount: tidb-backup-manager
  # BR is incompatible with auto random
  # Uncomment this when the following issues have been fixed:
  # https://github.com/pingcap/br/issues/241
  # https://github.com/pingcap/br/issues/228
  #br:
  #  cluster: ${cluster}
  #  sendCredToTikv: false
  #  clusterNamespace: ${cluster}
  #  pd: ${cluster}-pd.${cluster}
  #  logLevel: debug
  #  checksum: true
  from:
    host: ${cluster}-tidb.${cluster}.svc.cluster.local
    port: 4000
    user: ${SQM_SERVICE}_bak
    secretName: ${cluster}-tidb-backup-secret
    # mydumper doesn't support mTLS, turn this back on when switching to BR
    #tlsClient:
    #  enabled: true
  s3:
    provider: aws
    region: us-west-2
    bucket: tidb-staging/${SQM_SERVICE}/adhoc-backup-${USER}-${job_id}
    # use prefix instead of the path in the bucket name when switching to BR
    #prefix: ${SQM_SERVICE}/adhoc-backup-${USER}-${job_id}
  # these are also not needed with BR since tikv writes directly to S3
  storageClassName: ebs-gp2
  storageSize: 500Gi
```

With encryption enabled I get the following error in the logs:
```
E0422 21:20:19.383046       1 manager.go:260] backup cluster newswriter-shadow-tidb/adhoc-backup-jontirsen-1587590394 data to s3 failed, err: cluster newswriter-shadow-tidb/adhoc-backup-jontirsen-1587590394, execute rclone copyto command for upload backup data s3://tidb-staging/newswriter-shadow/adhoc-backup-jontirsen-1587590394/backup-2020-04-22T21:20:12Z.tgz failed, output: 2020/04/22 21:20:18 ERROR : backup-2020-04-22T21:20:12Z.tgz.tmp: corrupted on transfer: MD5 hash differ "cf2708ebc565d6f5b7d4beae7b927696" vs "f8dc3ea9bc801eb8382c7c5d6a151a26"
```

If I disable encryption it succeeds:
```
I0422 21:01:13.838566       1 manager.go:268] backup cluster newswriter-shadow-tidb/adhoc-backup-jontirsen-1587589230 data to s3 success
```

**Comment by Yisaer** [comment]
@tirsen  Hi could you provide the detail of encryption? Does it mean the S3-bucket-encrpytion? https://docs.aws.amazon.com/AmazonS3/latest/user-guide/default-bucket-encryption.html
