### ISSUE TITLE
do not remove the backup data when remove the backup CR

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2286]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now when we delete the backup CR, the backup data in S3 or GCS will be purged too, it should be possible that users can remove the backup CR with the backup data preserved.
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by tennix** [comment]
We should make this optional, users can choose the deletion policy whether to delete the backup files on S3/GCS.

**Comment by kolbe** [comment]
I think the most natural state is for the backup "artifact" to be decoupled from the Backup resource by default. A backup job should produce an artifact that is placed on external storage and deleting the Backup object should not have any effect on the artifact.

If we want a configuration option for the Backup job to delete the artifact, that may be useful, but it should not be enabled by default.

The ramifications of automatically deleting all backups when a cluster is deleted could be disastrous.

**Comment by tennix** [comment]
> I think the most natural state is for the backup "artifact" to be decoupled from the Backup resource by default. A backup job should produce an artifact that is placed on external storage and deleting the Backup object should not have any effect on the artifact.
> 
> If we want a configuration option for the Backup job to delete the artifact, that may be useful, but it should not be enabled by default.
> 
> The ramifications of automatically deleting all backups when a cluster is deleted could be disastrous.

Yes, I agree this should not be enabled by default.

**Comment by DanielZhangQD** [comment]
For this issue:

- We can add a field, e.g. `cleanData`, with default value `false`, so that the backup data will not be removed when CR is removed by default.
- If `cleanData` is false, I think no need to add finalized any more [here](https://github.com/pingcap/tidb-operator/blob/master/pkg/controller/backup/backup_control.go#L71) WDYT @cofyc @tennix @kolbe

**Comment by tennix** [comment]
I remember the main reason for the finalizer is when the `Backup` CR is deleted, even we have the backup files on S3, we cannot do the restore with incremental backup & restore.

**Comment by DanielZhangQD** [comment]
> I remember the main reason for the finalizer is when the `Backup` CR is deleted, even we have the backup files on S3, we cannot do the restore with incremental backup & restore.

I don't understand, what's the relationship between the finalizer and the incremental backup & restore?

**Comment by tennix** [comment]
When we do full backup, we need to record the tso. It's kept in the Backup object status field.

**Comment by DanielZhangQD** [comment]
Yes, but if users want to delete the backup, they should be able to do that without caring about the TSO.

**Comment by kolbe** [comment]
@tennix are you saying that it's not possible to *restore* unless the TSO from the Backup object is kept? That sounds very scary. All information needed to restore the backup should be included in the backup artifact.

**Comment by tennix** [comment]
> @tennix are you saying that it's not possible to _restore_ unless the TSO from the Backup object is kept? That sounds very scary. All information needed to restore the backup should be included in the backup artifact.

No, I just mean we need this tso when we do an incremental backup with tidb-binlog. We designed this when there is no `BR` tool. But I think we also need tso for BR and TiCDC. I'm not sure if the tso can be found in the backup files, but that would add extra complexity for users to set up incremental backup.

**Comment by DanielZhangQD** [comment]
> > @tennix are you saying that it's not possible to _restore_ unless the TSO from the Backup object is kept? That sounds very scary. All information needed to restore the backup should be included in the backup artifact.
> 
> No, I just mean we need this tso when we do an incremental backup with tidb-binlog. We designed this when there is no `BR` tool. But I think we also need tso for BR and TiCDC. I'm not sure if the tso can be found in the backup files, but that would add extra complexity for users to set up incremental backup.

This should be OK after #2774 is done.
