### ISSUE TITLE
How to view TiDB slow log?

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#231]
TiDB can output slow log to a separate log file. This makes it easy to view the slow logs. Otherwise, users have to grep slow log from all logs. However, users cannot view the slow logs by `kubectl` if TiDB pod emits logs to a separate log file.

Kubernetes [documentation](https://kubernetes.io/docs/concepts/cluster-administration/logging/#using-a-sidecar-container-with-the-logging-agent) suggests using sidecar to support multiple log files. The sidecar container can only tails the log file to stdout, so the resources used is small:
> order of couple of millicores for cpu and order of several megabytes for memory

So I think we should add sidecar container for TiDB pod for slow log.

**Comment by mlycore** [comment]
We could write our own Admission Controller plugin to inject the log sidecar just like what Istio does

**Comment by tennix** [comment]
@mlycore Since the TiDB pods are created by TiDB StatefulSet, and the StatefulSet is created by TidbCluster, we can totally control how our pods look like. So there is no need to add another plugin to inject log sidecar.

**Comment by aylei** [comment]
I'd like to help with this issue if there is no ongoing development work.

**Comment by weekface** [comment]
@aylei Of course you can, thank you.
