### ISSUE TITLE
TiKV Pod get warning when startup.

### ISSUE THREAD

**Issue by shonge** [pingcap/tidb-operator#2323]
## Bug Report

https://asktug.com/t/topic/33999

**What version of Kubernetes are you using?**

1.15.4
**What version of TiDB Operator are you using?**

Operator: v1.0.6
TiDB: 3.0.8
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

Running

**What did you do?**

1.Install tidb-cluster
2.kubectl logs -f tikv-pod-0

**What did you expect to see?**

**What did you see instead?**
```shell
[WARN] [server.rs:464] ["raft check data dir"] [err="config fs: data-dir.rotation.get: \"overlay\" no device find in block"]
```

**Comment by cofyc** [comment]
hi,
at startup, TiKV process will check rocksdb & raft data directories. If they're not a block device ([not found in `/sys/block`](https://github.com/tikv/tikv/blob/0d3168cfd8224fbc48a07796df83ddac0fbcbf46/components/tikv_util/src/config.rs#L592-L621)), this error will be printed.

According to this log, the source of filesystem `/var/lib/tikv` is `overlay` which is a nodev filesystem. 

What's your filesystem of local PV? Can you check the path of local PV on the node? If the mount point on the path of the local path disappeared, a wrong filesystem may be used.

**Comment by Yisaer** [comment]
@shonge  Feel free to reopen this issue if you have any problem.
