### ISSUE TITLE
monitor PVC will be deleted if TidbMonitor CR is deleted

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2329]
## Bug Report

**What version of Kubernetes are you using?**

1.12.8
**What version of TiDB Operator are you using?**

v1.1.0-rc.2
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

local-storage
**What's the status of the TiDB cluster pods?**

Running
**What did you do?**

Delete TidbMonitor CR
**What did you expect to see?**
monitor PVC remained
**What did you see instead?**
monitor PVC deleted

```
# k get pvc -n demo
NAME               STATUS   VOLUME              CAPACITY   ACCESS MODES   STORAGECLASS    AGE
demo-monitor       Bound    local-pv-45d26c43   440Gi      RWO            local-storage   37s
pd-demo-pd-0       Bound    local-pv-d097f77b   440Gi      RWO            local-storage   32s
tikv-demo-tikv-0   Bound    local-pv-3ac89acb   440Gi      RWO            local-storage   7s

# k delete tidbmonitor -n demo demo
tidbmonitor.pingcap.com "demo" deleted
# k get pvc -n demo           
NAME                   STATUS        VOLUME              CAPACITY   ACCESS MODES   STORAGECLASS    AGE
data0-demo-tiflash-0   Pending                                                     local-storage   1s
demo-monitor           Terminating   local-pv-45d26c43   440Gi      RWO            local-storage   56s
pd-demo-pd-0           Bound         local-pv-d097f77b   440Gi      RWO            local-storage   51s
tikv-demo-tikv-0       Bound         local-pv-3ac89acb   440Gi      RWO            local-storage   26s

# k get pvc -n demo 
NAME                   STATUS   VOLUME              CAPACITY   ACCESS MODES   STORAGECLASS    AGE
data0-demo-tiflash-0   Bound    local-pv-7855f795   440Gi      RWO            local-storage   78s
pd-demo-pd-0           Bound    local-pv-d097f77b   440Gi      RWO            local-storage   2m8s
tikv-demo-tikv-0       Bound    local-pv-3ac89acb   440Gi      RWO            local-storage   103s
```

**Comment by DanielZhangQD** [comment]
`ownerReferences` is set for the PVC:
```
  ownerReferences:
  - apiVersion: pingcap.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TidbMonitor
    name: demo
    uid: cfc06ffd-89b9-11ea-ab25-8a678ff421f7
```

**Comment by cofyc** [comment]
If we will create PVC for users, why not use statefulset?

**Comment by cofyc** [comment]
Do you think it's necessary to keep monitor data after the TidbMonitor is deleted? 
If we don't delete the PVC, the PVC can be reused by the new TidbMonitor if they forgot to clean up it. Because we will create the PVC for users, we can expose PVC template in `TidbMonitor`, then users can configure PVC reclaim policy etc..

**Comment by Yisaer** [comment]
> Do you think it's necessary to keep monitor data after the TidbMonitor is deleted?
> If we don't delete the PVC, the PVC can be reused by the new TidbMonitor if they forgot to clean up it. Because we will create the PVC for users, we can expose PVC template in `TidbMonitor`, then users can configure PVC reclaim policy etc..

It's ok to me whether keeping data after Tidbmonitor is killed. Maybe we should keep same strategy as tidbcluster.

**Comment by DanielZhangQD** [comment]
> Do you think it's necessary to keep monitor data after the TidbMonitor is deleted?
1. IF we keep the PVC and if users delete the TidbMonitor accidentally, they can recover it by just re-create the TidbMonior. 
2. During our benchmark test, the tidb/tikv/pd team always ask us to keep the monitoring data even if we delete the cluster to save the cost.
> If we don't delete the PVC, the PVC can be reused by the new TidbMonitor if they forgot to clean up it. Because we will create the PVC for users, we can expose PVC template in `TidbMonitor`, then users can configure PVC reclaim policy etc..
Agree, we can let users configure the reclaim policy as we do for TidbCluster.
