### ISSUE TITLE
why grafana do not have the tidb monitor dashbord?

### ISSUE THREAD

**Issue by lookhua** [pingcap/tidb-operator#2330]
when i deploy the tidb cluster monitor by the tidb-operator  , why grafana do not have the tidb monitor dashbord?

**Comment by Yisaer** [comment]
Hi @lookhua ,
Could you provide the information about how you installed the tidbcluer monitor? Through `TidbMonitor` or `helm? Which version is your operator?

If through `TidbMonitor`, please prviode the `TidbMonitor` spec in yaml. If through `Helm` please provide the `values.yaml` about monitor
