### ISSUE TITLE
Backup and restore Pods enter into `Completed` status even if the backup or restore failed

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2346]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Backup and restore Pods enter into `Completed` status even if the backup or restore failed
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Yisaer** [comment]
I think for `Restore`, we should set the ReStart Policy as Never and exit 1 when we encouter error in the job.
