### ISSUE TITLE
A new algorithm for tidb scheduler HA predicate

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#235]
Now the algorithm of [HA predicate](https://github.com/pingcap/tidb-operator/blob/master/pkg/scheduler/predicates/ha.go#L54) is complicated and hard to understand:

1. First, we sort all the nodes we get from kube-scheduler by how many same kind of pod it contains, find the nodes that have least pods.
2. When scheduling the first replicas pods, we must ensure no previous pods on the nodes.
3. For later pods, we choose the nodes that have least pods.

So we need an easier solution. If a user cannot access the system, it is – from the users' point of view – unavailable. In TiDB Operator, we say HA, it means the whole system is still available when there is **one** Kube node down. 

Discussed with @tennix @onlymellb and @xiaojingchen. The new algorithm is:

- ~~multiple pods are not allowed to be scheduled concurrently in TiDB Operator: lower ordinal pods must be scheduled before the current pod~~
- return the node to kube-scheduler if there is only one node and the pod's pvc is bound 
- return these nodes that have least pods and its pods count is less than replicas/2 to kube-scheduler
- let kube-scheduler to make the final decision

Then all the pods count of Kube nodes is equal or less then replicas / 2, it is available(the raft group is still in quorum.) when this node is down.

**Comment by xiaojingchen** [comment]
In order to avoid the `scale in` operation affecting HA, one more condition should be added to ensure that the pods scheduling is by its ordinal in order.

**Comment by weekface** [comment]
Good catch. I had updated the document.

**Comment by gregwebs** [comment]
The inclusive presence of ordinals in the StatefulSet is not a properly that allows for HA. Therefore we should not use this property in an HA design.

The ordinal number aspect of the StatefulSet doesn't really allow for failure tolerance. That is if we have a stateful set up to 4, it is possible for ordinal 2 to not be present. An simple example would be if we decided to scale-in right after we lost the node that ordinal 2 was on. Then 2 would not be present until we add an additional member to the stateful set or until we preform an expensive data transfer to that node just to satisfy the poor design of the StatefulSet.

**Comment by gregwebs** [comment]
> Then select the node whose pod count is less than replicas / 2

I don't understand this. Select any node that meets this condition?

**Comment by weekface** [comment]
> > Then select the node whose pod count is less than replicas / 2
> 
> I don't understand this. Select any node that meets this condition?

Yes, return these nodes to kube-scheduler, and then let kube-scheduler to make the final decision. I have modified the document to make it looks clear.



> The inclusive presence of ordinals in the StatefulSet is not a properly that allows for HA. Therefore we should not use this property in an HA design.
> 
> The ordinal number aspect of the StatefulSet doesn't really allow for failure tolerance. That is if we have a stateful set up to 4, it is possible for ordinal 2 to not be present. An simple example would be if we decided to scale-in right after we lost the node that ordinal 2 was on. Then 2 would not be present until we add an additional member to the stateful set or until we preform an expensive data transfer to that node just to satisfy the poor design of the StatefulSet.

The operator make sure the lower ordinals must be scheduled before the higher ordinals to control concurrency. The ordinal i means the pod that has this oridnal.

**Comment by gregwebs** [comment]
> Yes, return these nodes to kube-scheduler, and then let kube-scheduler to make the final decision. I have modified the document to make it looks clear.

That makes sense now!

The motivation for the lower ordinals rule to limit concurrency makes more sense. However, I still think that in the presence of some disruptive scenarios (like the one mentioned above) this will be problematic. Is there a different way to limit concurrency?

**Comment by weekface** [comment]
The statefulset has some [guarantees](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#deployment-and-scaling-guarantees
). Keep ordinal order is an important behavior of statefulset. We should do this to limit concurrency when scheduling.

This is one of the solutions we think of. There may be other better solutions.
