### ISSUE TITLE
Support creating node pools for tiflash and CDC on GKE with terraform

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2377]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Support creating node pools for tiflash and CDC on GKE with terraform
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by cofyc** [comment]
We're going to simplify terraform scripts decoupling tidb-operator setup from Kubernetes cluster provisioning. This is not necessary anymore.
I would suggest providing a generic way to add new node pools.
