### ISSUE TITLE
operator was blocked when delete a pd member that is not exist

### ISSUE THREAD

**Issue by xiaojingchen** [pingcap/tidb-operator#239]
some times the operator call pd api to delete pd member, but the pd member is not found, then the  operator was blocked.
the reasonable process is to return success directly and continue to perform other operations.

the tidb-operator's  log:
```
E1218 09:43:44.323228       1 tidb_cluster_controller.go:239] TidbCluster: example/example, sync failed failed 500 to delete member 4458752632436092868: "etcdserver: member not found"
, requeuing
E1218 09:43:45.640748       1 tidb_cluster_controller.go:239] TidbCluster: example/example, sync failed failed 500 to delete member 4458752632436092868: "etcdserver: member not found"
, requeuing
E1218 09:43:48.241726       1 tidb_cluster_controller.go:239] TidbCluster: example/example, sync failed failed 500 to delete member 4458752632436092868: "etcdserver: member not found"
, requeuing
E1218 09:43:53.396093       1 tidb_cluster_controller.go:239] TidbCluster: example/example, sync failed failed 500 to delete member 4458752632436092868: "etcdserver: member not found"
, requeuing
E1218 09:44:03.668888       1 tidb_cluster_controller.go:239] TidbCluster: example/example, sync failed failed 500 to delete member 4458752632436092868: "etcdserver: member not found"
, requeuing
E1218 09:44:12.470007       1 tidb_cluster_controller.go:239] TidbCluster: example/example, sync failed failed 500 to delete member 4458752632436092868: "etcdserver: member not found"
```

**Comment by xiaojingchen** [comment]
The reason is that the operator does not take into account the non-existent situation when call PD delete API.
Recommended that call a get member API before deleting it; if the member is not found return success directly.

the related code:
https://github.com/pingcap/tidb-operator/blob/master/pkg/controller/pd_control.go#L330
https://github.com/pingcap/tidb-operator/blob/master/pkg/controller/pd_control.go#L348
https://github.com/pingcap/tidb-operator/blob/master/pkg/controller/pd_control.go#L306

**Comment by gregwebs** [comment]
Should PD give a different error code?

**Comment by weekface** [comment]
This may be a solution. https://github.com/pingcap/tidb-operator/issues/238#issuecomment-448185522

PD don't return a 404 not found response if the member is not found when we are deleting it.
So we must get the member again to ensure it is not found if deleting failed. Here is an example:

**Comment by gregwebs** [comment]
There really shouldn't be any operations like this that give a 500 response. It would be good to get that fixed upstream.

**Comment by weekface** [comment]
we should open an issue on PD repo. @xiaojingchen

**Comment by xiaojingchen** [comment]
good, it is a better way.
