### ISSUE TITLE
example yamls for backup and restore with br on gcs

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2398]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Doc and example yamls for backup and restore with br on gcs
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Yisaer** [comment]
We also need br example for aws and ceph.
