### ISSUE TITLE
Metrics duration setting caused failure in auto-scaling sometimes

### ISSUE THREAD

**Issue by sunzhuohang** [pingcap/tidb-operator#2408]
## Bug Report

**What version of TiDB Operator are you using?**

TiDB Operator Version: version.Info{GitVersion:"v1.1.0-beta.1.292+ac2b137590d67c", GitCommit:"ac2b137590d67c556992b4d62b38bc2c44c5d126", GitTreeState:"clean", BuildDate:"2020-05-07T18:00:00Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

Test auto-scaler.

**What did you expect to see?**
Scale nodes normally.

**What did you see instead?**
![image](https://user-images.githubusercontent.com/46194778/81419398-c4187500-9180-11ea-9bf0-e1f779c9826e.png)
When the metricsTimeDuration setting is less than “1m”, there is a probability that no information can be obtained from metricsUrl.
metricsUrl: http://monitor-prometheus.pd-team-s2.svc:9090
![image](https://user-images.githubusercontent.com/46194778/81419801-6fc1c500-9181-11ea-8439-8bf188c64b17.png)

**Comment by Yisaer** [comment]
I guess the non-response is caused by the `scrape_interval` for prometheus configuration as its default value is 1m. If the metricsTimeDuration is too low, the metrics could be haven't been scraped.

**Comment by Yisaer** [comment]
It seems the response query from the `TidbMonitor` (prometheus) is empty when the frequency is too high. That's why the auto-scaler return the error. I think this problem isn't related to the auto-scaler manager. Feel free to reopen if you have any further question.

**Comment by sunzhuohang** [comment]
Thanks for the answer.
