### ISSUE TITLE
Incremental backup and restore with BR

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2409]
## Feature Request

**Is your feature request related to a problem? Please describe:**

BR has supported incremental backup and restore, the operator needs to support this function too.
**Describe the feature you'd like:**

Incremental backup and restore with BR.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by namco1992** [comment]
Hello @DanielZhangQD, I would like to pick this up as we actually need this feature in our cluster. Can you point me to some source code that I should start with?

**Comment by DanielZhangQD** [comment]
@namco1992 Thanks a lot for picking this!
You can refer to https://docs.pingcap.com/tidb/stable/backup-and-restore-tool#back-up-incremental-data for the incremental backup.
For the code change to increase new fields in the Backup CR, you can update the `pkg/apis/pingcap/v1alpha1/types.go` and then run `hack/update-all.sh`, a similar PR is https://github.com/pingcap/tidb-operator/pull/3134
You can follow up with @lichunzhu if any issues during the development. Thanks!

**Comment by namco1992** [comment]
@DanielZhangQD Got it thanks! I will take a look and try to create a PR ASAP!

**Comment by DanielZhangQD** [comment]
@namco1992 Are you still working on this issue?

**Comment by namco1992** [comment]
@DanielZhangQD yes I am, however, I have a question about the scheduled incremental backup. I was planning to add the `lastbackupts` field in the `BackupSchedule` and then the following scheduled incremental backup can refer to that. The `lastbackupts` must be after the GC safepoint, which means if some of the scheduled backups are missed then we might lose the data we need for the next scheduled backup.

For full backup we updated the GC life time and then change it back after the backup, but I'm not sure how to guarantee the `lastbackupts` is valid for scheduled incremental backup.

**Comment by DanielZhangQD** [comment]
For the scheduled incremental backup, what's your use case?
You want to do one full backup and then do scheduled incremental backup? What's the purpose of this?

**Comment by akashsharma95** [comment]
@DanielZhangQD My use case is I want to take full backup then take scheduled incremental backups with `BackupSchedule`

**Comment by DanielZhangQD** [comment]
> @DanielZhangQD My use case is I want to take full backup then take scheduled incremental backups with `BackupSchedule`

@akashsharma95 It's not suggested to do one ad-hoc full backup and then scheduled incremental backups, with this strategy, it would be very complicated to restore all of the data, you have to restore different backups one by one.
BTW, to use scheduled incremental backups, for example, one backup per hour, you have to change the GC time to larger than 1 hour, which will have an impact on the performance of the cluster.
Will binlog or CDC meet your requirement?

@namco1992 With the above description, I think we can support ad-hoc incremental backup for now, WDYT?
BTW, #3360 introduces `spec.br.options` for Backup CR, I think you can just try it.

**Comment by akashsharma95** [comment]
@DanielZhangQD Yes you are right even if I take daily backups to S3, restoring with this daily backup would be difficult task.
I think for taking incremental backup I can use TiCDC but I don't know how to restore from logs generated by TiCDC. The current doc only talks about TiCDC open protocol and MySQL as replication sink. Is there any other doc or resource that you can point to?

**Comment by DanielZhangQD** [comment]
> @DanielZhangQD Yes you are right even if I take daily backups to S3, restoring with this daily backup would be difficult task.
> I think for taking incremental backup I can use TiCDC but I don't know how to restore from logs generated by TiCDC. The current doc only talks about TiCDC open protocol and MySQL as replication sink. Is there any other doc or resource that you can point to?

@3pointer Could you please help provide any help here? Thanks!

**Comment by 3pointer** [comment]
> @DanielZhangQD Yes you are right even if I take daily backups to S3, restoring with this daily backup would be difficult task.
> I think for taking incremental backup I can use TiCDC but I don't know how to restore from logs generated by TiCDC. The current doc only talks about TiCDC open protocol and MySQL as replication sink. Is there any other doc or resource that you can point to?

Thanks for your attention. We already have a plan to restore TiCDC log with BR, you can find details in this [issue](https://github.com/pingcap/br/issues/325), currently the PRs already merged, and we are in test stage. and this feature will deliver as an experimental feature in next version (4.0.8). and we'll make up the document recently. and then you can try this feature in your test environment. we will looking forward to hearing your feedback.

**Comment by namco1992** [comment]
> > @DanielZhangQD My use case is I want to take full backup then take scheduled incremental backups with `BackupSchedule`
> 
> @akashsharma95 It's not suggested to do one ad-hoc full backup and then scheduled incremental backups, with this strategy, it would be very complicated to restore all of the data, you have to restore different backups one by one.
> BTW, to use scheduled incremental backups, for example, one backup per hour, you have to change the GC time to larger than 1 hour, which will have an impact on the performance of the cluster.
> Will binlog or CDC meet your requirement?
> 
> @namco1992 With the above description, I think we can support ad-hoc incremental backup for now, WDYT?
> BTW, #3360 introduces `spec.br.options` for Backup CR, I think you can just try it.

Hello @DanielZhangQD Yes I agree, I will support ad-hoc incremental backup for now. I should be able to  submit a PR tonight!

**Comment by DanielZhangQD** [comment]
> Hello @DanielZhangQD Yes I agree, I will support ad-hoc incremental backup for now. I should be able to submit a PR tonight!

Maybe no need to update code, you can try with `spec.br.options` introduced in #3360, if it works, could you please help update doc `backup-to-aws-s3-using-br.md` and `backup-to-gcs-using-br.md` in the `https://github.com/pingcap/docs-tidb-operator/` repo? Choose any language you prefer in `en` or `zh`.

**Comment by namco1992** [comment]
@DanielZhangQD ok got it, I can update both languages.

**Comment by namco1992** [comment]
@DanielZhangQD Just tested locally and the `spec.br.options` works as expected. However it feels a bit inconsistent as we support some of the arguments in `BRConfig` and some of the arguments as a free form array of strings.

Anyway, I understand that if the BR arguments ever-growing then it could be too much effort to keep up. I will update the doc now.

**Comment by DanielZhangQD** [comment]
> @DanielZhangQD Just tested locally and the `spec.br.options` works as expected. However it feels a bit inconsistent as we support some of the arguments in `BRConfig` and some of the arguments as a free form array of strings.
> 
> Anyway, I understand that if the BR arguments ever-growing then it could be too much effort to keep up. I will update the doc now.

Yes, thanks a lot!

**Comment by namco1992** [comment]
@DanielZhangQD Pls take a look of the PR https://github.com/pingcap/docs-tidb-operator/pull/760 Thanks!

**Comment by DanielZhangQD** [comment]
Close this via https://github.com/pingcap/docs-tidb-operator/pull/760.
