### ISSUE TITLE
Support to Pull an Image from a Private Registry

### ISSUE THREAD

**Issue by gejibin** [pingcap/tidb-operator#2418]
## Feature Request
Need TiDB to create a Pod that uses a Secret to pull an image from a private Docker registry or repository.

**Description:**
The user can configure the imagePullSecrets for a Pod to access the Docker credentials as follows:

apiVersion: v1
kind: Pod
metadata:
  &ensp;name: private-reg
spec:
  &ensp;containers:
  &ensp;\- name: private-reg-container
    &ensp;image: your-private-image
  &ensp;imagePullSecrets:
  &ensp;\- name: regcred

**Comment by cofyc** [comment]
this is useful. can you work on this? you can try to add `imagePullSecrets` in component spec and configure it into component statefulset if it's present.

**Comment by DanielZhangQD** [comment]
What about supporting serviceAccount for each component and the `imagePullSecrets` can be added to the SA as mentioned [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account), then we can meet this request and also benefit from the SA features. WDYT @cofyc
