### ISSUE TITLE
support all internal load balancer description fields

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#242]
It is easy enough to do

```
tidb.service.type=LoadBalancer
tidb.service.anotations=cloud.google.com/load-balancer-type=Internal
```

However, there are other available fields such as `loadBalancerIP` that are not as easy to add.

https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing

**Comment by tennix** [comment]
We can make it configurable but I'm not sure if it's suitable to do so. The load balancer IP may conflict with existing internal IP and it's difficult to get all existing internal IPs. In what cases the user wants to specify the load balancer IP? The load balancer IP would not change after the service is created, so it's stable enough for users.

**Comment by gregwebs** [comment]
The other solution here would be using internal domain names. But there are limitations to that: cross-VPC communication for example does not support internal domain names and instead requires a stable IP address.

From the docs: "The IP address will remain allocated only as long as the forwarding rule exists."
So yes, this seems like it should be stable.

The problem though is having the ability to change or re-create infrastructure. And this can happen accidentally sometimes even for example when using terraform (sometimes it recreates infrastructure when it could just update it).

Right now I want to take a backup, re-create my cluster, and then restore data. To do that I need to be able to specify the InternalIP.

On a somewhat related note, I can't seem to get helm `--set` to work for our annotations.

**Comment by tennix** [comment]
Backup and re-create the cluster should be a rare scenario in production. But if that is required, we can add it. I'll send a PR later to support this.

The `annotations` is a map, if you want to set it from command line, you should use `--set tidb.service.annotations."cloud\.google\.com/loadbalancer-type"=Internal` as stated in the Helm [documentation](https://github.com/helm/helm/blob/master/docs/using_helm.md#the-format-and-limitations-of---set)
