### ISSUE TITLE
chart/tidb-operator: helm template --namespace xxx does not generate correct files

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#2423]
## Bug Report

not all namespaced sources have correct `namespace` set.

```
kind create cluster
helm repo add pingcap https://charts.pingcap.org/
helm template tidb-operator-dev pingcap/tidb-operator --version v1.1.0-rc.3 --namespace pingcap > tidb-operator.yaml
kubectl apply -f tidb-operator.yaml
```

**Comment by 4c74356b41** [comment]
I'm looking at this as well, and it seems like all of the resources don't have a namespace in their templates? is this intentional or just dumb? I dont get it.

**Comment by DanielZhangQD** [comment]
Duplicate with https://github.com/pingcap/tidb-operator/issues/4112.
