### ISSUE TITLE
TiFlash supports advanced statefulset

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2460]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by cofyc** [comment]
basic scaling tests can be added here: https://github.com/pingcap/tidb-operator/blob/b2a5e3ab4351a04e9954ae191c249e2f90dad1b8/tests/e2e/tidbcluster/serial.go#L161
