### ISSUE TITLE
Add options to specify  customized version of Rule

### ISSUE THREAD

**Issue by qiffang** [pingcap/tidb-operator#2465]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, when customer upgrade TiDB, we will use the specify TiDB Rule. But some customers want to use the customized version of Rule because they updated some rules.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Yisaer** [comment]
I think https://github.com/pingcap/tidb-operator/pull/2294 may meet this requirement as it would mount the external configmap if user needed. WDYT @qiffang

**Comment by DanielZhangQD** [comment]
Close via https://github.com/pingcap/tidb-operator/pull/2744
