### ISSUE TITLE
UCP: support AutoSclaerRef for TidbCluster

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2484]
## Description

Currently, 1 tidbcluster could be controlled by multi `TidbclusterAutoScaler`  which is not we want. We need 1 tidbcluster should be controlled by no more than 1 `TidbclusterAutoScaler`.

To achieve this purpose, We want to add a new attribute in `TidbCluster` Status and named as `AutoSclaerRef`.

The `AutoSclaerRef` would be kind like mutex that the `TidbclusterAutoScaler` should first patch itself to the target Tidbcluster's `AutoSclaerRef`. If success, it would start to sync the auto-scaler procss for the target tidbcluster. If not success, it just only skip the current syncing.

The controller logic is much more similar as `MonitorRef`, you can know the reference from this pr. https://github.com/pingcap/tidb-operator/pull/2424

## Score

* 400

## Mentor(s)

* [@yisaer](https://github.com/Yisaer)

Contact the mentors: **#tidb-challenge-program** channel in [TiDB-Operator Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace
As the logic is not simple and the detail is still needed to be discussed, we are welcome for every challenger to contact the mentor if you have any questions.

## Recommended Skills
* Golang
* Kubernetes

**Comment by Yisaer** [comment]
@PengJi  assign the challenge to you, take your time.

**Comment by PengJi** [comment]
@Yisaer OK，I'm interested in it

**Comment by Yisaer** [comment]
@PengJi  Hi, this feature is important to Auto-scaling, so I'm going to realize this feature myself as it seems haven't any progress now.
