### ISSUE TITLE
 [Feature: AdvancedStatefulSet] Upgrading tidb cluster while pods are not consecutive

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2500]
## Bug Report

 https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/5827/tests

**Comment by cofyc** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/6036/tests

**Comment by cofyc** [comment]
I'm working on this.
