### ISSUE TITLE
Status address is unexpected and there is no tikv in types.

### ISSUE THREAD

**Issue by lhy1024** [pingcap/tidb-operator#2511]
## Bug Report

**What version of Kubernetes are you using?**
On 4.4 cluster

**What version of TiDB Operator are you using?**
On 4.4 cluster

**What did you do?**

show config via tidb

**What did you expect to see?**

There are three types, tidb, tikv and pd.

**What did you see instead?**

There are only two types and status address is unexpected.
![image](https://user-images.githubusercontent.com/19542290/82456766-3c6b2880-9ae7-11ea-98d7-49f01b9f84ce.png)

![image](https://user-images.githubusercontent.com/19542290/82456784-41c87300-9ae7-11ea-80fb-5c6d1cd53e77.png)

**Comment by DanielZhangQD** [comment]
`--status-addr=0.0.0.0:20180` is set for cloud deployment.
Which feature are you testing? 
Please paste the user doc link here. And did you check with the tidb or tikv team for the issue that no tikv config via SQL command?

**Comment by lhy1024** [comment]
Only test dynamic config, `set config tikv split.qps-threshold=3000` via sql.
The feature is available on Tiup.

**Comment by DanielZhangQD** [comment]
@lhy1024 Figured it out, the status-addr of tikv needs to be updated in cloud deployment.
Thanks for reporting this issue, and this will be traced in https://github.com/pingcap/tidb-operator/issues/1662.

**Comment by tennix** [comment]
I think we need another parameter (`advertise-status-addr`) for this in TiKV instead of reusing `status-addr` as advertise address. @lhy1024
