### ISSUE TITLE
Split e2e-test into independent jobs

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2512]
## Feature Request

Currently, if the e2e-test failed by 1 job like serial or advancedsts. we have to rerun the e2e-test and the total 4 jobs need to rerun again. Maybe we could split the e2e-test into 4 independent jobs. This would reduce the duplicated test.  WDYT?  @cofyc

**Comment by cofyc** [comment]
I think it's a good idea.

**Comment by cofyc** [comment]
- [ ] add new Jenkins file for general e2e kind job: https://github.com/pingcap/tidb-operator/pull/2872
- [ ] update Github settings for master and release-1.1 branches
