### ISSUE TITLE
Record status in memory for tidbclusterAutoScaler status

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2516]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Ref https://github.com/pingcap/tidb-operator/pull/2307#issuecomment-631843959

Currently, we record tidbclusterAutoScaler status in tidbclusterAutoScaler's status attribute which would cause the in-consistency between the tidbcluster's spec and tidbautoscaler's status.

To solve this problem, as @DanielZhangQD 's comment in #2307, we can try to record the status in operator memory. We would solve this before auto-scaling ga.

**Comment by DanielZhangQD** [comment]
The related codes have been removed in https://github.com/pingcap/tidb-operator/pull/2862.
