### ISSUE TITLE
Expose metrics separately to API clients

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-operator#2529]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, a client who can interact with the PD or TiKV API in order to fetch metrics has full access to the API. This is most relevant for deployments that use an external Prometheus (instance or similar).

1. If TLS is enabled, the client must authenticate using a certificate with the same CN as any other client.
2. Allowing clients that only need metrics to access the entire API is a security problem.

**Describe the feature you'd like:**

Metrics should be available separately from the rest of the API, to a client authenticating using a different TLS certificate CN than other clients.

One simple approach would be to add an option to the CRD to deploy a lightweight proxy that only forwards the metrics prefixes of API accesses.

**Describe alternatives you've considered:**

* Expose metrics via a totally different port
* Enable more granular authorization for the metrics parts of the API, with support for authentication using different CNs
* Remove requirement for CN authorization for metrics URLs on the API

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
As suggested by @gregwebs, we may "separate the authn from authz and authz is turned off for metrics API".

**Comment by gregwebs** [comment]
This isn't an issue for tidb-operator to fix. Closing it in favor of https://github.com/tikv/tikv/issues/7987
