### ISSUE TITLE
publish API and generated client as a separate package

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#2531]
## Feature Request

**Is your feature request related to a problem? Please describe:**

This is useful for external projects to vendor our API and client.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

We can move them into a go submodule (see [example](https://github.com/go-modules-by-example/submodules)) and release it with the root module (tidb-operator).

**Comment by cofyc** [comment]
another example: https://github.com/pingcap/advanced-statefulset/tree/master/client

**Comment by aylei** [comment]
ref: https://github.com/pingcap/tidb-operator/issues/3804

**Comment by aylei** [comment]
cc @lonng @dragonly @DanielZhangQD
