### ISSUE TITLE
Emit an event if failed to sync labels to tikv stores

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#2536]
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://github.com/pingcap/tidb-operator/blob/0e35de5d0a46292290046ea4accf6e1d4149253e/pkg/manager/member/tikv_member_manager.go#L720

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by PengJi** [comment]
let me fix it
