### ISSUE TITLE
e2e: "TLS for MySQL Client and TLS between TiDB components" is flaky

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#2547]
## Bug Report

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/6070/tests

**Comment by cofyc** [comment]
@weekface can you take a look at this?

**Comment by cofyc** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/6107/tests

**Comment by cofyc** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/6105/tests

**Comment by Yisaer** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/6107/tests

**Comment by cofyc** [comment]
all tests fail at the same place:

```
STEP: Begion to backup data cluster "backup"
May 25 18:22:12.519: FAIL: Unexpected error:
<*errors.errorString | 0xc00041d0f0>: {
s: "timed out waiting for the condition",
}
timed out waiting for the condition
occurred
```

This is a big test. Maybe we need to clean up resources before running testBR?

**Comment by cofyc** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/6116/tests

"Backup and restore with BR" without TLS may fail too.

**Comment by Yisaer** [comment]
E2E v1.18 / [tidb-operator] TiDBCluster [Feature: TLS] TLS for MySQL Client and TLS between TiDB components – tidb-operator e2e suite

**Comment by Yisaer** [comment]
It seems the tls case test failed due to the br e2e case is not stable. The restore would fail for some resaon.

**Comment by Yisaer** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/6321/tests

We met this problem again

**Comment by cofyc** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/423/tests/
