### ISSUE TITLE
Revise serial case in e2e test

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2549]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Serial test is time-consuming now, I think we can revise it in 3 ways.
1. Merge `[Feature: AdvancedStatefulSet][Feature: Webhook]` and `[Feature: AdvancedStatefulSet] Upgrade to advanced statefulset` together

2. port `[Feature: Defaulting and Validating]` to basic ginkgo context.

3. Merge `[Verify: Upgrading Operator from 1.0.6` and `upgrading tidb-operator in the same minor series should not trigger rolling-update`

**Comment by cofyc** [comment]
how about adding a new serial test job? we can move some tests to another job, then they can be run in parallel.

**Comment by cofyc** [comment]
of cause, if `[Feature: Defaulting and Validating]` can be moved out, that would be great

**Comment by Yisaer** [comment]
I suggest adding a new serial job when https://github.com/pingcap/tidb-operator/issues/2512 is done. @cofyc

**Comment by cofyc** [comment]
makes sense
