### ISSUE TITLE
scheduler schedule two pd pods on one node when failover happen

### ISSUE THREAD

**Issue by xiaojingchen** [pingcap/tidb-operator#259]
there are only 3 nodes can run pd and tikv, and one node became unavailable. After failover two pd pods were scheduled on one node.
The reasonable handling is to block the last pods when scheduling

**Comment by weekface** [comment]
#235 is a new HA algorithm.

**Comment by cofyc** [comment]
It seems that this has been fixed?

**Comment by xiaojingchen** [comment]
yes, it has been fixed

**Comment by xiaojingchen** [comment]
yes, it has been fixed
