### ISSUE TITLE
tidb-scheduler supports maxSkew feature

### ISSUE THREAD

**Issue by PengJi** [pingcap/tidb-operator#2604]
## Feature Request

**Is your feature request related to a problem? Please describe:**

There is a situation: scheduler topologykey=zone, replicas=5, component=tikv,
We have three zones: A,B and C. If A is supposed to be unschedulable, such as: nodes in A have no avaliable PV, or set as unschedulable by `kubectl cordon`, etc., then according to the current scheduler code logic, the maximum pod number of each zone(zone B and C) is 1, instead of scheduling policy described in the [document](https://pingcap.com/docs-cn/tidb-in-kubernetes/stable/tidb-scheduler/) that can be scheduled to any node, this may cause a scheduling failure.

**Describe the feature you'd like:**

If there are available nodes in the cluster, try to schedule to the available nodes instead of pod pending, of course, that is up to the user

**Describe alternatives you've considered:**

Like topologySpreadConstraints, defined a maxSkew,  which means the maximum permitted 
 difference between the number of pods in different zones, such as zone A: pod x 1, zone B: pod x 2. If maxskew =1, then the maximum number of pod allowed by zone C is 2(2-1=1), and if maxskew =2(3-1=2), then the maximum number of pod allowed by zone C is 3.

I'm not sure if this implementation is reasonable.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by weekface** [comment]
@cofyc @DanielZhangQD @Yisaer PTAL

**Comment by cofyc** [comment]
SGTM

**Comment by tennix** [comment]
There might be an issue that data will be distributed unevenly in each TiKV store. If setting AZ labels, PD will schedule data according to AZ, so TiKV store will have more data if there are few TiKV nodes in this AZ.

**Comment by DanielZhangQD** [comment]
We have supported the Pod Topology Spread Constraints feature, check detail in https://docs.pingcap.com/tidb-in-kubernetes/dev/configure-a-tidb-cluster#use-topologyspreadconstraints-to-make-pods-evenly-spread.
