### ISSUE TITLE
Update br version in the tidb-backup-manager image

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2627]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by tennix** [comment]
We should consider allowing specifying backup manager image when creating Backup CR.

**Comment by DanielZhangQD** [comment]
Then we have to release a backup-manager image for each released BR binary?
