### ISSUE TITLE
Use human readable format for backup size

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#2634]
## Feature Request

Currently, the backup storage size in `Backup` CR and `BackupSchedule` uses bytes as unit, this is unreadable for users. Previously, we use a plain number instead of a number with unit for making these CR easier to parse by API client.

We should consider if we can have both. When retrieving from `kubectl`, shown as a number with unit. When retrieving from other API clients, shown as a number using bytes as unit.

**Comment by cofyc** [comment]
it makes sense

cc @onlymellb what do you think?

**Comment by cofyc** [comment]
cc @zjj2wry  can you look at this issue?

currently the  `BackupSize` column `Backup` CR prints the raw backup size: 

https://github.com/pingcap/tidb-operator/blob/936f0751f5fe7c444ca01e20fc0efc84b61bcd64/pkg/util/crdutil.go#L111-L116

e.g.

```
NAME    BACKUPPATH   BACKUPSIZE      COMMITTS             STARTED   COMPLETED   AGE
xxx   s3://test/   1407065230427   417182047221055569   3h42m     146m        3h42m
```

This is not human readable. Without server-side printing, I guess we need an extra field `.status.backupSizeReadable` for output printing in `kubectl`.

**Comment by zjj2wry** [comment]
Because the type of BackupSize is integer, so it is not readable. Currently crd printer does not support custom column convert. So it can only be solved by adding a field.  i will create a pr to fix it

Quantity rewrites the String() function so it is readable
https://github.com/kubernetes/apimachinery/blob/76330795f827e44ffc47f4fdc8e0d39872bead8f/pkg/api/resource/quantity.go#L600~L608

**Comment by zjj2wry** [comment]
humanize package will be used
```
package main

import (
	"fmt"
	"k8s.io/apimachinery/pkg/api/resource"
	"github.com/dustin/go-humanize"
)

func main(){
	fmt.Println(resource.NewQuantity(1024, resource.BinarySI).String())
	fmt.Println(resource.NewQuantity(1407065230427, resource.BinarySI).String())
	fmt.Println(resource.NewQuantity(123124123431, resource.BinarySI).String())
	fmt.Println(humanize.Bytes(1024))
	fmt.Println(humanize.Bytes(1407065230427))
	fmt.Println(humanize.Bytes(123124123431))
	// 1Ki
	// 1407065230427
	// 123124123431
	// 1.0 kB
	// 1.4 TB
	// 123 GB
}
```
