### ISSUE TITLE
tidb-monitor causes controller panic

### ISSUE THREAD

**Issue by yeya24** [pingcap/tidb-operator#2635]
## Bug Report

Using the latest tidb-operator image.

![Screenshot from 2020-06-06 14-15-47](https://user-images.githubusercontent.com/25150124/83951564-463b9e00-a800-11ea-8b76-7c04c29baa25.png)

Caused by https://github.com/pingcap/tidb-operator/blob/master/pkg/monitor/monitor/monitor_manager.go#L264.

The `mm.cmControl` is nil since it is not initialized.

**Comment by cofyc** [comment]
Thanks for working on this!
