### ISSUE TITLE
[tidb-operator][Serial] [Feature: AutoScaling] auto-scaling TidbCluster  is flaky

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2648]
## Bug Report

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/operator_ghpr_e2e_test_kind/detail/operator_ghpr_e2e_test_kind/6444/tests

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by cofyc** [comment]
a new case: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind-serial/detail/tidb-operator-pull-e2e-kind-serial/638/tests

**Comment by DanielZhangQD** [comment]
The case has been removed and new cases added due to the refactor of the auto-scaling.
