### ISSUE TITLE
Ingress would direct to the wrong PD instance 

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2650]
## Bug Report

In our [document](https://github.com/pingcap/docs-tidb-operator/blob/master/en/access-dashboard.md#prerequisites), we recommended to use `Ingress` to access dashboard.

However, if there are multiple pd instances, the ingress may port the upstream to the wrong pd instance as dashboard would only be started in one pd instance.

One possible solution is to use `discovery` service to proxy the dashboard service. And the Ingress would expose the HTTP service for discovery service.

We can know the dashboard endpoint by visting pdapi `GetConfig`

**Comment by DanielZhangQD** [comment]
https://github.com/pingcap/pd/pull/2508 Dashboard has supported an internal proxy to forward the request, maybe we can just enable it by default with operator deployment. @Yisaer @zjj2wry

**Comment by zjj2wry** [comment]
got it, thanks. should we support this feature after pd 4.0.1 release?

**Comment by DanielZhangQD** [comment]
> got it, thanks. should we support this feature after pd 4.0.1 release?

We can finish the dev now and make it clear in the doc that it's supported from v4.0.1.

**Comment by Yisaer** [comment]
After 4.0.1 released, I think we could update the PD Config and make `Dashboard.InternalProxy` enabled by a switch.

**Comment by DanielZhangQD** [comment]
v4.0.1 is released on06/12.
