### ISSUE TITLE
Show the duration of backup and restore for `kubectl get`

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2659]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, when getting the backup and restore info with kubectl, only the started and completed time is shown:
```
# k get rt -n ns1 -o wide br00
NAME   STARTED   COMPLETED   AGE
br00   12d       12d         12d
# k get bk -n ns0 -o wide br00   
NAME   BACKUPPATH                     BACKUPSIZE   COMMITTS             STARTED   COMPLETED   AGE
br00   s3://danz-backup10/ns0/br00/   452459       416938466661105667   13d       13d         13d
```
It would be more straightforward to show the duration directly.
**Describe the feature you'd like:**

Show the duration of backup and restore for `kubectl get`
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zjj2wry** [comment]
what about add a field TTL?

**Comment by DanielZhangQD** [comment]
> what about add a field TTL?

Could you please explain in more detail?
