### ISSUE TITLE
tidb-scheduler supports for TiFlash

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2666]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, tidb-scheduler only applies customized HA scheduling for PD and TiKV, we'd better support TiFlash which can have similar scheduling strategy with TiKV.
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
Please note that TiFlash supports multiple PVCs.

**Comment by weekface** [comment]
K8s has a [topology spread constraints(EvenPodsSpread)](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) feature, which can achieve HA policy like we did in `tidb-scheduler`. And much more better than `tidb-scheduler`.

So use that feature(EvenPodsSpread) may be a better solution.

**Comment by weekface** [comment]
@DanielZhangQD Please take a look.

**Comment by DanielZhangQD** [comment]
Yes, I think it makes sense.
