### ISSUE TITLE
Provide way to set store labels for TiKV during initialization 

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2692]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Sometimes we need TiKV Initialize with some store labels in order to schedule the data they need instead of setting labels by pd-api after tikv started.

**Describe the feature you'd like:**

`TiKVSpec` should provide a way to let users setting the initialization labels.

**Comment by Yisaer** [comment]
@mahjonp  Does this feature meet your requirement?

**Comment by mahjonp** [comment]
Cool. /cc @BusyJay @cosven

**Comment by cosven** [comment]
My requirement is that different tikv pod can have different labels. 

To my understanding,  if we set labels in TiKVSpec, all tikv pods will have the same labels?

**Comment by Yisaer** [comment]
@cosven  Your understanding is right. For your requirement, I think mixing the [heterogeneous design](https://github.com/pingcap/tidb-operator/issues/2240) and this feature might work.

**Comment by DanielZhangQD** [comment]
We can set labels via config [here](https://github.com/tikv/tikv/blob/master/etc/config-template.toml#L174) and as @Yisaer has explained, when the heterogeneous deployment is supported, we can deploy TiKVs with different labels.
