### ISSUE TITLE
Add leader election to each tidb cluster's tidb-discovery service

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#2693]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by cofyc** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment

Alternatively, we can use this strategy to make sure the previous pod is terminated before upgrades.
