### ISSUE TITLE
Specify Database/Databases For Restore CR

### ISSUE THREAD

**Issue by sstubbs** [pingcap/tidb-operator#2695]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I apologise if I've missed this in the docs but I do not see an option when doing a restore with lightning to specify a specific database to restore.

**Describe the feature you'd like:**
An extra database field to specify either a database or regex for a list of databases.

**Describe alternatives you've considered:**
I've considered doing separate backups for databases but this seems unnecessary.

**Teachability, Documentation, Adoption, Migration Strategy:**
One scheduled backup can be created with the default settings to backup all databases. Then when doing a restore only the specific database/databases can be added rather than restoring all databases.

**Comment by DanielZhangQD** [comment]
@sstubbs Thanks for reporting this request!
It's not supported yet.
Would you like to submit PR for it? Thanks！

**Comment by sstubbs** [comment]
I've been looking through the operator source. I think it would take me a bit of time to get my head around how everything works. Happy to try but after more looking into it does it make more sense to use the binlog and write to an incremental file and then restore from that if needed? Rather than taking full backups each time.

**Comment by sstubbs** [comment]
I'm not very sure how the binlog works all I've seen is it's explanation on the website https://pingcap.com/docs/dev/tidb-binlog/tidb-binlog-overview/ would I be able to restore a specific database or would it restore all databases at that point in time?

**Comment by DanielZhangQD** [comment]
@sstubbs binlog is not used for backup, it's the data replication, e.g. from one TiDB Cluster to another cluster.
`mydumper+lightning` only supports full backup so that you can recover all of the data during a disaster.
If you only take incremental data, when the cluster is gone, how can you get all of the data back? you have to restore from the first full backup and then all of the following incremental data?

**Comment by sstubbs** [comment]
Ok understood thanks for the clarification.

**Comment by DanielZhangQD** [comment]
This should be done for both restoring with lightning and BR.

**Comment by sstubbs** [comment]
I've had a bit of time to look at this and I think I've got an understanding of how it works now. Does it make more sense to include this logic in the operator itself or to include it in lightning and br and parse an argument to them from the operator?

**Comment by DanielZhangQD** [comment]
I think just add options to the restore CR and then pass this option to the command options of lightning in the restore job is OK. For restore with BR, it should already support this with `spec.type` I think.

**Comment by lichunzhu** [comment]
> I've had a bit of time to look at this and I think I've got an understanding of how it works now. Does it make more sense to include this logic in the operator itself or to include it in lightning and br and pass an argument to them from the operator? I ask as mydumper has this passed to it and it world probably make more sense to keep things consistent. I'm not sure how easy this is though as I haven't looked at lighting and br source yet and would rather not if not needed.

Both Lightning([From v4.0.3 on](https://github.com/pingcap/docs/pull/3065/files)) and BR[[From v4.0.3 on](https://github.com/pingcap/docs/pull/3065/files)] support for restoring with [table-filter](https://docs.pingcap.com/tidb/dev/table-filter) in the newest versions. I think we should add `tableFilter` arguments as we did in [back using dumpling](https://github.com/pingcap/tidb-operator/pull/2870).
cc @DanielZhangQD WDYT

**Comment by sstubbs** [comment]
Thank you this table-filter syntax is exactly what I was hoping for. I will wait until this https://github.com/pingcap/tidb-operator/pull/2870 is merged then do a pr for the restore.

**Comment by lichunzhu** [comment]
> Thank you this table-filter syntax is exactly what I was hoping for. I will wait until #2870 is merged then do a pr for the restore.

Thank you for your contribution 👍  If you faced any problem you can directly @me or find me on tidbslack https://pingcap.com/tidbslack.

**Comment by sstubbs** [comment]
ok great thanks will do. I've joined tidbslack.

**Comment by DanielZhangQD** [comment]
> > I've had a bit of time to look at this and I think I've got an understanding of how it works now. Does it make more sense to include this logic in the operator itself or to include it in lightning and br and pass an argument to them from the operator? I ask as mydumper has this passed to it and it world probably make more sense to keep things consistent. I'm not sure how easy this is though as I haven't looked at lighting and br source yet and would rather not if not needed.
> 
> Both Lightning([From v4.0.3 on](https://github.com/pingcap/docs/pull/3065/files)) and BR[[From v4.0.3 on](https://github.com/pingcap/docs/pull/3065/files)] support restoring with [table-filter](https://docs.pingcap.com/tidb/dev/table-filter) in the newest versions. I think we should add `tableFilter` arguments as we did in [back using dumpling](https://github.com/pingcap/tidb-operator/pull/2870).
> What's more, I think add options to the restore CR and then pass this option to the command options of lightning in the restore job is OK.
> cc @DanielZhangQD WDYT

SGTM

**Comment by sstubbs** [comment]
I see the change to dumpling PR has been merged. I was trying to work on the restore part of this but BR doesn't seem to work with minio in the same way as lightning does. I've posted the issue here. https://github.com/pingcap/tidb-operator/issues/2996 

Perhaps it would be better if somebody more experienced with this operator worked on this as with something as important as restore I fear there are things I'm missing.

**Comment by lichunzhu** [comment]
> I see the change to dumpling PR has been merged. I was trying to work on the restore part of this but BR doesn't seem to work with minio in the same way as lightning does. I've posted the issue here. #2996
> 
> Perhaps it would be better if somebody more experienced with this operator worked on this as with something as important as restore I fear there are things I'm missing.

I have replied in this issue. Don't worry, you are doing a great job!

**Comment by DanielZhangQD** [comment]
@sstubbs Are you still working on this issue? Any help do you need?

**Comment by sstubbs** [comment]
I've been in contact with @lichunzhu via slack about it and was just waiting for 4.0.3 which included this feature. I will work on it this week.

**Comment by sstubbs** [comment]
Hi, So I've started working on this. Currently in the spec there is Backup.dumpling.tableFilter and Backup.table and Backup.database for BR. I would like to remove all three of these and just have one Backup.tableFilter that dumpling and br use. Seems to be simple enough for me to do. I just would like to find out if there is any issue in terms of backwards compatibility and whether the table and database are still perhaps needed. In my mind database and table can be easily handled by tableFilter but let me know if I'm misunderstanding something.

I havent looked at lightning yet but would just like to get dumpling and br backup and restore working first using tableFilter. It should a take a day to get this done. Then hopefully the lightning restore is pretty straightforward after that.

**Comment by DanielZhangQD** [comment]
@sstubbs We have to keep backward compatibility. i think we can add a new `Backup.tableFilter`, but we cannot remove the other fields, what about doing as below:
1. add `Backup.tableFilter`
2. add comments that the other fields are deprecated
3. when syncing the CR, check `Backup.tableFilter` first, if no values, then check the other fields. 
cc @lichunzhu

**Comment by sstubbs** [comment]
OK I thought this might be the case I will do what you suggest and add a pr.

**Comment by DanielZhangQD** [comment]
https://github.com/pingcap/tidb-operator/pull/3134 Supports backup specific database or table with Dumpling or BR and supports restore specific database or table with BR.
We also have to support restore specific database or table with lightning.
