### ISSUE TITLE
Add a pre-stage for expansion stage in tikv cluster.

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#2733]
## Feature Request

**Is your feature request related to a problem?**
When we have a tikv cluster need to increase the number of  nodes and the business client not inside the  k8s cluster,  we need to ensure that IP local and dns are synchronized in time.  
For user ,we have two ways:
1.  Pre-allocate IP write to IPAM db and sync to dns server  before expand cluster nodes.
2. Tidb operator provide a friendly expansion method like runmode=debug way, running a empty container without process. After we get a container ip and sync to dns server ,we delete pod and run normally.

**Describe the feature you'd like:**
Tidb Operator provide a friendly expansion method , add a pre-stage for expansion stage . Running empty container before network status or other status synchronization complete  .

**Comment by DanielZhangQD** [comment]
@mikechengwei 
Could you please explain more about your scenario? 
Your cluster is deployed on public cloud or private IDC?
Your application client accesses the TiKV cluster directly? app client (outside of k8s) -> private DNS service -> TiKV Pod?
Do you provision the container IPs of TiKV to your DNS server? What if the Pod is recreated during the rolling update, the IPs will be changed.

**Comment by mikechengwei** [comment]
I deployed in private IDC and we keep ip immutable.
My application outside of k8s cluster , the process of interaction between the client and the tikv server is   `app client -> private dns server -> tikv pod `.
k8s coredns iteself is used to tikv cluster internal communication.
So in expand node stage,i must sync dns map quickly outside of k8s cluster before the client perceive the new container dns name.
