### ISSUE TITLE
Pod and PVC should be deleted after successful Backup/Restore

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-operator#2735]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Backup and Restore leave behind Pods and PVCs even after they complete successfully.

The PVCs continue to hold onto deletable PVs, and in the case of EBS volumes and other kinds of billable storage, this means that the user is going to be paying quite a lot of money for data that is *also* likely stored in S3 or elsewhere.

**Describe the feature you'd like:**

Backup and Restore should delete associated Pods and PVCs if they complete successfully. 

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
@kolbe I would like to add doc only for now for this deletion with below reasons:

- We recommend users doing backup & restore with BR from v3.1.
- This only applies to ad-hoc backup with `mydumper`and restore with `Lightning`, for production, scheduled backup will be used and all of the backups share the same PVC, and for restore, usually, it should be done once only for a cluster.
- The logs of the Pod will be removed if we clean the Pod.

We may evaluate whether need to clean the job automatically later.

**Comment by kolbe** [comment]
This makes perfect sense, and I think addressing this in documentation is fine. Thanks!

**Comment by DanielZhangQD** [comment]
Update: Even if the ad-hoc backups share the same PVC with the scheduled backup.
