### ISSUE TITLE
apiextensions.k8s.io/v1beta1/CustomResourceDefinition is deprecated

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#2753]
## Bug Report

**What version of Kubernetes are you using?**
`v1.16`

**What version of TiDB Operator are you using?**

`v1.1.0`

**What did you see instead?**
apiextensions.k8s.io/v1beta1/CustomResourceDefinition is deprecated by apiextensions.k8s.io/v1/CustomResourceDefinition and not supported by Kubernetes v1.19+ clusters.

**Comment by cofyc** [comment]
actually, it will be removed in v1.22 (see the fix PR: https://github.com/kubernetes/kubernetes/pull/92220)

we should provide a v1 version at least before v1.22.

**Comment by cofyc** [comment]
I removed this from the v1.1.2 milestone as this is not urgent.

**Comment by liubog2008** [comment]
How about using [controller-gen](https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen) to generate CRD. Kubebuilder use this package.

**Comment by xiaojie19852006** [comment]
finally,how to fix the problem?can you give me a new crd.yaml?

**Comment by KanShiori** [comment]
> finally,how to fix the problem?can you give me a new crd.yaml?

Fix by PR https://github.com/pingcap/tidb-operator/pull/4151
