### ISSUE TITLE
terraform eks provider 12.1.0 cannot find kubeconfig

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-operator#2757]
## Bug Report

I upgraded the eks provider in tidb-operator/deploy/modules/aws/tidb-operator/main.tf to 12.1.0 (from 5.1.0) to try to resolve some deployment problems. I found that version 12.1.0 of the operator for some reason cannot find the kubeconfig placed in the credentials/ directory, so tries to use a default k8s endpoint, and failing to connect.

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

**What version of TiDB Operator are you using?**

TiDB Operator Version: version.Info{GitVersion:"v1.1.0", GitCommit:"bc9ca21adb990ca01f41c0ea9b7f6bf5d2efc16b", GitTreeState:"clean", BuildDate:"2020-05-28T11:31:09Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

```
diff --git a/deploy/modules/aws/tidb-operator/main.tf b/deploy/modules/aws/tidb-operator/main.tf
index e9256441..8b037f43 100644
--- a/deploy/modules/aws/tidb-operator/main.tf
+++ b/deploy/modules/aws/tidb-operator/main.tf
@@ -5,7 +5,7 @@ provider "aws" {
 module "eks" {
   source = "terraform-aws-modules/eks/aws"

-  version            = "5.1.0"
+  version            = "12.1.0"
   cluster_name       = var.eks_name
   cluster_version    = var.eks_version
   vpc_id             = var.vpc_id
```

**What did you expect to see?**

I was hoping the apply would succeed 🙂

`terraform apply` should complete without me having to explicitly set KUBECONFIG.

**What did you see instead?**

```
Error: Post "https://0910A4E96A87C7428973241DF47664EA.yl4.us-west-2.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps": dial tcp: lookup 0910A4E96A87C7428973241DF47664EA.yl4.us-west-2.eks.amazonaws.com on 192.168.65.1:53: no such host

  on .terraform/modules/tidb-operator.eks/terraform-aws-eks-12.1.0/aws_auth.tf line 64, in resource "kubernetes_config_map" "aws_auth":
  64: resource "kubernetes_config_map" "aws_auth" {
```

If I do `export KUBECONFIG=credentials/kubeconfig_kolbe-my-cluster` and re-run `terraform apply`, it completes as expected.

**Comment by DanielZhangQD** [comment]
Not sure if it's the issue of the helm provider.

**Comment by DanielZhangQD** [comment]
We will provide new procedures to deploy EKS in https://github.com/pingcap/tidb-operator/issues/2787.
