### ISSUE TITLE
evaluate to introduce chaos-mesh into the operator test

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2759]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
We may need to introduce the chaos-mesh into the operator test flow to help improve the quality.

**Comment by Yisaer** [comment]
I think https://github.com/pingcap/tipocket have already do this test.
