### ISSUE TITLE
Add commitTs to RestoreStatus

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-operator#2774]
## Feature Request

**Is your feature request related to a problem? Please describe:**

It's difficult right now to identify the commitTs of a Restore operation.

**Describe the feature you'd like:**

The RestoreStatus object should include a commitTs that matches the field in the corresponding BackupStatus object.

**Describe alternatives you've considered:**

A user can record the commitTs from a Backup, but after completing the backup and removing associated resources it may be difficult to find, and if the user is doing a Restore to a different cluster, it is painful to have to consult the Backup object on the cluster where the backup was taken.

A user can manually interact with the Pod or PVC associated with the Restore job to consult the `metadata` file, but that is not very convenient.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by kolbe** [comment]
This command can be executed to view the `metadata` file included in the backup while the Restore pod is running:

```
kubectl exec "$restore_pod" \
  -n "$downstream_namespace" -- \
  find /backup -name metadata -exec cat {} \;
```

**Comment by DanielZhangQD** [comment]
This should be done for both restores with `lightning` and `BR`.
