### ISSUE TITLE
New terraform scripts for EKS deployment

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2787]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The current terraform scripts deploy the Kubernetes cluster, Helm, Tiller, and also the TiDB Operator which is error-prone and causes many issues during the deployment.
**Describe the feature you'd like:**

Write new terraform scripts to:
- Deploy the kubernetes cluster and the node pools for different components only
- The scripts should be generic and extensible so that the node pools can be customized and the users can add new node pools for different components easily.
- Do not deploy Helm, Tiller or TiDB Operator

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
@weekface @cofyc @Yisaer WDYT?

**Comment by cofyc** [comment]
SGTM
> Deploy the kubernetes cluster and the node pools for different components only
this should be generic and extensible

**Comment by DanielZhangQD** [comment]
> SGTM
> 
> > Deploy the kubernetes cluster and the node pools for different components only
> 
> this should be generic and extensible

Yes, that's covered in the item `The node pools should be able to customized so that users can add new node pools for different components easily.`.
I will improve the description.

**Comment by Yisaer** [comment]
LGTM

**Comment by DanielZhangQD** [comment]
New provider and module versions should be used.

**Comment by cofyc** [comment]
@kolbe

what do you think if we just use [`eksctl`](https://eksctl.io/) to create the EKS cluster in our docs?

I think providing a solution for creating a Kubernetes cluster on AWS is not our purpose. I would suggest using official solution provided by cloud providers. 

[`eksctl`](https://eksctl.io/) is the official CLI for Amazon EKS and it's flexible and extensive.

For GKE, `gcloud` is good enough.

**Comment by kolbe** [comment]
@cofyc this is such a good question. Our terraform stuff seems so fragile and so frequently broken. It's a lot of work to maintain it and it gives a very bad user experience.

I've also never even heard of `eksctl` and the idea of having to install more nonsense on my machine is not very appealing.

Is it realistic to easily use eksctl to create various different node pools depending on which components an end user wants to deploy?

Are you up for maybe making a new issue where you provide some simple (even very incomplete) examples of how this all might work?

**Comment by cofyc** [comment]
sure, I'll prepare some examples.

**Comment by DanielZhangQD** [comment]
We have to make sure the following functions are covered in the new procedures:

- bastion VM
- customize node pools
- user_data in https://github.com/pingcap/tidb-operator/blob/master/deploy/modules/aws/tidb-cluster/templates/userdata.sh.tpl
- pre_userdata in https://github.com/pingcap/tidb-operator/blob/master/deploy/modules/aws/tidb-cluster/pre_userdata
- labels
- taints
- suspended_processes

**Comment by DanielZhangQD** [comment]
Close via https://github.com/pingcap/docs-tidb-operator/pull/584.
