### ISSUE TITLE
grafana version is outdated

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tidb-operator#2797]
## Bug Report

Now TiDB 4.0 uses grafana 6.1.6, but when deploying by tidb-operator, it will use 6.0.1 instead.

**Comment by DanielZhangQD** [comment]
We may update the version to 6.7.4 which is the latest version of 6.x.

**Comment by BusyJay** [comment]
I suggest to keep consistent across products instead of just upgrading to latest.

**Comment by DanielZhangQD** [comment]
OK, then please notify the Operator team when the granfana or prom version is updated in TiDB.
