### ISSUE TITLE
record the unbind time  with pod and pvc 

### ISSUE THREAD

**Issue by danche** [pingcap/tidb-operator#2813]
## Feature Request

**Is your feature request related to a problem? Please describe:**

we have used the Tidb-operator in the product environment. It's dangerous and difficult to clear pvc`s data. So we have recorded the unbind time for deciding.
So can we commit the PR to review?

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
@danche Could you please explain more detail about `recorded the unbind time for deciding`? What's it for?
