### ISSUE TITLE
the switch of denying the delete TC

### ISSUE THREAD

**Issue by danche** [pingcap/tidb-operator#2814]
## Feature Request

**Is your feature request related to a problem? Please describe:**

we have used the Tidb-operator in the product environment. It's dangerous to delete TC, the operation may result in lose of all data. So we have developed the switch to deny the deleting TC, except the switch is open.
So can we commit the PR to review?

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
@danche Deleting the tc will not remove the PVCs so the data will preserve.
I think yes, you can submit PR where you can explain more about this feature and we can discuss the issues if any on the PR.
Thanks!
