### ISSUE TITLE
自动备份完成无法显示S3的路径(operator 1.1,   tidb 4.0)

### ISSUE THREAD

**Issue by gejibin** [pingcap/tidb-operator#2822]
定时备份成功了，但是无法获取s3 path。

1. 获取s3 path
root@10.226.132.107 online]# kubectl get bk -n   tidb-jln-0624
NAME                                        BACKUPPATH                                                                                                  BACKUPSIZE   COMMITTS             AGE
tidb-jln-0624-auto-2020-06-24t06-14-00      s3://database-bak/tidb-jln-0624-auto/auto-backup/tidb-jln-0624-pd.tidb-jln-0624-2379-2020-06-24t06-14-00/   5267         417589965171982337   4d
tidb-jln-0624-auto-2020-06-24t06-21-00           <没有s3 path>                                                                                                       0                                 4d

2.  spec
Spec:
  Br:
    Cluster:  tidb-jln-0624
  From:
    Host:         tidb-jln-0624-tidb
    Secret Name:  tidb-jln-0624-replicator-secret
    User:         jd_replicator
  Resources:
  S 3:
    Bucket:       database-bak
    Endpoint:     http://s3.cn-north-1.jdcloud-oss.com
    Prefix:       tidb-jln-0624-auto/auto-backup/tidb-jln-0624-pd.tidb-jln-0624-2379-2020-06-24t06-21-00
    Provider:     ceph
    Secret Name:  tidb-jln-0624-s3-secret
Status:
  Backup Path:
  Backup Size:  0
  Commit Ts:
  Conditions:
    Last Transition Time:  2020-06-24T06:32:57Z
    Message:
    Reason:
    Status:                True
    Type:                  Scheduled
  Time Completed:          <nil>
  Time Started:            <nil>
Events:                    <none>
[root@10.226.132.107 online]#

3. logs
_test]
I0624 06:32:55.691257       1 backup.go:92] [2020/06/24 06:32:55.691 +00:00] [INFO] [client.go:841] ["fast checksum success"] [database=test] [table=table_test]
I0624 06:32:55.691401       1 backup.go:92] [2020/06/24 06:32:55.691 +00:00] [INFO] [client.go:168] ["save backup meta"] [path=s3://database-bak/tidb-jln-0624-auto/auto-backup/tidb-jln-0624-pd.tidb-jln-0624-2379-2020-06-24t06-21-00] [jobs=0]
I0624 06:32:55.834232       1 backup.go:92] [2020/06/24 06:32:55.834 +00:00] [INFO] [ddl.go:407] ["[ddl] DDL closed"] [ID=6f4c4027-a701-4139-a777-e74562630f8f] ["take time"=673.408µs]
I0624 06:32:55.834249       1 backup.go:92] [2020/06/24 06:32:55.834 +00:00] [INFO] [ddl.go:301] ["[ddl] stop DDL"] [ID=6f4c4027-a701-4139-a777-e74562630f8f]
I0624 06:32:55.836137       1 backup.go:92] [2020/06/24 06:32:55.835 +00:00] [INFO] [domain.go:607] ["domain closed"] ["take time"=2.118281ms]
I0624 06:32:55.836148       1 backup.go:92] [2020/06/24 06:32:55.835 +00:00] [INFO] [collector.go:195] ["Full backup Success summary: total backup ranges: 1, total success: 1, total failed: 0, total take(s): 0.15, total kv: 1143, total size(Byte): 41148, avg speed(Byte/s): 274892.89"] ["backup checksum"=11.393564ms] ["backup fast checksum"=204.43µs] ["backup total regions"=1]
I0624 06:32:55.838913       1 backup.go:92]
I0624 06:32:55.839059       1 backup.go:107] Backup data for cluster tidb-jln-0624/tidb-jln-0624-auto-2020-06-24t06-21-00 successfully
I0624 06:32:55.865358       1 manager.go:234] reset cluster tidb-jln-0624/tidb-jln-0624-auto-2020-06-24t06-21-00 tikv_gc_life_time to 10m0s success
I0624 06:32:55.865374       1 manager.go:249] backup cluster tidb-jln-0624/tidb-jln-0624-auto-2020-06-24t06-21-00 data to s3://database-bak/tidb-jln-0624-auto/auto-backup/tidb-jln-0624-pd.tidb-jln-0624-2379-2020-06-24t06-21-00/ success
I0624 06:32:56.039266       1 manager.go:266] Get size 25845 for backup files in s3://database-bak/tidb-jln-0624-auto/auto-backup/tidb-jln-0624-pd.tidb-jln-0624-2379-2020-06-24t06-21-00/ of cluster tidb-jln-0624/tidb-jln-0624-auto-2020-06-24t06-21-00 success
I0624 06:32:56.158381       1 manager.go:281] get cluster tidb-jln-0624/tidb-jln-0624-auto-2020-06-24t06-21-00 commitTs 417590247553499137 success
I0624 06:32:56.184362       1 backup_status_updater.go:66] Backup: [tidb-jln-0624/tidb-jln-0624-auto-2020-06-24t06-21-00] updated successfully
[root@10.226.132.107 online]#

**Comment by DanielZhangQD** [comment]
@gejibin Could you please help collect the logs of all of the kube-apiservers during the time when the backup occurs? Thanks!
