### ISSUE TITLE
how to add "imagePullSecret"

### ISSUE THREAD

**Issue by tkalanick** [pingcap/tidb-operator#283]
i am trying to deploy TiDB from a data center inside of China. since i can't reliably access dockerhub, i have to use a private docker registry which requires "imagePullSecret". i figured that i can add the following block 
```   
 {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
{{- end }}    
```

to the template files before i realized that tidb-operator is calling APIs from the go code to setup deployments. how can i work around this? thanks.

**Comment by tennix** [comment]
@tkalanick Yeah, you're right. tidb-operator doesn't support `imagePullSecret` right now. The go code has to be modified to support this. Would you like to send a PR to support this?

**Comment by tkalanick** [comment]
@tennix i actually spent some time trying to make go code modifications in tidb-operator before i found this instruction 
["Add ImagePullSecrets to a service account"](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account), it worked for me and probably saved me a day of go coding.

i am modifying the GCP tidb-operator so that i can deploy tidb to a generic K8S cluster. making changes to yaml files is so much easier than changing go code. so my feedback to you folks is please use as less go code as possible.

**Comment by gregwebs** [comment]
Great! Should we link to that with a comment in values.yaml that someone will find if they search for imagePullSecret?

**Comment by tkalanick** [comment]
it would be nice if you can start a help file which talks about how to install on a generic K8S cluster. it dose not have to be very long. i found the gcp package very useful. probably the only thing missing is how to set up storage class and PVC. i am especially interested in how to setup [local PV](https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/)

**Comment by weekface** [comment]
@tkalanick Here is the setup local PV document: https://github.com/pingcap/tidb-operator/blob/master/docs/setup.md#local-persistent-volume
