### ISSUE TITLE
Make Pod Webhook as default for Operator

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2832]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In 1.1.x , we use Pod webhook to manage the status for tikv and pd in upgrading and scaling-in as an extra option. I suggest use Pod webhook directly without option in 1.2.x as it could be the default choice for `heterogeneous` design controller.

To finish this task, we should finish these things:
1. Make webhook enabled in default
2. Make basic e2e test Webhook enabled.
3. hidden the failurePolicy from values.yaml, make it `Ignore` when apiserver < 1.15, `Fail` when apiserver >= 1.15
4. Make pingcap resource validate and mutation webhook enabled in default.

**Comment by DanielZhangQD** [comment]
Have all of our current test cases covered the Pod Webhook enabled case?

**Comment by Yisaer** [comment]
I think so, currently the pod webhook test cases have covered the basic scaling/upgrading and asts.

**Comment by Yisaer** [comment]
WDYT？ @cofyc @weekface @DanielZhangQD

**Comment by cofyc** [comment]
SGTM

**Comment by DanielZhangQD** [comment]
SGTM, and suggest running all of our test cases for both Pod webhook enabled & disabled scenarios.

**Comment by Yisaer** [comment]
I think when we use pod webhook admission directly without any option, we can only cover the cases with  Pod webhook enabled situation, that is to say, we can discard some e2e cases present. @DanielZhangQD

**Comment by cofyc** [comment]
is it possible to configure `failurePolicy: Ignore` in Kubernetes version below v1.15? because we're still using Kubernetes v1.12, we should make sure the cluster is not affected while the admission controller is unavailable.

**Comment by Yisaer** [comment]
@cofyc sure. I will record this as a new issue.

**Comment by cofyc** [comment]
we can enable it by default but don't remove the option in v1.12, the final removal of the option can be removed in v1.13 if all users are happy with the pod webhook.

**Comment by cofyc** [comment]
do you plan to enable the validation webhook by default in v1.2?

**Comment by Yisaer** [comment]
@cofyc  I think we can.
