### ISSUE TITLE
backups block namespace deletion

### ISSUE THREAD

**Issue by mightyguava** [pingcap/tidb-operator#2888]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**
v1.1.0

**What did you do?**
I deleted the namespace the `TidbCluster` was in.

**What did you expect to see?**

The namespace eventually gets deleted

**What did you see instead?**

The namespace got stuck in the `Terminating` state. Here's what I think happened:

There were `Backups` for the cluster. To delete them, the operator first runs a `Job` to delete the data from S3. However, since the namespace is `Terminating`, Kubernetes refuses to create the `Job`. The operator will keep retrying, and the finalizer on the `Backup` prevents it from being deleted. So the namespace just ends up stuck.

The only workaround seems to be to delete the finalizers.

[operator-logs.txt](https://github.com/pingcap/tidb-operator/files/4891954/operator-logs.txt)

**Comment by kolbe** [comment]
Related to docs-tidb-operator/issues/537

**Comment by DanielZhangQD** [comment]
This should be fixed after https://github.com/pingcap/tidb-operator/issues/2286 is fixed.
