### ISSUE TITLE
Deploy a new cluster joining an existing cluster

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2895]
## Feature Request

**Is your feature request related to a problem? Please describe:**

During migration, for example, from a cluster outside of Kubernetes to Kubernetes, or from one Kubernetes cluster to another one, it would be more graceful if we support creating a cluster joining an existing cluster, in this case, the data will be synced to the new cluster and users can scale down the old cluster step by step.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
We can add `spec.PDAddress` of `[]string`, and if it's configured, update the PD startup script to join the `spec.PDAddress` instead of requesting the startup parameters from the Discovery component.

**Comment by cvvz** [comment]
The format of each `spec.PDAddress` needs to be `scheme://address:port`.
