### ISSUE TITLE
Resizing PV

### ISSUE THREAD

**Issue by sstubbs** [pingcap/tidb-operator#2903]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I'm currently running tidb on openebs local pvs.

**Describe the feature you'd like:**
Increasing amount of space of pv. I've updating the cluster CRD but the pvc and pv remain at the previous size.

**Describe alternatives you've considered:**
I can't think of an alternative for this.

**Comment by DanielZhangQD** [comment]
If your sc supports volume expansion, you can refer to https://docs.pingcap.com/tidb-in-kubernetes/stable/configure-storage-class#network-pv-configuration to update its size.

**Comment by sstubbs** [comment]
Thanks a lot. Sorry I missed this in the documentation.

**Comment by DanielZhangQD** [comment]
@sstubbs FYI, we plan to support patching the PVC automatically when you increase the storage request in the CR, you can check detail in https://github.com/pingcap/tidb-operator/issues/3004#issuecomment-662799686.

**Comment by sstubbs** [comment]
ok great thanks.
