### ISSUE TITLE
Support configuring cluster domain in the TidbCluster CR

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2929]
## Feature Request

**Is your feature request related to a problem? Please describe:**

- Some users may customize the cluster domain of the Kubernetes cluster, e.g. `test.local` instead of `cluster.local`
- For across kubernetes deployment, we have to set full addresses for each pod and service, e.g. ns0-pd-0.ns0-pd-peer.ns0.svc.test.local

**Describe the feature you'd like:**

Support configuring cluster domain in the TidbCluster CR, and set full addresses for each pod and service when the cluster domain is configured.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
Please note that if the cluster domain is not configured in the CR, there should be no changes to the current behavior and the cluster should not be rolling updated after upgrading TiDB Operator to the version including this feature.

**Comment by mikechengwei** [comment]
I can complete this feature because I have this requirement. I have mentioned similar issues #1366 which is closed
