### ISSUE TITLE
controller manager should check the PD svc/pod status.

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#293]
My cluster has a single PD pod stuck in status Pending. If I look at the controller manager logs, I see repeats of this:

```
pd_member_manager.go:204] failed to sync TidbCluster: [tidb54/demo]'s status, error: Get http://demo-pd.tidb54:2379/pd/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

tidb-operator should know already from Kubernetes that there are no pods running for the service. Either because there are no endpoints or because it looks at the status of the underlying pods.

**Comment by tennix** [comment]
So you want to remove the annoying error logs in this case?

**Comment by gregwebs** [comment]
It would be great to see "service tidb54/demo-pd has no endpoints" instead. Just knowing that something cannot connect within a timeout is a very vague failure mode both for the user of the log and tidb-operator.

**Comment by zhaohaidao** [comment]
Is there anyone working on it?
I want to have a try

**Comment by tennix** [comment]
@zhaohaidao Currently, no one working on it. So just go ahead. We really appreciate your help.

**Comment by weekface** [comment]
close in favor of #545
