### ISSUE TITLE
The time zone of pods for automatic backup and manual backup cannot be set

### ISSUE THREAD

**Issue by gejibin** [pingcap/tidb-operator#2944]
tidb实例的输出时间是北京时间，但是做手动备份和自动备份的时间是UTC时间。
The output time of the tidb instance log is Beijing time, but the time for manual backup and automatic backup is UTC time.

The log output time of the manual backup pod is UTC time：
> kubectl logs backup-test-utc-backup-01-4bzpm -n gejb-test
Create rclone.conf file.
/tidb-backup-manager backup --namespace=gejb-test --backupName=test-utc-backup-01 --tikvVersion=v4.0.0
I0715 07:54:57.111015       1 backup.go:71] start to process backup gejb-test/test-utc-backup-01
I0715 07:54:57.142404       1 backup_status_updater.go:66] Backup: [gejb-test/test-utc-backup-01] updated successfully
I0715 07:54:57.180364       1 backup_status_updater.go:66] Backup: [gejb-test/test-utc-backup-01] updated successfully
I0715 07:54:57.183689       1 manager.go:183] cluster gejb-test/test-utc-backup-01 tikv_gc_life_time is 10m0s
I0715 07:54:57.189625       1 manager.go:247] set cluster gejb-test/test-utc-backup-01 tikv_gc_life_time to 72h success
I0715 07:54:57.189687       1 backup.go:68] Running br command with args: [backup full --storage=s3://tidb-dev/test-utc-backup-T01/ --s3.provider=ceph

The log output time of pd is Beijing time：
>kubectl logs test-utc-001-pd-0 -n gejb-test
Name:      test-utc-001-pd-0.test-utc-001-pd-peer.gejb-test.svc
Address 1: 10.233.95.95 test-utc-001-pd-0.test-utc-001-pd-peer.gejb-test.svc.cluster.local
nslookup domain test-utc-001-pd-0.test-utc-001-pd-peer.gejb-test.svc.svc success
starting pd-server ...
/pd-server --data-dir=/var/lib/pd --name=test-utc-001-pd-0 --peer-urls=http://0.0.0.0:2380 --advertise-peer-urls=http://test-utc-001-pd-0.test-utc-001-pd-peer.gejb-test.svc:2380 --client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://test-utc-001-pd-0.test-utc-001-pd-peer.gejb-test.svc:2379 --config=/etc/pd/pd.toml --initial-cluster=test-utc-001-pd-0=http://test-utc-001-pd-0.test-utc-001-pd-peer.gejb-test.svc:2380
[2020/07/15 08:31:20.726 +00:00] [INFO] [util.go:50] ["Welcome to Placement Driver (PD)"]
[2020/07/15 08:31:20.726 +00:00] [INFO] [util.go:51] [PD] [release-version=v4.0.0]
[2020/07/15 08:31:20.726 +00:00] [INFO] [util.go:52] [PD] [edition=Community]
[2020/07/15 08:31:20.726 +00:00] [INFO] [util.go:53] [PD] [git-hash=56d4c3d2237f5bf6fb11a794731ed1d95c8020c2]
[2020/07/15 08:31:20.726 +00:00] [INFO] [util.go:54] [PD] [git-branch=heads/refs/tags/v4.0.0]
[2020/07/15 08:31:20.726 +00:00] [INFO] [util.go:55] [PD] [utc-build-time="2020-05-28 01:39:35"]
[2020/07/15 08:31:20.726 +00:00] [INFO] [metricutil.go:81] ["disable Prometheus push client"]

**Comment by DanielZhangQD** [comment]
Need to support setting Timezone for the following CRs or components:
TidbMonitor, Backup, Restore, BackupSchedule, Pump, admission-webhook, advanced-statefulset-controller

The TiKVGroup and TiDBGroup will be updated on https://github.com/pingcap/tidb-operator/issues/2240.

**Comment by DanielZhangQD** [comment]
@gejibin Would you like to submit PR for this fix?

**Comment by cofyc** [comment]
You can change the timezone of your tidb-operator deployment, then `cron` spec used by BackupSchedule will be parsed in your specified timezone. This is almost the same as Kubernetes [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/). 

https://github.com/pingcap/tidb-operator/blob/ba35f0a176798ce7f13d7fb6a1fb9e7b933d49bb/charts/tidb-operator/values.yaml#L11-L12

**Comment by DanielZhangQD** [comment]
> CronJob

Yes, it makes sense.

**Comment by cofyc** [comment]
TODO

- [ ] admission-webhook, advanced-statefulset-controller deployed via tidb-operator chart should honor `.Values.timezone` 
- [ ] backup-manager job should use the same timezone of tidb-controller-manager
