### ISSUE TITLE
tidb-operator overwrite labels and annotations

### ISSUE THREAD

**Issue by gejibin** [pingcap/tidb-operator#2946]
Based on its own management requirements, the public cloud platform needs to mark some of its own labels or annotations, but it will be overwritten by TiDB-Operator.
Want TiDB-Operator to update the labels or annotations by appending instead of overwriting.

**Comment by DanielZhangQD** [comment]
Yes, it makes sense.
@gejibin Would you like to submit PR for this?

**Comment by SabaPing** [comment]
Could I pick up this issue? I plan to start working today.🤔

**Comment by SabaPing** [comment]
#3892
