### ISSUE TITLE
Support tidbMonitor multiple replicas to ensure high availability

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#2968]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Should we support multiple replicas of TidbMonitor to ensure high availability?  Now ,the replica is one, hard-coded .

https://github.com/pingcap/tidb-operator/blob/e84a3d4fd007a62dfb3fd61681636357ebd787d3/pkg/monitor/monitor/util.go#L229
**Describe the feature you'd like:**

I think we can support replica field in tidbMonitor spec.

**Comment by mikechengwei** [comment]
And i can do it .

**Comment by DanielZhangQD** [comment]
@mikechengwei Thanks a lot!
BTW, usually, we would have monitoring data persistent, how will the data be handled if multiple replicas are created?

**Comment by mikechengwei** [comment]
Currently we use deployment with specified pvc to deploy tidbmonitor. Can we change to use statefulset object? Monitoring is about storage-related services. @DanielZhangQD

**Comment by DanielZhangQD** [comment]
> Currently we use deployment with specified pvc to deploy tidbmonitor. Can we change to use statefulset object? Monitoring is about storage-related services. @DanielZhangQD

Yes, it makes sense, please help evaluate it.
BTW, if we decide to change to sts, we have to consider the migration:

- The resource migration from deployment to sts
- The data migration from the previous Pod

If we just create sts and new PVC in the new version and keep the deployment and PVC of the previous versions, is there a way to provide procedure to guide users about how to access the old data? If yes, then I think it's OK to not consider the migration and after several days, when users do not need the old data, they can just remove the deployment and the PVC.
WDYT @mikechengwei @cofyc

**Comment by mikechengwei** [comment]
When user upgrade  operator , we can keep deployment monitor and create  new sts monitor. In the code, we can determine whether the k8s environment has monitor deployment, it can continue running with old way until the user thinks there is no problem, manauly delete deployment and pvc.

**Comment by DanielZhangQD** [comment]
> When user upgrade operator , we can keep deployment monitor and create new sts monitor. 
Yes.
> In the code, we can determine whether the k8s environment has monitor deployment, 
If we can provide a procedure to guide users to access the old data, I think no need to care about the deployment in the code.

**Comment by mikechengwei** [comment]
I will provide a guide as soon.

**Comment by cofyc** [comment]
I found that we didn't follow the same name convention of Statefulset on PVC objects. Do you think is it possible to provide a smooth migration without manual intervention?

If not, maybe we can have a field `controller` field to specify which workload we're going to use? It has two fields: Deployment, StatefulSet. New users can use `StatefulSet`.

**Comment by mikechengwei** [comment]
I think we should provide such a smooth migration process:

1. deployment -> deployment + statefulset -> statefulset. 
2. deployment->statefulset

User can run tidbmonitor with old way by deployment , and they can change to keep deployment and statefulset monitor tidb at the same time  or change to statefulset directly. 

Providing a `controller` field with value contains `statefulset`,`deployment`,and it is a list type.

```
monitor:
  controller: 
      - deployment
      - statefulset
```


## TODO list
1. write a new method `syncTidbMonitorStatefulset` , if `monitor.controller` contains `sts`.  
    - statefulset should inherit the existing monitor configuration. I think it is easy.
2. provide  a upgrade monitor document to user

And if  user use thanos architecture,we must sure thanos sidecar can config extra replica label.

**Comment by DanielZhangQD** [comment]
@mikechengwei How will the old data be handled?
Do you plan to migrate the data manually or just leave the old data as it is and provide a procedure to access them?
And what's the behavior for the below configurations:
```
monitor:
  controller: []
```
Defaults to `deployment` or `statefulset`?

```
monitor:
  controller: 
  - statefulset
```
So this just syncs the sts, if users deployed the monitor with `deployment` before the upgrade, the operator does not need to remove the deployment and its PVC after the upgrade, right?

```
monitor:
  controller: 
  - deployment
  - statefulset
```
Sync both of them or just `sts`?

**Comment by mikechengwei** [comment]
> Do you plan to migrate the data manually or just leave the old data as it is and provide a procedure to access them?
Old users should let them upgrade themselves ,data does not need to be migrated. Both sts and deployment can be run at the same time. The user decides when to take the deployment offline.
> monitor:
> controller: []
Run with deployment (default)

>monitor:
>  controller: 
> - statefulset
Run with statefulset 

> So this just syncs the sts, if users deployed the monitor with deployment before the upgrade, the operator does not need to remove the deployment and its PVC after the upgrade, right?
yes!

>monitor:
>  controller: 
>  - deployment
>  - statefulset
Both running.

This scheme is more flexible.

**Comment by cofyc** [comment]
>> 2. deployment->statefulset

what if we run a migration process if the deployment and its PVCs are found? because PVC objects are created by our controller, we can just rename it before creating the stateful set?

**Comment by mikechengwei** [comment]
We can't rename pvc in k8s ，reference https://stackoverflow.com/questions/48403542/how-to-rename-persistence-volume-claim.

> 2. deployment->statefulset
If use select this option, the data will lost.

**Comment by cofyc** [comment]
I see. even if we can delete & create to "rename" the PVC, but it might be complex.

**Comment by cofyc** [comment]
But I think it's worth a try if we can migrate the data automatically. the basic procedure will be:

- create a new PVC (xxx-0) and bind it the PV manually
- delete the old PVC
- create the stateful (xxx), because the PVC xxx-0 already exists, the pod will use the old data

**Comment by DanielZhangQD** [comment]
> But I think it's worth a try if we can migrate the data automatically. the basic procedure will be:
> 
> * create a new PVC (xxx-0) and bind it the PV manually

Can this work? I tried with local-storage but it seems that the new PVC can't bind to the PV.

> * create the statefulset (xxx), because the PVC xxx-0 already exists, the pod will use the old data
> * delete the old deployment and PVC

Before the deployment is removed, two Pods will write data to the same directory, not sure if any unexpected issues will occur.

**Comment by DanielZhangQD** [comment]
@mikechengwei 

1. If we cannot migrate automatically,

> Old users should let them upgrade themselves ,data does not need to be migrated. 

We have to provide a procedure to guide users to access the old data.

2. For the deployment -> sts migration, what about the following logic based on your proposal above:
```
monitor:
  controller: []
```
```
monitor:
  controller: 
  - deployment
```

In the above two cases, sync deployment + PVC as we are doing now.

```
monitor:
  controller: 
  - statefulset
```
```
monitor:
  controller: 
  - deployment
  - statefulset
```

In the above two cases:

- For new deployment, just sync sts, no need to care about the deployment, because there is no need to have both deployment and sts deployed at the same time for a new cluster.
- For upgrade from previous versions, just sync sts and leave the deployment and its PVC as it is and let users handle it (of course we have to make it clear in the doc)

**Comment by cofyc** [comment]
> > But I think it's worth a try if we can migrate the data automatically. the basic procedure will be:
> > 
> > * create a new PVC (xxx-0) and bind it the PV manually
> 
> Can this work? I tried with local-storage but it seems that the new PVC can't bind to the PV.
> 
> > * create the statefulset (xxx), because the PVC xxx-0 already exists, the pod will use the old data
> > * delete the old deployment and PVC
> 
> Before the deployment is removed, two Pods will write data to the same directory, not sure if any unexpected issues will occur.

a more detailed version:

- save the name of old PV on the CR object (can continue the migration work if the operator crashes in the middle)
- update the PV to pre-bind the new PVC (xxx-0) 
   - add the name of PVC (xxx-0) in the claimRef
- delete the old deployment and PVC
- create the statefulset (xxx)
   - the PVC xxx-0 will be created and will bind to the old PV because it has already been pre-bound to the PVC xxx-0

**Comment by cofyc** [comment]
pre-binding of PV & PVC can be done in two ways:

- specify the PV name in the PVC's `volumeName` field
- specify the PVC name in the PV's `claimRef.name` field 

 in this scenario, the latter is better I guess because it can avoid the PV to be bound with other PVC by the PV controller after it's unbound from the old PVC

**Comment by mikechengwei** [comment]
1. Does local pv support `ReadWriteMany` access mode ? 
2. I think  it is ok for user migrate themselves. The importance of monitoring data depends on whether the user is concerned. If he is concerned, manually deleting the deployment is no problem.

**Comment by mikechengwei** [comment]
After my manual testing, I found that it is available to modify the pv claimRef.name for migrating. I redesigned the plan.

We provide the `controller` field contains sts and deployment value, and the type is string. When user change the value to statefulset , start upgrade process as follows:

1. delete deployment 
2. modify the `claimRef.name` field of  existing pv 
3. create new pvc for statefulset first pod.
4. create sts with one or multiple replicas , sts use volumeTemplate field.
5. create service for sts.
5. delete old pvc.
 
I don't think sts change to deployment deploy needs to be considered in this process, is this process irreversible?

**Comment by cofyc** [comment]
If we can migrate the data automatically. I think we can change the underlying controller from Deployment to Statefulset directly. 
Which controller we use internally to manage Pods & PVCs does not matter as users create/edit our TidbMonitor CR object.

All we need to do:

1) make sure the migration is well tested
2) add a release note telling the users the pod will be recreated after the tidb-operator is upgraded

**Comment by DanielZhangQD** [comment]
> 1. delete deployment
> 2. modify the claimRef.name field of existing pv
> 3. create new pvc for statefulset first pod.

The above steps will be done by TiDB Operator automatically? Is it safe to do that? @mikechengwei @cofyc

**Comment by mikechengwei** [comment]
The plan  is ok.  We need to ensure the reliability of the code .
I think running sts and deployment at the same time ,user delete deployment manually. It is more reliable.

**Comment by DanielZhangQD** [comment]
Then we can let users delete the deployment and old PVC manually.

**Comment by mikechengwei** [comment]
What do you think? @cofyc

**Comment by cofyc** [comment]
I still prefer changing the internal implementation from deployment to statefulset directly and take over the old PV if found.

We don't need to change the API interface and maintain two similar code paths in our code. 

It gives the best user experience. No manual intervention is required, only the pod is recreated I think it's fine.

**Comment by DanielZhangQD** [comment]
SGTM
