### ISSUE TITLE
Make the spec.pd, spec.tidb, and spec.tikv optional in the TidbCluster CR

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2971]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Make the spec.pd, spec.tidb, and spec.tikv optional in the TidbCluster CR, e.g. change them to pointer.
Part of #2240 
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mikechengwei** [comment]
And I think we can control replica to make tidb ,tikv and pd optional. What do you think? @DanielZhangQD

**Comment by DanielZhangQD** [comment]
> I have a question that when the configmap of tikv or tidb update , how to trigger workload update? For example, the pdAddress update ,tikv or tidb need to update. @DanielZhangQD

If setting `spec.configUpdateStrategy: RollingUpdate`, when the cm is updated, a new name will be [generated](https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/tidb_member_manager.go#L421) for the cm and the sts spec will be updated to [use the new cm](https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/tidb_member_manager.go#L560), which will trigger the rolling update.

**Comment by DanielZhangQD** [comment]
> And I think we can control replica to make tidb ,tikv and pd optional. What do you think? @DanielZhangQD

Just change the `spec.pd/tidb/tikv` to pointer and check `spec.pd/tidb/tikv !=nil` is OK.

**Comment by mikechengwei** [comment]
ok. thanks.

**Comment by DanielZhangQD** [comment]
Close via #3009.
