### ISSUE TITLE
TidbCluster controller update for the spec.pd, spec.tidb, and spec.tikv change

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2973]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TidbCluster controller update for the spec.pd, spec.tidb, and spec.tikv change in https://github.com/pingcap/tidb-operator/issues/2971
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mikechengwei** [comment]
I think `PDAddress` change , we need to rolling update tidb and tikv. What do you think? @DanielZhangQD

**Comment by DanielZhangQD** [comment]
> I think `PDAddress` change , we need to rolling update tidb and tikv. What do you think? @DanielZhangQD

If no change to the spec and just upgrade the TiDB Operator, the cluster should not roll update.
If users config the `spec.pdAddress`, yes, TiDB and TiKV will roll update.

**Comment by mikechengwei** [comment]
From what you said, I think it is a very dangerous action for users to modify the pdAddress field of an existing cluster. We should not support the update of pdAddress, we should only support creation and deletion, because  both tikv and tidb are storage with state, we cannot update them as pure computing nodes. @DanielZhangQD

**Comment by mikechengwei** [comment]
In other words, we should only support updating when pdAddress is configured incorrectly. Instead of updating the pdAddress field across the two clusters.

**Comment by DanielZhangQD** [comment]
> In other words, we should only support updating when pdAddress is configured incorrectly. Instead of updating the pdAddress field across the two clusters.

How can you implement this?
BTW, if `spec.pd` is configured, then the PD Address of TiDB and TiKV should use the `<cluster>-pd` instead of `spec.pdAddress`, then it should be OK if users configure the `spec.pdAddress` for an existing cluster.

**Comment by DanielZhangQD** [comment]
> We should not support the update of pdAddress, we should only support creation and deletion
> In other words, we should only support updating when pdAddress is configured incorrectly. Instead of updating the pdAddress field across the two clusters.

I think if both `spec.pd` and `spec.pdAddress` are configured, the `<cluster>-pd` address should take precedence over `spec.pdAddress`.

**Comment by DanielZhangQD** [comment]
Close via #3009.
