### ISSUE TITLE
When deleting a failed backup CR, the backup data on s3 is not cleaned up。

### ISSUE THREAD

**Issue by gejibin** [pingcap/tidb-operator#2989]
A manual backup failed，delete this backup CR, but the backup data on s3 is not cleaned up。

When backup failed, the data on s3 are rubbish。

Want to clean up the backup files on S3 when deleting the backup CR.

**Comment by cofyc** [comment]
it makes sense IMO
if we should delete the data on the deletion of the backup CR, we should delete even if the backup process fails

**Comment by DanielZhangQD** [comment]
We have supported `cleanData` in #2892, should we also clean the data in S3 for the failed backup CR if `cleanData` is set to false? WDYT @cofyc @lichunzhu

**Comment by cofyc** [comment]
IMO `cleanData=false` implies the underlying data should not be managed by our controller like `Retain` policy

**Comment by DanielZhangQD** [comment]
@gejibin What's your opinion?

**Comment by lichunzhu** [comment]
IMO we should

> We have supported `cleanData` in #2892, should we also clean the data in S3 for the failed backup CR if `cleanData` is set to false? WDYT @cofyc @lichunzhu

**Comment by cofyc** [comment]
if we clean the data if the backup process fails no matter what value the `cleanData` is, I would suggest using a different name as this name will be confusing.

**Comment by gejibin** [comment]
if delete a failed backup CR, clean up the rubbish data on s3 no matter what value the cleanData is.

**Comment by DanielZhangQD** [comment]
close via #3002
