### ISSUE TITLE
Some doubt about AnnPVCPodScheduling

### ISSUE THREAD

**Issue by knightXun** [pingcap/tidb-operator#3007]
In scheduler, AnnPVCPodScheduling act like a locker, make scheduler plugins can schedule tikv/pd serially.  But I was very confused when I notice scheduler can remove old pod's AnnPVCPodScheduling flag. Why can't scheduler wait the old pod run ok? the pvc_cleaner will remove this flag after the tikv/pd is really running.

**Comment by cofyc** [comment]
@weekface can you take a look?

**Comment by weekface** [comment]
@knightXun 

If the old pod scheduled, the tidb-scheduler can schedule other pods soon.

tidb-scheduler should not wait the old pod running, this may need seconds or minutes, it blocks the tidb-scheduler schedule other pods for a long time.

**Comment by knightXun** [comment]
@weekface If so,  I believe there is racing here, When the old pod is still sheduling, The new one can take this flag, That mean there will at least two pods  on the scheduling, That may make some mistake

**Comment by weekface** [comment]
The new pod must [acquire](https://github.com/pingcap/tidb-operator/blob/master/pkg/scheduler/predicates/ha.go#L99) the lock to schedule.
