### ISSUE TITLE
Launch a TiDB cluster failed

### ISSUE THREAD

**Issue by bigsheeper** [pingcap/tidb-operator#3014]
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of TiDB Operator are you using?**
```
TiDB Operator Version: version.Info{GitVersion:"v1.1.2", GitCommit:"04c96f3b1b35f0196f4298c15b6c12559976b57b", GitTreeState:"clean", BuildDate:"2020-07-01T11:43:16Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
no TiDB Cluster

**What did you do?**
I follow the instruction in TiDB Operator Get Started document ( <https://docs.pingcap.com/tidb-in-kubernetes/v1.0/deploy-tidb-from-kubernetes-minikube>). And I deploy TiDB in the Minikube Cluster. 

However, when I get to *Launch a TiDB cluster* ( <https://docs.pingcap.com/tidb-in-kubernetes/v1.0/deploy-tidb-from-kubernetes-minikube#launch-a-tidb-cluster> ) with command:
```
helm install pingcap/tidb-cluster --name demo --set \
  schedulerName=default-scheduler,pd.storageClassName=standard,tikv.storageClassName=standard,pd.replicas=1,tikv.replicas=1,tidb.replicas=1 --version=1.1.2
```

An error came out: 
```
Error: render error in "tidb-cluster/templates/monitor-secret.yaml": template: tidb-cluster/templates/monitor-secret.yaml:1:7: executing "tidb-cluster/templates/monitor-secret.yaml" at <(.Values.monitor.create) and (.Values.monitor.grafana.create)>: can't give argument to non-function .Values.monitor.create
```

**What did you expect to see?**
Launch a TiDB cluster successfully.

**What did you see instead?**
render error above

**Comment by bigsheeper** [comment]
And I'm sure my tidb-scheduler and tidb-controller-manager are running:
```bash
sheep@sheep:~/workspace/tidb-operator$ kubectl get pods --namespace tidb-admin -o wide --watch
NAME                                       READY   STATUS    RESTARTS   AGE   IP           NODE       NOMINATED NODE   READINESS GATES
tidb-controller-manager-588848b7b6-r6rrr   1/1     Running   0          41s   172.18.0.5   minikube   <none>           <none>
tidb-scheduler-6586c74c8b-qtkd5            2/2     Running   0          41s   172.18.0.4   minikube   <none>           <none>
```

**Comment by cofyc** [comment]
@bigsheeper can you try the latest tidb-operator version? v1.1 

https://docs.pingcap.com/tidb-in-kubernetes/stable/get-started

**Comment by cofyc** [comment]
ah, I see you are using tidb-operator v1.1, but using the v1.0 docs. I would suggest you following the latest docs.

**Comment by bigsheeper** [comment]
Well, thank u for your reply very much! I would try again by following the latest docs.
