### ISSUE TITLE
Can't collect logs through dashboard

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tidb-operator#3025]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

tidb-operator: v1.1.1
tidb cluster: v4.0.2

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

![image](https://user-images.githubusercontent.com/12085878/88613434-04bcc600-d0c0-11ea-9f14-3ea54f5844cf.png)
Collect logs through dashboard.

**What did you expect to see?**
Collect logs successufully.

**What did you see instead?**
Collect logs failed.

**Comment by weekface** [comment]
In kubernetes env, the container logs are printed to `stderr` not a log file. But the Dashboard only collect and search logs from a log file now, so the log search can't work in kubernetes env now. We suggest user use [EFK](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-elasticsearch-fluentd-and-kibana-efk-logging-stack-on-kubernetes) to collect logs in kubernetes env.
