### ISSUE TITLE
tidb-lightning does not need to access pd

### ISSUE THREAD

**Issue by gejibin** [pingcap/tidb-operator#3026]
When tidb-lightning is used for data import, in public cloud environment, pd is not exposed to outside, so tidb-lightning should not access pd.  A configuration option can be added to configure the tidb-lightning to run without access to pd.

Public cloud environments generally only exposes two service, tidb and grafana.
公有云环境一般只会暴露tidb和grafana这个两个服务。

**Comment by DanielZhangQD** [comment]
tidb-lightning should be deployed in the same namespace with the TiDB Cluster so that it can access the PD.
You can follow the doc here https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/restore-data-using-tidb-lightning.

**Comment by DanielZhangQD** [comment]
@gejibin Please reopen this issue if any more support required.
