### ISSUE TITLE
Support syncing TiDB when TiKV is under syncing

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#3033]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When TiKV is upgrading or scaling, tidb can't be syncing. As tikv syncing would be rather time-consuming (especially in prod), I suggest tidb can be syncing even tikv is under syncing.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
Duplicate with https://github.com/pingcap/tidb-operator/issues/1245.
