### ISSUE TITLE
tidb-initializer: init container requires docker hub 

### ISSUE THREAD

**Issue by serbaut** [pingcap/tidb-operator#3042]
## Bug Report

**What version of Kubernetes are you using?**
v1.18.3

**What version of TiDB Operator are you using?**
TiDB Operator Version: version.Info{GitVersion:"v1.1.3", GitCommit:"1cf12d67fba0f68dd2e8c2b6744e2f91de8ef3e7", GitTreeState:"clean", BuildDate:"2020-07-27T10:49:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**What's the status of the TiDB cluster pods?**
```
$ kubectl -n databases get po -o wide
NAME                                       READY   STATUS                  RESTARTS   AGE   IP           NODE      NOMINATED NODE   READINESS GATES
default-discovery-545477b5f5-rqd5b         1/1     Running                 0          30m   10.42.5.6    worker3   <none>           <none>
default-pd-0                               1/1     Running                 0          30m   10.42.4.7    worker2   <none>           <none>
default-pd-1                               1/1     Running                 0          30m   10.42.5.7    worker3   <none>           <none>
default-pd-2                               1/1     Running                 1          30m   10.42.3.10   worker1   <none>           <none>
default-tidb-0                             2/2     Running                 0          28m   10.42.5.9    worker3   <none>           <none>
default-tidb-1                             2/2     Running                 0          28m   10.42.4.9    worker2   <none>           <none>
default-tidb-initializer-vvxwp             0/1     Init:ImagePullBackOff   0          30m   10.42.4.6    worker2   <none>           <none>
default-tikv-0                             1/1     Running                 0          29m   10.42.5.8    worker3   <none>           <none>
default-tikv-1                             1/1     Running                 0          29m   10.42.4.8    worker2   <none>           <none>
default-tikv-2                             1/1     Running                 0          29m   10.42.3.11   worker1   <none>           <none>
tidb-controller-manager-8655b6f79b-m8fbj   1/1     Running                 0          32m   10.42.4.5    worker2   <none>           <none>
tidb-scheduler-6654df6f84-pp9bm            2/2     Running                 0          32m   10.42.5.5    worker3   <none>           <none>

```
**What did you do?**
Created a new cluster with the following initializer:

```
apiVersion: pingcap.com/v1alpha1
kind: TidbInitializer
metadata:
  name: tidb-initializer
  namespace: databases
spec:
  image: tcr.trioptima.net/docker.io/tnir/mysqlclient
  cluster:
    namespace: databases
    name: default
  initSql: |-
    create database foo;
  # initSqlConfigMap: tidb-initsql
  passwordSecret: tidb-secret

```

**What did you expect to see?**
Successfull tidb initialization.

**What did you see instead?**
Init container failed to pull busybox:1.31.1 since there is a firewall blocking internet access.

` Warning  Failed     24m (x4 over 26m)    kubelet, worker2   Failed to pull image "busybox:1.31.1": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
`

The init container image should be configurable or use the same image as the main container which is configurable.

**Comment by DanielZhangQD** [comment]
@serbaut Thanks for reporting this issue!
Would you like to submit PR for this fix?

**Comment by serbaut** [comment]
I can submit a PR. Would you like to reuse the mysql image or make the init container image configurable?

**Comment by DanielZhangQD** [comment]
Currently, it uses the busybox image, I think we can make it configurable and optional, if not configured, just use the default image [here](https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/tidb_init_manager.go#L51), WDYT? @serbaut

**Comment by serbaut** [comment]
Would the initContainerImage need imagePullPolicy and imagePullSecrets too then?

Just thinking since tnir/mysqlclient is based off alpine/busybox 1.31.1 we could use the same image to make it simpler?

**Comment by DanielZhangQD** [comment]
> Just thinking since tnir/mysqlclient is based off alpine/busybox 1.31.1 we could use the same image to make it simpler?

I think it's OK, and also share the imagePullPolicy.
imagePullSecrets is for Pod.
cc @cofyc

**Comment by cofyc** [comment]
SGTM

**Comment by serbaut** [comment]
I am a bit confused about the helm chart https://github.com/serbaut/tidb-operator/blob/master/charts/tidb-cluster/templates/tidb-initializer-job.yaml#L28

The operator renders the init script here https://github.com/serbaut/tidb-operator/blob/master/pkg/manager/member/template.go#L333

What is the helm chart used for?

**Comment by DanielZhangQD** [comment]
> I am a bit confused about the helm chart https://github.com/serbaut/tidb-operator/blob/master/charts/tidb-cluster/templates/tidb-initializer-job.yaml#L28
> 
> The operator renders the init script here https://github.com/serbaut/tidb-operator/blob/master/pkg/manager/member/template.go#L333
> 
> What is the helm chart used for?

The chart is used in TiDB Operator v1.0.x, from v1.1.x, we have transferred to CR for the cluster management so you can ignore the chart.
