### ISSUE TITLE
Build CLI for TiDB Operator

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#305]
It will be convenient if we build a CLI utility to manage tidb-cluster and the other resources like `istio-ctl`.

v1 plan:

Commands:
- [x] use: select tidb cluster to use
- [x] list: list tidb clusters
- [x] info: get tidb cluster help info
- [x] get: get tidb cluster resource details
- [x] debug: troubleshooting tidb cluster
- [ ] pdctl: launch pdctl
- [x] ctop: real-time container monitoring

Misc:
- [x] unit test
- [x] CI/CD
- [x] document
- [ ] e2e test
- [ ] *select by store-id/member-id
- [ ] *columns beyond k8s meta (volume available bytes, etc.)
- [x] *auto-completion @onlymellb 

*:optionally

**Comment by aylei** [comment]
#357 Completes part of the CLI design

**Comment by tennix** [comment]
Can we add a checklist for the CLI in this issue to help track what will be implemented and the current progress?

**Comment by aylei** [comment]
> Can we add a checklist for the CLI in this issue to help track what will be implemented and the current progress?

Of course, I've added that.

**Comment by gregwebs** [comment]
@aylei should this be close now or we are still going through the checklist?

**Comment by aylei** [comment]
@gregwebs Thanks for your attention! I am going to close it now

**Comment by aylei** [comment]
un-done items are supposed to be tracked in separate issues, closing
