### ISSUE TITLE
Support image digest in ComponentSpec

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-operator#3050]
## Feature Request

**Is your feature request related to a problem? Please describe:**

It should be possible to specify an image's digest instead of a tag.

Today, the digest can be appended to the `baseImage` field, but the cluster `version` field is still appended to that to get an image name, which is illegal:

```
Failed to apply default image tag "pingcap/tidb@sha256:387829e3352027dc03ecd8f2935a896558dee36df4a5a5a7c45d95b8ea686d5f:v4.0.3": couldn't parse image reference "pingcap/tidb@sha256:387829e3352027dc03ecd8f2935a896558dee36df4a5a5a7c45d95b8ea686d5f:v4.0.3": invalid reference format
```

If you set the components `version` to an empty string, a colon is still appended, which is also illegal:

```
Failed to apply default image tag "pingcap/tidb@sha256:387829e3352027dc03ecd8f2935a896558dee36df4a5a5a7c45d95b8ea686d5f:": couldn't parse image reference "pingcap/tidb@sha256:387829e3352027dc03ecd8f2935a896558dee36df4a5a5a7c45d95b8ea686d5f:": invalid reference format
```

**Describe the feature you'd like:**

I see a couple different options:

1. Add a `digest` field to ClusterComponent. It should not be allowed to set both `version` and `digest`. If `digest` is set, it should be appended to `baseImage`, separated by `@` instead of the `:` used for a tag.

2. Allow a user to explicitly append a digest to `baseImage`, but avoid appending a colon if they set ClusterComponent.version to an empty string (or some other value).

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
@kolbe There are several ways to do this:

- set `spec.version: ""`, do not set `spec.tidb.version`, set `spec.tidb.image: pingcap/tidb@sha256:387829e3352027dc03ecd8f2935a896558dee36df4a5a5a7c45d95b8ea686d5f`, and in this case, we have to set `spec.pd.version: v4.0.3`, `spec.tikv.version: v4.0.3`.
- set `spec.tidb.baseImage: pingcap/tidb@sha256`, `spec.tidb.version: 387829e3352027dc03ecd8f2935a896558dee36df4a5a5a7c45d95b8ea686d5f`
