### ISSUE TITLE
TLS support for heterogeneous components

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3061]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mikechengwei** [comment]
I think heterogeneous cluster use tls feature just need to create the same secret as original cluster.

**Comment by DanielZhangQD** [comment]
No need to create the secret anymore, we can just reuse the secret of the original cluster and update the code to get the secret name, for example, https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/tidb_member_manager.go#L588 and https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/tidb_member_manager.go#L594.
