### ISSUE TITLE
Monitoring for heterogeneous components

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3062]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We have to make sure the monitoring works as expected for heterogeneous components. 
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mikechengwei** [comment]
I test with deploying heterogeneous and basic cluster,then i deploy heterogeneous monitor and basics monitor. I find monitor works for heterogeneous components.

![image](https://user-images.githubusercontent.com/13257127/90319212-98b7da00-df68-11ea-8739-c8554e133a6d.png)
heterogeneous ：
![image](https://user-images.githubusercontent.com/13257127/90319219-a5d4c900-df68-11ea-81c2-c57e87069dfe.png)
basic:
![image](https://user-images.githubusercontent.com/13257127/90319223-abcaaa00-df68-11ea-88e8-4cf3ee98a61c.png)

**Comment by mikechengwei** [comment]
I think we need provide a centralized monitoring solution， and  i will contribute my thanos solution soon.

**Comment by DanielZhangQD** [comment]
We'd better update the TidbMonitor controller to support retrieving metrics from multiple TidbClusters so that we can have all of the metrics in the TidbMonitor for the original cluster.
