### ISSUE TITLE
What will happen when multiple operators get installed

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb-operator#308]
I known there should be only one tidb-operator in a K8s cluster, but users are able to install tidb-operator in different namespace by mistake. Can we prevent this from happening? Or what would occur if thera are multiple tidb-operators in a cluster?

**Comment by weekface** [comment]
If it has already been installed, it will prevent it from being installed again?

**Comment by gregwebs** [comment]
Helm would stop a second install with the same helm release name.

If they are all set to [clusterScoped: false](https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-operator/values.yaml#L5), this is a supported mode of operation.

It is possible to prevent a `clusterScoped: true` install by not giving out cross-namespace permission.

**Comment by gregwebs** [comment]
There are two scenarios that would cause problems:

1) two `clusterScoped: true` installs
2) one `clusterScoped: true` install, and one `clusterScoped: false` install.

**Comment by zyguan** [comment]
Thanks @gregwebs ! I have one more question. What are the limitations/drawbacks to set `clusterScoped` to false ?

**Comment by gregwebs** [comment]
With `clusterScoped: true` you can manage just one tidb-operator. With `clusterScoped: false` you are managing many, and using more resources (although the tidb-operator resource requests are small). There is potential advantage though to `clusterScoped: false`: it allows you to try out a newer version of tidb-operator on just one tidb cluster.

I would like for us to handle these scenarios. I think there are some etcd features that would make handling this simple enough, but I don't know if they are exposed in Kubernetes.
