### ISSUE TITLE
TiDB Operator installation failure when set `clusterScoped: false`

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3110]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

**What did you expect to see?**
TiDB Operator installation succeeds.
**What did you see instead?**

Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: clusterroles.rbac.authorization.k8s.io “tidb-operator:tidb-controller-manager” is forbidden: User “maozhipeng” cannot get resource “clusterroles” in API group “rbac.authorization.k8s.io” at the cluster scope

**Comment by DanielZhangQD** [comment]
The error occurs when the user installs TiDB Operator with a namespace-scoped user.

**Comment by DanielZhangQD** [comment]
`tidb-scheduler` requires clusterrulebinding with `system:kube-scheduler` and `system:volume-scheduler` clusterrole, so we cannot install TiDB Operator with a namespace-scoped user, right? Any suggestions for this? cc @weekface @cofyc

**Comment by cofyc** [comment]
I don't think it's possible to run `kube-scheduler` in one namespace only.
