### ISSUE TITLE
Monitoring aggregation for the TidbClusters deployed across Kubernetes clusters

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3118]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
Need to verify if https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/aggregate-multiple-cluster-monitor-data works well for the cluster deployed across Kubernetes clusters.

**Comment by just1900** [comment]
Changes related

https://github.com/pingcap/tics/pull/4099
https://github.com/pingcap/tiflow/pull/4658
https://github.com/tikv/pd/pull/4671
https://github.com/tikv/tikv/pull/12008
https://github.com/pingcap/tidb/pull/32546
https://github.com/pingcap/tidb-binlog/pull/1135
