### ISSUE TITLE
tidb-lightning supports local backend on k8s

### ISSUE THREAD

**Issue by gejibin** [pingcap/tidb-operator#3162]
tidb-lightning supports local backend on k8s.
The following two ways of configuration are supported:
1. Support configuration of s3 data source;
2. Support configuration of local directory as data source, that is, import from pod local disk.

---------------------------------------------------------------------------------

支持以下两种方式配置：
1. 支持配置s3的数据源，从s3上导入;
2.支持配置本地目录作为数据源，从pod本地盘导入。

**Comment by DanielZhangQD** [comment]
@gejibin Could you please help submit PR for this?

**Comment by DanielZhangQD** [comment]
https://docs.pingcap.com/zh/tidb/dev/tidb-lightning-backends#tidb-lightning-local-backend

**Comment by csuzhangxc** [comment]
for the local backend, we also need another PV to store the immediate SST files.

**Comment by csuzhangxc** [comment]
@DanielZhangQD shoud we need to remove `tidb` backend support in Helm charts when adding `local` backend support?

**Comment by DanielZhangQD** [comment]
> @DanielZhangQD shoud we need to remove `tidb` backend support in Helm charts when adding `local` backend support?

@csuzhangxc Currently, we do not support tidb backend in the tidb-lightning charts, it's just importer backend now, we just need to add the local backend support.
