### ISSUE TITLE
Support canary deployments

### ISSUE THREAD

**Issue by cvvz** [pingcap/tidb-operator#3166]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When a new version tidb-operator is deployed, all tidb clusters will be managed by it. If there is any problem happens in the new version tidb-operator, all of the tidb clusters will be infulenced.
**Describe the feature you'd like:**

When a new version tidb-operator is deployed, only some specific tidb clusters will be managed by it, the others are still managed by old version tidb-operator. When the new version tidb-operator is fully tested, replace the old one.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
I think there are two issues here:

- TiDB Operator supports managing TidbClusters by label selector.
-  Support to deploy multiple cluster-scoped TiDB Operators in the same Kubernetes cluster.

cc @weekface 

@shonge Is this the same request we discussed before?
I recall that you will have a proposal for this, right? You can put it here and we can discuss it.
BTW, for your case, we also have to consider the v1.0 and v1.1 co-existence case.

**Comment by shonge** [comment]
Hi,@DanielZhangQD  PTAL #3236
