### ISSUE TITLE
TidbInitializer pod can`t Pull busyBox Image from Private Registry

### ISSUE THREAD

**Issue by zgcbj** [pingcap/tidb-operator#3178]
https://github.com/pingcap/tidb-operator/blob/1cf12d67fba0f68dd2e8c2b6744e2f91de8ef3e7/pkg/manager/member/tidb_init_manager.go#L332

**Comment by DanielZhangQD** [comment]
Please try v1.1.4, which includes this PR https://github.com/pingcap/tidb-operator/pull/3069/files.
