### ISSUE TITLE
Cluster role binding for TidbMonitor is updated to different subjects

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3179]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Create several TidbMonitors with the same name in different namespaces.

**What did you expect to see?**
The `subjects` in the clusterrolebinding should not be be updated.
**What did you see instead?**
The `subjects` in the clusterrolebinding is updated to different namespaces frequently.
```
subjects:
- kind: ServiceAccount
  name: tidb-monitor
  namespace: tidb
```

**Comment by DanielZhangQD** [comment]
For the [cluster scoped case](https://github.com/pingcap/tidb-operator/blob/master/pkg/monitor/monitor/monitor_manager.go#L309), I think we should only have one clusterrole and one clusterrolebinding binding to all of the service accounts instead of creating one clusterrole and clusterrolebinding for each of the TidbMonitor object.
BTW, do we really need clusterrole and clusterrolebinding for TidbMonitor? I think role and rolebinding should be enough, WDYT? @cofyc @weekface @Yisaer

**Comment by Yisaer** [comment]
"I think role and rolebinding should be enough" currently, yes. But if you want to support heterogeneous cluster (constructed by multi tidbcluster), I think cluster role might be necessary as tidbclusters could be deployed across different namespaces.

"updated to different namespaces frequently." could you provide more detail about how subjects changed? I think this is a bug implementation regardless of cluster role or namespace role choices for tidbmonitor.

**Comment by DanielZhangQD** [comment]
```
# k get clusterrole | grep monitor
ns0-monitor                                                            105m
ns9-monitor                                                            7d19h
test311-monitor                                                        2d
```
@Yisaer  Because the name of the clusterrole and clusterrolebinding do not take namespace into consideration, and users created several tidbmonitors with the same name in different namespaces, so that each sync for one tidbmonitor will update the same clusterrole and clusterrolebinding, that's why the subjects are changed, you can have a try.

**Comment by Yisaer** [comment]
> the name of the clusterrole and clusterrolebinding do not take namespace into consideration

ok, I think that's the root cause. FYI @weekface
