### ISSUE TITLE
Do not scale in TiKV if the available replicas are less than 3

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3182]
## Feature Request

**Is your feature request related to a problem? Please describe:**

With the current implementation, when there are only 3 available replicas, if users try to scale in TiKV, the Operator will delete the store, however, due to the constraint of raft group, the store cannot become tombstone and will remain `offline` forever, so it's better that Operator checks the available replicas before scaling in and do not delete store if the available replicas <= 3.
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by cvvz** [comment]
If tidb-operator has modified `spec.replicas` of StatefulSet to 2, it will not be able to scaling out tidb-cluster by itself any more:
```shell
I0906 17:12:05.189967       1 tikv_scaler.go:68] scaling out tikv statefulset tidb-cluster/backdb-tikv, ordinal: 2 (replicas: 3, delete slots: [])
I0906 17:12:05.204073       1 tidb_cluster_controller.go:303] TidbCluster: tidb-cluster/backdb, still need sync: tikv.ScaleOut, cluster tidb-cluster/backdb ready to scale out, wait for next round, requeuing
``` 
Because it keeps waiting for the PVC of `tikv-2` to be deleted.

**Comment by DanielZhangQD** [comment]
That's another issue, do you mean if scale in from 3 to 2 and then scale out from 2 to 3, the scale-out cannot be done?
If so, please help create another issue and attach the log of the tidb-controller-manager.

**Comment by cvvz** [comment]
Yes, and the issue is here https://github.com/pingcap/tidb-operator/issues/3229. I think these two issues can be solved in the same way.
