### ISSUE TITLE
Specify Database/Databases For Restore CR

### ISSUE THREAD

**Issue by sstubbs** [pingcap/tidb-operator#3183]
In continuation to this issue https://github.com/pingcap/tidb-operator/issues/2695 I have tried adding tablefilter to the restore CR in this commit https://github.com/sstubbs/tidb-operator/commit/48455223191abcf21decdba532049eb535015da5 

It is parsing the --filter argument to lightning but this argument is not available in lightining. Will this be added?

**Comment by DanielZhangQD** [comment]
@sstubbs It's `-f` for lightning:
```
  -f value
        select tables to import
```

**Comment by sstubbs** [comment]
thank you very much. I will get a PR done in the next few days after I test it a bit.

**Comment by DanielZhangQD** [comment]
OK, thanks!

**Comment by lichunzhu** [comment]
@sstubbs Hello, do you have any further problem on this issue?
