### ISSUE TITLE
Unable to get the correct folder for recovery while doing a periodic backup task

### ISSUE THREAD

**Issue by shuijing198799** [pingcap/tidb-operator#319]
When I create a cronjob to do periodic backup, the folder of persistent volume is "scheduled-backup-`date +%Y-%m-%dT%H%M%S`-${MY_POD_NAME}" but when I want to do restore, the pvc and the backupname is the same ".Values.name" . so if I do periodic backup in persistent volume. I can't get the correct pvc and folder address to restore.

**Comment by gregwebs** [comment]
@LinuxGit has this changed now?

**Comment by LinuxGit** [comment]
Yes. Now the scheduled backup name is `backupName=scheduled-backup-`date -u -d @${timestamp}  "+%Y%m%d-%H%M%S"``.
You could restore the backup via tide-backup chart:
https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-backup/templates/backup-pvc.yaml#L1
@shuijing198799 already knows. I fixed it in https://github.com/pingcap/tidb-operator/pull/576.
