### ISSUE TITLE
Support helm3 in the docs

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3217]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, most of the helm commands in the docs (https://docs.pingcap.com/zh/tidb-in-kubernetes/stable) are with helm2, as helm3 has become the stable version for a long time, we should provide commands with helm3.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mikechengwei** [comment]
I think there is no problem with the existing helm chart we use in helm3, I have been using helm3 for a long time. We just need to declare this in the documentation.

**Comment by DanielZhangQD** [comment]
Yes, we just need to update the commands in the docs to use helm3.

**Comment by handlerww** [comment]
Some scripts in hack/*.sh need to support helm3.

**Comment by DanielZhangQD** [comment]
Traced in https://github.com/pingcap/docs-tidb-operator/issues/869.
