### ISSUE TITLE
TidbMonitor pods not deployed - err: tidbclusters.pingcap.com "basic" not found

### ISSUE THREAD

**Issue by Mertonidas** [pingcap/tidb-operator#3221]
Hi,

My environment is the following:

Kubernetes version (AKS): v1.16.10
TiDB Operator version: v1.1.4 -> deployed with Helm 3

SC:
\
azurefile           kubernetes.io/azure-file \
azurefile-premium   kubernetes.io/azure-file \
default (default)   kubernetes.io/azure-disk \
managed-premium     kubernetes.io/azure-disk

pd-tidb-cluster-pd-0       Bound    pvc-709772f9-85b6-4925-8193-5eef42487d00   25Gi       RWO            managed-premium \
pd-tidb-cluster-pd-1       Bound    pvc-97f44745-5225-45ac-87a5-4b12516383d3   25Gi       RWO            managed-premium \
pd-tidb-cluster-pd-2       Bound    pvc-c09c6262-6b7d-49b5-8d02-79ec73bd0625   25Gi       RWO            managed-premium \
tikv-tidb-cluster-tikv-0   Bound    pvc-1ff9d170-e5e3-4072-a2a0-6ac2d89abb46   100Gi      RWO            managed-premium \
tikv-tidb-cluster-tikv-1   Bound    pvc-3a0a3101-a4c0-4f02-9610-f04b17f20084   100Gi      RWO            managed-premium \
tikv-tidb-cluster-tikv-2   Bound    pvc-8e55c8ae-356b-409c-8e2f-a82ec2f8c865   100Gi      RWO            managed-premium

PODS STATUS:

tidb-cluster-discovery-555fbbf8f6-2v4v2    1/1     Running   0          6m12s   10.244.2.7    aks-nodepool2-24600337-vmss000002   <none>           <none>
tidb-cluster-pd-0                          1/1     Running   0          6m12s   10.244.4.6    aks-nodepool2-24600337-vmss000000   <none>           <none>
tidb-cluster-pd-1                          1/1     Running   0          6m12s   10.244.2.8    aks-nodepool2-24600337-vmss000002   <none>           <none>
tidb-cluster-pd-2                          1/1     Running   0          6m12s   10.244.3.7    aks-nodepool2-24600337-vmss000001   <none>           <none>
tidb-cluster-tidb-0                        2/2     Running   0          4m13s   10.244.2.10   aks-nodepool2-24600337-vmss000002   <none>           <none>
tidb-cluster-tidb-1                        2/2     Running   0          4m13s   10.244.4.8    aks-nodepool2-24600337-vmss000000   <none>           <none>
tidb-cluster-tidb-2                        2/2     Running   0          4m13s   10.244.3.9    aks-nodepool2-24600337-vmss000001   <none>           <none>
tidb-cluster-tikv-0                        1/1     Running   0          5m13s   10.244.3.8    aks-nodepool2-24600337-vmss000001   <none>           <none>
tidb-cluster-tikv-1                        1/1     Running   0          5m13s   10.244.4.7    aks-nodepool2-24600337-vmss000000   <none>           <none>
tidb-cluster-tikv-2                        1/1     Running   0          5m13s   10.244.2.9    aks-nodepool2-24600337-vmss000002   <none>           <none>
tidb-controller-manager-7498f76564-64v5j   1/1     Running   0          32m     10.244.2.6    aks-nodepool2-24600337-vmss000002   <none>           <none>
tidb-scheduler-5b4d4d55d4-wwldd            2/2     Running   0          32m     10.244.2.5    aks-nodepool2-24600337-vmss000002   <none>           <none>

With tidb-operator and TidbCluster deployed I tried to deploy TidbMonitor.

I followed the steps described in this url: https://docs.pingcap.com/tidb-in-kubernetes/stable/monitor-using-tidbmonitor

The resource TidbMonitor (named "base") was deployed but not pods were deployed when applying the yaml file.

`$ kubectl get tidbmonitor`
NAME    AGE
basic      3m

The tidb-controller-manager logs show the following:

`1 tidb_monitor_controller.go:119] TidbMonitor: tidb-cluster/basic, sync failed, err: get tm[tidb-cluster/basic]'s target tc[tidb-cluster/basic] failed, err: tidbclusters.pingcap.com "basic" not found`

Trying to understand the log output I ran the following command:

`kubectl get tm`
error: the server doesn't have a resource type "tm"

I inspected the CRD yaml file (https://raw.githubusercontent.com/pingcap/tidb-operator/v1.1.4/manifests/crd.yaml) and found that the TidbMonitor CR doesn't have the `shortNames: tm`.

I downloaded the CRD file and manually add the _shortNames_ of TidbMonitor CR. After that, the command `kubectl get tm` returns the TidbMonitor resource correctly, but the controller logs show the same error.

Thank you

Regards

**Comment by DanielZhangQD** [comment]
@Mertonidas The `spec.clusters[0].name` should be set to the TidbCluster name of your TiDB Cluster, which is `tidb-cluster` in your case.
Sorry that the doc does not make it clear, I will update the doc soon.
