### ISSUE TITLE
Tidb-scheduler schedules unexpectly when deleting specific slots.

### ISSUE THREAD

**Issue by cvvz** [pingcap/tidb-operator#3227]
## Bug Report

**What did you do?**

The replicas of tikv is 3,  and then I annotate the tidb cluster with `tikv.tidb.pingcap.com/delete-slots: '[1]'`. After that, tidb-operator starts to delete the store of `tikv-1`, and it will take a while before `tikv-1` Pod actually being deleted. At the same time, the new tikv Pod `tikv-3` is  created by statefulset controller. However, it is in a state of `Pending` because of the HA schedule policy(**The max pods per topology is 1 when the replicas is 3**) of tidb-scheduler.

**What did you expect to see?**
1. `tidb-scheduler` should know about the deleting Pod information, and let the new tikv Pod be scheduled to the same topology of the deleting Pod.
2. Waiting for Pods that have been created but is not running and ready before deleting Pod. I think this can be solved by changing the `Statefulset.Spec.PodManagementPolicy` from `Parallel` to `OrderedReady`.

**Comment by DanielZhangQD** [comment]
I think the key point here is to make tidb-scheduler support advanced statefulset.
It's OK to set `Statefulset.Spec.PodManagementPolicy` from `Parallel`.
WDYT? cc @weekface
