### ISSUE TITLE
It's dangerous to set the "PodManagementPolicy" of Statefulset to "Parallel"

### ISSUE THREAD

**Issue by cvvz** [pingcap/tidb-operator#3228]
## Bug Report

As I mentioned in https://github.com/pingcap/tidb-operator/issues/3227, the default value of `Statefulset.Spec.PodManagementPolicy` is `OrderedReady`, but tidb-operator sets it to `Parallel`, which means: 
> ParallelPodManagement will create and delete pods as soon as the stateful set replica count is changed, and will not wait for pods to be ready or complete termination.

This can be dangerous when deleting Pod without considering whether other Pods is ready or not.

**Comment by DanielZhangQD** [comment]
Except for #3227, which I think is an issue we should address in `tidb-schduler`, do you find any other disadvantages with `Parallel`?

**Comment by cvvz** [comment]
@DanielZhangQD I don't find out other situations that will be influenced by it right now. But it can be hard to solve https://github.com/pingcap/tidb-operator/issues/3228 perfectly if `Statefulset.Spec.PodManagementPolicy` is `Parallel`. Because the newly created Pod can be in `Pending` state, but StatefulSet will delete the old Pod regardless of it.

**Comment by DanielZhangQD** [comment]
OK, I see, I think we can support configuring `PodManagementPolicy` in the TidbCluster CR.
Would like to submit PR for this?

**Comment by cvvz** [comment]
Ok, I'd glad to. I may do this on a certain weekend :)

**Comment by DanielZhangQD** [comment]
@cvvz Thanks a lot!
