### ISSUE TITLE
Validating whether the image of additianalcontainer is empty.

### ISSUE THREAD

**Issue by cvvz** [pingcap/tidb-operator#3230]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When I edit the specification of `TidbCluster`, I delete the `spec.tikv.additionalContainers.image` by mistake, and Statefulset start to upgrade, however the new revision Pod can't be created because container image is empty.
![image](https://user-images.githubusercontent.com/44308864/92345986-fcfc3280-f0fd-11ea-829c-ac989e4737a7.png)

**Describe the feature you'd like:**

Don't allow TidbCluster to be updated if `spec.tikv.additionalContainers.image` is empty. 

**Describe alternatives you've considered:**

Validating whether the image of additianalcontainer is empty in ValidatingWebhook or not override it if the image is empty.

**Comment by DanielZhangQD** [comment]
> Validating whether the image of additianalcontainer is empty in ValidatingWebhook

This is OK, we should add validation in both the webhook and the controller [here](https://github.com/pingcap/tidb-operator/blob/master/pkg/controller/tidbcluster/tidb_cluster_control.go#L102).
BTW, for the validation in the controller, what about adding a condition in the TidbCluster status, similar with what we have done for the backup [here](https://github.com/pingcap/tidb-operator/blob/master/pkg/controller/backup/backup_controller.go#L198) and [here](https://github.com/pingcap/tidb-operator/blob/master/pkg/backup/backup/backup_manager.go#L90-L100) and with this, we can also see what's wrong in the TidbCluster yaml.

> or not override it if the image is empty.

This is not gonna work as we do not know what's the previous spec of the TidbCluster.

**Comment by DanielZhangQD** [comment]
@cvvz Would like to take this too?

**Comment by cvvz** [comment]
@DanielZhangQD OK :)

**Comment by cvvz** [comment]
> BTW, for the validation in the controller, what about adding a condition in the TidbCluster status

@DanielZhangQD The information of validation failure is already recorded in TC event, users can use `kubectl describe` to know about it. Maybe it is not necessary to adding a condition in the TidbCluster status?
![image](https://user-images.githubusercontent.com/44308864/96067477-69700b80-0ecc-11eb-9d8d-604791f7d085.png)
