### ISSUE TITLE
Support serviceAccount in TiDBSpec

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-operator#3244]
## Feature Request

**Is your feature request related to a problem? Please describe:**

`RESTORE DATABASE ... FROM 's3://...'` (https://docs.pingcap.com/tidb/stable/sql-statement-restore#remote-destinations) requires that TiDB nodes be able to read from the referenced S3 bucket.

**Describe the feature you'd like:**

TiDBSpec should support serviceAccount in order to assign an IAM role to TiDB pods.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by gregwebs** [comment]
In general we probably need to document how to ensure service accounts can be properly set on pods. The main problem is that integration with the cloud provider service account isn't standardized.

**Comment by DanielZhangQD** [comment]
The following components need to support:
PD, TiDB, TiCDC, Pump

**Comment by DanielZhangQD** [comment]
We'd better define `spec.serviceAccount` and `spec.<component>.serviceAccount` so that all of the components can share the `spec.serviceAccount` if no special requirement and they can also configure their separate serviceAccount.

**Comment by tirsen** [comment]
Under what circumstances does PD and Pump also access S3?

**Comment by DanielZhangQD** [comment]
> Under what circumstances does PD and Pump also access S3?

We just want to enable the serviceAccount capabilities for the controller managed components, the serviceAccount is not necessarily to be used to access S3 only, it can also be used for other cases, e.g. imagePullSecret (though we have supported this).
