### ISSUE TITLE
Backup with BR failed

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3259]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

S3 storage:
Jinshan Yun S3

![image](https://user-images.githubusercontent.com/36026334/92732754-74092380-f3a9-11ea-8b4f-39e48dac134c.png)

**Comment by L3T** [comment]
使用金山云对象存储(部分兼容 aws S3协议)，进行备份时，由于金山云部分对象没有返回 etag 造成获取备份大小失败。
我这边已经联系了金山云的同学进行处理，金山云原计划本周四修复，今天同步进度时金山的同学反馈因为排期问题会往后推迟，我这边会同步更新进度.

**Comment by L3T** [comment]
百度云的测试结果稍后我这边也贴出来。

**Comment by L3T** [comment]
金山云青岛机房已经修复该问题，我这边已经验证通过，金山云正在推进全网上线

**Comment by DanielZhangQD** [comment]
@lichunzhu We may also consider to record the size in the metafile and then retrieve the size from the metafile later.

**Comment by DanielZhangQD** [comment]
https://github.com/pingcap/br/issues/550 is created to retrieve the backup size from BR.
