### ISSUE TITLE
Backup to GCS returns error "backupmeta not exist" when the backupmeta file exists in the bucket

### ISSUE THREAD

**Issue by namco1992** [pingcap/tidb-operator#3288]
## Bug Report

**What version of Kubernetes are you using?**
`v1.16.13-gke.401`

**What version of TiDB Operator are you using?**
`v1.1.4`

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
```
NAME                 PROVISIONER                    AGE
local-storage        kubernetes.io/no-provisioner   6h34m
ssd                  kubernetes.io/gce-pd           476d
standard (default)   kubernetes.io/gce-pd           571d
```

TiKV is using `local-storage`.

**What's the status of the TiDB cluster pods?**
All running.

**What did you do?**
I applied a backup CR:
```yaml
---
apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: dev-tidb-backup-gcs
  namespace: dev-tidb
spec:
  cleanPolicy: Retain
  from:
    host: dev-tidb-tidb.dev-tidb.svc.cluster.local
    port: 4000
    user: root
    secretName: dev-tidb-backup-user-secret
  br:
    cluster: dev-tidb
    clusterNamespace: dev-tidb
  gcs:
    projectId: [MY_GCP_PROJECT]
    secretName: dev-tidb-gcs-secret
    bucket: [MY_GCS_BUCKET]
```

**What did you expect to see?**
Backup finished successfully.

**What did you see instead?**
```
I0918 14:05:51.304576       1 backup.go:104] Backup data for cluster dev-tidb/dev-tidb-backup-gcs successfully
I0918 14:05:51.314143       1 manager.go:261] reset cluster dev-tidb/dev-tidb-backup-gcs tikv_gc_life_time to 10m0s success
I0918 14:05:51.314177       1 manager.go:276] backup cluster dev-tidb/dev-tidb-backup-gcs data to gcs://nv-dev-tidb-backup/ success
I0918 14:05:51.488847       1 manager.go:293] Get size 0 for backup files in gcs://nv-dev-tidb-backup/ of cluster dev-tidb/dev-tidb-backup-gcs success
E0918 14:05:51.524789       1 manager.go:298] get cluster dev-tidb/dev-tidb-backup-gcs commitTs failed, err: backupmeta not exist
I0918 14:05:51.546535       1 backup_status_updater.go:64] Backup: [dev-tidb/dev-tidb-backup-gcs] updated successfully
error: backupmeta not exist
```

However, when I check the gcs bucket, I can see the `backupmeta` file listed in the bucket. Is it possible that there is a potential race condition or I did something wrong?

**Comment by DanielZhangQD** [comment]
The backup files are eventually consistent in the GCS, it's possible that the files are not ready when we try to retrieve the metadata.
Does the backup fail always?

**Comment by namco1992** [comment]
Hello @DanielZhangQD , unfortunately, yes. I tried a few times and it fails every time, maybe it fails occasionally but the chance seems to be quite high. 

Btw, I noticed in the log that `Get size 0 for backup files`, which means that it doesn't get the backup file size correctly [here](https://github.com/pingcap/tidb-operator/blob/48eb1cd816c7f1496745babcb4fc7de862961e03/cmd/backup-manager/app/backup/backup.go#L131).

**Comment by namco1992** [comment]
Another thing I noticed is that I can't set the `spec.gcs.storageClass`. I tried value `REGIONAL`(which is the legacy storage class), `STANDARD`(the current storage class that replaces `REGIONAL`) and `COLDLINE`, but none of them is accepted.

The error I get:
```
[2020/09/19 09:30:24.165 +00:00] [ERROR] [backup.go:25] ["failed to backup"] [error="msg:\"Io(Custom { kind: InvalidInput, error: \\\"invalid storage_class COLDLINE: expected value at line 1 column 1\\\" })\" "] [errorVerbose="msg:\"Io(Custom { kind: InvalidInput, error: \\\"invalid storage_class COLDLINE: expected value at line 1 column 1\\\" })\" 
github.com/pingcap/br/pkg/backup.(*pushDown).pushBackup
/home/jenkins/agent/workspace/build_br_multi_branch_v4.0.4/go/src/github.com/pingcap/br/pkg/backup/push.go:113
github.com/pingcap/br/pkg/backup.(*Client).BackupRange
/home/jenkins/agent/workspace/build_br_multi_branch_v4.0.4/go/src/github.com/pingcap/br/pkg/backup/client.go:498
github.com/pingcap/br/pkg/backup.(*Client).BackupRanges.func2.1
/home/jenkins/agent/workspace/build_br_multi_branch_v4.0.4/go/src/github.com/pingcap/br/pkg/backup/client.go:427
github.com/pingcap/br/pkg/utils.(*WorkerPool).ApplyOnErrorGroup.func1
/home/jenkins/agent/workspace/build_br_multi_branch_v4.0.4/go/src/github.com/pingcap/br/pkg/utils/worker.go:62
golang.org/x/sync/errgroup.(*Group).Go.func1
/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1357"] [stack="github.com/pingcap/log.Error
/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200511115504-543df19646ad/global.go:42
github.com/pingcap/br/cmd.runBackupCommand
/home/jenkins/agent/workspace/build_br_multi_branch_v4.0.4/go/src/github.com/pingcap/br/cmd/backup.go:25
github.com/pingcap/br/cmd.newFullBackupCommand.func1
/home/jenkins/agent/workspace/build_br_multi_branch_v4.0.4/go/src/github.com/pingcap/br/cmd/backup.go:84
github.com/spf13/cobra.(*Command).execute
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
/home/jenkins/agent/workspace/build_br_multi_branch_v4.0.4/go/src/github.com/pingcap/br/main.go:57
runtime.main
/usr/local/go/src/runtime/proc.go:203"]
Error: msg:"Io(Custom { kind: InvalidInput, error: \"invalid storage_class COLDLINE: expected value at line 1 column 1\" })"
, err: exit status 1
```

Anyway, the storage class is determined by the bucket and the bucket is prepared beforehand. May I ask what's the purpose of passing in the storage class here?

**Comment by DanielZhangQD** [comment]
> �Anyway, the storage class is determined by the bucket and the bucket is prepared beforehand. May I ask what's the purpose of passing in the storage class here?

@namco1992 no special purpose here, just to support some options as rclone has done, but not all of them.

@lichunzhu Could you please help follow this issue?

**Comment by lichunzhu** [comment]
OK, I will take a look at this.

**Comment by DanielZhangQD** [comment]
@namco1992 Did you use the GCS in the same region with your TiDB?

**Comment by lichunzhu** [comment]
I can reproduce this when I set storageClass. I create an issue https://github.com/pingcap/br/issues/522 in br to trace this problem.

**Comment by DanielZhangQD** [comment]
My previous description about eventually consistent seems wrong, according to the doc [here](https://cloud.google.com/storage/docs/consistency), it should be strongly consistent for `Read-after-write` operation, could you please help check with the GCP support?

**Comment by namco1992** [comment]
Hello @DanielZhangQD @lichunzhu , yes the GCS is the same region as the TiDB. But I noticed something interesting. If I provide the `spec.gcs.prefix` then it can get the size and metadata successfully. The folder struct looks like this:
![image](https://user-images.githubusercontent.com/9165473/93844730-c7943f00-fcd0-11ea-811b-1e20d88d57cf.png)

However, when I don't provide the `spec.gcs.prefix` and backup to the bucket path directly, it can't get the metadata. Can you replicate this on your side?

**Comment by DanielZhangQD** [comment]
OK, it should be the cause. The Prefix should be provided for ad-hoc backup to distinguish the different backups because the metadata is placed in the current path and different backups will overwrite the data without prefix.

**Comment by lichunzhu** [comment]
https://github.com/pingcap/br/issues/522 is already fixed. Reopen this issue if any similar problem is found in the next operator version v1.1.6.
