### ISSUE TITLE
tidb-cluster has incorrect check of %% for permit_host

### ISSUE THREAD

**Issue by donbowman** [pingcap/tidb-operator#3290]
## Bug Report

In tidb-cluster, in _initialize_tidb_users.py.tpl:25, permit_host in python is compared against `%%`, but initialised to `%`. I think it should be `%` as described in the docs and via the logic.

https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-cluster/templates/scripts/_initialize_tidb_users.py.tpl#L25

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of TiDB Operator are you using?**

1.1.5

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

gke pd

**What did you do?**

when installing the tidb, after the init script is done, I cannot connect anymore. I believe this is because the initial user (and root user) are both locked to the wrong host.

**What did you expect to see?**

connect from external host

**What did you see instead?**

could not connect

**Comment by mikechengwei** [comment]
```
          if permit_host != '%%':
              conn.cursor().execute("update mysql.user set Host=%s where User='root';", (permit_host,))
```
Is you set permit_host manually?
I think you set permit_host not included `%%` value  or use default `%` value , this code always reference `permit_host` actual value.  The `permit_host` field in code https://github.com/pingcap/tidb-operator/blob/2ec8dfbf05fbb3513aea878ce4c2c13bf64a97b2/charts/tidb-cluster/templates/scripts/_initialize_tidb_users.py.tpl#L26 will replace `%s` placeholder.

**Comment by mikechengwei** [comment]
Are there any other errors log ?

**Comment by donbowman** [comment]
not sure what the intent of the code is, i was debugging another problem.

if you create a non-root user in the secret, permit host must be %, there's no other value that makes sense. if you set it to %% then mysql will reject
```
conn.cursor().execute("create user %s@%s identified by %s;", (user, permit_host, password,))
```
there.

so i'm not sure what %% would be used for, the helm chart doesn't refer, it looked odd to me.

i guess if you:
a) create 1 user in the secret
b) that user is root
c) set the permit host to %%

then you would have th eaffect of updating the root password but not changing the host it comes from.

**Comment by DanielZhangQD** [comment]
@donbowman Thanks for reporting this issue!
1. For the code issue here https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-cluster/templates/scripts/_initialize_tidb_users.py.tpl#L25, @shonge will help confirm it.
2. No matter the code above is expected or not, it will not cause that your TiDB cannot be accessed, because, with the above code, the permitHost will be set correctly.

Not sure if you use MySQL client 8.x, if yes, you must explicitly specify --default-auth=mysql_native_password, because mysql_native_password is no longer the default plugin.
