### ISSUE TITLE
The grafana metrics and log search modules cannot be used in the dashboard

### ISSUE THREAD

**Issue by zhenjiaogao** [pingcap/tidb-operator#3329]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Deployed in k8s environment, when click `Monitor & Alert` in dashboard, it will jump to service, such as http://basic-grafana.tidb.svc:3000, but `metrics` cannot be displayed.

Another problem is that the `search logs` module cannot search for any logs.

**Describe the feature you'd like:**
Support the display of grafana metrics in the `Monitor & Alert` module and the `search log` module to support log search.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
The unsupported functions are updated in https://github.com/pingcap/docs-tidb-operator/pull/739.
