### ISSUE TITLE
Support backup to compatible s3 system that only supports list object v1

### ISSUE THREAD

**Issue by duanliguo** [pingcap/tidb-operator#3330]
## Feature Request

**Is your feature request related to a problem? Please describe:**
数据备份至没有兼容S3 listObjects V2的对象存储系统时， cmd/backup-manager/app/backup/manager.go:#L280 getBackupSize 会报错

**Describe the feature you'd like:**
在初始化s3blob的时候支持是否使用listObjectsV1，https://github.com/pingcap/tidb-operator/blob/4b8b87f1671063ed0ba68d1cab5e7dd89aaba6d4/cmd/backup-manager/app/util/remote.go#L151行传入参数

**Describe alternatives you've considered:**
在S3的configure  s3Query 里面增加一个配置项，初始化s3blob的时候设置下是否使用listObject V1，见文档https://godoc.org/gocloud.dev/blob/s3blob，
s3blob.Options{UseLegacyList: true}表示使用listObject V1

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
We will update our code to not get the file size through listing the files in S3.
cc @lichunzhu

**Comment by lichunzhu** [comment]
Gotta. I will use `br` metadata to get filesize.

**Comment by kennytm** [comment]
The size is still available even if you use ListObjectsV1, no?

**Comment by lichunzhu** [comment]
> The size is still available even if you use ListObjectsV1, no?

Some OSS doesn't support `ListObjectsV1` which will cause an error at cmd/backup-manager/app/backup/manager.go:#L280 getBackupSize.
