### ISSUE TITLE
`recoverFailover` may be forgotten to unset

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3335]
## Feature Request

**Is your feature request related to a problem? Please describe:**

#3189 introduces `recoverFailover` field in the spec of TidbCluster to recover from the failover Pods, however, after setting it to `true` and the Pods created due to failover are removed, users have to set it to `false` manually, which is not elegant and users may forget to do that.
We want a more reliable and automatical way to do the recover.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
@mikechengwei I recall you ever mentioned about event flow, could you please explain in more detail? or any useful link to share here?

**Comment by mikechengwei** [comment]
Let me make a brief description first.

sometime we will do something  like recover from the failover Pods,offline tikv node to tombstone node by pd-ctl tool etc.These are only processing once,if we follow the principle of kubernetes current state and expected state,user need to do two steps conatain set and unset spec field,and users need to manually judge when to unset spec field.

This way is not elegant enough, so we can provide a event flow framework for task type processing,user just need to set spec field once.

Demo design:

spec:
  event:
    - type: recoverFailover
      extra-parameters: xxx
  eventQueue:
    - type: recoverFailover   
      uuid: xxxx-xxxx-xxxx-xxxx    
status:
  eventResult:
    - type: recoverFailover   
      result: finished
      createtime: 2020-10-09 13:00:00
      finishtime: 2020-10-09 13:00:00
      uuid: xxxx-xxxx-xxxx-xxxx

**Comment by better0332** [comment]
we intend to add new fields `recoverFailoverUID` under `tikv.spec`,`tiflash.spec`, `dm.spec.worker`, the fields `recoverFailover` under the original spec continue to be retained.

`recoverFailoverUID` indicates that Operator can recover the specified failover stores, it takes effect only when set `recoverFailover=false`(default)

API e.g. tikv
```go
type TiKVSpec struct {
...
        // RecoverFailoverUID indicates that Operator can recover the specified tikv `FailoverStores`, it takes effect only when set `recoverFailover=false`
        // +optional
        RecoverFailoverUID types.UID `json:"recoverFailoverUID,omitempty"`
}

// TiKVFailoverStore is the tikv failover store information
type TiKVFailoverStore struct {
	PodName string `json:"podName,omitempty"`
	StoreID string `json:"storeID,omitempty"`
	// +nullable
	CreatedAt metav1.Time `json:"createdAt,omitempty"`
}

type TiKVStatus struct {
...
	FailoverStores   map[types.UID][]TiKVFailoverStore   `json:"failoverStores,omitempty"`
}
```

After each round of failover starts, generate a new UID , and then filling `status.failoverStores`. When this round of failover recovers, the operator deletes `status.failoverStores` according to the `recoverFailoverUID` key specified by the user.

**Comment by DanielZhangQD** [comment]
@better0332 
What about using the API as below for `TiKVFailover` because it will be used for different components:
```
type Failover struct {
  RecoverByUID types.UID `json:"recoverByUID,omitempty"`
}
```
