### ISSUE TITLE
tidb operator failure self-recovery regenerate the new cluster id

### ISSUE THREAD

**Issue by WentaoJin** [pingcap/tidb-operator#3349]
1、When the pd cluster is unavailable, the regenerated pod from the tidb operator failure self-recovery will regenerate the new cluster id，then  tikv save old cluster id，so even if the pd cluster is alive, the tidb cluster cannot be served. solved by the according to tikv local cluster id pd recover(https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/pd-recover)

tidb  operator failure self-recovery 8 pod
![image](https://user-images.githubusercontent.com/34805682/95658137-d725db80-0b4a-11eb-9bb1-db6a23f99bac.png)

tikv pd cluster id is not consistent，tikv tidb pod CrashLoopBackOff status
![image](https://user-images.githubusercontent.com/34805682/95657990-27506e00-0b4a-11eb-9a1c-28dbaee32ac5.png)

2、Spec：
When the pd cluster is unavailable, can the tidb operator control the generation of pods without self-recovery from failure

**Comment by DanielZhangQD** [comment]
@WentaoJin What's the operator version?

**Comment by DanielZhangQD** [comment]
[Uploading ods-cfp_discovery.log…]()

**Comment by DanielZhangQD** [comment]
[ods-cfp_discovery.log](https://github.com/pingcap/tidb-operator/files/5362632/ods-cfp_discovery.log)

**Comment by WentaoJin** [comment]
> @WentaoJin What's the operator version?

v1.0 version，rememeber v1.0.3

**Comment by WentaoJin** [comment]
> @WentaoJin What's the operator version?
