### ISSUE TITLE
e2e test is not stable

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3381]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by DanielZhangQD** [comment]
The current e2e test is not stable, this issue is to trace the failures for further analysis.

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2133/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2139/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2160/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2172/tests

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2178/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2180/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2191/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2193/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind-serial/detail/tidb-operator-pull-e2e-kind-serial/2037/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2207/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2246/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2249/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2255/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2274/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2272/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2257/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2315/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2317/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2320/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2321/pipeline/

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2323/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind-serial/detail/tidb-operator-pull-e2e-kind-serial/2165/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2355/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2358/pipeline

**Comment by hzliangbin** [comment]
something i can do for this？

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2393/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2399/pipeline

**Comment by DanielZhangQD** [comment]
> @DanielZhangQD something i can do for this？

@hzliangbin Great! The current e2e is not stable enough and I just record the failures in this issue, would you like to help investigate here?
It would be a great help to us.

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2408/pipeline

**Comment by hzliangbin** [comment]
@DanielZhangQD it would be nice if there is some docs I can reference. I am familiar with k8s stack. but know less about tidb.

**Comment by DanielZhangQD** [comment]
@hzliangbin It may not be easy to debug the e2e test without knowledge of the TiDB Operator, would you like to take a look at other issues?
Or you prefer to continue to check this test issue?

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2453/pipeline

**Comment by DanielZhangQD** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2455/pipeline

**Comment by hzliangbin** [comment]
@DanielZhangQD thx. I see....

**Comment by DanielZhangQD** [comment]
Trace this in #3652.
