### ISSUE TITLE
Restore status is not updated after the job is finished

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/tidb-operator#3385]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

v1.1.3

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Restore data through restore CR.

**What did you expect to see?**
Restore status should be updated and marked as `Complete`.

**What did you see instead?**
It's not updated.
https://asktug.com/t/topic/62805/6

**Comment by DanielZhangQD** [comment]
Close via https://github.com/pingcap/tidb-operator/pull/3648.
