### ISSUE TITLE
br: There is no need to set tikv_gc_life_time during backup and recovery

### ISSUE THREAD

**Issue by LinuxGit** [pingcap/tidb-operator#3386]
br support automatic setting `tikv_gc_life_time` during backup and recovery now. Recently there is a related [bug fix](https://github.com/pingcap/br/pull/553). It's not included in v4.0.7.

**Comment by namco1992** [comment]
Hello @DanielZhangQD @LinuxGit I would like to take a look on this one. It seems the logic is mostly in `performBackup` and `performRestore`, is cleaning up the related logic sufficient for this issue?

**Comment by DanielZhangQD** [comment]
@namco1992 Thanks for checking this issue!

With the following conditions:
1. TiDB Operator needs to support most of the TiDB versions
2. There is a bug for the GC setting in BR which will be released in v4.0.8

What about:
1. Change CR structure in types.go as below:
"From TiDBAccessConfig `json:"from,omitempty"`" to "From *TiDBAccessConfig `json:"from,omitempty"`"
"To TiDBAccessConfig `json:"to,omitempty"`" to "To *TiDBAccessConfig `json:"to,omitempty"`"
2. Check `spec.from` and `spec.to` during the backup/restore, if not nil, go with the current logic to set GC; if nil, skip the GC setting logic
3. Update docs (S3/GCS) and [examples](https://github.com/pingcap/tidb-operator/tree/master/manifests/backup) of BR to remove the `spec.from` and `spec.to` and make it clear that with TiDB Operator < v1.1.7 or TiDB version < v4.0.8, `spec.from` and `spec.to` need to be set.

@namco1992 @LinuxGit WDYT?

**Comment by namco1992** [comment]
Hello @DanielZhangQD sorry for the late reply! I got the idea, but I'm not sure how `spec.from` and `spec.to` are related to this issue. Is there a way to automatically recognize `spec.from` and `spec.to` in TiDB Operator < v1.1.7 or TiDB version < v4.0.8 so we use it to decide if the GC life time should be set or not? If so can point me to the related issue/PR? Thanks!

**Comment by DanielZhangQD** [comment]
> Hello @DanielZhangQD sorry for the late reply! I got the idea, but I'm not sure how `spec.from` and `spec.to` are related to this issue. Is there a way to automatically recognize `spec.from` and `spec.to` in TiDB Operator < v1.1.7 or TiDB version < v4.0.8 so we use it to decide if the GC life time should be set or not? If so can you point me to the related issue/PR? Thanks!

@namco1992 sorry for the late response!

> I got the idea, but I'm not sure how spec.from and spec.to are related to this issue.

For BR, now they are only used to connect to the TiDB service to set the GC.

> Is there a way to automatically recognize spec.from and spec.to in TiDB Operator < v1.1.7 or TiDB version < v4.0.8 so we use it to decide if the GC life time should be set or not?

As I have said in the above comment, we change the `spec.from` and `spec.to` to pointer and check them during the backup/restore, if they are not nil, then set the GC, if they are nil, then no need to set the GC.
And we update the doc as stated in step 3, so that for the supported versions, users do not need to set the `spec.from` and `spec.to` in the CRs, but for the unsupported versions, they need to set them.

**Comment by namco1992** [comment]
> For BR, now they are only used to connect to the TiDB service to set the GC.
> 
> >

@DanielZhangQD Thank you for the explanation! I didn't know the `spec.from` and `spec.to` only for setting the GC life time. Then I will work on this.

**Comment by namco1992** [comment]
@DanielZhangQD I'm in the middle of it and found out that `dumpling` doesn't need to set the GC life time neither based on the [documentation](https://docs.pingcap.com/tidb/stable/backup-and-restore-using-dumpling-lightning), should I update this or leave it to another PR?

**Comment by DanielZhangQD** [comment]
> @DanielZhangQD I'm in the middle of it and found out that `dumpling` doesn't need to set the GC life time neither based on the [documentation](https://docs.pingcap.com/tidb/stable/backup-and-restore-using-dumpling-lightning), should I update this or leave it to another PR?

@namco1992 Yes, please also help update this in this PR. And please also help update the doc of TiDB Operator to link to the dumpling doc above so that users before v4.x can set the GC manually.
Thanks!

**Comment by DanielZhangQD** [comment]
> > @DanielZhangQD I'm in the middle of it and found out that `dumpling` doesn't need to set the GC life time neither based on the [documentation](https://docs.pingcap.com/tidb/stable/backup-and-restore-using-dumpling-lightning), should I update this or leave it to another PR?
> 
> @namco1992 Yes, please also help update this in this PR. And please also help update the doc of TiDB Operator to link to the dumpling doc above so that users before v4.x can set the GC manually.
> Thanks!

@namco1992 After a second thought, I think we'd better keep the GC logic for dumpling now, as we recommend users with TiDB v3.0.x to use dumpling/lightning to do backup/restore, however, v3.0.x does not support setting GC automatically.
So, please just update the code for BR, thanks!
Sorry for the confusion!
