### ISSUE TITLE
Tidb scheduler should support HA scheduling in failover situation

### ISSUE THREAD

**Issue by cvvz** [pingcap/tidb-operator#3407]
## Bug Report

**What did you do?**

When a Pod of PD or TiKV is down unexpectly, after a while, tidb-operator begins to do failover, that is, create a new Pod. 

**What did you expect to see?**
The new component with the new generated Pod should keep high availability.

**What did you see instead?**
The new pod may be scheduled to a topology that can ruin the high availability of the component.

**Comment by cvvz** [comment]
I think tidb-scheduler should consider the failure members of PD and TiKV when scheduling. In other words, do not count the topology of the failure members. I'll fix this.

**Comment by DanielZhangQD** [comment]
@cvvz #3388 fixed this issue, right?

**Comment by cvvz** [comment]
@DanielZhangQD It's different. This is about to keep HA scheduling in failover situation.
