### ISSUE TITLE
Can slow log files be uploaded to S3 through configuration?Just like the backup file can be uploaded to S3

### ISSUE THREAD

**Issue by XiaoGe2030** [pingcap/tidb-operator#3433]
## Feature Request

**Describe the feature you'd like:**

I want to get the original file of the slow log .

**Describe alternatives you've considered:**

1. kubectl cp command  to get slow log file. (kubectl config needs to be configured manually)
2. start a job in k8s  to upload slow log file to s3.
3. tidb-operator could periodically upload files to  s3 through some configuration items.

Can you give me some advice？

**Comment by mikechengwei** [comment]
I think it is same as #3416 .

**Comment by XiaoGe2030** [comment]
> I think it is same as #3416 .

I  want to get the original file of the slow log from  k8s，#3416 is a search log feature request. they are  different

**Comment by mikechengwei** [comment]
Currently you can use additionalContainers and additionalVolumes spec field  to develop your own program which collect slow log.
Reference:
https://github.com/pingcap/tidb-operator/blob/87e442759c1bf59c8ada922b7316ba4aa96d0f8e/pkg/apis/pingcap/v1alpha1/types.go#L771

**Comment by DanielZhangQD** [comment]
> > I think it is same as #3416 .
> 
> I want to get the original file of the slow log from k8s，#3416 is a search log feature request. they are different

@XiaoGe2030 You do not deploy log collection solutions like EFK? Or even if with the log collection solutions deployed, you still want to get the original file of the slow log?

**Comment by DanielZhangQD** [comment]
@XiaoGe2030 This is duplicate with https://github.com/pingcap/tidb-operator/issues/3437, I will close this issue now, just update in #3437 if any comments, thanks!
