### ISSUE TITLE
TiDB update crd.yaml for latest kubernetes Version

### ISSUE THREAD

**Issue by spf913** [pingcap/tidb-operator#3436]
## Bug Report

**What version of Kubernetes are you using?**
 v1.19

**What version of TiDB Operator are you using?**
1.1.6

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
local-storage

**What's the status of the TiDB cluster pods?**
Pending

**What did you do?**
I test tidb operator crd.yaml with v1.15.0 kubernetes version. No error
But when I try to test with the latest kubernetes v1.19 it gives me error
 apiextensions.k8s.io/v1beta1
This is the culprit. Kubernetes keep complaining to update this to
 apiextensions.k8s.io/v1
There is 6 line on the crd.yaml with /v1beta
I replaced them with notepad with the following:
 apiextensions.k8s.io/v1
and getting json error

**What did you expect to see?**
crd.yaml will get deployed successfully with the latest kubernetes version 1.19

**What did you see instead?**
Not deployed tidb cluster using kubernetes current v1.19

Also please update the local storage provisioner yaml file to adopt the latest kubernetes v1.19

Pls, keep in mind, this is best practice... before make any software open source.. make it truly open source... make it adopt with the latest one... make it easy that anyone can use with little study or just by reading the Docs.. please don't PLAY

**Comment by DanielZhangQD** [comment]
We trace this issue in https://github.com/pingcap/tidb-operator/issues/2753.
BTW, we have tested our CRD with Kubernetes v1.19 and it works.
Anyway, We will provide a v1 version CRD later.

**Comment by kamaljitsinghsikhamazon** [comment]
Hello sir,
Can you guys provide the crd for v1.19 kubernetes now??
And is it possible write a small documentation about the crd update??
Like, whenever any new kubernetes version will come, we will just edit those lines and crd will get adopt with the latest kubernetes version automatically!!!!
Like a helm template or bash script or make file to generate crd and get adopt with any kubernetes version. 
Because in this case the tidb crd is the backbone of this kind of deployment. 
I am using kubernetes with haproxy keepalive nginx ingress heketi with glusterfs on 7 node kubernetes cluster..checking out TiDB !!!

**Comment by DanielZhangQD** [comment]
@kamaljitsinghsikhamazon would you mind submitting PR for this to contribute to this open-source software?

**Comment by kamaljitsinghsikhamazon** [comment]
@DanielZhangQD  sure,
The kubernetes infrastructure (no single point of failure with keepalive) kind of a big setup.
Writing down python script to automate this.

**Comment by DanielZhangQD** [comment]
> @DanielZhangQD sure,
> The kubernetes infrastructure (no single point of failure with keepalive) (make heketi volume partion for TiDB using glusterfs on RAM)kind of a big setup.
> Writing down python script to automate this.
> 
> With default Tidb code and application logic, if we try to mount the data volume on ramdisk it will get crash in 3 hours under heavy workload. Fixing that problem too!!! Then I will push the code

@kamaljitsinghsikhamazon OK, understand that, thank you!
BTW, for the solution, we may check if it's possible to generate both versions of CRDs because some users may still use the old version of Kubernetes which does not support v1.

**Comment by kamaljitsinghsikhamazon** [comment]
Why don't just push a crd with different name...
I just provisioned the dind volume, apply tidb-operator, tidb-cluster with editing values.. deploy through helm (on docu its missing) you guys didnt put down the instructions... btw running smooth... just wanna adopt with v1.19... this crd is pretty big... can you guys just make a crd for v1.19 and put it on the repo??? 
Just in case for people like me... always want to use latest software

**Comment by DanielZhangQD** [comment]
Yes, I understand that.
Currently, this CRD is generated automatically with run `hack/update-crd-groups.sh`, so we may have to find a way to generate both versions.

**Comment by DanielZhangQD** [comment]
Trace this in https://github.com/pingcap/tidb-operator/issues/2753.
