### ISSUE TITLE
BR version should be consistent with TiDBCluster

### ISSUE THREAD

**Issue by shuijing198799** [pingcap/tidb-operator#3441]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now the BR version is controlled by the TiDB-Operator and not following the TiDB cluster's version. In some cases, different versions of br and tidb will be incompatible.
For example, When I use BR 4.0.6 to restore TiDB cluster 4.0.7 when tiflash data sync is open. It always fails in the restore process.
At the first plan, we managed to use tidb in sql to fix this issue, however, this design is dependent on the Privilege TiDB pod. For the system safety, this pod will be deleted later.  So we have to consider another design.

**Describe the feature you'd like:**

BR version follow up the tidb cluster's version

**Describe alternatives you've considered:**

no

**Teachability, Documentation, Adoption, Migration Strategy:**

I write a proposal https://docs.google.com/document/d/17L9AlDBbvOjHF9wCVXpeA5qrRJUr05dH5moXyJ-QN10/edit#

**Comment by DanielZhangQD** [comment]
Some improvements to the original proposal:
1. Use EmptyDir instead of PVC to copy the BR binary.
2. Add `image` field in the `spec.br` of Backup and Restore CR, which is optional, 
    if set, use that image for the init container (in case that user may configure there own image from their Harbor);
    if not set, use `pingcap/tidb-lightning:${tikv_version}` as the image.
3. The init container should also set the ResourceRequirements, just use the value of `spec.ResourceRequirements` for the  backup/restore container.
cc @shuijing198799 @namco1992

**Comment by DanielZhangQD** [comment]
@namco1992 `pingcap/br:v4.0.8` is ready.

**Comment by namco1992** [comment]
> 2. Add `image` field in the `spec.br` of Backup and Restore CR, which is optional,
>    if set, use that image for the init container (in case that user may configure there own image from their Harbor);
>    if not set, use `pingcap/br:${tikv_version}` as the image (please note that `pingcap/br` images are being worked on, v4.0.8 may be ready today).

@DanielZhangQD For the second point, I suppose I need to choose `br/dumpling/lightning` image correspondingly based on the spec?

Besides that, it should be clear for now, I can't give my commitment that I can finish it by Thursday though 😅

**Comment by DanielZhangQD** [comment]
> > 1. Add `image` field in the `spec.br` of Backup and Restore CR, which is optional,
> >    if set, use that image for the init container (in case that user may configure there own image from their Harbor);
> >    if not set, use `pingcap/br:${tikv_version}` as the image (please note that `pingcap/br` images are being worked on, v4.0.8 may be ready today).
> 
> @DanielZhangQD For the second point, I suppose I need to choose `br/dumpling/lightning` image correspondingly based on the spec?
> 
> Besides that, it should be clear for now, I can't give my commitment that I can finish it by Thursday though 😅

@namco1992 OK, understand. Take your time and we will wait for this fix, thanks!

**Comment by DanielZhangQD** [comment]
> For the second point, I suppose I need to choose br/dumpling/lightning image correspondingly based on the spec?

Let's add `spec.image` field and consider BR only in this fix first.
if spec.br != nil
  if spec.image != ""
    take spec.image as the image of the init container
WDYT? @namco1992
