### ISSUE TITLE
Support change the store label online by using PD API

### ISSUE THREAD

**Issue by rleungx** [pingcap/tidb-operator#3447]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Currently, the cluster deployed by the operator can not change the store label by using pd-ctl. When using `store label <store_id> host/rack h1/r1`, the label will be overwritten. 

**Describe the feature you'd like:**

It's better to support change the store label online by using PD API

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
Currently, TiDB Operator will retrieve the labels info from the Node where the TiKV Pods are scheduled according to the PD configuration of `location-labels: ["region", "zone", "rack", "host"]`, if users update the store label manually for the ones in `location-labels`, it will cause a mismatch between the store labels and the node labels and may cause unexpected scheduling issue.
Suggest that if users want to differentiate the labels for the stores on the same Node, define other labels for them that are not included in the `location-labels`.

**Comment by DanielZhangQD** [comment]
@rleungx I will close this issue now, feel free to reopen it if necessary.
