### ISSUE TITLE
tidb-controller-manager complains about no permission to list storageclass

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3459]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Deploy TiDB Operator v1.1.6 from RedHat operator hub, however, the following logs are printed in the tidb-controller-manager:
![image](https://user-images.githubusercontent.com/36026334/98093681-374a3c00-1ec3-11eb-8af5-329a8c7f7415.png)

However, the RBAC rules are available in https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-operator/templates/controller-manager-rbac.yaml, so maybe we should update it to the operator hub. 
**What did you expect to see?**

**What did you see instead?**

**Comment by AstroProfundis** [comment]
Would be fixed in https://github.com/operator-framework/community-operators/pull/2606

**Comment by DanielZhangQD** [comment]
operator-framework/community-operators#2606 merged.
