### ISSUE TITLE
E2E test: TiDBCluster Basic: Deploying, Scaling, Update Configuration is not stable 

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#3466]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind/detail/tidb-operator-pull-e2e-kind/2515/tests

**Comment by mikechengwei** [comment]
```
1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
```
![image](https://user-images.githubusercontent.com/13257127/100953227-19690900-354d-11eb-8989-8c31e2c7ece1.png)
![image](https://user-images.githubusercontent.com/13257127/100953226-1706af00-354d-11eb-95a8-1f523a0e53bf.png)

**Comment by DanielZhangQD** [comment]
Fixed in the PRs for https://github.com/pingcap/tidb-operator/issues/3652.
