### ISSUE TITLE
lightning backup import

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#347]
The lightning importer is becoming a mature tool now. We should consider supporting it in our backup chart.

**Comment by weekface** [comment]
@gregwebs we may not support lightning recently, can we close this issue?

**Comment by gregwebs** [comment]
I would really like lightning support so I can restore quickly from a large backup.

**Comment by tennix** [comment]
I've heard that lightning will be refactored to integrate into TiDB itself. So I would suggest we wait until it has a clear roadmap. Before that, we can just provide some YAML files to avoid writing CRD controller.

**Comment by gregwebs** [comment]
If lightning is available to use directly in TiDB that is a non-optimal deployment to increase user convenience. Its current form should still be available to use the way it is now, and that is the way that I would always use it in the cloud.
