### ISSUE TITLE
Grafana dashboards and datasource provisioning

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#348]
Now that we have upgraded to grafana 5.x and higher, we may consider making use of [grafana provisioning](http://docs.grafana.org/administration/provisioning/) to bundle pre-defined dashboards and datasources. This will simplify the setup procedure and help addressing #207 #133 .

Besides, as @tennix suggested, we may consider using [jsonnet](https://github.com/google/jsonnet) (and there is a jsonnet library [grafonnet](https://github.com/grafana/grafonnet-lib) which dedicate to grafana dashboards templating) to maintain our dashboards, this will be a great help for dashboards configuration review.

**Comment by gregwebs** [comment]
@aylei is this closed by #388?

**Comment by aylei** [comment]
Yes, close via #388
