### ISSUE TITLE
support volumeMode in PVC generated

### ISSUE THREAD

**Issue by dragonly** [pingcap/tidb-operator#3493]
## Feature Request
Now we cannot specify `spec.volumeMode` in PVC, which is generated by TiDB-Operator for PD, TIKV, etc...
Officially, [Kubernetes supports `volumeMode: Filesystem | Block`](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-mode), and will use `Filesystem` as default when not specified, which is the case now.
If people want to use `Block` mode now, they must manually create PVCs for all the components before creating the `TidbCluster` CR, which is VERY troublesome. Just imaging what happens when `replicas` are changed...

**Is your feature request related to a problem? Please describe:**

No

**Describe the feature you'd like:**

Support `volumeMode` in `TidbCluster` CR.

**Describe alternatives you've considered:**

Manually manage PVCs for TidbCluster.

**Teachability, Documentation, Adoption, Migration Strategy:**

If someone's K8s cluster can perform better on `Block` mode, there will be a performance gain.

**Comment by DanielZhangQD** [comment]
After consulting with the TiKV team, TiKV does not support reading or writing to block devices now and does not have any plan to support this, so I'd like to close this issue now.
