### ISSUE TITLE
Tombstone store node can‘t update when controller rolling update cluster. 

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#3546]
## Bug Report

What version of Kubernetes are you using?
1.14.8

**What version of TiDB Operator are you using?**
1.0.6

**What did you do?**

1. Offline one tikv node and turn into tombstone store.
2. Change nodeAffinity configuration and rolling update  tidb cluster .
3. Tikv sts set rolling partition to 1 and long pending,tikv-0 node can’t update.

**What did you expect to see?**
Tombstone store node can update when cluster rolling update.

**Comment by DanielZhangQD** [comment]
@mikechengwei I think it's OK to upgrade the Pod if no store found for it, would you like to submit PR for this issue?

**Comment by mikechengwei** [comment]
ok

**Comment by DanielZhangQD** [comment]
@mikechengwei This issue should have been fixed by https://github.com/pingcap/tidb-operator/pull/3694, could you please help verify this in your cluster?

**Comment by mikechengwei** [comment]
ok.
