### ISSUE TITLE
edit tidb-cluster pd/config: max-merge-region-size can`t work

### ISSUE THREAD

**Issue by zgcbj** [pingcap/tidb-operator#3558]
## Bug Report

**What version of Kubernetes are you using?**
v1.16.4

**What version of TiDB Operator are you using?**
v1.1.6

**What did you do?**
1. kubectl edit tc tidb-test -n tidb-test 
edit pd config:   
```
pd:
...
        [schedule]
          max-merge-region-size = 21
```
2. pd pod restart

**What did you expect to see?**
pd-ctl config show  will show max-merge-region-size=21
**What did you see instead?**
pd-ctl config show get default value 20
cat /etc/pd/pd.toml 
/ # cat /etc/pd/pd.toml 
```
[dashboard]
  internal-proxy = true

[schedule]
  max-merge-region-size = 21
```

**Comment by DanielZhangQD** [comment]
@rleungx Could you please help check this issue?

**Comment by rleungx** [comment]
Once the pd is started, we can only use `pd-ctl`/HTTP API to modify this parameter.

**Comment by zgcbj** [comment]
> Once the pd is started, we can only use `pd-ctl`/HTTP API to modify this parameter.

After edit k8s tidbcluster`s config , pd will restart

**Comment by rleungx** [comment]
Yes, but the restart won't clean the data of etcd actually and PD saves these kinds of config in etcd. So the original config file will be not useful.

**Comment by zgcbj** [comment]
> Yes, but the restart won't clean the data of etcd actually and PD saves these kinds of config in etcd. So the original config file will be not useful.

@DanielZhangQD  will tidb operator do something about this?

**Comment by DanielZhangQD** [comment]
> > Yes, but the restart won't clean the data of etcd actually and PD saves these kinds of config in etcd. So the original config file will be not useful.
> 
> @DanielZhangQD will tidb operator do something about this? for example: start a job, call pd-ctl to modify pd config

It's a little complicated for TiDB Operator to do that, especially that this is only a one-time job while Operator runs reconcile loops to sync periodically, I have created an issue https://github.com/pingcap/docs-tidb-operator/issues/959 to update the doc to make it clear.

**Comment by zgcbj** [comment]
> > > Yes, but the restart won't clean the data of etcd actually and PD saves these kinds of config in etcd. So the original config file will be not useful.
> > 
> > 
> > @DanielZhangQD will tidb operator do something about this? for example: start a job, call pd-ctl to modify pd config
> 
> It's a little complicated for TiDB Operator to do that, especially that this is only a one-time job while Operator runs reconcile loops to sync periodically, I have created an issue [pingcap/docs-tidb-operator#959](https://github.com/pingcap/docs-tidb-operator/issues/959) to update the doc to make it clear.

ok,thx!
