### ISSUE TITLE
Proposal: use zap for structured logging

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb-operator#356]
Although glog/klog seems to be the standard logging in k8s ecosystem, I still suggest to use structured logging like zap. It's easy to write and maintain, also makes logging message more unified. Let's consider the following example.

```go
log.Infof("TidbCluster: [%s/%s]'s StatefulSet: [%s/%s] updated successfully", ns, tcName, ns, setName)
```

```go
log.Info("stateful set updated",
    zap.String("ns", ns),
    zap.String("tc", tcName),
    zap.String("set", setName),
)
```

By using zap style logging, you can:
- easily add/delete(comment) a field or reorder fields
- distinguish event message from annotation fields by code
- dump complex struct to json simply by `zap.Any("status", ss.Status)`

To keep using glog format (for consistency), you can simply implement a new zap encoder. [Here](https://gist.github.com/zyguan/adbce6c1ca9739ec2d7078b4e718d89b) is an example (as well as some benchmarks). The result indicates that the proformance of console-based encoders of zap are not fast but not too bad. However, we can easily switch to prod logger (which is really blazing fast) when the logging performance  matters.

**Comment by gregwebs** [comment]
I like this! Can you convert your glog encoder from a gist to an actual library? Others would be interested in this outside of PingCAP.

**Comment by zyguan** [comment]
Sure! the current implementation is just a wrapper of zap's [ConsoleEncoder](https://gist.github.com/zyguan/adbce6c1ca9739ec2d7078b4e718d89b#file-glog_encoder-go-L73). It leads to two buf pools thus is not memory efficient. I will optimize it later.

**Comment by zyguan** [comment]
https://github.com/zyguan/zapglog
I created a repo for the encoder (tests and readme are to be added). Here is the latest bench result:
```
goos: linux
goarch: amd64
pkg: private/bench-log
BenchmarkStdLog-4           	 1000000	      2323 ns/op	     296 B/op	      14 allocs/op
BenchmarkGLog-4             	  500000	      3226 ns/op	     352 B/op	      15 allocs/op
BenchmarkLogrus-4           	  200000	      6040 ns/op	    1264 B/op	      31 allocs/op
BenchmarkZapProd-4          	10000000	       146 ns/op	       3 B/op	       0 allocs/op
BenchmarkZapDev-4           	  300000	      4506 ns/op	    1481 B/op	      11 allocs/op
BenchmarkZapGLogEncoder-4   	  500000	      3206 ns/op	     440 B/op	       5 allocs/op
BenchmarkPingCAPLog-4       	  300000	      4262 ns/op	     408 B/op	       6 allocs/op
PASS
ok  	private/bench-log	11.247s
```

**Comment by gregwebs** [comment]
Its a lot of drudgery to make these changes. Will the existing Infof version work and how much slower is that then glog?

**Comment by gregwebs** [comment]
Sorry, I should clarify that I am wondering how this change will be introduced. It would be nice to not have to change every single logging statement at once.

**Comment by zyguan** [comment]
I think the fast way to introduce zap is to use sugared logger, it's provide `Infof` interface. However, it's still formated style rather than structured style. The legacy logging statements can be handled by this way temporarily, but I think we may still need to change these statements later. BTW, another problem for zap is that it does not support `glog.V(n)`.

**Comment by gregwebs** [comment]
Can we support verbosity by adding more log levels? Debug1, Debug2, etc

**Comment by aylei** [comment]
ping @zyguan

**Comment by zyguan** [comment]
Sorry for the late reply, currently it's just a zap encoder, I will try to add support for verbosity later.

**Comment by zyguan** [comment]
I updated my prototype, see [this commit](https://github.com/zyguan/zapglog/commit/0225eb50c8048c3fe333f1b2212a1e56fba19aa3). Also note that the official klog already supports [logr](https://github.com/go-logr/logr) now, so you can use the glog encoder directly. eg:
```go
package main

import (
	"github.com/go-logr/zapr"
	"github.com/zyguan/zapglog"
	"github.com/zyguan/zapglog/log"
	"go.uber.org/zap"
	"k8s.io/klog"
)

func main() {
	logger, err := zapglog.NewGLogDev()
	if err != nil {
		panic(err)
	}
	klog.SetLogger(zapr.NewLogger(logger.WithOptions(zap.AddCallerSkip(5))))
	klog.V(0).Info("hello")
	klog.Info("world")

	log.V(0).Info("hello world")
	log.L().Info("life, the universe, and everything", zap.Int("answer", 42))
}
```

However, there are two issues with klog currently:
1. the caller is not correctly set by default, you need add caller skip manually.
2. due to [this line](https://github.com/kubernetes/klog/blob/d256e8871dc002fa06b16e040f24c3278dd638d3/klog.go#L713), there will be one more empty line for each log entry.
   ```
   I1125 02:01:51.491340   23882 demo/main.go:17] hello

   I1125 02:01:51.491382   23882 demo/main.go:18] world

   I1125 02:01:51.491388   23882 demo/main.go:20] hello world
   I1125 02:01:51.491393   23882 demo/main.go:21] life, the universe, and everything	{"answer":42}
   ```
