### ISSUE TITLE
e2e test improvement

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3560]
## Feature Request

**Is your feature request related to a problem? Please describe:**

e2e test is not good enough.

**Describe the feature you'd like:**

Currently, the e2e test has the following issues which need to be improved:

- It's not clear how to add a new e2e test case.
- The e2e test cases are not stable and fail frequently during the CI.
- Different types of PR should trigger different part of the CI, e.g. only markdown change should not trigger a full e2e test CI, neither should a **Draft** PR

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
Related issues:

- #3466
- #3381 
- #3168 
- #2601

**Comment by mikechengwei** [comment]
https://github.com/pingcap/tidb-operator/issues/3590 solve #3466

**Comment by dragonly** [comment]
> #3590 solve #3466

Could you confirm this? Because I found #3590 is closed for no clear reason.

**Comment by mikechengwei** [comment]
Sorry , at first I thought it was, but later found out that it was not a problem,so i close #3590 @dragonly

**Comment by DanielZhangQD** [comment]
Trace this in https://github.com/pingcap/tidb-operator/issues/3652.
