### ISSUE TITLE
TiDB plugins should be fully supported

### ISSUE THREAD

**Issue by dragonly** [pingcap/tidb-operator#3576]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The current implementation of TiDB plugins mechanism is not complete, because there's no configurations about where to load the .so plugin binaries.

**Describe the feature you'd like:**

Fully functional TiDB plugins support.

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

Any scenario where users may find TiDB plugins useful.

**Comment by DanielZhangQD** [comment]
This is already supported.
