### ISSUE TITLE
"tkctl list" not working

### ISSUE THREAD

**Issue by Kumson** [pingcap/tidb-operator#3577]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**What version of TiDB Operator are you using?**
TiDB Operator Version: version.Info{GitVersion:"v1.1.6", GitCommit:"f30eef72f653441951507420c9f9f45448be78fd", GitTreeState:"clean", BuildDate:"2020-10-16T05:05:48Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
NAME            PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-storage   kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  17d

NAMESPACE        NAME                         STATUS   VOLUME              CAPACITY   ACCESS MODES   STORAGECLASS    AGE
tidb-cluster-1   pd-tidb-cluster-1-pd-0       Bound    local-pv-734dcd6c   49Gi       RWO            local-storage   6d1h
tidb-cluster-1   tikv-tidb-cluster-1-tikv-0   Bound    local-pv-13b06f1d   49Gi       RWO            local-storage   6d1h
tidb-cluster-1   tikv-tidb-cluster-1-tikv-1   Bound    local-pv-30ac998    49Gi       RWO            local-storage   6d1h
tidb-cluster-1   tikv-tidb-cluster-1-tikv-2   Bound    local-pv-9cd89c11   49Gi       RWO            local-storage   6d1h

**What's the status of the TiDB cluster pods?**
NAME                                       READY   STATUS      RESTARTS   AGE    IP              NODE                                     NOMINATED NODE   READINESS GATES
tidb-cluster-1-discovery-89f845cc9-27d4q   1/1     Running     0          6d1h   10.244.2.16     NODE-101274-r159samm.kscn   <none>           <none>
tidb-cluster-1-pd-0                        1/1     Running     0          6d1h   10.38.163.170   NODE-101359-dskbper6.kscn   <none>           <none>
tidb-cluster-1-tidb-0                      2/2     Running     0          6d1h   10.38.163.198   NODE-101341-ft3houkw.kscn   <none>           <none>
tidb-cluster-1-tidb-initializer-64dxp      0/1     Completed   0          6d1h   10.244.1.16     NODE-101214-zfocgndy.kscn   <none>           <none>
tidb-cluster-1-tikv-0                      1/1     Running     0          6d     10.38.163.70    NODE-101340-7fzdln8s.kscn   <none>           <none>
tidb-cluster-1-tikv-1                      1/1     Running     0          6d1h   10.38.163.250   NODE-101274-r159samm.kscn   <none>           <none>
tidb-cluster-1-tikv-2                      1/1     Running     0          6d1h   10.38.163.68    NODE-101359-ft3houkw.kscn   <none>           <none>

**What did you do?**
**NOTE**: I installed tkctl after the tidb cluster 
start tidb cluster -> install tkctl -> use "tkctl list -A" -> nothing outputed
![image](https://user-images.githubusercontent.com/36814424/101326819-c96da780-38a8-11eb-899c-ba3e3d9acffb.png)

**What did you expect to see?**
"tkctl list -A":
the cluster I installed in the K8S cluster

**What did you see instead?**
"tkctl list -A":
nothing

**Comment by DanielZhangQD** [comment]
@Kumson Sorry that we have not maintained the `tkctl` tool for a long time, actually from v1.1.x, we recommend to use kubectl directly, you can use `kubectl get tc -A` to list all the clusters.

**Comment by grandsail** [comment]
> @Kumson Sorry that we have not maintained the `tkctl` tool for a long time, actually from v1.1.x, we recommend to use kubectl directly, you can use `kubectl get tc -A` to list all the clusters.

thanks for replying, I will use `kubectl`.

**Comment by Kumson** [comment]
> @Kumson Sorry that we have not maintained the `tkctl` tool for a long time, actually from v1.1.x, we recommend to use kubectl directly, you can use `kubectl get tc -A` to list all the clusters.

Thanks for replying, I will use `kubectl`.

**Comment by DanielZhangQD** [comment]
@grandsail I see that you want to use `tkctl` in your daily operation as described in https://github.com/pingcap/docs-tidb-operator/issues/1030, would you like to submit PR to fix this issue?

**Comment by DanielZhangQD** [comment]
@grandsail
> Hi, is tkctl under maintainance now? If not, I would like to try to fix it.

Great! Thanks! Actually, we have not maintained it for a long time and very few users use this tool now.

> Looks like modifications https://github.com/pingcap/tidb-operator/pull/4161 and https://github.com/pingcap/tidb-operator/pull/4307 on those files under pkg/tkctl/cmd are global replacements of dependencies. Did them make tkctl usable now?

No.
