### ISSUE TITLE
e2e case `TiDBMonitor switch from deployment to StatefulSet` is not stable

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3584]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The e2e case `Deploy TiDBMonitor and Upgrade Operator, TiDBMonitor switch from deployment to StatefulSet` is not stable:

- https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind-serial/detail/tidb-operator-pull-e2e-kind-serial/2871/pipeline
- https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind-serial/detail/tidb-operator-pull-e2e-kind-serial/2857/pipeline
- https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb-operator-pull-e2e-kind-serial/detail/tidb-operator-pull-e2e-kind-serial/2859/pipeline

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
@mikechengwei Please help check this issue, thanks!

**Comment by mikechengwei** [comment]
Currently other e2e case also stable , i can't reproduce well.

**Comment by mikechengwei** [comment]
I think this is not a problem in this e2e case, it is caused by the contributor's code.
