### ISSUE TITLE
does distinct-agg-push-down is same as agg-push-down-join

### ISSUE THREAD

**Issue by zgcbj** [pingcap/tidb-operator#3592]
https://github.com/pingcap/tidb-operator/blob/4f0d096e4177a3458b231cf62bd8b08afa09c7dd/pkg/apis/pingcap/v1alpha1/tidb_config.go#L286
 
I want modify distinct-agg-push-down by edit tidb-cluster cr, but can`t find any doc about it. I found this in code and confuesd, can any one show me why ?

**Comment by DanielZhangQD** [comment]
It's the same definition in TiDB [here](https://github.com/pingcap/tidb/blob/master/config/config.go#L439).

**Comment by DanielZhangQD** [comment]
@zgcbj I will close this issue now, please feel free to reopen it if any more questions about this.
