### ISSUE TITLE
update chart version

### ISSUE THREAD

**Issue by swartz-k** [pingcap/tidb-operator#3604]
## Bug Report

**What version of Kubernetes are you using?**
none

**What version of TiDB Operator are you using?**
v1.1.7

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
helm version with `version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}`
**What did you expect to see?**
![image](https://user-images.githubusercontent.com/49771587/102082908-ba10d000-3e4d-11eb-9951-328c659463ed.png)

**What did you see instead?**
![image](https://user-images.githubusercontent.com/49771587/102082927-c09f4780-3e4d-11eb-83f2-25fd0f4a0b0a.png)

** What did I do to solve**
refer [code](https://github.com/swartz-k/tidb-operator/commit/837847c11a88fcd5aa93fa731c20312fb76376cd)

may use `for FILE in ./charts/*; do helm lint $FILE; done` to check chart error
![image](https://user-images.githubusercontent.com/49771587/102085208-47095880-3e51-11eb-8a4c-7ad583665dcf.png)

**Comment by DanielZhangQD** [comment]
@swartz-k Thanks for reporting this issue!
I think no need for the following changes:

- Update chart version from `version: dev` to `v1-dev`, the chart version will be replaced with the real version when released.
- Add icon link

It's OK to update the API version from `rbac.authorization.k8s.io/v1beta1` to `rbac.authorization.k8s.io/v1`.
For the names, I would like to keep them unchanged to keep backward compatibility.
WDYT?

**Comment by swartz-k** [comment]
> @swartz-k Thanks for reporting this issue!
> I think no need for the following changes:
> 
> * Update chart version from `version: dev` to `v1-dev`, the chart version will be replaced with the real version when released.
> * Add icon link
> 
> It's OK to update the API version from `rbac.authorization.k8s.io/v1beta1` to `rbac.authorization.k8s.io/v1`.
> For the names, I would like to keep them unchanged to keep backward compatibility.
> WDYT?

I am agree with what you said `version` and `icon link` not need；but i have one question，why change RBAC name will break backward compatibility，it has been used in code？

**Comment by DanielZhangQD** [comment]
> why change RBAC name will break backward compatibility，it has been used in code？

Actually no, just want to be cautious about the name changes.
It's OK to change them with the update fully tested.
Would you like to submit PR and also please help update the manual test procedures and results in detail?
We have to cover the fresh installation and upgrade cases.
Thanks!

**Comment by swartz-k** [comment]
> It's OK to change them with the update fully tested.
> Would you like to submit PR and also please help update the manual test procedures and results in detail?
> We have to cover the fresh installation and upgrade cases.
> Thanks!

It`s my pleasure，i will read the total logic and submit PR to fix this issue.
Have a good day!
