### ISSUE TITLE
Sync TiKV Statefulset no matter whether the TiKV cluster is bootstrapped

### ISSUE THREAD

**Issue by cvvz** [pingcap/tidb-operator#3612]
## Bug Report

**What did you do?**

1. Create a tidb cluster with wrong value of `TC.spec.tikv.affinity.nodeAffinity` field, which caused the TiKV cluster not able to be scheduled. And all TiKV Pods are in status of `Pending`.
2. Correcte the value, but all TiKV Pods are still `Pending`, and the Statefulsets of TiKV are not updated.  

**What did you expect to see?**
Tidb-operator sync loop should not be blocked no matter what status of TiKV cluster is.

**What did you see instead?**
When TiKV cluster is not bootstrapped successfully(**no Pod(store) created**), Tidb operator return error  [here](https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/tikv_member_manager.go#L647-L651), which block the sync loop.

**Root Cause**
PD client return error when tidb operator tried to get stores information but no store created(error infomation: `TiKV cluster not bootstrapped, please start TiKV first`), which blocks the sync loop of TiKV in [syncTidbClusterStatus](https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/tikv_member_manager.go#L647-L651).

**Comment by dragonly** [comment]
Thanks for the bug report ❤️ 
Could you please detail the bug description according to the template, so that we can better investigate into this?

**Comment by cvvz** [comment]
@dragonly PTAL. Sorry that I can't find the logs. But I've figured out the root cause of this bug. PD client return error when tidb operator tried to get stores info but there is no store created, and the reconcile loop of TiKV will return from `syncTidbClusterStatus`, thus sts of TiKV will not be synced.

**Comment by DanielZhangQD** [comment]
@cvvz That's the designed behavior now, the sync for different components is done in a fixed order, if PD is not ready, the other components will not be synced, we will evaluate this behavior later.
Related issues: https://github.com/pingcap/tidb-operator/issues/1245.
