### ISSUE TITLE
User guide for Rancher's RKE or Minikube

### ISSUE THREAD

**Issue by mysticaltech** [pingcap/tidb-operator#369]
Hello, thank you for your wonderful work! This is a true breath of fresh air in the NewSQL world. Finally a well-built project. 

I am myself and like many others running my own Kubernetes cluster thanks to Rancher's RKE https://github.com/rancher/rke. It is one of the most used Kubernetes distribution after GKE and EKS.

Rancher is quite popular in the Kubernetes world... So it would be fantastic to have a user guide or quick start guide for this platform!

Thanks!

**Comment by gregwebs** [comment]
@mysticaltech I am glad you like the project. is there anything in particular we would need in our guide for RKE?

Our [docs are here](https://github.com/pingcap/tidb-operator/blob/master/docs/user-guide.md), let us know what is most important to improve.

**Comment by mysticaltech** [comment]
You already have tutorials for DinD, Google GKE, and AWS EKS. But those are specific Kubernetes use cases, it doesn't show how to use the tidb-operator in a "vanilla" Kubernetes cluster. Not everyone uses Google or AWS.

It would be fantastic if you added a tutorial for Rancher RKE or Minikube, both of which are more "vanilla" Kubernetes distributions. 

Rancher RKE is the 4th most used Kubernetes distribution in production after Azure AKS.

**Comment by gregwebs** [comment]
Okay, so a tutorial for on-prem install. We are developing expertise in that area now so it would make sense for us to have one.

We can't run on Minikube because it is a single node K8s cluster. We use DinD because it is multi-node. 

BTW, where do you get your K8s usage numbers from?

**Comment by mysticaltech** [comment]
I apologize, my bad, Kubeadm DinD is indeed vanilla on-prem Kubernetes! So the DinD tutorial works great even for Rancher RKE. Just to answer your question, Rancher Labs made it much easier to install Kubernetes with RKE, so most on-prem setups are using this now. About the numbers, I can't remember where I read this exactly... Thanks again for your time.
