### ISSUE TITLE
Operator should remove members from the Dashboard topology when scaling in

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-operator#3697]
## Feature Request

**Is your feature request related to a problem? Please describe:**

At present, when a component is scaled in, it still shows up in TiDB Dashboard. Dashboard expects that it is the deployment tool's responsibility to remove entries for scaled-in instances.

**Describe the feature you'd like:**

When nodes are removed from the cluster, TiDB Operator should ensure that they're gracefully removed from TiDB Dashboard.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
Only handle the TiDB scaling in is good now, for the other components, e.g. PD, TiKV, TiFlash, please help verify that the members/stores scaled in will disappear from the TiDB Dashboard.
