### ISSUE TITLE
Auto generating crd yaml specification

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#370]
We may generate the CRD specification (to be more accurate, the `.spec.validation` part) by the go struct definition, so that we can maintain CRD validation easily.

There is already some handy libraries for this, for example [crd-validation](https://github.com/ant31/crd-validation).

**Comment by weekface** [comment]
@aylei do we still need it?

**Comment by aylei** [comment]
@weekface Yes, this should be postpone to later 1.x however
