### ISSUE TITLE
aarch64/arm64 support

### ISSUE THREAD

**Issue by pdiaz** [pingcap/tidb-operator#3728]
## Feature Request

tiup does support the aarch64 architecture but I don't find any aarch64 Docker images to use with this operator.

Do you have any plans to support aarch64?

**Comment by DanielZhangQD** [comment]
cc @chenmin1992 
Would you like to submit PR for this feature?

**Comment by DanielZhangQD** [comment]
cc @shuke987 Your team will do the necessary change to support arm64, right?

**Comment by DerrickMartinez** [comment]
Any thoughts on arm64?

**Comment by DanielZhangQD** [comment]
We will provide the images in June, refer to https://github.com/PingCAP-QE/ci/issues/160.

**Comment by xavier83** [comment]
hasn't arm been supported since 2016? https://twitter.com/pingcap/status/778522025631420416

**Comment by pdiaz** [comment]
@xavier83 It has been tested maybe since that Tweet, when I reported this issue back in January there was support for ARM64 on TiUP but not on the operator.

I just checked again on Docker Hub and there seems to be an image for the operator since about 5 months ago pingcap/tidb-operator-arm64. No idea how well supported is it now as I haven't tested it yet.

**Comment by DanielZhangQD** [comment]
@pdiaz @xavier83 
Yes, you can use the arm images:
operatorImage: pingcap/tidb-operator-arm64:v1.2.x
# ...
tidbBackupManagerImage: pingcap/tidb-backup-manager-arm64:v1.2.x

**Comment by xavier83** [comment]
@DanielZhangQD it might be great if the arm64 images are available as part of the `pingcap/tidb-operator:v1.2.x` tag itself, so it works on multi-arch clusters as is. It would work without affecting the regular x86_64 image as well (using _docker manifests_) see https://hub.docker.com/_/postgres?tab=tags for eg. Thanks

**Comment by DanielZhangQD** [comment]
@xavier83 Sure, we will work on that soon.

**Comment by DanielZhangQD** [comment]
Multi-arch images are provided from v1.3.2 for tidb-operator and tidb-backup-manager.
