### ISSUE TITLE
With helm,I reapply but get an error about "invalid ownership metadata"

### ISSUE THREAD

**Issue by huang12zheng** [pingcap/tidb-operator#3779]
https://github.com/roboll/helmfile/issues/1668

## Question

How do I set the template, to make
app.kubernetes.io/managed-by: tidb-operator

## other 
```
Release.Service: The service that is rendering the present template. On Helm, this is always Helm.
```
https://helm.sh/docs/chart_template_guide/builtin_objects/#helm

**Comment by DanielZhangQD** [comment]
@huang12zheng 
What's the version of tidb-operator?
From v1.1.0, the tidb-cluster chart has been abandoned and please use the TidbCluster CR for the TiDB cluster management.
You can check detail in the [doc](https://docs.pingcap.com/tidb-in-kubernetes/stable/notes-tidb-operator-v1.1).

**Comment by huang12zheng** [comment]
thanks.  
I did so when I saw the chart update.
