### ISSUE TITLE
According to the minimum installation document, the image does not exist when using the image on alicloud to deploy tidb cluster monitoring

### ISSUE THREAD

**Issue by Aaron-23** [pingcap/tidb-operator#3780]
![image](https://user-images.githubusercontent.com/50609288/106842294-bc213d80-66de-11eb-801c-bc1457358e82.png)

**Comment by DanielZhangQD** [comment]
@Aaron-23 Sorry for the trouble.
Could you please try the `pingcap/tidb-monitor-initializer:v4.0.10` directly?
There is something wrong with the repo in the ali registry so the images are not synced to that repo.
And we also consider migrating the images to another vendor.

**Comment by DanielZhangQD** [comment]
@Aaron-23 The images are synced to the ali repo now, please try again.

**Comment by Aaron-23** [comment]
@DanielZhangQD Yes, thank you！
