### ISSUE TITLE
Optimize the region leader checking logic during TiKV upgrade

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3781]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, during TiKV upgrade, we will first add evict leader scheduler to the store to evict region leaders, and when the [leader count is 0](https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/tikv_upgrader.go#L185), we can safely delete the Pod, however, the leader info is retrieved from PD, which may be stale because if the PD leader is just restarted, it may not have all the leader info, so we'd better check the leader info from the TiKV directly.
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lonng** [comment]
Reference https://github.com/pingcap/tiup/blob/master/pkg/cluster/spec/tikv.go#L361

**Comment by DanielZhangQD** [comment]
PD issue https://github.com/tikv/pd/issues/3406
