### ISSUE TITLE
Create a parent proc for tikv-server in container

### ISSUE THREAD

**Issue by hykych** [pingcap/tidb-operator#3795]
## Feature Request

**Is your feature request related to a problem? Please describe:**

If 2 replicas of a region failed, I need to run the following command on the tikv instance which own the third replicas
`./tikv-ctl --db /var/lib/tikv/db unsafe-recover remove-fail-stores -s <s1,s2> --all-regions
`  

but I got the error which is caused by the tikv-server is still running.
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RocksDb("IO error: While lock file: /var/lib/tikv/db/LOCK: Resource temporarily unavailable")', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
`

**Describe the feature you'd like:**
For now the tikv-server PID 1 in a container. I wish tikv-server has a parent process which allow us to stop the tikv-server inside a container.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
@hykych You can refer to this [doc](https://docs.pingcap.com/tidb-in-kubernetes/dev/tips#use-the-diagnostic-mode) to add annotation and then kill the container manually, after the container is restarted, you can run tikv-ctl normally since the tikv-server process is not started.

**Comment by hykych** [comment]
@DanielZhangQD  I tried, it works. thank you.
