### ISSUE TITLE
Liveness and readiness probe in TiDB Operator

### ISSUE THREAD

**Issue by dragonly** [pingcap/tidb-operator#3799]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently the TiDB Operator could be in an out-of-service state, such as waiting for the next leader election lease. This can not be easily monitored now.

**Describe the feature you'd like:**

Add liveness and readiness probe as defined in [Kubernetes Pod Lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#when-should-you-use-a-liveness-probe).

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mikechengwei** [comment]
I can help do this pr.
