### ISSUE TITLE
Correctly handle multiple pvc situations

### ISSUE THREAD

**Issue by dragonly** [pingcap/tidb-operator#3802]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently TiDB Operator supports mounting multiple PVCs to a single Pod for PD/TiKV/TiDB. But a lot of code in TiDB Operator still assumes that there is only one PVC for a Pod, and uses https://github.com/pingcap/tidb-operator/blob/d813569b79c8bbb640a2272392645f3300c0b318/pkg/manager/member/scaler.go#L179 to deal with it.

**Describe the feature you'd like:**

Deprecate the usage of `ordinalPVCName()`, and deal with multiple PVCs using https://github.com/pingcap/tidb-operator/blob/8b3658a30af7a1eb13a5dbbe5ecf44132508c439/pkg/util/util.go#L421

We should also change https://github.com/pingcap/tidb-operator/blob/d813569b79c8bbb640a2272392645f3300c0b318/pkg/manager/member/scaler.go#L116 to use `ResolvePVCFromPod()` as mentioned above.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

Each caller side of `ordinalPVCName()` needs to deal with this properly, which is a considerable amount of work. Maybe we could make several PRs to fix this.

**Comment by DanielZhangQD** [comment]
Getting the PVCs from the Pod spec should be the most reliable way, refer to https://github.com/pingcap/tidb-operator/blob/master/pkg/util/util.go#L421.

**Comment by DanielZhangQD** [comment]
We also need to implement the `Scaler` method for TiDB.
Please also help change the logic for DM master and worker.

**Comment by dragonly** [comment]
when all the functional PRs are merged, we should then refactor the related code to pull out common utility functions such as mounting a pvc to a pod

**Comment by dragonly** [comment]
Should also add e2e cases for all those scenarios after all PRs are merged.

**Comment by dragonly** [comment]
> We also need to implement the `Scaler` method for TiDB.

Currently TiDB pods are usually deployed without PVC. We should postpone the implementation for TiDB, and make a more thorough analysis first.

**Comment by dragonly** [comment]
We should also change `v1alpha1.UnjoinedMember` to reflect the correct PVCs for unjoined PD/DM members.

**Comment by DanielZhangQD** [comment]
Remaining tasks:

- Code change for TiDB
- Code change for DM
- e2e

**Comment by DanielZhangQD** [comment]
Code change for TiDB https://github.com/pingcap/tidb-operator/pull/4033.
No need to change for DM now.
