### ISSUE TITLE
UPGRADE FAILED: rendered manifests contain a new resource that already exists

### ISSUE THREAD

**Issue by qiffang** [pingcap/tidb-operator#3828]
## Bug Report

**What version of Kubernetes are you using?**

I want to upgrade operator from `1.1.9` to `1.1.11`.
The command is here 
```
helm upgrade --install tidb-operator /charts/tidb-operator.tgz --namespace=tidb-admin 
```
But I run into:
```
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: , name: tidb-operator:tidb-controller-manager, existing_kind: rbac.authorization.k8s.io/v1, Kind=ClusterRole, new_kind: rbac.authorization.k8s.io/v1, Kind=ClusterRole
```

It is casued that Operator wat upgrade `ClusterRole` from `rbac.authorization.k8s.io/v1beta1` to  `rbac.authorization.k8s.io/v1` in `1.1.10`.

Operator need to add release notes for changing of apiversion.

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by DanielZhangQD** [comment]
Refer to https://github.com/helm/helm/issues/7697.
