### ISSUE TITLE
How can i connect tidb

### ISSUE THREAD

**Issue by tulid** [pingcap/tidb-operator#3841]
## Question
according to the official doc, i still do not unstander how to connect tidb using mysql.

i deployed the tidb on kubernetes, and all service and pod run seccessfully.
`
root@dev-legend:~/jinquan/pingcap/pingcap-1.11.1/tidb-operator-release-1.1# kubectl get pod -n tidb-admin
NAME                                       READY   STATUS    RESTARTS   AGE
tidb-controller-manager-6c7c6f6bb6-qcc4t   1/1     Running   7          24h
tidb-scheduler-d74f9946-mv2cv              2/2     Running   5          24h
root@dev-legend:~/jinquan/pingcap/pingcap-1.11.1/tidb-operator-release-1.1# kubectl get po -n tidb-cluster
NAME                              READY   STATUS    RESTARTS   AGE
basic-discovery-c65484d7d-cvdm8   1/1     Running   0          20m
basic-monitor-7d4b9d8c87-grxs2    3/3     Running   0          6h16m
basic-pd-0                        1/1     Running   0          20m
basic-tidb-0                      2/2     Running   0          18m
basic-tikv-0                      1/1     Running   0          19m
mysqlcli-7fb64959fd-b8dgk         1/1     Running   0          24h
` 

can u tell me where the mysql i should be deployed, is on local host or is on pod?

`mysql -h 127.0.0.1 -u root -p 4000` 

Using above command, i cannot connect tidb. the error will occur as bellow 
`# mysql -h 127.0.0.1 -u root -p 4000
Enter password:
ERROR 1698 (28000): Access denied for user 'root'@'localhost'`

If you saw the question, pls tell me how can i connect tidb.

**Comment by DanielZhangQD** [comment]
@tulid You can follow this [doc](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/access-tidb) to connect to the TiDB.

**Comment by dragonly** [comment]
@tulid Since this issue is stale for several days, I will close it for the moment. Feel free to reopen and append your questions!
