### ISSUE TITLE
Add readiness probe and liveness probe for the components

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3857]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, we do not support setting the readiness probe and liveness probe for the components except for the readiness probe for TiDB, however, we should support setting them for the following reasons:

- The readiness probe will also be honored by the sts controller during the rolling update because sts controller will wait for the Pod ready until updating the next Pod.
- Some Pods can hang there and can be recovered by the Liveness probe

The following cases should be considered:

- TLS is enabled for all the components and between TiDB server and client, because the access to the status port of one component may also need certs like TiDB
- The probe configuration should be able to customize since in some scenarios we may have to customize them

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mikechengwei** [comment]
I can help do this pr.

**Comment by DanielZhangQD** [comment]
Related components:

- PD/TiDB/TiKV/TiFlash/Pump/CDC
- DM master/DM worker
