### ISSUE TITLE
Run containers as non-root user

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3874]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, all the containers managed by the TiDB Operator including itself are run as root user, however, this is not allowed in some Kubernetes clusters or platforms.
**Describe the feature you'd like:**

Support running the containers as non-root user, we can support configuring the [securityContext](https://kubernetes.io/zh/docs/tasks/configure-pod-container/security-context/) for the following components/resources:

- tidb-controller-manager
- tidb-scheduler
- advanced-statefulset-controller
- admission-webhook
- TidbCluster
- TidbMonitor
- TidbInitializer
- Backup
- Restore
- BackupSchedule
- DmCluster

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
Currently, [PodSecurityContext](https://github.com/pingcap/tidb-operator/blob/master/pkg/apis/pingcap/v1alpha1/types.go#L820) is supported for PD/TiDB/TiKV/TiFlash/Pump, all the other components, e.g. TiCDC, monitoring, etc. are not supported, we can refer to the implementation of PodSecurityContext to support the other components.

**Comment by liubog2008** [comment]
TODO:
- [ ] Change all operator Dockerfiles to non root
- [ ] Set `runAsNonRoot` field for all operator kubernetes manifests
- [ ] Change all ti-component Dockerfiles to non root
- [ ] Support PodSecurityContext for all ti-components

@DanielZhangQD PTAL, anything else？

**Comment by DanielZhangQD** [comment]
@liubog2008 It's not necessary to update the Dockerfiles, we can just configure the PodSecurityContext to run as a non-root user, right?

**Comment by liubog2008** [comment]
Yes, but `PodSecurityContext` can be omit if we update Dockerfile.

**Comment by liubog2008** [comment]
And built as non-root image is a better practice

**Comment by DanielZhangQD** [comment]
Yes, I understand that. 
However, all the users till now are running as root, what if they don't want to run as non-root, with the current image and PodSecurityContext, users can choose to run as root or non-root, and all the current users do not need to change the operation experience. 
BTW, running with non-root may make the debug more difficult, e.g. we may need to install some tools during the debug.

**Comment by liubog2008** [comment]
This feature is for supporting `PodSecurityContext` for all ti-components

**Comment by liubog2008** [comment]
See https://github.com/pingcap/tidb-operator/issues/3907 for changing default deploy and build files
