### ISSUE TITLE
No need to set part of the default configurations for TiFlash

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3876]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For v4.0.12 or later, 5.0.0 or later, TiFlash can ignore these `user.*`, `quotas.*` settings.
Refer to https://github.com/pingcap/tics/issues/1497, https://github.com/pingcap/tiup/pull/1211/files.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
The default configurations are set [here](https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/tiflash_util.go#L102), we can just refer to the implementation in TiUP to check the versions and skip the default settings.

**Comment by JaySon-Huang** [comment]
How to check/compare what the cluster version is inside the function `getTiFlashConfig`?

**Comment by DanielZhangQD** [comment]
You can refer to this [function](https://github.com/pingcap/tidb-operator/blob/master/pkg/apis/pingcap/v1alpha1/tidbcluster.go#L97) to define a similar one for TiFlash.

**Comment by DanielZhangQD** [comment]
This will be traced in https://github.com/pingcap/tidb-operator/issues/4238.
