### ISSUE TITLE
raft-max-inflight-msgs is disappeared when using tidb-operator

### ISSUE THREAD

**Issue by hykych** [pingcap/tidb-operator#3889]
## Bug Report

**What version of Kubernetes are you using?**
v1.13.2

**What version of TiDB Operator are you using?**
v1.1.9

**What did you do?**
I created a tidbcluster yaml, and assign the config `raft-max-inflight-msgs`, but this config not show up in the actual resource in the kubernetes.
![image](https://user-images.githubusercontent.com/10421724/113229986-a6895800-92ca-11eb-9e64-05bbfc327795.png)

**What did you expect to see?**
I can see the config parameter `raft-max-inflight-msgs`
**What did you see instead?**
I didn't see it. only see `raft-base-tick-interval` and `raft-store-max-leader-lease`

**Comment by hykych** [comment]
@DanielZhangQD  Yes, I' applyed the CRD for v1.1.9

**Comment by DanielZhangQD** [comment]
The TOML format should be as following:
```
config: |
  [raftstore]
  raft-max-inflight-msgs = 1024
```

**Comment by hykych** [comment]
@DanielZhangQD I've changed it. still doesn't work. this is what I got from the config
![image](https://user-images.githubusercontent.com/10421724/113237458-71383680-92d9-11eb-9554-c415c03f3007.png)

this is what i got from the kubernetes
![image](https://user-images.githubusercontent.com/10421724/113237604-b9efef80-92d9-11eb-99c2-bc2fa4c2e795.png)

**Comment by hykych** [comment]
@DanielZhangQD  turns out the TOML format configuration works. thanks, this can be closed now.
