### ISSUE TITLE
Q: Is it possible to remove PVC(s) automatically when deleting the corresponding tidb-cluster

### ISSUE THREAD

**Issue by Thearas** [pingcap/tidb-operator#3893]

**Comment by mikechengwei** [comment]
That's ok , we can provide a cleanPolicy field for pvc.

**Comment by DanielZhangQD** [comment]
@Thearas Sorry that we do not support this feature now.
@mikechengwei How could that meet the request? We may have to add a GC controller to check and remove the orphaned PVCs, however, when it comes to the deletion of PVC/PV, we prefer the users to do that manually to ensure data safety.

**Comment by Thearas** [comment]
@DanielZhangQD @mikechengwei Thanks, I run many TiDB tests in my cluster, so deleting PVCs automatically when test is finished will be very helpful to me.
Currently I write a simple script to delete the dangling PVCs. (According to https://docs.pingcap.com/tidb-in-kubernetes/dev/destroy-a-tidb-cluster#delete-data)
```sh
IFS='
'
pvc2tcs=( $(kubectl get pvc -l app.kubernetes.io/managed-by=tidb-operator,app.kubernetes.io/name=tidb-cluster -o jsonpath="{range .items[*]}{.metadata.name}{' '}{.metadata.labels.app\.kubernetes\.io/instance}{'\n'}{end}") )
echo "Cleanup all dangling PVCs created by tidb-operator."
for pvc2tc in "${pvc2tcs[@]}"; do
    pvc=$(echo "${pvc2tc}" | awk -F ' ' '{print $1}')
    tc=$(echo "${pvc2tc}" | awk -F ' ' '{print $2}')
    kubectl get tc "${tc}" >/dev/null || kubectl delete pvc "${pvc}"
done
```

**Comment by shonge** [comment]
We should use `enablePVReclaim: true` when scale in pd or tikv will trigger PV reclaim automatically:
https://github.com/pingcap/tidb-operator/blob/2286554cda1ec355f1b9f8cff76a078b76f001ae/charts/tidb-cluster/values.yaml#L32

**Comment by DanielZhangQD** [comment]
> We should use `enablePVReclaim: true` when scale in pd or tikv will trigger PV reclaim automatically:
> https://github.com/pingcap/tidb-operator/blob/2286554cda1ec355f1b9f8cff76a078b76f001ae/charts/tidb-cluster/values.yaml#L32

With this, you have to:
```
pvReclaimPolicy: Delete # To remove the PVs automatically when the PVCs are deleted
enablePVReclaim: true
```
Scale in the replicas of each component to 0 and after all the Pods are deleted, delete the tc.
