### ISSUE TITLE
Optimization for `PodsAreChanged` function

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3895]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

In the function here https://github.com/pingcap/tidb-operator/blob/master/tests/e2e/util/pod/pod.go#L40-L45, it's not reasonable to return an error if the Pod has been changed, which is already indicated by the `true`.
And the return value check for this function in the caller functions should also be updated accordingly.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by shonge** [comment]
I can help to fix it.
