### ISSUE TITLE
No need to wait tikv transfer leader timeout while upgrading tidb cluster with single tikv node 

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tidb-operator#3902]
## Feature Request

**Is your feature request related to a problem? Please describe:**

It will take 10 minutes to wait tikv leader to transfer. Although there is only one tikv node. It's not necessary.

**Describe the feature you'd like:**

Upgrade the tikv directly if there is only one tikv

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by tisonkun** [comment]
/unassign @shonge 
/assign @mianhk

Thanks for taking over this issue @shonge . It seems the original effort is stale and @mianhk picked up the issue again. You're welcome to give #4091 a review :)
