### ISSUE TITLE
stage for backup CR looks confusing

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/tidb-operator#3904]
## Question

https://github.com/pingcap/tidb-operator/blob/697fd25ee728f900e81969fa4dd82181d81be171/cmd/backup-manager/app/backup/manager.go#L146

https://github.com/pingcap/tidb-operator/blob/697fd25ee728f900e81969fa4dd82181d81be171/cmd/backup-manager/app/backup/manager.go#L170

We set backup(br) job's status from Running -> Prepare -> Completed, which looks very confusing.

https://github.com/pingcap/tidb-operator/blob/697fd25ee728f900e81969fa4dd82181d81be171/cmd/backup-manager/app/export/manager.go#L157

https://github.com/pingcap/tidb-operator/blob/697fd25ee728f900e81969fa4dd82181d81be171/cmd/backup-manager/app/export/manager.go#L341

It looks the same for export(dumpling) job.

**Comment by lichunzhu** [comment]
Suggest changing to Prepare -> Running -> Completed

**Comment by liubog2008** [comment]
@DanielZhangQD Just exchange Prepare and Running? Are there any problems of API meaning changes?

**Comment by DanielZhangQD** [comment]
> @DanielZhangQD Just exchange Prepare and Running? 

- Backup with BR
  - `Prepare` should be updated in https://github.com/pingcap/tidb-operator/blob/master/cmd/backup-manager/app/backup/manager.go#L183 block.
  - `Running` should be updated before the real backup https://github.com/pingcap/tidb-operator/blob/master/cmd/backup-manager/app/backup/manager.go#L264.
- Backup with Dumpling
  - `Prepare` should be updated before setting GC https://github.com/pingcap/tidb-operator/blob/master/cmd/backup-manager/app/export/manager.go#L165 and `Running` before dumpling data https://github.com/pingcap/tidb-operator/blob/master/cmd/backup-manager/app/export/manager.go#L245.

> Are there any problems of API meaning changes?

It's OK, this fix just changes the condition order in the CR status.

Test Cases:

- Backup with BR with `spec.from` configured
- Backup with BR without `spec.from` configured
- Backup with Dumpling
