### ISSUE TITLE
DM doesn't necessary to be in the same namespace as a TiDB's 

### ISSUE THREAD

**Issue by coderplay** [pingcap/tidb-operator#3906]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We can create cross TiDB clusters tasks in DM. However currently,  DM depends on tidb's discovery,   it is forced to be in the same namespace as one tidb's. 

**Describe the feature you'd like:**
Since discovery is lightweight,  it's better to launch a dedicate discovery for DM,

**Comment by DanielZhangQD** [comment]
Solution:

Create a dedicated discovery service for each DM cluster.
