### ISSUE TITLE
How to load custom dashboard to grafana

### ISSUE THREAD

**Issue by slow-zhang** [pingcap/tidb-operator#3921]
## Question

I build a cluster by TiDB + CustomServerA. By [monitor-with-externalConfigMap](https://github.com/pingcap/tidb-operator/tree/master/examples/monitor-with-externalConfigMap), the CustomServerA's metrics is loaded to tidb cluster, but I can not load my custom dashboard to TiDBMonitor.

Is there some way I can add my CustomServerA's dashboard to grafana like tidb's dashboard

**Comment by mikechengwei** [comment]
There is no good way now, we will support this feature.

**Comment by slow-zhang** [comment]
ok, a workaround is using the grafana `upload .json file` function.

please @me if this supported

**Comment by mikechengwei** [comment]
@slow-zhang Master branch have support this feature.

**Comment by slow-zhang** [comment]
is there some example for how to use this feature

**Comment by mikechengwei** [comment]
Refer to https://github.com/pingcap/tidb-operator/tree/master/examples/monitor-with-externalConfigMap/grafana,you need to upgrade to master branch.
