### ISSUE TITLE
Support setting liveness probe and readiness probe for TidbMonitor

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3935]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Support setting liveness probe and readiness probe for Grafana and Prometheus containers in TidbMonitor.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mikechengwei** [comment]
Liveness probe will affect prom wal replay , ref :https://github.com/prometheus-operator/prometheus-operator/pull/3502
