### ISSUE TITLE
Why not support set "--kubeconfig"？ It is not convenience to debug with bin file

### ISSUE THREAD

**Issue by zhucan** [pingcap/tidb-operator#3945]
https://github.com/pingcap/tidb-operator/blob/5f1c1350fd24e48aeac978b32e2c307647b4f9c9/cmd/controller-manager/main.go#L93

**Comment by zhucan** [comment]
@DanielZhangQD

**Comment by DanielZhangQD** [comment]
@zhucan Yes, it's not convenient to debug with binary now, would you like to help improve this?

**Comment by zhucan** [comment]
ok
