### ISSUE TITLE
TiKV connection PD failed

### ISSUE THREAD

**Issue by lzj47010** [pingcap/tidb-operator#3948]
Deploying tidb in multi k8s cluster; 
 error message
 [ERROR] [util.rs:560] ["connect failed"] [error="Grpc(RpcFailure(RpcStatus { status: 14-UNAVAILABLE, details: Some(\"DNS resolution failed for service: cluster41-pd-2.cluster41-pd-peer.tidb-cluster.svc.cluster41.com:2379\") }))"] [endpoints=http://cluster41-pd-2.cluster41-pd-peer.tidb-cluster.svc.cluster41.com:2379]

pd  service DNS resolution service
![image](https://user-images.githubusercontent.com/50096566/116187530-45816280-a758-11eb-904b-a9f5a5b7cddc.png)

Access to PD API  success
![image](https://user-images.githubusercontent.com/50096566/116187609-6b0e6c00-a758-11eb-89f5-2fde47b9d0a7.png)

**Comment by tisonkun** [comment]
Thanks for your reports @lzj47010 ! Could you please report the issue in English?

**Comment by july2993** [comment]
which cluster does the error come from? the cluster with `cluster41.com` domain or the other k8s cluster?
pls provide the topology and more context

**Comment by lzj47010** [comment]
> the cluster with `cluster41.com` domain

 cluster with cluster41.com domain 
Using rewrite module to point to cluster.local
![image](https://user-images.githubusercontent.com/50096566/116333859-d57de580-a806-11eb-9b4d-9f5d6e279664.png)

**Comment by july2993** [comment]
did you nslookup in the tikv pod?
what is the currently status of both cluster

**Comment by lzj47010** [comment]
> did you nslookup in the tikv pod?
> what is the currently status of both cluster

cluster2.com cluster not deployed yet
The above is implemented in tikv pod
![image](https://user-images.githubusercontent.com/50096566/116337207-55f31500-a80c-11eb-8b9f-969e93a39537.png)


cluster statue

![image](https://user-images.githubusercontent.com/50096566/116337117-38be4680-a80c-11eb-883e-4ae5b5b95f60.png)

discovery logs

![image](https://user-images.githubusercontent.com/50096566/116337279-74591080-a80c-11eb-83ab-2f858173c2a5.png)

tidb-controller-manager logs
![image](https://user-images.githubusercontent.com/50096566/116337391-9b174700-a80c-11eb-9225-d0e96be6efe2.png)

**Comment by july2993** [comment]
so, the question is tikv can not resolve host `cluster41-pd-2.cluster41-pd-peer.tidb-cluster.svc.cluster41.com`, but you can resolve it if you nslookup the same host in the tikv pod?

would you provide more logs of the tikv?

**Comment by lzj47010** [comment]
> so, the question is tikv can not resolve host `cluster41-pd-2.cluster41-pd-peer.tidb-cluster.svc.cluster41.com`, but you can resolve it if you nslookup the same host in the tikv pod?
> 
> would you provide more logs of the tikv?

yes ，It can be successful in tikv pod

tikv pod logs 
[tikv-0.log](https://github.com/pingcap/tidb-operator/files/6388755/tikv-0.log)

**Comment by july2993** [comment]
could you see any error from the coredns logs?

**Comment by lzj47010** [comment]
> could you see any error from the coredns logs?

Coredns has no relevant error

![image](https://user-images.githubusercontent.com/50096566/116342802-cc484500-a815-11eb-85cf-58733fdbbec7.png)

![image](https://user-images.githubusercontent.com/50096566/116342822-d5d1ad00-a815-11eb-83f4-0b19eec68bc1.png)

**Comment by july2993** [comment]
since it should work but something wrong with tiki, I have no glue now, would you provide a reproducible step? (with your tidb cluster yaml and coredns config)

**Comment by lzj47010** [comment]
> seem it should work but something wrong with tiki, I have no glue now, would you provide a reproducible step? (with your tidb cluster yaml and coredns config)

Sorry,  I found the problem, coredns configuration error; Now tidb has been successfully deployed across clusters. Thank you for your answer!

**Comment by july2993** [comment]
> > seem it should work but something wrong with tiki, I have no glue now, would you provide a reproducible step? (with your tidb cluster yaml and coredns config)
> 
> Sorry, I found the problem, coredns configuration error; Now tidb has been successfully deployed across clusters. Thank you for your answer!

you are welcome, would you elaborate on the problem?

**Comment by lzj47010** [comment]
> > > seem it should work but something wrong with tiki, I have no glue now, would you provide a reproducible step? (with your tidb cluster yaml and coredns config)
> > 
> > 
> > Sorry, I found the problem, coredns configuration error; Now tidb has been successfully deployed across clusters. Thank you for your answer!
> 
> you are welcome, would you elaborate on the problem?

before，configured  coredns rewrite module
![image](https://user-images.githubusercontent.com/50096566/116375128-8c975280-a841-11eb-962b-4f8204cdc559.png)

now   Configure cluster41.com separately
![image](https://user-images.githubusercontent.com/50096566/116375309-be101e00-a841-11eb-9083-2d13e0ea8d41.png)

**Comment by july2993** [comment]
> igur

**Comment by july2993** [comment]
> > > > seem it should work but something wrong with tiki, I have no glue now, would you provide a reproducible step? (with your tidb cluster yaml and coredns config)
> > > 
> > > 
> > > Sorry, I found the problem, coredns configuration error; Now tidb has been successfully deployed across clusters. Thank you for your answer!
> > 
> > 
> > you are welcome, would you elaborate on the problem?
> 
> before，Configure coredns rewrite module
> ![image](https://user-images.githubusercontent.com/50096566/116375128-8c975280-a841-11eb-962b-4f8204cdc559.png)
> 
> now Configure cluster41.com separately
> ![image](https://user-images.githubusercontent.com/50096566/116375309-be101e00-a841-11eb-9083-2d13e0ea8d41.png)

but it seems should both work? and you did resolve it when you run `nslookup` in the tikv pod

**Comment by lzj47010** [comment]
yes ,nslookup in the tikv pod is success; Maybe there is something wrong with the rewrite module

![image](https://user-images.githubusercontent.com/50096566/116401802-3edd1300-a85e-11eb-8ede-8137a51c10c2.png)

**Comment by july2993** [comment]
> I know ,coredns rewrite module also needs to be specified ANSWER SECTION，when the QUESTION SECTION was rewritten
> 
> configure QUESTION SECTION
> ![image](https://user-images.githubusercontent.com/50096566/116402764-61bbf700-a85f-11eb-9fa4-eeb1b4a58d13.png)
> 
> configure ANSWER SECTION
> 
> ![image](https://user-images.githubusercontent.com/50096566/116402862-7a2c1180-a85f-11eb-837a-6ae551c081c9.png)

thinks for you sharing, so seems tikv will not work if the answer section is not the same as question but just curl can still work
