### ISSUE TITLE
Support for setting custom annotations on tidb-scheduler pod in tidb-operator helm chart

### ISSUE THREAD

**Issue by agaffney** [pingcap/tidb-operator#3957]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The Datadog agent detects the `tidb-scheduler` pod as the standard k8s scheduler, since it uses the upstream image. However, it uses a custom port, so the automatic Datadog agent config for it doesn't work. I need to be able to specify annotations on the pod to override the automatic Datadog agent config.

**Describe the feature you'd like:**

It should be possible to set `scheduler.podAnnotations` in the helm chart to apply custom annotations to the `tidb-scheduler` pod.

**Describe alternatives you've considered:**

The only currently alternatives are forking the helm chart or a post-renderer script, neither of which is a good solution in my environment.

**Teachability, Documentation, Adoption, Migration Strategy:**

The need to set custom annotations on pods is a relatively common one.

**Comment by DanielZhangQD** [comment]
@agaffney Thanks for reporting this issue!
Would you like to submit PR for this?

**Comment by agaffney** [comment]
I was able to work around this a different way (by completely disabling the `kube-scheduler` auto-discovery config in the datadog agent), so I no longer need this. However, being able to add pod annotations to the various Deployments managed by the helm chart would likely be helpful to somebody at some point.

**Comment by DanielZhangQD** [comment]
OK, thanks!
