### ISSUE TITLE
Proposal: Merge PR branch onto master in Jenkins checkout phrase

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#396]
```
checkout([$class: 'GitSCM', branches: [[name: "${BUILD_BRANCH}"]], userRemoteConfigs:[[url: "${BUILD_URL}", credentialsId: "${CREDENTIALS_ID}"]]])
```
-> 

```
checkout([$class: 'GitSCM', branches: [[name: "${BUILD_BRANCH}"]], userRemoteConfigs:[[url: "${BUILD_URL}", credentialsId: "${CREDENTIALS_ID}"]], mergeRemote: 'origin', mergeTarget: 'master', fastForwardMode: 'NO_FF'])
``` 

xref: https://jenkins.io/doc/pipeline/steps/workflow-scm-step/

Currently, CI job checkouts PR branch to test, but the PR branch may be out of date.

It's best and convenient to merge the PR branch onto master before running the CI job. And it helps when the broken master is fixed,  blocked PRs are not needed to be rebased onto the new master. (example https://github.com/pingcap/tidb-operator/pull/392#issuecomment-483493629)

**Comment by cofyc** [comment]
cc @tennix @weekface

**Comment by weekface** [comment]
I am fine with it @onlymellb PTAL

**Comment by cofyc** [comment]
Another way is to enable "Require branches to be up to date before merging" in github repo settings.

**Comment by cofyc** [comment]
@weekface It seems that we have "Require branches to be up to date before merging" enabled?

**Comment by weekface** [comment]
yes

**Comment by cofyc** [comment]
Then I think we can close this now.
