### ISSUE TITLE
TiFlash in Advanced TiDBClsuter Example logger & cert-allowed-cn need quote

### ISSUE THREAD

**Issue by swartz-k** [pingcap/tidb-operator#3967]
1.  security.cert-allowed-cn 
https://github.com/pingcap/tidb-operator/blob/f9418af1581b11c5774c8537359c49ad64f3cc52/examples/advanced/tidb-cluster.yaml#L900

need to be 

```
cert-allowed-cn = "CNNAME"
```
otherwise, will get error

![image](https://user-images.githubusercontent.com/49771587/117438052-a0d70000-af63-11eb-94f6-125bf443b840.png)

2. logger.log
https://github.com/pingcap/tidb-operator/blob/f9418af1581b11c5774c8537359c49ad64f3cc52/examples/advanced/tidb-cluster.yaml#L896

need to be 

```
log = "/data0/logs/somelog"
```

otherwise, will get error
![image](https://user-images.githubusercontent.com/49771587/117438374-104cef80-af64-11eb-8d5d-73fef01a39d8.png)

looks related to use "|", when value is string need to be quoted

**Comment by DanielZhangQD** [comment]
@swartz-k Thanks a lot for reporting this issue!

Would you like to submit PR to fix this?

**Comment by swartz-k** [comment]
> @swartz-k Thanks a lot for reporting this issue!
> 
> Would you like to submit PR to fix this?

Sure. I will check if there are any problems like this.
