### ISSUE TITLE
No TIDB after operator & cluster were created using helm

### ISSUE THREAD

**Issue by fzhan** [pingcap/tidb-operator#3978]
## Bug Report

**What version of Kubernetes are you using?**
1.20.4

**What version of TiDB Operator are you using?**
1.1.12

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
rook-cephfs

**What's the status of the TiDB cluster pods?**

NAME | READY | STATUS | RESTARTS | AGE | IP | NODE | NOMINATED   NODE | READINESS   GATES
-- | -- | -- | -- | -- | -- | -- | -- | --
tidb-controller-manager-d9c76b574-z6694 | 1/1 | Running | 0 | 77m | 10.1.245.14 | s2.n.local | &lt;none&gt; | &lt;none&gt;
tidb-scheduler-74b466874d-vdlfv | 2/2 | Running | 0 | 77m | 10.1.11.170 | node14.n.local | &lt;none&gt; | &lt;none&gt;
tidb-cl-p75hgq-monitor-5fcf55cc79-nbx6z | 3/3 | Running | 0 | 4m25s | 10.1.140.169 | master.n.local | &lt;none&gt; | &lt;none&gt;
tidb-cl-p75hgq-discovery-97d74758b-26cvz | 1/1 | Running | 0 | 4m20s | 10.1.0.115 | node15.n.local | &lt;none&gt; | &lt;none&gt;
tidb-cl-p75hgq-pd-0 | 1/1 | Running | 0 | 4m25s | 10.1.140.170 | master.n.local | &lt;none&gt; | &lt;none&gt;
tidb-cl-p75hgq-pd-1 | 1/1 | Running | 0 | 4m24s | 10.1.0.116 | node15.n.local | &lt;none&gt; | &lt;none&gt;
tidb-cl-p75hgq-pd-2 | 1/1 | Running | 2 | 4m24s | 10.1.11.172 | node14.n.local | &lt;none&gt; | &lt;none&gt;
tidb-cl-p75hgq-tikv-0 | 1/1 | Running | 0 | 3m39s | 10.1.2.17 | s3.n.local | &lt;none&gt; | &lt;none&gt;
tidb-cl-p75hgq-tikv-1 | 1/1 | Running | 0 | 3m39s | 10.1.11.173 | node14.n.local | &lt;none&gt; | &lt;none&gt;
tidb-cl-p75hgq-tikv-2 | 1/1 | Running | 0 | 3m39s | 10.1.243.12 | s1.n.local | &lt;none&gt; | &lt;none&gt;

**What did you do?**
helm3 install, tikv and pd are ready, but tidb is not being created.

**What did you expect to see?**
tidb created after tikv & pd are ready

**What did you see instead?**
there's no pod created for tidb

**Comment by DanielZhangQD** [comment]
@fzhan 
1. The `tidb-cluster` chart has been abandoned since v1.1.0, please check detail in https://docs.pingcap.com/tidb-in-kubernetes/dev/notes-tidb-operator-v1.1.
2. Please change to the TidbCluster CR, if TiDB Pods are not created after that, please check the logs of `tidb-controller-manager` Pods.
