### ISSUE TITLE
Upgrade Go version to 1.16

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb-operator#3988]
## Development Task

So far, TiDB Operator development uses Go 1.13 which is end of life for a while. Also for supporting running on Apple M1 silicon, it is required to upgrade to 1.16.

@CadmusJiang and @zhouqiang-cl are in charge for upgrading Go version to 1.16 and most of validation works are done manually. Hopefully we get it done in this month.

This also supports TiDB stacks to upgrade Go version to 1.16 pingcap/tidb#22198

**Comment by tisonkun** [comment]
@CadmusJiang @purelind any updates?

**Comment by purelind** [comment]
@tisonkun  @csuzhangxc  Part of github action workflow already update，rest of ci will take some time to test before upgrade go version in ci

**Comment by tisonkun** [comment]
@purelind is there a schedule, e.g., before July 1st, that we plan to upgrade all pipeline and can do `go.mod` changes?

**Comment by tisonkun** [comment]
@purelind any updates?

**Comment by csuzhangxc** [comment]
we are pausing this now.

**Comment by feitian124** [comment]
> we are pausing this now.

may i ask why? BTW, hello from csu

**Comment by csuzhangxc** [comment]
> @csuzhangxc can you elaborate a bit on "any contributions"? It's hard to guess which contributions you looking for for update go version to 1.16. Update the config? Modify CI pipelines? Or other blockers.

we need to upgrade CI both for UT and E2E, and may have some problems for E2E (not tested yet)

**Comment by DanielZhangQD** [comment]
Trace the go version upgrade in https://github.com/pingcap/tidb-operator/issues/4474.
