### ISSUE TITLE
Add Pod Annotation Spec for Discovery component

### ISSUE THREAD

**Issue by handlerww** [pingcap/tidb-operator#4012]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Components such as PD, TiDB, TiKV have already supported set annotations by tc.Spec.Annotations. However, Discovery doesn't support this, we need to add this configuration.
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
Refer to #3892.

**Comment by DanielZhangQD** [comment]
The following components should be covered:

- Discovery for TidbCluster
- Discovery for DmCluster
- `spec.labels` for TidbMonitor
- TidbInitializer
