### ISSUE TITLE
Dynamic update tidbmonitor when prometheus configuration update.

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#4020]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Dynamic update tidbmonitor when prometheus or grafana configuration changed.

**Describe the feature you'd like:**
I think we can add a field called `revision` into `spec` and `status`.
When configuration changed, we can generate new revision hash value and set it to `spec` revision field. The tidbmonitor  find the status and spec field value not equal, it can trigger sts recreating.

**Comment by DanielZhangQD** [comment]
We can add a prefix to the configmap of the TidbMonitor as we're doing for PD, etc. so that the Pod will be rolling updated after configuration change.

**Comment by DanielZhangQD** [comment]
After further investigation, we can add a sidecar to watch for the configuration files and if any changes, call the reload API of Prometheus to reload the configs.

**Comment by mikechengwei** [comment]
Currently we use `KeyToPath` method to mount the grafana and prometheus configuration, it does not allow us to hot update the configmap.
Ref:
https://github.com/pingcap/tidb-operator/blob/06bebe64c518a85cfe7fe1b1623cdfdad8d5f045/pkg/monitor/monitor/util.go#L693

If we adopt the sidecar approach, we need to split the grafana and prometheus configuration into two configmaps in order to use the configmap hot update mechanism.  wdyt? @DanielZhangQD
