### ISSUE TITLE
tikv should contain monitor port on spec.containers.port

### ISSUE THREAD

**Issue by gejibin** [pingcap/tidb-operator#4021]
### tikv should contain monitor port (20180) on spec.containers.port, like tidb and tiflash:
    name: tiflash
    ports:
    - containerPort: 8234
      name: metrics
      protocol: TCP

    name: tidb
    ports:
    - containerPort: 10080
      name: status
      protocol: TCP

**Comment by DanielZhangQD** [comment]
@gejibin Try `tc.Spec.TiKV.EnableNamedStatusPort` in https://github.com/pingcap/tidb-operator/pull/3875 from v1.1.12.

**Comment by DanielZhangQD** [comment]
@gejibin Feel free to reopen this issue if any more questions.
