### ISSUE TITLE
apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition

### ISSUE THREAD

**Issue by RogueJin** [pingcap/tidb-operator#4032]
## Bug Report
apiextensions.k8s.io/v1beta1 is deprecated, is there any plan to replace with v1?

**What version of Kubernetes are you using?**
1.20

**What did you do?**
kubectl apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/v1.1.12/manifests/crd.yaml

**What did you expect to see?**
no warning messages

**What did you see instead?**
![image](https://user-images.githubusercontent.com/21214103/122342977-cb12d900-cf77-11eb-9aa7-9d7cf93f768a.png)

**Comment by DanielZhangQD** [comment]
Duplicate with https://github.com/pingcap/tidb-operator/issues/2753.
