### ISSUE TITLE
Support PriorityClass on Backup jobs

### ISSUE THREAD

**Issue by lorqor** [pingcap/tidb-operator#4052]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Without a priorityClass, the backup pods could be evicted during the backup and cause the backup process to fail.

**Describe the feature you'd like:**
Should either allow the user to specify a priorityClass or default a higher priorityClass to the backup jobs.

**Describe alternatives you've considered:**
Add in the documentation saying that this a possible failure, and add diagnosis and mitigation steps.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
@lorqor Thanks for reporting this issue!
Would you like to help submit PR for this improvement?
