### ISSUE TITLE
Helm Chart Errors

### ISSUE THREAD

**Issue by ttadeo** [pingcap/tidb-operator#4069]
Using the latest TiDB Operator 1.1.13

It seems our Helm Chart needs to be looked at. I can deploy the tidb-cluster but get these Helm Erroros:
 helm repo update
Hang tight while we grab the latest from your chart repositories...
index.go:339: skipping loading invalid entry for chart "tidb-backup" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-backup" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-backup" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-cluster" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-cluster" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-cluster" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-drainer" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-drainer" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-drainer" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-lightning" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-lightning" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-lightning" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-operator" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-operator" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tidb-operator" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tikv-importer" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tikv-importer" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
index.go:339: skipping loading invalid entry for chart "tikv-importer" "nightly" from https://charts.pingcap.org/: validation: chart.metadata.version "nightly" is invalid
...Successfully got an update from the "pingcap" chart repository

**Comment by DanielZhangQD** [comment]
We should also skip `nightly` in the code [here](https://github.com/pingcap/tidb-operator/blob/master/ci/release_tidb_operator_binary_and_image.groovy#L66).
