### ISSUE TITLE
Improve the performance of cleanup backup files

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#4073]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, when we clean up the backup files in the S3/GCS, the objects are deleted one by one, refer to the code [here](https://github.com/pingcap/tidb-operator/blob/master/cmd/backup-manager/app/clean/clean.go#L40), however, when the data scale is very big, there may be 1 Million files for just one backup, which will take a very long time to clean one backup.
So we should find a better way to speed up the clean-up operation.
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by SunRunAway** [comment]
Worth considering: https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html
