### ISSUE TITLE
TidbMonitor.prometheus.reserveDays may too long

### ISSUE THREAD

**Issue by better0332** [pingcap/tidb-operator#4084]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**
master

**What did you expect to see?**
add retentionTime overwrite reserveDays, if I set remoteWrite

**What did you see instead?**
reserveDays may too long, min is 1d

**Comment by mikechengwei** [comment]
Refer:
`apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: basic
spec:  
 prometheus:
    reserveDays: 12
`
