### ISSUE TITLE
Better local volume setup and operation documentation

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#410]

**Comment by weekface** [comment]
We may supply a shell script to reduce usage complexity, something like this:

```
$ pv-manager <device-name> <options>
```

<device-name> is the device on the host, for example: `/dev/nvme`
<options> includes:
- --shared bool
- --volume-count int
- --storage-class string

For example:

```
pv-manager /dev/nvme --shared --volume-count=3 --storage-class=shared-nvme-disks
```

The `/dev/nvme` will be formatted and mount to `/shared-nvme-disks/disk0`, and these directories will be created and bind mounted:

```
$ mkdir /shared-nvme-disks/disk0

$ mkdir /shared-nvme-disks/disk0/local-pv01
$ mkdir /shared-nvme-disks/disk0/local-pv02
$ mkdir /shared-nvme-disks/disk0/local-pv03

$ mkdir /mnt/shared-nvme-disks/local-pv01
$ mkdir /mnt/shared-nvme-disks/local-pv02
$ mkdir /mnt/shared-nvme-disks/local-pv013

$ cat /etc/fstab
/dev/nvme /shared-nvme-disks/disk0     ext4    noatime,nodelalloc 0 0
/shared-nvme-disks/disk0/local-pv01 /mnt/shared-nvme-disks/local-pv01 none bind 0 0
/shared-nvme-disks/disk0/local-pv02 /mnt/shared-nvme-disks/local-pv02 none bind 0 0
/shared-nvme-disks/disk0/local-pv03 /mnt/shared-nvme-disks/local-pv03 none bind 0 0
```

@tennix @xiaojingchen @onlymellb @aylei @cofyc

**Comment by cofyc** [comment]
通用的文档和脚本打算维护在 local-static-provisioner 项目里

- https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/76
- https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/81

**Comment by cofyc** [comment]
Open an issue for scripts: https://github.com/pingcap/tidb-operator/issues/417.
