### ISSUE TITLE
Use securityContext for sysctl instead of running as privileged

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-operator#4137]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Some init containers in TiDB/TiKV run as `privileged`.

If all the initContainer does is use sysctl to set some keep alive flags, since k8s 1.11, the preferred way to do this is to set sysctl attributes in the pod’s securityContext. This prevents the need for the privileged initContainer. See: https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#setting-sysctls-for-a-pod

**Comment by DanielZhangQD** [comment]
@kolbe Thanks for reporting this issue!
Set the security context requires the configurations of Kubelet:
`Warning: If you allow unsafe sysctls via the allowedUnsafeSysctls field in a PodSecurityPolicy, any pod using such a sysctl will fail to start if the sysctl is not allowed via the --allowed-unsafe-sysctls kubelet flag as well on that node.`

However, in some Kubernetes env, we cannot update the Kubelet options so we just use the privileged init containers.

**Comment by DanielZhangQD** [comment]
If you're sure that all the unsafe sysctls have been allowed in the --allowed-unsafe-sysctls kubelet flag, just remove the `tc.spec.tidb/tikv.annotations.tidb.pingcap.com/sysctl-init: "true"`, then it will not create the privileged init container and just leverage the securityContext functionality.
