### ISSUE TITLE
Provide examples of istio and tidb operator integration

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#4150]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Istio is an open platform for providing a uniform way to integrate microservices, manage traffic flow across microservices, enforce policies and aggregate telemetry data.
We can use the capabilities of istio to build a proxy layer on top of the tidb computing layer,so the first step we should provide an example.

**Describe the feature you'd like:**
 An example of istio and tidb operator integration.

**Comment by rahilsh** [comment]
@mikechengwei please apply the changes mentioned in https://github.com/pingcap/tidb-operator/pull/4445 manually and let us know if it is working for you

**Comment by rahilsh** [comment]
Added steps to try it out on https://github.com/pingcap/tidb-operator/pull/4445#issuecomment-1055220399
