### ISSUE TITLE
Operator can't work in Kubernetes 1.22.1

### ISSUE THREAD

**Issue by KanShiori** [pingcap/tidb-operator#4154]
## Bug Report

**What version of Kubernetes are you using?**

v1.22.1

**What version of TiDB Operator are you using?**

v1.2.1

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

local storage

**What's the status of the TiDB cluster pods?**

**What did you do?**

Deploy TiDBOperator

**What did you expect to see?**

**What did you see instead?**
TiDBOperator controller-manager log
```
I0824 03:19:47.860466       1 reflector.go:158] Listing and watching *v1beta1.Ingress from k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96
E0824 03:19:47.864918       1 reflector.go:123] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)
```

Ref: https://kubernetes.io/blog/2021/08/04/kubernetes-1-22-release-announcement/#removal-of-several-deprecated-beta-apis

**Comment by sergeyshaykhullin** [comment]
@KanShiori I am getting the same error on `v1.22.3+k3s1` and `v1.2.4`

Controller manager is spamming with

```
E1123 14:02:47.051344       1 reflector.go:123] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)
E1123 14:02:48.056068       1 reflector.go:123] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)
E1123 14:02:49.060782       1 reflector.go:123] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)
```

**Comment by KanShiori** [comment]
> @KanShiori I am getting the same error on `v1.22.3+k3s1` and `v1.2.4`
> 
> Controller manager is spamming with
> 
> ```
> E1123 14:02:47.051344       1 reflector.go:123] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)
> E1123 14:02:48.056068       1 reflector.go:123] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)
> E1123 14:02:49.060782       1 reflector.go:123] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)
> ```

It will be fixed by v1.3.0, you can use the master branch at present.

**Comment by sergeyshaykhullin** [comment]
I am using helm, can i use master version somehow?

**Comment by KanShiori** [comment]
> I am using helm, can i use master version somehow?

You can change image version to nightly in the [value.yaml](https://github.com/pingcap/tidb-operator/blob/ea98b7d77357b232094196db4acbcb790c99588a/charts/tidb-operator/values.yaml), then use `helm install <name> ./charts` to deploy.
