### ISSUE TITLE
The way to deploy tikv+pd without tidb

### ISSUE THREAD

**Issue by sergeyshaykhullin** [pingcap/tidb-operator#4196]
## Question

Lately i found tikv-operator to deploy tikv+pd only, but it seems out of date https://github.com/tikv/tikv-operator

This repo has some useful helm charts for tidb stack/tidb operator, but not for tikv+pd

What is the preferred way to deploy and operate on tikv separately from tidb inside k8s?

**Comment by mikechengwei** [comment]
TiDB-Operator also can deploy and manage tikv component，just to set tidb replica as zero value. Refer #1325

**Comment by DanielZhangQD** [comment]
@mikechengwei @sergeyshaykhullin You can deploy TiKV+PD with TiDB Operator, just do not configure `spec.tidb` in the TidbCluster CR.

**Comment by sergeyshaykhullin** [comment]
@mikechengwei @DanielZhangQD Am i right that if i not specify tidb section - no recources from tidb will apply? (Services, Roles, Bindings, Statefulsets, Secrets, Configmaps)

But if i set tidb replicas to 0 i will have tidb sts with replicas 0 and all relates manifests?

**Comment by DanielZhangQD** [comment]
> Am i right that if i not specify tidb section - no recources from tidb will apply? (Services, Roles, Bindings, Statefulsets, Secrets, Configmaps)
Yes.

**Comment by sergeyshaykhullin** [comment]
Thanks!

**Comment by sergeyshaykhullin** [comment]
Hmm, why does tidb-operator helm chart is not installing crds?

**Comment by mikechengwei** [comment]
Ref: https://docs.pingcap.com/tidb-in-kubernetes/stable/get-started#install-tidb-operator-crds.
You need to apply crd yaml manually.

**Comment by mikechengwei** [comment]
@sergeyshaykhullin

**Comment by sergeyshaykhullin** [comment]
Yes, but it also can be a `crds` folder inside tidb-operator helm chart and values.yaml with `installCrds: false # by default to not to have breaking changes`, because they are required for its operation and can be deployed together https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

It will have some benefits:
1. Built-in crds - easier installation. No crds files inside CD/infrastructure automation tools, no downloads from network
2. Crds versioning - each helm chart version will have its own fully compatible crds with current tidb-operator version
3. Conditional consistent crds+operator deletion - uninstalling tidb-operator helm chart with `installCrds: true` can also delete all related crds

**Comment by DanielZhangQD** [comment]
@sergeyshaykhullin 
Thanks for your suggestion!
Even if we install the CRD when installing the helm chart, we still:
1. Upgrade the crd manually during the upgrade, which is a more frequent operation
2. Sometimes, we do not want to delete the crd when we uninstall the tidb-operator, for example, the incompatible issue https://docs.pingcap.com/tidb-in-kubernetes/dev/release-1.2.0-beta.1#compatibility-changes
