### ISSUE TITLE
Pods restart without new configmap auto generated just now

### ISSUE THREAD

**Issue by clementshawn** [pingcap/tidb-operator#4199]
## Problem report

Description: Pods run with old configmap, however the new configmap has been generated just now.

### version
kubernetes: 1.18.8-aliyun.1
tidb-operator: 1.2.3
advanced-statefulset: true
tidbcluster: 5.2.0

**Comment by DanielZhangQD** [comment]
@clementshawn Sorry for the late response.
Could you please describe this issue in more detail?
What did you do?
And what's your expection?
