### ISSUE TITLE
typo in `google-kubernetes-tutorial.md`

### ISSUE THREAD

**Issue by chux0519** [pingcap/tidb-operator#42]
typo in [doc](https://github.com/pingcap/tidb-operator/blob/master/docs/google-kubernetes-tutorial.md#enable-api-acess)

acess may be access ?

**Comment by tennix** [comment]
Nice catch! Could you send us a PR to fix this? You can follow [CONTRIBUTING guide](https://github.com/pingcap/tidb-operator/blob/master/docs/CONTRIBUTING.md) for how to contribute.

**Comment by chux0519** [comment]
sure, I will send a PR for this
