### ISSUE TITLE
podSecurityContext sysctls are not allowed while sysctl-init is true or privileged is true

### ISSUE THREAD

**Issue by clementshawn** [pingcap/tidb-operator#4200]
## Question

First depolyed using operator-1.1.12 with annotations: tidb.pingcap.com/sysctl-init: 'true' works fine, after upgrade to operator-1.2.3, the annotation didn't work, k8s events notify that unsafe sysctl is not allowed, and the same with privileged is true.

### versions
kubernetes: 1.18.8-aliyun.1
tidb-operator: 1.2.3
advanced-statefulset: true
tidbcluster: 5.2.0

**Comment by DanielZhangQD** [comment]
@clementshawn
Was the init container created?
Could you please show the result of describing the TiDB Pod?
