### ISSUE TITLE
Enable useNodeNameOnly in local-volume-provisioner deployment

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#421]
If by accident kubernetes node object has been recreated, new node object with the same name for the same node will get a new UID. By default, provisioner includes node.UID in its name, it will filter out local PVs that were not created with this name and [do not reclaim these PVs](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/faqs.md#pv-with-delete-reclaimpolicy-is-released-but-not-going-to-be-reclaimed).

**Comment by cofyc** [comment]
I'll close this. It's better to enable `useNodeNameOnly` but it's not safe to change this field. When `useNodeNameOnly` is changed to `true` from `false`, old PVs will not be managed by provisioner. If we set `useNodeNameOnly: true` in provisioner yaml file. I'm afraid our users may upgrade the configuration by accident.

**Comment by gregwebs** [comment]
@cofyc we need to at least document the best practices even if they are not the default.

I still suggest making this the default since we are still pre GA. Now is our last chance to make breaking changes.

**Comment by cofyc** [comment]
closing, see discussion [here](https://github.com/pingcap/tidb-operator/pull/703#issuecomment-516231202).
