### ISSUE TITLE
Support reschedule a specified tikv pod and auto transfer leader before deletion

### ISSUE THREAD

**Issue by liubog2008** [pingcap/tidb-operator#4215]
## Feature Request

**Is your feature request related to a problem? Please describe:**

A tikv pod with EBS is hard to restarted gracefully.

**Describe the feature you'd like:**

1. transfer leader before tikv pod deletion
2. delete a specified tikv pod
2. rebalance after new tikv pod is started

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
Please also cover the case where the user wants to restart one Pod.
