### ISSUE TITLE
backupschedule two backup running at the same time

### ISSUE THREAD

**Issue by jiyfhust** [pingcap/tidb-operator#4220]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

v1.1.12
i think there exsits the same problem on the newest code.

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

1. create backupschedule, let it have some backups
2. pause backupschedule by set backupschedule.Spec.Pause = true
3. wait enough time when all the backup should be cleaned by config.backupschedule.Spec.MaxReservedTime
4. restart backupschedule by set backupschedule.Spec.Pause = false

**What did you expect to see?**

as i do that, what i see should be like this:
1.a new backup is created because it should be schedule again
2.all old backups should be cleaned because it execeed the MaxReservedTime
3. backupschedule.Status.Last-Backup should be the new backup

**What did you see instead?**

* backupschedule.Status.Last-Backup is nil
* backupschedule.Status.All-Backup-Clean-Time is set 

because the last-backup is nil, although there is a backup is running, after next sched time, it can not check the running backup, and create a new backup again.

then two backup running together.

**Comment by DanielZhangQD** [comment]
@jiyfhust Thanks for the analysis!
Could you please help submit PR to fix this issue?

**Comment by jiyfhust** [comment]
> @jiyfhust Thanks for the analysis! Could you please help submit PR to fix this issue?

OK，i'm glad to have a try to fix it.
