### ISSUE TITLE
tidb in heterogeneous cluster won't start if `clusterDomain` is defined

### ISSUE THREAD

**Issue by hihihuhu** [pingcap/tidb-operator#4246]
## Bug Report

**What version of Kubernetes are you using?**
v1.17.14

**What version of TiDB Operator are you using?**
latest master

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
inrelevant

**What's the status of the TiDB cluster pods?**
inrelevant

**What did you do?**
start a heterogeneous cluster with tidb only with `clusterDomain` defined

**What did you expect to see?**
tidb could start

**What did you see instead?**
tidb won't start

the startup script tries to verify the pd address with the discovery service if `clusterDomain` is defined https://github.com/pingcap/tidb-operator/blob/v1.2.4/pkg/manager/member/template.go#L52

however, there is no discovery service for the heterogeneous cluster as it doesn't have pd defined https://github.com/pingcap/tidb-operator/blob/v1.2.4/pkg/manager/member/tidb_discovery_manager.go#L64

thus, the startup script in stuck at https://github.com/pingcap/tidb-operator/blob/v1.2.4/pkg/manager/member/template.go#L57

**Comment by KanShiori** [comment]
Seem to be an issue. Did you have to set `clusterDomain` ?

**Comment by KanShiori** [comment]
`clusterDomain` is used to deploy tidb across multi Kubernetes, so it may not work in other scenarios now

**Comment by hihihuhu** [comment]
we do use `clusterDomain` for the main tidb cluster, but don't need it for the heterogeneous one as it is tidb only and this should be a low priority.

**Comment by mikechengwei** [comment]
I think heterogeneous cluster should rely on main tidb cluster discovery service. So, should we set the cluster name env of the heterogeneous cluster as the name of the main cluster? @DanielZhangQD

**Comment by DanielZhangQD** [comment]
> I think heterogeneous cluster should rely on main tidb cluster discovery service. So, should we set the cluster name env of the heterogeneous cluster as the name of the main cluster? @DanielZhangQD

@mikechengwei Yes, we should use the discovery service for the original cluster for the heterogeneous clusters when clusterDomain is configured.
What about we add a new env for the heterogeneous clusters?
Would you like to submit PR for this?

**Comment by KanShiori** [comment]
The issue is fixed by PR #4387, so close it
