### ISSUE TITLE
The Real replicas of TiKV more than what I set in the TiDBCluster.

### ISSUE THREAD

**Issue by hykych** [pingcap/tidb-operator#4268]
## Bug Report

**What version of Kubernetes are you using?**
v1.19.9

**What version of TiDB Operator are you using?**
v1.1.9

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
ssd-storage for tikv
shared-ssd-storage for pd

**What's the status of the TiDB cluster pods?**
they are all running.

**What did you do?**
try to scale in and scale out the tikv of TiDBCluster

**What did you expect to see?**
try to make the replicas of the TiKV statefulset is the same as the replicas set in TiDBCluster.

**What did you see instead?**
the real replicas of the TiKV always has one more than what I set.

At first I found the statefulset scale from 30 to 31 by itself, and then it keeps to 31. 
so I try to set the replicas to 29, but it scale in to 30 from 31.
`prod-tikv, ordinal: 30 (replicas: 30, delete slots: [])`
I view on the dashboard that all stores are normal.

it's weird when I run the command: `kubectl get tidbcluster prod -o yaml`
![image](https://user-images.githubusercontent.com/10421724/142385243-4253a051-be38-4636-a38f-a91e55ca02e2.png)
the desired number is 29, but the ready number is 30.

**Comment by KanShiori** [comment]
maybe have triggered a failover.
see doc: https://docs.pingcap.com/tidb-in-kubernetes/stable/use-auto-failover#failover-with-tikv

**Comment by hykych** [comment]
@KanShiori fix it. thank you so much.
