### ISSUE TITLE
Error occurred when running `kubectl apply`

### ISSUE THREAD

**Issue by sukkiCat** [pingcap/tidb-operator#4275]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
**What version of TiDB Operator are you using?**

```
Defaulted container "tidb-scheduler" out of: tidb-scheduler, kube-scheduler
TiDB Operator Version: version.Info{GitVersion:"v1.2.4", GitCommit:"684ce274555ac739a58c6ed07ff673a2d98a5429", GitTreeState:"clean", BuildDate:"2021-10-21T03:22:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

```
NAME                 PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
standard (default)   k8s.io/minikube-hostpath   Delete          Immediate           false                  8m52s

sukki_qin@cloudshell:~$ kubectl get pvc -n tidb-admin
No resources found in tidb-admin namespace.
```
**What's the status of the TiDB cluster pods?**

```
sukki_qin@cloudshell:~$ kubectl get po -n tidb-admin -o wide
NAME                                       READY   STATUS             RESTARTS        AGE   IP           NODE       NOMINATED NODE   READINESS GATES
tidb-controller-manager-7c79b4567c-lmd7w   1/1     Running            0               10m   172.17.0.3   minikube   <none>           <none>
tidb-scheduler-759b84cd6d-5zpw2            1/2     CrashLoopBackOff   6 (4m18s ago)   10m   172.17.0.4   minikube   <none>           <none>
```
**What did you do?**

I've tried to deploy a test cluster using minikube following the instruction of https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/get-started#%E4%BD%BF%E7%94%A8-minikube-%E5%88%9B%E5%BB%BA-kubernetes-%E9%9B%86%E7%BE%A4
**What did you expect to see?**
```
customresourcedefinition.apiextensions.k8s.io/tidbclusters.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/backups.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/restores.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/backupschedules.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/tidbmonitors.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/tidbinitializers.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/tidbclusterautoscalers.pingcap.com created

```
**What did you see instead?**
```
customresourcedefinition.apiextensions.k8s.io/backupschedules.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/backups.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/dmclusters.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/restores.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/tidbclusterautoscalers.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/tidbinitializers.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/tidbmonitors.pingcap.com created
The CustomResourceDefinition "tidbclusters.pingcap.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**Comment by csuzhangxc** [comment]
@sukkiCat I'm sorry for the late reply.

1. as you're using Kubernetes v1.22.2, we no longer recommend using `tidb-scheduler`, so I think you can disable it when deploying the TiDB Operator.
2. for Kubernetes v1.22.2, some issues we've fixed recently (see #4151) and will be released in TiDB Operator v1.3. so, can you use a lower version of Kubernetes for the testing now?

**Comment by KanShiori** [comment]
If you want to test operator in Kubernetes v1.22, you can use the master branch.

You can change image version to nightly in the [value.yaml](https://github.com/pingcap/tidb-operator/blob/ea98b7d77357b232094196db4acbcb790c99588a/charts/tidb-operator/values.yaml), then use `helm install <name> ./charts` to deploy.

**Comment by KanShiori** [comment]
About this issue, because v1 CRDs is too big, so you have to use `kubectl create` or `kubectl replace` to deploy CRD.  
```
customresourcedefinition.apiextensions.k8s.io/backupschedules.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/backups.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/dmclusters.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/restores.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/tidbclusterautoscalers.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/tidbinitializers.pingcap.com created
customresourcedefinition.apiextensions.k8s.io/tidbmonitors.pingcap.com created
The CustomResourceDefinition "tidbclusters.pingcap.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**Comment by DanielZhangQD** [comment]
The doc has been updated and the master branch has supported v1.22.

**Comment by mfmarche** [comment]
I'm hitting this issue as well (CRDs is too big). I think the comment above implies that I have to use create or replace, and never apply. However, this appears to be outside the normal workflow of kubectl (for the purpose of finding differences in changes). Does this suggest that the annotations/CRD is too large and maybe the data should be stored in someother means?

**Comment by DanielZhangQD** [comment]
@mfmarche It will try to add an annotation with the whole CRD when you `apply` the CRD, however, there is a size limitation for the annotation.

**Comment by donbowman** [comment]
i think what @mfmarche is saying... we need to reduce the size somehow.

It is common practice to install an entire set of yaml in one shot (e.g. CD). So
kubectl apply all.yaml

and all.yaml includes tidb + other unrelated items.

but, tidb, and tidb alone, no longer works w/ kubectl apply. Its not a realistic workaround to say "remove that one, and only use kubectl replace for it". This means we no longer have a declarative system.

is it possible to remove some of the extra information to that it fits?

**Comment by DanielZhangQD** [comment]
@donbowman Not to remove the crd, just to replace it.
BTW, do you have any suggestions for how to reduce the size?

**Comment by donbowman** [comment]
i mean, as part of our workflow, all yaml gets reapplied each time (even if no change).
so now tidb cannot be part of our workflow.

to reduce the size? maybe reduce some comment text in it? kubectl seems to put the entire object as json in an annotation.

**Comment by DanielZhangQD** [comment]
`kubectl replace` cannot be used in your workflow?
 We have already removed the `descriptions` in the CRD.

**Comment by donbowman** [comment]
we generate a single multi-document yaml file, with all of the code for the kubernetes cluster.
this includes all other operators, all other crd, all of our code, etc.
we then call apply. many files will be unchanged, but some will be changed.

this guarantees we are always in sync with the desired state of the entire cluster.

replace is not appropriate for the entire set.

i'm reluctant to remove tidb.

is it the case that tidb no longer works w/ kubectl, and one must move to server-side apply for it?

**Comment by DanielZhangQD** [comment]
It works with `kubectl create/replace`, we will check how to make it fit with `apply`.

**Comment by DanielZhangQD** [comment]
@donbowman Does `kubectl apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/crd.yaml --server-side=true` work for you? The service side apply is enabled by default since Kubernetes v1.16.

**Comment by SamSpiri** [comment]
ended up in this issue while googling my error when using it in combination with terraform.
Adding server_side_apply=true works:
```

locals {
  tidb_operator_version = "v1.5.1"
}

# fetch a raw multi-resource yaml
data "http" "tidb_operator_crds" {
  url = "https://raw.githubusercontent.com/pingcap/tidb-operator/${local.tidb_operator_version}/manifests/crd.yaml"
}

# split raw yaml into individual resources
data "kubectl_file_documents" "tidb_operator_crds" {
  content = data.http.tidb_operator_crds.body
}

# apply each resource from the yaml one by one
resource "kubectl_manifest" "tidb_operator_crds" {
  for_each   = data.kubectl_file_documents.tidb_operator_crds.manifests
  yaml_body  = each.value
  server_side_apply = true
}
```

**Comment by JadeQin** [comment]
I meet the same error.
`The CustomResourceDefinition "tidbclusters.pingcap.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

I exec `kubectl apply  -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/crd.yaml` in k8s v1.21.13

**Comment by csuzhangxc** [comment]
@JadeQin you can use `kubectl create` instead of `kubectl apply`.
