### ISSUE TITLE
`config` field is updated in TidbCluster

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#4298]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Deploy a basic TiDB cluster with TLS enabled
**What did you expect to see?**
The `spec` part in TidbCluster CR is not updated
**What did you see instead?**
The config field is updated as below:
```
  pd:
    baseImage: pingcap/pd
    config: |
      [dashboard]
        internal-proxy = true
        tidb-cacert-path = "/var/lib/tidb-client-tls/ca.crt"
        tidb-cert-path = "/var/lib/tidb-client-tls/tls.crt"
        tidb-key-path = "/var/lib/tidb-client-tls/tls.key"

      [security]
        cacert-path = "/var/lib/pd-tls/ca.crt"
        cert-path = "/var/lib/pd-tls/tls.crt"
        key-path = "/var/lib/pd-tls/tls.key"
```
The certs fields are configured by TiDB Operator automatically, however, they should be set to the PD configurations file without updating the TidbCluster spec except for the default configurations we set explicitly.

**Comment by DanielZhangQD** [comment]
The other components have the similar issue.
We also need to check if any other fields have the similar issue.

**Comment by KanShiori** [comment]
PD, Pump, TiDB and TiKV have this issue.
