### ISSUE TITLE
Can I use hostPath as a data store?

### ISSUE THREAD

**Issue by glyslxq** [pingcap/tidb-operator#4308]
Local PV is too cumbersome to manage

**Comment by just1900** [comment]
Referring to https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/#how-is-it-different-from-a-hostpath-volume,
> The biggest difference is that the Kubernetes scheduler understands which node a Local Persistent Volume belongs to. With HostPath volumes, a pod referencing a HostPath volume may be moved by the scheduler to a different node resulting in data loss. But with Local Persistent Volumes, the Kubernetes scheduler ensures that a pod using a Local Persistent Volume is always scheduled to the same node.

one can't garantee that the pod restart on the previous node

**Comment by glyslxq** [comment]
> Referring to https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/#how-is-it-different-from-a-hostpath-volume,
> 
> > The biggest difference is that the Kubernetes scheduler understands which node a Local Persistent Volume belongs to. With HostPath volumes, a pod referencing a HostPath volume may be moved by the scheduler to a different node resulting in data loss. But with Local Persistent Volumes, the Kubernetes scheduler ensures that a pod using a Local Persistent Volume is always scheduled to the same node.
> 
> one can't garantee that the pod restart on the previous node, which will cause unexpected behavior after pod get restarted.

Our elasticsearch cluster deployment uses hostpath. When a child node is evicted, it can automatically reconstruct data on another machine. Maybe tidb is different. I don't know much about tidb. Thank you for your answer

**Comment by DanielZhangQD** [comment]
@glyslxq I will close this issue for now, feel free to reopen this if any more questions, thanks!
