### ISSUE TITLE
tidb error

### ISSUE THREAD

**Issue by clcc2019** [pingcap/tidb-operator#4351]
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/46099295/148372084-34af05d5-485b-4d24-8af1-f14915e823fa.png">

<img width="939" alt="image" src="https://user-images.githubusercontent.com/46099295/148372116-224c10a4-c6bb-44f4-a8ea-014a7935f72b.png">

**Comment by DanielZhangQD** [comment]
@clcc2019 You're using TiDB v5.3.0, right?
@tiancaiamao is checking this issue.

**Comment by DanielZhangQD** [comment]
Fixed in https://github.com/pingcap/tidb/pull/31081.
