### ISSUE TITLE
no tidb cluster in grafana 

### ISSUE THREAD

**Issue by clcc2019** [pingcap/tidb-operator#4357]
<img width="619" alt="image" src="https://user-images.githubusercontent.com/46099295/148503265-65f13a25-f9bb-4b84-a4f3-886577e7d28b.png">
<img width="953" alt="image" src="https://user-images.githubusercontent.com/46099295/148503331-ed9258ea-bf36-44a1-b579-6d20c050576a.png">
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/46099295/148503448-d76b3b40-7e3b-4034-b93d-5c3e28c52a23.png">

**Comment by DanielZhangQD** [comment]
Could you please share the TiDB Operator version, the yaml of TidbCluster and TidbMonitor?

**Comment by clcc2019** [comment]
> Could you please share the TiDB Operator version, the yaml of TidbCluster and TidbMonitor?

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/46099295/148513976-0720333f-5634-4642-928a-5605d8557e8b.png">

install tidb crd and operator

use helm install tidb-cluster

**Comment by DanielZhangQD** [comment]
The helm chart for tidb-cluster has been deprecated since v1.1.0.
Please check https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/deploy-on-general-kubernetes to install TiDB cluster and check https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/monitor-a-tidb-cluster to deploy TiDB Monitor.
