### ISSUE TITLE
Is tidb upgrade need to check pod ready？

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#4366]
## Bug Report

**What did you do?**
Now tidb upgrade not check pod ready.Do we need to add this step to avoid ambiguity?Although we check tc.Status.TiDB.Member health status.

Ref:
https://github.com/pingcap/tidb-operator/blob/9eb0658f655986d8afbe22f154e005ac114dc962/pkg/manager/member/tidb_upgrader.go#L102

**What did you expect to see?**

**What did you see instead?**

**Comment by DanielZhangQD** [comment]
@mikechengwei The check of member health for TiDB is more strict than the Pod ready, so it should be OK for the current logic.

**Comment by DanielZhangQD** [comment]
@mikechengwei Sorry, it's possible that even if the member is healthy the endpoint is not ready yet.
Please also help check Pod ready for DM master, PD, TiCDC in addition to TiDB.

**Comment by mikechengwei** [comment]
> @mikechengwei Sorry, it's possible that even if the member is healthy the endpoint is not ready yet. Please also help check Pod ready for DM master, PD, TiCDC in addition to TiDB.

ok,i will optimize together.
