### ISSUE TITLE
e2e for across Kubernetes deployment is not stable enough

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#4368]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
https://ci.pingcap.net/blue/organizations/jenkins/tidb-operator-pull-e2e-kind-across-kubernetes/detail/tidb-operator-pull-e2e-kind-across-kubernetes/349/tests

**Comment by DanielZhangQD** [comment]
https://ci.pingcap.net/blue/organizations/jenkins/tidb-operator-pull-e2e-kind-across-kubernetes/detail/tidb-operator-pull-e2e-kind-across-kubernetes/352/tests

**Comment by DanielZhangQD** [comment]
https://ci.pingcap.net/blue/organizations/jenkins/tidb-operator-pull-e2e-kind-across-kubernetes/detail/tidb-operator-pull-e2e-kind-across-kubernetes/361/tests

**Comment by DanielZhangQD** [comment]
https://ci.pingcap.net/blue/organizations/jenkins/tidb-operator-pull-e2e-kind-across-kubernetes/detail/tidb-operator-pull-e2e-kind-across-kubernetes/365/tests

**Comment by DanielZhangQD** [comment]
https://ci.pingcap.net/blue/organizations/jenkins/tidb-operator-pull-e2e-kind-across-kubernetes/detail/tidb-operator-pull-e2e-kind-across-kubernetes/367/tests

**Comment by just1900** [comment]
Seems like most cases failed because of status check, will fix this ASAP.
