### ISSUE TITLE
Can operator support 3.x tidb cluster?

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#4385]
## Bug Report

**What version of Kubernetes are you using?**
1.20.1

**What version of TiDB Operator are you using?**
master

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**
basic-discovery-7957595645-pr98s   1/1     Running            0          8m40s
basic-pd-0                         1/1     Running            0          8m40s
basic-tikv-0                       0/1     CrashLoopBackOff   4          3m23s

![image](https://user-images.githubusercontent.com/13257127/150673270-8674a8b9-71dd-4e91-89ea-bb4e97066fc5.png)

**What did you do?**
Deploy a tidb cluster with v3.0.20 version.
**What did you expect to see?**
The cluster can't run.

**What did you see instead?**
The cluster can run.

**Comment by DanielZhangQD** [comment]
Set `spec.enableDynamicConfiguration: false`.
