### ISSUE TITLE
runmode=debug support for TiFlash pods

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/tidb-operator#4393]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

`runmode=debug` support for TiFlash pods. https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/tips/#%E8%AF%8A%E6%96%AD%E6%A8%A1%E5%BC%8F

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
We can also support TiCDC and Pump.
