### ISSUE TITLE
Add tolerations onto pods of tidb cluster

### ISSUE THREAD

**Issue by mathspanda** [pingcap/tidb-operator#44]
Pods of tidb clusters are necessary to be deployed on dedicated nodes under certain scenarios. Some taints may be added to these dedicated nodes to ensure that other pods will not be scheduled onto them. So maybe we should apply corresponding tolerations to tidb pods?

**Comment by weekface** [comment]
Yes, operator should allow users to add tolerations to TiDB pods.

**Comment by weekface** [comment]
@mathspanda Could you send us a PR to add this feature? You can follow [CONTRIBUTING](https://github.com/pingcap/tidb-operator/blob/master/docs/CONTRIBUTING.md) guide for how to contribute.

**Comment by mathspanda** [comment]
sure, i will send a PR.

**Comment by weekface** [comment]
Close in favor of #49
