### ISSUE TITLE
sync failed failed to get tc 

### ISSUE THREAD

**Issue by donbowman** [pingcap/tidb-operator#4414]
## Question

tidb-operator v1.3.0
tikv/pd/tidb v5.4.0
kubernetes v1.19.16

I am seeing a constant scrolling of these messages:
```
[tidb-controller-manager-d89ff9c6c-g5f4k] E0215 21:33:34.339259       1 pod_control.go:139] TidbCluster pod: tidb/db-tikv-2, sync failed failed to get tc "tidb/tidb-shared": tidbcluster.pingcap.com "tidb-shared" not found, requeuing
[tidb-controller-manager-d89ff9c6c-g5f4k] E0215 21:33:34.339465       1 pod_control.go:139] TidbCluster pod: titan/db-tikv-1, sync failed failed to get tc "titan/tidb-shared": tidbcluster.pingcap.com "tidb-shared" not found, requeuing
```

one for each tikv across my kubernetes cluster.

I don't have a tidbcluster.pingcap.com instance called 'tidb-shared':
```
kubectl get tidbclusters.pingcap.com -A
NAMESPACE   NAME   READY   PD                  STORAGE   READY   DESIRE   TIKV                  STORAGE   READY   DESIRE   TIDB                  READY   DESIRE   AGE
tidb        db     True    pingcap/pd:v5.4.0   15Gi      3       3        pingcap/tikv:v5.4.0   15Gi      3       3        pingcap/tidb:v5.4.0   3       3        513d
titan       db     True    pingcap/pd:v5.4.0   1Gi       3       3        pingcap/tikv:v5.4.0   10Gi      3       3        pingcap/tidb:v5.4.0           0        591d
```

so where does this error come from? How do I resolve it?

**Comment by DanielZhangQD** [comment]
OK, we will check it ASAP.

**Comment by KanShiori** [comment]
Are there any tikv that don't have a corresponding tc? 
The name 'tidb-shared' is from pod's label 'app.kubernetes.io/instance', see https://github.com/pingcap/tidb-operator/blob/17b1e59a4d07b9d3bce32132ff21158d982225cd/pkg/controller/tidbcluster/pod_control.go#L177

**Comment by DanielZhangQD** [comment]
@donbowman Do you use tidb-cluster helm chart to deploy the TiDB cluster?
Please note that that chart has been deprecated since TiDB Operator v1.1.0.

**Comment by donbowman** [comment]
I use the helm chart to render the values.yaml and then store that, i use kustomize to apply.

How does one apply w/o ?

**Comment by donbowman** [comment]
> Are there any tikv that don't have a corresponding tc? The name 'tidb-shared' is from pod's label 'app.kubernetes.io/instance', see
> 
> https://github.com/pingcap/tidb-operator/blob/17b1e59a4d07b9d3bce32132ff21158d982225cd/pkg/controller/tidbcluster/pod_control.go#L177

thank you for the pointer.
I'm not sure what a `tc` is. Perhaps you can point me in the correct direction?

**Comment by KanShiori** [comment]
> > Are there any tikv that don't have a corresponding tc? The name 'tidb-shared' is from pod's label 'app.kubernetes.io/instance', see
> > https://github.com/pingcap/tidb-operator/blob/17b1e59a4d07b9d3bce32132ff21158d982225cd/pkg/controller/tidbcluster/pod_control.go#L177
> 
> thank you for the pointer. I'm not sure what a `tc` is. Perhaps you can point me in the correct direction?

`tc` is an abbreviation for `tidbcluster`, according to the error message, it is possible that pods 'tidb/db-tikv-2' and 'titan/db-tikv-1' have the label 'app.kubernetes.io/component: tidb-shared'

**Comment by donbowman** [comment]
so thank you for that.
so it must be globally unique? i have 2 tidb clusters, one in namespace titan, one in namespace tidb.
I'm guessing from above this single label must be uniq globally even if cluster are in different namespace?

**Comment by DanielZhangQD** [comment]
@donbowman 
> so it must be globally unique? i have 2 tidb clusters, one in namespace titan, one in namespace tidb.
No
> I'm guessing from above this single label must be uniq globally even if cluster are in different namespace?
No
> I originally generated this from helm template as well, but now its just static. Is this a problem?
Yes, this is the problem, the point here is that the value of `pod.Labels[label.InstanceLabelKey]` should be the name of the TidbCluster CR, if you render the CR from helm chart, that would be incorrect.
So you can remove the labels from your TidbCluster CR, delete, and recreate them.

**Comment by DanielZhangQD** [comment]
If you still have issues, please upload your CR and we can check it.
