### ISSUE TITLE
Add an e2e case to cover the remoteWrite spec in TidbMonitor

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#4455]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Add an e2e case to cover the remoteWrite spec configurations in TidbMonitorRefer, refer to the code change in https://github.com/pingcap/tidb-operator/pull/4247.
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mikechengwei** [comment]
Since the basic auth example is too complicated, only manual tests will be added first.
