### ISSUE TITLE
E2E case for random tidb password is unstable

### ISSUE THREAD

**Issue by KanShiori** [pingcap/tidb-operator#4489]
## Question

> /home/jenkins/agent/workspace/tidb-operator-pull-e2e-kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:3297
Expected tidbcluster connect success
Unexpected error:
    <*errors.errorString | 0xc0021eb490>: {
        s: "cannot connect to tidb cluster, err: Error 1045: Access denied for user 'root'@'127.0.0.1' (using password: YES)",
    }
    cannot connect to tidb cluster, err: Error 1045: Access denied for user 'root'@'127.0.0.1' (using password: YES)
occurred
/home/jenkins/agent/workspace/tidb-operator-pull-e2e-kind/go/src/github.com/pingcap/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:3311

Seems that the password isn't correct.

Some failed CI: 
https://ci.pingcap.net/job/tidb-operator-pull-e2e-kind/2677/
https://ci.pingcap.net/job/tidb-operator-pull-e2e-kind/2671/
https://ci.pingcap.net/job/tidb-operator-pull-e2e-kind/2660/

**Comment by mikechengwei** [comment]
```
cannot connect to tidb cluster, err: Error 1045: Access denied for user 'root'@'127.0.0.1' (using password: YES)
```
Above log is normal , because sometimes the tidb pod is not ready , the service have no endpoints .DB tools connect tidb service will throw this error.

**Comment by mikechengwei** [comment]
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/13257127/159803332-80eacc44-e83d-4488-9baf-10291c72399e.png">

I have tested it by hand twice manually and not find problem.
BTW, If we want to get password by below command in manual test,we will get a password with a '%' suffix character. The '%' suffix character need to removed because it not contain in password.

```
 kubectl get secret basic-init -o=jsonpath='{.data.root}'  | base64 --decode
^c4er?78gN{3w%
```

**Comment by mikechengwei** [comment]
@KanShiori

**Comment by KanShiori** [comment]
I met this issue after some retries

> • Failure [65.923 seconds]
TiDBCluster
/root/yusihao/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:73
  [Feature]: RandomPassword
  /root/yusihao/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:3296
    deploy tidb cluster with random password [It]
    /root/yusihao/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:3297

    Expected tidbcluster connect success
    Unexpected error:
        <*errors.errorString | 0xc0014bdb60>: {
            s: "cannot connect to tidb cluster, err: Error 1045: Access denied for user 'root'@'127.0.0.1' (using password: YES)",
        }
        cannot connect to tidb cluster, err: Error 1045: Access denied for user 'root'@'127.0.0.1' (using password: YES)
    occurred

    /root/yusihao/tidb-operator/tests/e2e/tidbcluster/tidbcluster.go:3311

And I can't use the password in secret to connect 😢

**Comment by KanShiori** [comment]
The generated password is ".FBV3\`wQ20h6", seems that the string is invalid. I set this password in new cluster but failed to connect.

> kubectl get secret -n tidb-cluster-9841 random-password-init  -o=jsonpath='{.data.root}'  | base64 --decode
.FBV3\`wQ20h6

**Comment by mikechengwei** [comment]
> The generated password is ".FBV3\`wQ20h6", seems that the string is invalid. I set this password in new cluster but failed to connect.
> 
> ![image](https://user-images.githubusercontent.com/26425336/159837569-0be899c4-2f32-4beb-b662-db4c3a6907ce.png)
> 
> maybe the reason is `\` char

ok，i will test it again.
