### ISSUE TITLE
How to set container privilege mode?

### ISSUE THREAD

**Issue by glyslxq** [pingcap/tidb-operator#4499]
I read the document and only support podSecurityContext.

Container level securityContext is not supported.
```
kubectl explain sts.spec.template.spec.containers.securityContext.privileged
```

**Comment by DanielZhangQD** [comment]
@glyslxq Thanks for reporting this issue!
It's not supported yet, would you like to submit PR for this?

**Comment by mikechengwei** [comment]
I think we can support #4472 issue.

**Comment by mikechengwei** [comment]
Now this feature can use `podpatch` implement, ref: https://github.com/pingcap/tidb-operator/tree/master/examples/podpatch
