### ISSUE TITLE
pd-0 is pending,  0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.

### ISSUE THREAD

**Issue by m9rco** [pingcap/tidb-operator#4509]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/pingcap/tidb-operator/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [TiDB Operator Readme](https://github.com/pingcap/tidb-operator)
  - [TiDB Operator Doc](https://github.com/pingcap/tidb-operator/tree/master/docs)

I use this YAML to create the required local PV & PVC

```bash
kubectl apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/local-dind/local-volume-provisioner.yaml
```

However, the following abnormal problems were found

```
 kubectl -n tidb-test describe po tidb-pd-0

  Type     Reason            Age                     From               Message
  ----     ------            ----                    ----               -------
  Warning  FailedScheduling  43s (x3743 over 2d14h)  default-scheduler  0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.
```

```
kubectl -n tidb-test describe pvc pd-tidb-pd-0

  Type    Reason               Age                       From                         Message
  ----    ------               ----                      ----                         -------
  Normal  WaitForPodScheduled  113s (x14984 over 2d14h)  persistentvolume-controller  waiting for pod tidb-pd-0 to be scheduled
```

**Comment by m9rco** [comment]
```
kubectl get po -n kube-system -l app=local-volume-provisioner && \
kubectl get pv | grep local-storage
```

However, it was not created PV

**Comment by KanShiori** [comment]
Did you complete step 1 in doc [configure-storage-class](https://docs.pingcap.com/tidb-in-kubernetes/stable/configure-storage-class#local-pv-configuration)?

**Comment by m9rco** [comment]
yep,  I follow the latest documentation to create, prompting me to "local-storage" not mounted

https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/get-started#minikube

**Comment by m9rco** [comment]
Then, I found the deployment mode of "local-storage-class" through this document

https://book.tidb.io/session2/chapter1/tidb-operator-deployment-private-tidb.html

```
 kubectl -n tidb-test get storageClass

NAME                 PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
backup-storage       kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  28m
local-storage        kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  28m
shared-ssd-storage   kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  28m
ssd-storage          kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  28m
```

**Comment by KanShiori** [comment]
Maybe check the log of local-provisioner to find the reason.

**Comment by KanShiori** [comment]
> yep, I follow the latest documentation to create, prompting me to "local-storage" not mounted
> 
> https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/get-started#minikube

Cluster in get-started uses storageclass `default`, don't need to create local storage.

**Comment by m9rco** [comment]
I don't have a store class

**Comment by m9rco** [comment]
`local-provisioner` Log all normal

**Comment by KanShiori** [comment]
Could you please check the sub dir in discovery dir is a mountpoint?

**Comment by m9rco** [comment]
```
I0418 03:53:08.723073       1 common.go:334] StorageClass "backup-storage" configured with MountDir "/data/tidb-mnt/backup", HostDir "/data/tidb-mnt/backup", VolumeMode "Filesystem", FsType "", BlockCleanerCommand ["/scripts/quick_reset.sh"]
I0418 03:53:08.723115       1 common.go:334] StorageClass "local-storage" configured with MountDir "/data/tidb-mnt/disks", HostDir "/data/tidb-mnt/disks", VolumeMode "Filesystem", FsType "", BlockCleanerCommand ["/scripts/quick_reset.sh"]
I0418 03:53:08.723120       1 common.go:334] StorageClass "shared-ssd-storage" configured with MountDir "/data/tidb-mnt/sharedssd", HostDir "/data/tidb-mnt/sharedssd", VolumeMode "Filesystem", FsType "", BlockCleanerCommand ["/scripts/quick_reset.sh"]
I0418 03:53:08.723125       1 common.go:334] StorageClass "ssd-storage" configured with MountDir "/data/tidb-mnt/ssd", HostDir "/data/tidb-mnt/ssd", VolumeMode "Filesystem", FsType "", BlockCleanerCommand ["/scripts/quick_reset.sh"]
I0418 03:53:08.723131       1 main.go:63] Loaded configuration: {StorageClassConfig:map[backup-storage:{HostDir:/data/tidb-mnt/backup MountDir:/data/tidb-mnt/backup BlockCleanerCommand:[/scripts/quick_reset.sh] VolumeMode:Filesystem FsType:} local-storage:{HostDir:/data/tidb-mnt/disks MountDir:/data/tidb-mnt/disks BlockCleanerCommand:[/scripts/quick_reset.sh] VolumeMode:Filesystem FsType:} shared-ssd-storage:{HostDir:/data/tidb-mnt/sharedssd MountDir:/data/tidb-mnt/sharedssd BlockCleanerCommand:[/scripts/quick_reset.sh] VolumeMode:Filesystem FsType:} ssd-storage:{HostDir:/data/tidb-mnt/ssd MountDir:/data/tidb-mnt/ssd BlockCleanerCommand:[/scripts/quick_reset.sh] VolumeMode:Filesystem FsType:}] NodeLabelsForPV:[kubernetes.io/hostname] UseAlphaAPI:false UseJobForCleaning:false MinResyncPeriod:{Duration:5m0s} UseNodeNameOnly:false LabelsForPV:map[] SetPVOwnerRef:false}
I0418 03:53:08.723155       1 main.go:64] Ready to run...
I0418 03:53:08.723276       1 common.go:396] Creating client using in-cluster config
I0418 03:53:09.023266       1 main.go:85] Starting controller
I0418 03:53:09.023290       1 main.go:101] Starting metrics server at :8080
I0418 03:53:09.023377       1 controller.go:47] Initializing volume cache
I0418 03:53:09.223819       1 controller.go:111] Controller started

```

**Comment by KanShiori** [comment]
> ```
> I0418 03:53:08.723073       1 common.go:334] StorageClass "backup-storage" configured with MountDir "/data/tidb-mnt/backup", HostDir "/data/tidb-mnt/backup", VolumeMode "Filesystem", FsType "", BlockCleanerCommand ["/scripts/quick_reset.sh"]
> I0418 03:53:08.723115       1 common.go:334] StorageClass "local-storage" configured with MountDir "/data/tidb-mnt/disks", HostDir "/data/tidb-mnt/disks", VolumeMode "Filesystem", FsType "", BlockCleanerCommand ["/scripts/quick_reset.sh"]
> I0418 03:53:08.723120       1 common.go:334] StorageClass "shared-ssd-storage" configured with MountDir "/data/tidb-mnt/sharedssd", HostDir "/data/tidb-mnt/sharedssd", VolumeMode "Filesystem", FsType "", BlockCleanerCommand ["/scripts/quick_reset.sh"]
> I0418 03:53:08.723125       1 common.go:334] StorageClass "ssd-storage" configured with MountDir "/data/tidb-mnt/ssd", HostDir "/data/tidb-mnt/ssd", VolumeMode "Filesystem", FsType "", BlockCleanerCommand ["/scripts/quick_reset.sh"]
> I0418 03:53:08.723131       1 main.go:63] Loaded configuration: {StorageClassConfig:map[backup-storage:{HostDir:/data/tidb-mnt/backup MountDir:/data/tidb-mnt/backup BlockCleanerCommand:[/scripts/quick_reset.sh] VolumeMode:Filesystem FsType:} local-storage:{HostDir:/data/tidb-mnt/disks MountDir:/data/tidb-mnt/disks BlockCleanerCommand:[/scripts/quick_reset.sh] VolumeMode:Filesystem FsType:} shared-ssd-storage:{HostDir:/data/tidb-mnt/sharedssd MountDir:/data/tidb-mnt/sharedssd BlockCleanerCommand:[/scripts/quick_reset.sh] VolumeMode:Filesystem FsType:} ssd-storage:{HostDir:/data/tidb-mnt/ssd MountDir:/data/tidb-mnt/ssd BlockCleanerCommand:[/scripts/quick_reset.sh] VolumeMode:Filesystem FsType:}] NodeLabelsForPV:[kubernetes.io/hostname] UseAlphaAPI:false UseJobForCleaning:false MinResyncPeriod:{Duration:5m0s} UseNodeNameOnly:false LabelsForPV:map[] SetPVOwnerRef:false}
> I0418 03:53:08.723155       1 main.go:64] Ready to run...
> I0418 03:53:08.723276       1 common.go:396] Creating client using in-cluster config
> I0418 03:53:09.023266       1 main.go:85] Starting controller
> I0418 03:53:09.023290       1 main.go:101] Starting metrics server at :8080
> I0418 03:53:09.023377       1 controller.go:47] Initializing volume cache
> I0418 03:53:09.223819       1 controller.go:111] Controller started
> ```

seem that can't find any sub dir in `HostDir`

**Comment by m9rco** [comment]
I didn't create any sub directories in this directory

**Comment by KanShiori** [comment]
> I didn't create any sub directories in this directory

Oh, For each directory, a corresponding PV will be created. Note sub dir must be a mountpoint.

**Comment by m9rco** [comment]
thanks
