### ISSUE TITLE
Add the Kubernetes' Lifecycle hook support for TiKV and PD

### ISSUE THREAD

**Issue by wxiaomou** [pingcap/tidb-operator#4516]
## Feature Request

We want to add the Kubernetes' Lifecycle hook support for TiKV and PD container in the TiDB operator.

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

[Kubernetes core/v1.Lifecycle ](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/)  describes actions that the management system should take in response to container lifecycle events. For the PostStart and PreStop lifecycle handlers, management of the container blocks until the action is complete, unless the container process fails, in which case the handler is aborted.

We want to add the Kubernetes' Lifecycle hook support for TiKV and PD container in the TiDB operator.

**Describe alternatives you've considered:**

n/a
**Teachability, Documentation, Adoption, Migration Strategy:**

n/a

**Comment by mikechengwei** [comment]
I think the tidb operator has managed the pod life cycle well enough,can you give some specific scenarios for hook configuration?
The tidb operator itself hopes to hide the underlying logic, instead of opening and wrapping more and more native configurations, which will violate the design of the operator.

**Comment by wxiaomou** [comment]
@mikechengwei We want to have some custom logics in the `PostStart` and `PreStop` hook to improve the system reliability. For example, in the `PostStart` we want to do a couple curl commands to make sure the new started TiKV container does not host any leader before it became healthy. And some custom logic in `PreStop` to make sure the TiKV container will be shutdown gracefully.

**Comment by wxiaomou** [comment]
@mikechengwei Just to provide more context. We need lifecycle hook to be able to integrate with kube-system components such as node drainer.

**Comment by wxiaomou** [comment]
@mikechengwei Does it make sense to you?

**Comment by wxiaomou** [comment]
@mikechengwei thank you, my understading of #4472 is that after this PR we will be able to write our lifecycle hook configuration in TiDB cluster spec, it will merged by the operator so that we don't need to modify the CRD, am I understanding right?
example configuration: 

```    
lifecycle:
    preStop:
      exec:
        command:
        - "sh"
        - "-c"
        - |
          some shell command
```

**Comment by mikechengwei** [comment]
yes i will finish this PR

**Comment by wxiaomou** [comment]
@mikechengwei just a quick follow up, do we need pingcap to align on this change?

**Comment by mikechengwei** [comment]
i'm working on this pr.

**Comment by mikechengwei** [comment]
ok,i'm working on this pr as soon as possible.

**Comment by mikechengwei** [comment]
@wxiaomou This feature has entered the review stage, wait a moment.

**Comment by wxiaomou** [comment]
@mikechengwei Thanks a lot!
