### ISSUE TITLE
tikv status_address  in pd which is given by tidb-opertor is 0.0.0.0

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb-operator#4518]
### Appearance

I found that `tikv status_address` is `0.0.0.0` in `pd` , and it is given by `tidb-operator`. This caused the failure of br log backup. Then I could set  `enableDynamicConfiguration: true` in `TiDBCluster.spec`  to avoid the problem. 

### Relative code 

https://github.com/pingcap/tidb-operator/blob/0d13639f284bc55a89138d22b65852ecc625f4ac/pkg/manager/member/template.go#L285-L286

### Questions 
1. Why is it designed like this? 
2. Can we change it by default? If not, whether we could describe the problem and solution in docs?

**Comment by KanShiori** [comment]
I guess it is to avoid rolling upgrade after upgrading the operator.

All examples have the field `enableDynamicConfiguration: true` now, maybe we can change the default.

CC @DanielZhangQD

**Comment by DanielZhangQD** [comment]
Yes, this is to avoid rolling update to the current clusters after introducing this parameter.
And we have updated all the examples to include this field and also make it clear in the doc https://docs.pingcap.com/tidb-in-kubernetes/dev/configure-a-tidb-cluster#enabledynamicconfiguration.
