### ISSUE TITLE
docs: The local SSD disk performance issue on GKE

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#453]
- [ ] performance issues
- [ ] capacity limitations
  - workarounds
    - (medium-term) setup raid/lvm manually
    - (medium-term) setup raid/lvm with an operator automaticaly

**Comment by gregwebs** [comment]
@cofyc I think that after we merge https://github.com/pingcap/tidb-operator/pull/612 this issue can be closed out?

**Comment by weekface** [comment]
This issue can be closed now? @gregwebs
