### ISSUE TITLE
Why do not create crd tidbclusters in code automatically?

### ISSUE THREAD

**Issue by mathspanda** [pingcap/tidb-operator#46]
During the process of deploying tidb-operator according to docs, i found that crd tidbclusters must be applied manually. Why do not create the crd automatically in code, just like what did in etcd-operator and prometheus-operator?

**Comment by weekface** [comment]
Creating the CRD object is a one-time task. It is not necessary to create the CRD in code. Manual creation is OK.

Other projects do same with us: [rook](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L6), [mysql-operator](https://github.com/oracle/mysql-operator/blob/master/contrib/manifests/custom-resource-definitions.yaml)

**Comment by mathspanda** [comment]
i got it.
