### ISSUE TITLE
ERROR: "Job for docker.service canceled." error when DIND*_PROXY set

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#461]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

```
export DIND_PROPAGATE_HTTP_PROXY=true
cd $GOPATH/src/github.com/pingcap/tidb-operator
manifests/local-dind/dind-cluster-v1.12.sh up
```

upstream issue: https://github.com/kubernetes-sigs/kubeadm-dind-cluster/issues/280

**What did you expect to see?**

**What did you see instead?**

failed with 'Job for docker.service canceled.' error

**Comment by onlymellb** [comment]
This problem has been fixed in PR kubernetes-sigs/kubeadm-dind-cluster#271. we use the image with a fixed version. If we need to fix this problem, we need to update the kubeadm-dind-cluster image.

**Comment by cofyc** [comment]
That would be better, I'll try the new image.
