### ISSUE TITLE
support use default storageClassClassName  and define global.storageClassName 

### ISSUE THREAD

**Issue by willzhang** [pingcap/tidb-operator#4666]
## Feature Request

**Describe the feature you'd like:**
when use helm install tidb cluster,  support the follow feature for storage configure:

1、support use default storageClassClassName in kubernetes if user not define storageClassClassName itself
2、suport  define global.storageClassName in helm charts

**Describe alternatives you've considered:**
it will make install easyer.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by mikechengwei** [comment]
We recommend using yaml instead of helm to install the cluster, ref: https://github.com/pingcap/tidb-operator/tree/master/examples.

**Comment by willzhang** [comment]
helm will be easy for configuration and install , rook operator and rook cluster is a good example.

**Comment by willzhang** [comment]
The tidb cluster helm chart seems to be no longer maintained.
