### ISSUE TITLE
why v1.3.7 use latest tag of docker images

### ISSUE THREAD

**Issue by willzhang** [pingcap/tidb-operator#4670]
## Bug Report

**What version of Kubernetes are you using?**
1.24.3

**What version of TiDB Operator are you using?**
1.3.7

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
longhorn

**What's the status of the TiDB cluster pods?**
all running

**What did you do?**
```
helm install tidb-operator \
  --namespace tidb-admin \
  --create-namespace \
  --version v1.3.7 \
  pingcap/tidb-operator


helm install tidb-cluster \
  --namespace tidb-cluster \
  --create-namespace \
  --version v1.3.7 \
  pingcap/tidb-cluster
```

get tidb running pods image tag, it have `image: docker.io/pingcap/tidb:latest`  why use latest tag?
```
# kubectl -n tidb-cluster get pods -o yaml |grep image:
      image: pingcap/tidb-operator:v1.3.7
......
      image: docker.io/pingcap/tidb:latest
      image: pingcap/tikv
      image: docker.io/pingcap/tikv:latest
      image: pingcap/tikv
      image: docker.io/pingcap/tikv:latest
      image: pingcap/tikv
      image: docker.io/pingcap/tikv:latest
```

and official helm charts values.yaml have a version tag,
```
pd:
.....
  replicas: 3
  image: pingcap/pd:v5.4.1
```

**What did you expect to see?**

**What did you see instead?**

**Comment by KanShiori** [comment]
`tidb-cluster` chart is unsupported after operator v1.1, please use the `TidbCluster` CR, ref doc: https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/get-started
