### ISSUE TITLE
Create TiKV and TIDB pods immediately with initcontainers to delay startup

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#469]
## Feature Request

See #355. We can provision and scale capacity faster with autoscalers and autoprovisioners if the pods for TIKV and TIDB are created immediately when the PD pods are created.

We can do this and avoid downside by creating the pods with an init container. The init container will block the startup of the TiKV pod until PD is ready. Similarly it will block TiDB startup until TIKV and PD are ready.

There are at least a few approaches to signalling the init container to exit.

* It directly checks that the services are ready via API call
* It checks on the status from the readiness probe
* tidb-operator signals the init container

I am looking for feedback on the best approach here.

**Comment by cofyc** [comment]
It seems better to look at pending pods instead of TidbCluster CRDs to provision new nodes. It will be universal and can be used for any kinds of pods in cluster management.

I agree to create the pods immediately and use init container to check is it ready to run. The idea is like the webhook that we are going to implement to prevent pods from being deleted until they are ready to exit.

But I'm not familiar with this, not sure if it is hard to implement in init containers. cc @weekface

**Comment by weekface** [comment]
Create all pods and keep them pending is ok to me and it can provision and scale capacity faster with autoscalers and autoprovisioners.

But use the init container solution may not a good solution, it requires a lot of refactoring of existing code. For example, the operator will not create TiKV's statefulset before PD is [running](https://github.com/pingcap/tidb-operator/blob/c8648e7fe5f9fe1e547ef5a4e3a78399f0c628ff/pkg/manager/member/tikv_member_manager.go#L98) now. All the three components's operations are sequential, include create, upgrade, scale and any other operations.

I suggest:
- add another controller to watch the TidbCluster object, when it is created, increase the Kube nodes if necessary, this is easy to implement now.
- using validating admission webhooks, we can implement this feature easily by creating these three statefulsets at once, but it needs a refactor of operator.

**Comment by gregwebs** [comment]
> add another controller to watch the TidbCluster object, when it is created, increase the Kube nodes if necessary, this is easy to implement now.

I can do this, but it won't be compatible with autoscalers and provisioners that are based on pending pods.

> it requires a lot of refactoring of existing code.

I think the code you pointed to would just change the check to be:

if tc.PDIsAvailable() { tc.stopTiKVInitContainer() }

**Comment by weekface** [comment]
Now, TiKV statefulset will not be created before PD pods are ready. This solution will create all the three statefulsets at once. This is a big change for operator i think. It's not easy for me to assess the impact of this change without a detailed proposal or design document.

And what does `tc.stopTiKVInitContainer() ` do?

**Comment by gregwebs** [comment]
> And what does tc.stopTiKVInitContainer() do?

The purpose of the init container is to prevent startup of the actual containers. So if you stop the init container for TiKV the actual TiKV container will start up.

**Comment by gregwebs** [comment]
> It's not easy for me to assess the impact of this change without a detailed proposal or design document.

okay, we can try to outline the changes that are needed.

**Comment by gregwebs** [comment]
closing in favor of #581
