### ISSUE TITLE
Improve components' readiness check mechanisms

### ISSUE THREAD

**Issue by wxiaoke** [pingcap/tidb-operator#4760]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Use "kubectl get pod" to check that the status of pd is running, but the process of pd has not yet started

**Describe the feature you'd like:**

Add pod readiness check to check whether the status of components (PD, TiDB, TiKV) is normal
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

The design of the current operator will seriously mislead users: in fact, the service does not start up, but the status displayed by the get pod is running;

It is strongly recommended to add a pod readiness check

**Comment by hanlins** [comment]
Thanks @wxiaoke! Rephasing the issue in english for a bit. Basically the pods status are somewhat misleading, take PD pods for example, when a PD pod just come up, by default k8s will consider it as ready as long as the process is up and running, however, PD could be actually syncing metadata with other PD pods which means it cannot serve requests at the time. Need to expose some readiness probe so k8s/tidb-operator can better coordinate the pods and minimize the turbulence on changes (e.g. rolling upgrade).

**Comment by hanlins** [comment]
Seems to have overlap with #4758

**Comment by mikechengwei** [comment]
This is the same problem as #3857 , I will finish it quickly.

**Comment by mikechengwei** [comment]
close by #4761 .

**Comment by csuzhangxc** [comment]
#4763
