### ISSUE TITLE
IPV6 support: tidb-monitor-reloader can't start in IPv6/IPv4 dual-stack network and set IPv6 as default 

### ISSUE THREAD

**Issue by mayjiang0203** [pingcap/tidb-operator#4789]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Deploy monitor according following documents.
https://docs.pingcap.com/zh/tidb-in-kubernetes/v1.4/monitor-a-tidb-cluster

**What did you expect to see?**

**What did you see instead?**

reloader:
    Container ID:  containerd://a56af6a80d21fd41fd30c11ee8728d23884ec681faf3461374bbe8a117db64ba
    Image:         pingcap/tidb-monitor-reloader:v1.0.1
    Image ID:      [docker.io/pingcap/tidb-monitor-reloader@sha256:516ab6564724f3aa186ae2ccf27c06dc7df5c4cd7c570986e94282019def024e](http://docker.io/pingcap/tidb-monitor-reloader@sha256:516ab6564724f3aa186ae2ccf27c06dc7df5c4cd7c570986e94282019def024e)
    Port:          9089/TCP
    Host Port:     0/TCP
    Command:
      /bin/reload
      --root-store-path=/data
      --sub-store-path=tidb:v4.0.0
      --watch-path=/prometheus-rules/rules
      --prometheus-url=http://127.0.0.1:9090/
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 25 Nov 2022 10:44:01 +0000
      Finished:     Fri, 25 Nov 2022 10:44:01 +0000
    Ready:          False
    Restart Count:  4
    Environment:
      TZ:  UTC

  Normal   Pulling    113s (x2 over 2m33s)  kubelet            Pulling image "pingcap/tidb-monitor-reloader:v1.0.1"
  Warning  Unhealthy  113s                  kubelet            Readiness probe failed: Get "http://[fd00:100:96:1::17]:3000/api/health": dial tcp [fd00:100:96:1::17]:3000: connect: connection refused
  Normal   Started    111s (x2 over 2m26s)  kubelet            Started container reloader
  Normal   Created    111s (x2 over 2m26s)  kubelet            Created container reloader
  Normal   Pulled     111s                  kubelet            Successfully pulled image "pingcap/tidb-monitor-reloader:v1.0.1" in 1.844769041s

**Comment by csuzhangxc** [comment]
this is caused as Grafana is listening on IPv4 (`http_addr` config item)

**Comment by mayjiang0203** [comment]
/usr/share/grafana $ netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:40564         127.0.0.1:9090          ESTABLISHED 1/grafana-server
tcp        0      0 127.0.0.1:40552         127.0.0.1:9090          TIME_WAIT   -
tcp        0      0 127.0.0.1:40562         127.0.0.1:9090          TIME_WAIT   -
tcp        0      0 127.0.0.1:40556         127.0.0.1:9090          TIME_WAIT   -
tcp        0      0 127.0.0.1:40560         127.0.0.1:9090          TIME_WAIT   -
tcp        0      0 127.0.0.1:40498         127.0.0.1:9090          TIME_WAIT   -
tcp        0      0 127.0.0.1:40558         127.0.0.1:9090          ESTABLISHED 1/grafana-server
tcp        0      0 127.0.0.1:40548         127.0.0.1:9090          TIME_WAIT   -
tcp        0      0 127.0.0.1:40550         127.0.0.1:9090          TIME_WAIT   -
tcp        0      0 127.0.0.1:40554         127.0.0.1:9090          TIME_WAIT   -
tcp        0      0 100.96.1.24:51412       34.120.177.193:443      TIME_WAIT   -
tcp        0      0 :::3000                 :::*                    LISTEN      1/grafana-server
tcp        0      0 :::9088                 :::*                    LISTEN      -
tcp        0      0 :::9089                 :::*                    LISTEN      -
tcp        0      0 :::9090                 :::*                    LISTEN      -

reloader startup after grafana startup, so close this issue.

**Comment by csuzhangxc** [comment]
> this is caused as Grafana is listening on IPv4 (`http_addr` config item)

the default `0.0.0.0` works
