### ISSUE TITLE
Increase k8s client-go rate-limit qps

### ISSUE THREAD

**Issue by Thearas** [pingcap/tidb-operator#4829]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Hi, I'm from the TiDB QA team. We run **hundreds of tidb** in our K8s. When deploying tens of tidb at the same time, we found that deploying tidb cluster (even the smallest tc) were very slow, nearly 30m.
The reason is that the k8s client-go used by the tidb operator has a [QPS 5 rate-limit](https://github.com/kubernetes/client-go/blob/fda1b1132eb29d16df78d1204ee575092900867c/rest/config.go#L44):
![tc-ratelimit](https://user-images.githubusercontent.com/44015907/211243787-416a8b78-e9d5-4431-802a-5f771f8708ec.jpeg)

After increasing QPS, these logs above disappear and the deployment time is reduced to 5m.

**Describe the feature you'd like:**

Add two configurations to set [QPS and Burst](https://github.com/kubernetes/client-go/blob/fda1b1132eb29d16df78d1204ee575092900867c/rest/config.go#L116), e.g. `kubeClientQPS` and `kubeClientBurst`

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by csuzhangxc** [comment]
👍 good suggestion.
