### ISSUE TITLE
Check annotation and label diff when sync services 

### ISSUE THREAD

**Issue by wxiaomou** [pingcap/tidb-operator#4972]
## Bug Report
I added new annotation to pd services and pd headless service, but the service not get updated by the tidb operator.

Seems when we sync [tidb services](https://sourcegraph.com/github.com/pingcap/tidb-operator@master/-/blob/pkg/manager/member/tidb_member_manager.go) we have checked the label and annotation of the new service. Should we do the similar thing for other components as well? 

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by csuzhangxc** [comment]
It seems doing a similar thing for other components should be better.  And TiDB service label & annotation check was added in #3892

**Comment by wxiaomou** [comment]
@csuzhangxc Thanks, just pulled a pr https://github.com/pingcap/tidb-operator/pull/4973/files
