### ISSUE TITLE
EBS snapshot BR: resource leak if backup isn't deleted properly

### ISSUE THREAD

**Issue by lobshunter** [pingcap/tidb-operator#4994]
## Bug Report

**What version of TiDB Operator are you using?**
v1.5.0-beta.1

**What did you do?**
- create a [snapshot backup](https://docs.pingcap.com/tidb-in-kubernetes/stable/backup-to-aws-s3-by-snapshot), and grant permissions by [credentials secret](https://docs.pingcap.com/tidb-in-kubernetes/stable/grant-permissions-to-remote-storage#grant-permissions-by-accesskey-and-secretkey)
- after backup is finished, run `kubectl delete ns $NAMESPACE` without deleting backup CR first.

**What did you expect to see?**
namespace and corresponding s3 objects are deleted

**What did you see instead?**
namespace and backup are stucked at terminating state, and s3 backup objects wouldn't be automatically removed. Because the credential secret is deleted with namespace deletion is triggered, tidb-operator lost the permission to operate with those objects, and tidb-operator wouldn't remove finalizers of backup CR until clean up is finished.

**Comment by lobshunter** [comment]
Moreover, it doesn't really matter how permission is granted. Backup fails to be cascading deleted on namespace deletion anyway. Because tidb-operator creates a cleanup Job to do housekeeping work, but a deleting namespace disallows any kind of resorce creation.

**Comment by BornChanger** [comment]
Leave it as it is.
