### ISSUE TITLE
unable to deploy cross k8s tc using official tikv/tidb image

### ISSUE THREAD

**Issue by lobshunter** [pingcap/tidb-operator#5037]
## Bug Report

**What version of Kubernetes are you using?**
1.23

**What version of TiDB Operator are you using?**
master(2da77b887b76d6c7c1cd09782d6ee0a1184d5832)

**What's the status of the TiDB cluster pods?**
tidb/tikv pod stucked in an infinite check loop, keeps printing `waiting for the verification of PD endpoints ...`

**What did you do?**
Follow the [official instruction](https://docs.pingcap.com/tidb-in-kubernetes/dev/deploy-tidb-cluster-across-multiple-kubernetes), deploy tidb cluster across multiple kubernetes.

**What did you expect to see?**
Deploy successfully.

**What did you see instead?**
tc stucked at `TiKV Store(s) are not up`, or `TiDB(s) are not healthy`.

**Additional Info**
Looks like because tikv [startup script](https://github.com/pingcap/tidb-operator/blob/2da77b887b76d6c7c1cd09782d6ee0a1184d5832/pkg/manager/member/startscript/v2/tikv_start_script.go#L97) uses wget, but since a certain version of tidb, the official image(pingcap/tikv, pingcap/tidb) doesn't provide build-in wget command.

Images I tried:
pingcap/tikv:v6.5.1 works, and has wget command
pingcap/tikv:v7.1.0 doesn't work, wget command not found

**Comment by lijie0123** [comment]
new tikv image has curl, can operator use that?

**Comment by csuzhangxc** [comment]
The usage of `wget` in the start script is part of Pods' spec, if we change the start script, all existing TidbCluster will be affected and all Pods will be rolling restarted.

**Comment by BornChanger** [comment]
Please also add the `wget` into tidb image for 6.5.x arm and 7.1.x

**Comment by csuzhangxc** [comment]
this should have already been fixed in 7.1.1
