### ISSUE TITLE
How to use SDK to access RawKV from outside the k8s cluster?

### ISSUE THREAD

**Issue by Smityz** [pingcap/tidb-operator#5051]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We have deployed a TiKV cluster on k8s, which can only be accessed from within the k8s cluster. In order to enable access to the TiKV cluster from outside the k8s cluster, we need to configure CoreDNS resolution on each client machine, but this is not elegant. Is there a way to specify the DNS for accessing the k8s internal cluster through the application layer?

**Comment by csuzhangxc** [comment]
Can you set up a LoadBalancer service that can be accessible from the outsider of the K8s cluster?

**Comment by csuzhangxc** [comment]
> In our scenario, we use RawKV directly, not relay on TiDB instances

You can set up a LoadBalancer service to TiKV directly.

**Comment by Smityz** [comment]
I am sorry for not getting what's your mean, client will get the headless service URL of each TiKV, in that way, can LoadBalance work well? And when I scale out the TiKV cluster, should I assign a new load balancer address for the new TiKV instance?

**Comment by csuzhangxc** [comment]
Oh, if you want to access each TiKV instance, LoadBalance may not work well. and you may need to set another address or configure CoreDNS resolution as you previously did.

**Comment by Smityz** [comment]
Can we implement DNS resolution within the SDK without modifying the system's DNS settings? Would this be a good approach?

**Comment by aeblyve** [comment]
Writing a comment as we are facing this issue as well. Using the RawKV API from outside the cluster seems not supported, but this is useful for some apps, for example JuiceFS.
