### ISSUE TITLE
The GC safepoint exceeds resolved ts, causing the backup task to fail

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5073]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

wangle1321/tidb-operator:202305261650

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

gp3

**What's the status of the TiDB cluster pods?**

running

**What did you do?**

1. scale cluster
2. do volumebackup

**What did you expect to see?**
1. volumebackup success

**What did you see instead?**
1.volumebackup failed
![uBFcOZ5bEZ](https://github.com/pingcap/tidb-operator/assets/81375082/c4288897-3d36-45c2-9804-cfed4a185578)
http://adf14c0e0fa524754ab988c5d14ee0a7-30b3685179f2b6df.elb.us-west-2.amazonaws.com:3000/d/RDVQiEzZz/cluster-tikv-details?orgId=1&refresh=1m
http://a4a4138a084174ae6a0ba1ee6df36f90-1580f33cc8128292.elb.us-west-2.amazonaws.com:3000/d/RDVQiEzZz/cluster-tikv-details?orgId=1&refresh=1m&from=now-3h&to=now
http://a07830e0799414a16a11a4d1f47ba52a-f700025f4475a6ca.elb.us-west-2.amazonaws.com:3000/d/RDVQiEzZz/cluster-tikv-details?orgId=1&refresh=30s&from=now-30m&to=now

**Comment by BornChanger** [comment]
At that time, the cluster is scaling out. Adding learner peer blocks advancing of resolved-ts.  Retry will succeed.
