### ISSUE TITLE
add maxFailoverCount to TiKV

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#508]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We should add a maxFailoverCount to TiKV just like [TiDB](https://github.com/pingcap/tidb-operator/blob/4c183422345d8fe9e5a450f3729339ee01684767/pkg/manager/member/tidb_failover.go#L46) does.

Or the operator will create another 3 TiKV instances if all the 3 TiKV instances down but The PD instances are health.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by weekface** [comment]
@tennix @xiaojingchen @onlymellb @aylei @cofyc PTAL

**Comment by cofyc** [comment]
target 1.1?

**Comment by weekface** [comment]
I am not sure if this feature is necessary.

**Comment by weekface** [comment]
Add `maxFailoverCount` to TiKV is necessary now: #963
