### ISSUE TITLE
The number of regions is much greater than the concurrent number of br, resulting in a particularly long volume restore time

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5085]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**
wangle1321/tidb-operator:202305261650

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
gp3

**What's the status of the TiDB cluster pods?**
normal

**What did you do?**
1. create cluster(cross k8s)
2. run workload on cluster
3. do volume backup
4. do volume restore(total data 7T, 6 tikv, 6T disk, backup-20230614-inc-4)
![image](https://github.com/pingcap/tidb-operator/assets/81375082/e5285dfa-7424-490a-b8c0-cb61a74e2074)

**What did you expect to see?**
volume restore success and only cost half an hour

**What did you see instead?**
volumerestore has not been completed in 4 hours
![image](https://github.com/pingcap/tidb-operator/assets/81375082/423a5929-c5d2-4da5-ab87-8a64e177cf09)

**Comment by BornChanger** [comment]
It's an expected result against cold EBS volumes
