### ISSUE TITLE
One of the k8s backups failed, and the status of the entire task should be updated to failed

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5086]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**
wangle1321/tidb-operator:202305261650

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
gp3

**What's the status of the TiDB cluster pods?**
normal

**What did you do?**
1. create cluster(cross k8s)
2. create volumebackup(Fill in buckets that already have data)

**What did you expect to see?**
1. status of the entire task should be updated to failed

**What did you see instead?**
1. status of the entire task is always running
![image](https://github.com/pingcap/tidb-operator/assets/81375082/c858bc14-b31a-45de-a553-d0f3d86d0d82)
![image](https://github.com/pingcap/tidb-operator/assets/81375082/f6c8b710-1ed8-4fc0-b609-60dbac2194ca)

**Comment by BornChanger** [comment]
Associate the pr

**Comment by WangLe1321** [comment]
![image](https://github.com/pingcap/tidb-operator/assets/13897016/d521c39b-348c-47a6-82f2-956f83039cd6)
![image](https://github.com/pingcap/tidb-operator/assets/13897016/e6c46ef0-cbf4-45e9-bb0a-82f9fcabf6da)

This issue is fixed by https://github.com/pingcap/tidb-operator/pull/5153
