### ISSUE TITLE
Deleting volume backup during its running can cause snapshot leakage

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5087]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**
wangle1321/tidb-operator:202305261650

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
gp3

**What's the status of the TiDB cluster pods?**
noraml

**What did you do?**
1. create cluster(cross k8s)
2. create volume backup
3. delete volume backup when it is running status

**What did you expect to see?**
1. bucket is deleted
2. snapshot is deleted

**What did you see instead?**
1. snapshot is not be deleted
2. there is only 2 volume backup(each has 6 2T snapshot,total 12 2T snapshot), but has more than 12 snapshot in aws account
![image](https://github.com/pingcap/tidb-operator/assets/81375082/bcfedba9-3a19-4969-a487-05bf4b4a1559)
![image](https://github.com/pingcap/tidb-operator/assets/81375082/e0353e67-7bc9-4c75-b524-3fe0af9e7ce2)

**Comment by BornChanger** [comment]
duplicate with https://github.com/pingcap/tidb-operator/issues/5074
