### ISSUE TITLE
Volume restore takes a long time

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5089]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**
wangle1321/tidb-operator:202305261650

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
gp3(4000 iops 287 throughput)

**What's the status of the TiDB cluster pods?**
normal

**What did you do?**
1. create cluster(cross k8s)
2. do volume backup(6 TiKVs, 6T disks, each with a data volume of approximately 1.2T)
3. do volume restore

**What did you expect to see?**
1. restore will cost about half an hour

**What did you see instead?**
1. it cost about 2.5 hours
2. 
![image](https://github.com/pingcap/tidb-operator/assets/81375082/18a86aa4-1496-4d80-8bb9-00e5774e57c7)

**Comment by BornChanger** [comment]
It's expected since restored volumes are not warmed up
