### ISSUE TITLE
Volume Restore failed

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5090]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**
wangle1321/tidb-operator:202305261650

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
gp3(3000 iops 125 throughput)

**What's the status of the TiDB cluster pods?**
normal

**What did you do?**
1. create cluster(cross k8s)
2. do volume backup(6 TiKVs, each 6 T volume, each tikv has 1.3T data)
![image](https://github.com/pingcap/tidb-operator/assets/81375082/94ddf467-a46a-4bd0-aea7-8c3f0496c605)

4. do volume restore

**What did you expect to see?**
1. restore success

**What did you see instead?**
1.restore failed,  PD can not find the region 
![image](https://github.com/pingcap/tidb-operator/assets/81375082/5cad87b3-c9ee-43bb-ac83-e03929d0a144)

**Comment by BornChanger** [comment]
Wait for repro

**Comment by BornChanger** [comment]
Please reopen it for next occurence
