### ISSUE TITLE
backup: take cluster manifest backup along with data.

### ISSUE THREAD

**Issue by BornChanger** [pingcap/tidb-operator#5116]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We need to save manifest information of backup cluster with backup metadata, so that, restored cluster can share the same meta information.

1. this config snapshot should be able to allow user to create a restore cluster using exactly the same setup as backup source cluster. e.g. replica #, cpu, storage of each components
2. this config snapshot should exclude backup source cluster specific info like `creationTimestamp`, `generation`, `uid`, `status` etc.
3. this snapshot should be stored in persistent storage like S3 together with data snapshot so users can easily download and use
4. Users don't expect a big performance impact when enabling config snapshot.

**Describe the feature you'd like:**

[Take cluster manifest backup along with data.](https://pingcap.zendesk.com/agent/tickets/1887)

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by BornChanger** [comment]
We can take 2-steps to do that:
phase 1 is to backup manifest only with backup data. @oliviachenairbnb

**Comment by oliviachenairbnb** [comment]
> We can take 2-steps to do that:

correct for phase one we need the manifests snapshot taken together with data snapshot and stored in same s3 folder. the manifests we need including tidbcluster, tidbinitializer, tidbmonitor etc.

**Comment by WangLe1321** [comment]
@oliviachenairbnb The CRDs related to tidb-operator are in https://github.com/pingcap/tidb-operator/tree/master/manifests/crd/v1 . I think the manifests that you want take are `tidbclusterautoscalers`, `tidbclusters`, `tidbdashboards`, `tidbinitializers`, `tidbmonitors`, `tidbngmonitorings`, do you agree? For the contents of the manifests, I will store the contents that you can get by `kubectl get {crd-name} {cr-name} -o yaml`, is it OK?

**Comment by oliviachenairbnb** [comment]
> @oliviachenairbnb The CRDs related to tidb-operator are in https://github.com/pingcap/tidb-operator/tree/master/manifests/crd/v1 . I think the manifests that you want take are `tidbclusterautoscalers`, `tidbclusters`, `tidbdashboards`, `tidbinitializers`, `tidbmonitors`, `tidbngmonitorings`, do you agree? For the contents of the manifests, I will store the contents that you can get by `kubectl get {crd-name} {cr-name} -o yaml`, is it OK?

sounds good to me. not sure that is `tidbclusterautoscalers` here? I don't think we have such resource in current namespace

**Comment by WangLe1321** [comment]
The CRDs I mentioned above are all the resources we can backup, and if there are some CRDs you don't have, we will ignore them. So we will backup all the manifests that belong to the CRDs I mentioned and reference the `TiDBCluster` in all namespaces.

**Comment by oliviachenairbnb** [comment]
gotcha! are we going to store in together with data backup in s3?

**Comment by WangLe1321** [comment]
Yes!
