### ISSUE TITLE
The previous backup failed, which will affect the time for rerun the backup

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5144]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do a volumebackup, but volumebackup is failed
2. rerun volumebackup

**What did you expect to see?**
1. when I rerun volumebackup, the snapshot of this volumebackup will be executed immediately

**What did you see instead?**
1. the snapshot of this volumebackup's progress is 0%, until the failed volumebackup's snapshot is completed
![2166f380-40f7-4c15-9b39-827c254b4705](https://github.com/pingcap/tidb-operator/assets/81375082/5ad35fd1-f81a-410d-ad79-f612cc05d881)
![j4EO7JA6Df](https://github.com/pingcap/tidb-operator/assets/81375082/1e6f0c10-edd7-4e91-b2cb-b91f88d651c1)

**Comment by WangLe1321** [comment]
Maybe deleting the failed volume backup before executing a new backup is a workaround.
