### ISSUE TITLE
kill restore pod will cause restore task failed

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5157]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. run volume restore
2. kill restore pod

**What did you expect to see?**
1. volume restore success

**What did you see instead?**
1. volume restore failed
2. 
![image](https://github.com/pingcap/tidb-operator/assets/81375082/74d92fff-d476-45b0-b7f8-0222756d777f)
![image](https://github.com/pingcap/tidb-operator/assets/81375082/12d8a354-044d-430d-8d6a-84dbe02a21f6)
![image](https://github.com/pingcap/tidb-operator/assets/81375082/8d3c691d-6673-4cdd-9291-0852ace722f8)

**Comment by WangLe1321** [comment]
Can you reproduce this error and show the log of failed restore pod? It's hard to reproduce this error without the chaos tool because the lifetime of the restore volume pod is too short.

**Comment by WangLe1321** [comment]
The chaos is container killed, which means the br process failed, so that the br job failed. So the restore task failure is what we expect.
