### ISSUE TITLE
Delete a running VolumeBackup, backup CRs are deleted, but metadata and EBS snapshots are still remained

### ISSUE THREAD

**Issue by WangLe1321** [pingcap/tidb-operator#5159]
## Bug Report

**What version of Kubernetes are you using?**

release-1.5

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

1. create a VolumeBackup with `cleanPolicy: Delete`
2. wait the backup in the data plane initialize complete and start running 2nd phase
3. delete the VolumeBackup CR

**What did you expect to see?**

VolumeBackup CR in control plane and backup CR in data plane are all deleted, metadata and EBS snapshots are also deleted.

**What did you see instead?**

VolumeBackup CR in control plane and backup CR in data plane are all deleted, but metadata and EBS snapshots aren't deleted.

**Comment by BornChanger** [comment]
Need to check operator cleanup logic

**Comment by BornChanger** [comment]
I think the problem should be fixed by https://github.com/pingcap/tidb-operator/pull/5199. Please double check. @WangLe1321
