### ISSUE TITLE
Need to add the restore name to the warmup job name, otherwise it will affect the next restore task

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5160]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. create volumerestore task t1
2. after t1 is completed, create another volumerestore task t2

**What did you expect to see?**
1. task t2 will also successed

**What did you see instead?**
1. the warmup job is not start up
![img_v2_0cb4dd15-2f39-427a-a6af-6c56cf1ef2dg](https://github.com/pingcap/tidb-operator/assets/81375082/60b9b17b-8e69-4407-ba01-65fd5e30ff15)
![img_v2_9cbcdcac-b2a9-4f85-ac99-688c402b1f0g](https://github.com/pingcap/tidb-operator/assets/81375082/57045365-241f-47b8-8a78-e16789bdbb94)

**Comment by BornChanger** [comment]
Fixed with warmup pr
