### ISSUE TITLE
ebs br: support retry to restore at recoverregion and waitapply phase

### ISSUE THREAD

**Issue by BornChanger** [pingcap/tidb-operator#5236]
## Feature Request

**Is your feature request related to a problem? Please describe:**

If tikv node is killed, ebs snapshot restore will fail even if the tikv node comes back later

**Describe the feature you'd like:**

Region recovery and wait apply phases need to support restart.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by BornChanger** [comment]
fixed by https://github.com/pingcap/tidb/pull/46094

**Comment by zhongmin-amin** [comment]
verified
