### ISSUE TITLE
failure to access AWS during backup will cause the entire task to fail

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5266]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volumebackup

**What did you expect to see?**
1. volume backup success 

**What did you see instead?**
1. volumebackup failed
2. 
![76a3c31e-e759-4831-bf84-797ae3c9c50b](https://github.com/pingcap/tidb-operator/assets/81375082/6f88fedc-b92b-4562-abf8-cce12e252758)

**Comment by BornChanger** [comment]
It's a rare case where AWS dns service is restarted. And the failure is not critical.
