### ISSUE TITLE
az c snpshot backup takes a long time

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5268]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volumeback

**What did you expect to see?**
1. az a/b/c snpshot backup takes about the same time

**What did you see instead?**
1. az c snpshot backup takes a long time，Especially in the case of large amount of data
![ca9f6ae6-e6a7-4fcc-8d2d-ebf69a7d16f8](https://github.com/pingcap/tidb-operator/assets/81375082/56708a9e-b7e6-4af5-820e-05deae88830e)
![img_v2_2ee8c13e-dd7a-446c-b619-70f9ab60474g](https://github.com/pingcap/tidb-operator/assets/81375082/c67fbbcc-6205-4b4b-a5f2-e0dbda1f5b31)

**Comment by BornChanger** [comment]
We can do nothing if AWS side can't guarantee their SLA. AWS claims the hosts in AZ C are under heavier load.
