### ISSUE TITLE
ebs br: for a 100T cluster after restore, the QPS decreased and became unstable in the first two hours

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5269]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**
gcr.io/pingcap-public/dbaas/tikv:v6.5.4-20230822-1692700456
gcr.io/pingcap-public/dbaas/tidb:v6.5.4-20230822-1692700456
gcr.io/pingcap-public/dbaas/pd:v6.5.4-20230822-1692700456
gcr.io/pingcap-public/dbaas/br:v6.5.4-20230822-1692700456

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volumerestore(100T)
2. add workload on restore cluster

**What did you expect to see?**
1. the QPS of restore cluster is same with backup cluster

**What did you see instead?**
1. the QPS decreased and became unstable in the first two hours
![image](https://github.com/pingcap/tidb-operator/assets/81375082/c8c26810-b3c8-40f7-a8b7-5731311f6fb4)

**Comment by BornChanger** [comment]
The reason is that file based warmup doesn't warmup all blocks of the tikv data volumes. Instead, only blocks containing data are warmed up. Blocks emptied by compaction or GC are not warmed up yet. Restored cluster has very good performance if we use FSR to warmup volumes.

**Comment by BornChanger** [comment]
I would close it now since the behavior is as expected.
