### ISSUE TITLE
there are 2 running volumebackup during volumebackupschedule

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5271]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. run volumebackupschedule
2. one volumebackup failed

**What did you expect to see?**
1. after volumebackup failed, there is only 1 running volumebackup during volumebackupschedule

**What did you see instead?**
1.there are 2 running volumebackup during volumebackupschedule
![image](https://github.com/pingcap/tidb-operator/assets/81375082/06d2e0f7-9837-4467-9188-fc6b4c5debc5)

**Comment by BornChanger** [comment]
It's working as design.
![image](https://github.com/pingcap/tidb-operator/assets/97348524/d664b829-1fe8-4520-83eb-e8df8cb8c882)
