### ISSUE TITLE
backup job is stuck(snapshot is completed)

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5281]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volumebackup

**What did you expect to see?**
1. volumebackup successed

**What did you see instead?**
1. one backup job is stuck(snapshot is completed)
2. 
![03ddb638-7239-4727-862d-ba62f122a716](https://github.com/pingcap/tidb-operator/assets/81375082/1d1b9eca-e200-4e45-93c5-d2102b2d42ed)
![31b070df-be7a-495b-b3bd-c20fd772e6c6](https://github.com/pingcap/tidb-operator/assets/81375082/c88531a0-3a0f-4906-befd-92df92919bcc)

**Comment by BornChanger** [comment]
Corresponding PR is tracked here https://github.com/pingcap/tidb/issues/46850
