### ISSUE TITLE
The EBS backup task may cause the import task to fail

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5282]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. start EBS backup and import tasks simultaneously on a cluster

**What did you expect to see?**
1. ebs backup success
2. import job success

**What did you see instead?**
1. import job failed, because ebs backup will prevent region split throughout the entire process
![bdc47639-dd5c-4aec-bce8-f375fe8f2588](https://github.com/pingcap/tidb-operator/assets/81375082/98e2a05a-b894-49f1-a2cd-dbb7c5f125be)

**Comment by BornChanger** [comment]
EBS BR and lightning by local backend or fast ddl etc are not compatible. We need to block each other and give clear error message.

**Comment by BornChanger** [comment]
Also tracked in tikv issue https://github.com/pingcap/tidb/issues/46850

**Comment by BornChanger** [comment]
It's an expected behavior when ebs br runs long enough and the pd scheduling is disabled.
