### ISSUE TITLE
volumerestore 时，operator 报错“sync failed, err: read backup meta from bucket qa-workload-datasets and prefix airbnb-ebs/rpod_loss_with_pdleader_10min-tidb-operator-ebs-2, err: blob (key "backupmeta") (code=Unknown)”

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5284]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volume restore

**What did you expect to see?**
1. volume restore success

**What did you see instead?**
1. volume restore failed
![image](https://github.com/pingcap/tidb-operator/assets/81375082/3aeb5720-f060-4949-9063-ec873684dad2)
![881708af-0988-4705-ba6c-c4c527c70466](https://github.com/pingcap/tidb-operator/assets/81375082/25aef6dc-f6a6-4d3c-860e-76587bb3cdbe)
![8f10739a-bb7b-4ea0-809b-5282fe6ee809](https://github.com/pingcap/tidb-operator/assets/81375082/8109af83-0372-4b5f-8371-cca11786c1c9)

**Comment by BornChanger** [comment]
Close it since the failure is as expected.
