### ISSUE TITLE
ebs br: When the restore data pod fails, the volumerestore task status is not set to failed

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5293]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volumerestore
2. do chaos, Kill restore data container process

**What did you expect to see?**
1. volumerestore status is failed

**What did you see instead?**
1. volumerestore is running 
![d963e3f5-0616-4104-8573-ece477b5d3b1](https://github.com/pingcap/tidb-operator/assets/81375082/406e7a58-48a2-4c47-a423-2faa24d40948)
![f1401891-c047-48c2-8e11-ce29658939bf](https://github.com/pingcap/tidb-operator/assets/81375082/a03fe5c5-42a1-4643-8cfc-59121e7fd7a3)

**Comment by BornChanger** [comment]
It's a status update issue. Operator observer needs to refresh the status even if restore pod fails.
