### ISSUE TITLE
TiKV failure last for 1 minute can cause backup failure

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5294]
## Bug Report

**What version of Kubernetes are you using?**
br image:br-flute-ebs-all-6.5:230916142228

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do backup
2. use chaos mesh let tikv  failure last for 1 minute

**What did you expect to see?**
1. backup will success

**What did you see instead?**
1. backup failed
![6445b2d6-ddff-4517-9877-10e874be8584](https://github.com/pingcap/tidb-operator/assets/81375082/d00a1ed1-95a5-4596-b421-94af55baea57)

**Comment by BornChanger** [comment]
We have to tolerate the rare failure since it occurs at very early phase of backup.
