### ISSUE TITLE
kill restore-data pod will cause restore failed

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5295]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volumerestore
2. delete restore-data pod

**What did you expect to see?**
1. volumerestore success

**What did you see instead?**
1. restore-data pod restart and still running, but volumerestore failed
![52ecd84e-7b65-4845-93ba-ca8b655e40fe](https://github.com/pingcap/tidb-operator/assets/81375082/63ee9e51-472b-478b-a52c-5d06ba4cba33)
![img_v2_ecf9c922-ca17-4f03-b74e-db6a53f1928g](https://github.com/pingcap/tidb-operator/assets/81375082/5411ddf0-f035-47ee-ab83-f89e28244058)

**Comment by BornChanger** [comment]
The problem is fixed already.
