### ISSUE TITLE
Add network policy rules to TiDB cluster to isolate and secure user data

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#53]
Currently, any pod can access any TiDB clusters deployed in the same Kubernetes cluster, since by default TiDB root password is empty. To isolate and secure TiDB cluster, we should introduce [network policy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) to each TiDB cluster created by TiDB Operator.

**Comment by weekface** [comment]
I am working on this feature.

**Comment by weekface** [comment]
Discussed with @tennix @onlymellb and @xiaojingchen 
It is very hard for TiDB Operator creating and managing the NetworkPolicy object.

- we must let operator pods can access the TiDB cluster, so we must let the user add a Label to the operator's Namespace to create the NetworkPolicy
- the user may want to add IP CIDR to the NetworkPolicy or others
- the user may want to add other Namespace and its pods to access the TiDB cluser
- the user must configure a network provider with network policy support with K8s
- and others ...

All these are too complicated for operator to manage.
So we will give the user guide and document to let themselves to add NetworkPolicy to TiDB cluster.
