### ISSUE TITLE
volumeback failed. reason is "Pod backup-fed-ebs-tidb-operator-ebs-1-init-w5glk has failed, original reason "

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5330]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volumeback

**What did you expect to see?**
1. volmebackup success

**What did you see instead?**
1. volmebackup failed, can see reason is "Pod backup-fed-ebs-tidb-operator-ebs-1-init-w5glk has failed, original reason "
2. 
![img_v2_6ef13cd0-4198-45e8-aabe-91869f82d09g](https://github.com/pingcap/tidb-operator/assets/81375082/8a268ddb-331f-44d9-b26a-881e79a2f90d)
https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-10800~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20filter*20kubernetes.namespace_name*20*3d*20*22ebs-chaos-restore-2-tps-3060164-1-822*22*0a*7c*20filter*20kubernetes.pod_name*20*3d*20*22backup-fed-ebs-tidb-operator-ebs-1-init-w5glk*22*0a*23*7c*20filter*20kubernetes.container_name*20*20*3d*20*22grafana*22*0a*7c*20limit*202000~queryId~'c25405f92729be-9198c4d2-4364e8a-ecd04d9b-977ea26cd7aa2ce1f2b9215a~source~(~'*2faws*2fcontainerinsights*2fop-test-infra*2fapplication~'*2faws*2fcontainerinsights*2fop-test-infra*2fdataplane~'*2faws*2fcontainerinsights*2fop-test-infra*2fhost~'RDSOSMetrics))

**Comment by BornChanger** [comment]
Close it since it is duplicated with issue #5331
