### ISSUE TITLE
Tidb running in kubernetes cluster with non-default domain does not start with TLS enabled between tidb component

### ISSUE THREAD

**Issue by jarupatjdbr** [pingcap/tidb-operator#5375]
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:38:29Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}
```

**What version of TiDB Operator are you using?**
`TiDB Operator Version: version.Info{GitVersion:"v1.5.1", GitCommit:"2802a0834c50dab95e5eb4409dfbcc9717330721", GitTreeState:"clean", BuildDate:"2023-10-20T08:12:28Z", GoVersion:"go1.21.3", Compiler:"gc", Platform:"linux/arm64"}`

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

```
kubectl get sc
NAME                 PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
standard (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  36m
kubectl get pvc -n tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4
NAME                                                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pd-tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-0   Bound    pvc-a410b8ad-eb36-45c8-a5b7-5ba870bce6fc   1Gi        RWO            standard       33m
```

**What's the status of the TiDB cluster pods?**
```
NAME                                       READY   STATUS    RESTARTS   AGE   IP           NODE                 NOMINATED NODE   READINESS GATES
tidb-controller-manager-7946c7cff9-79dzt   1/1     Running   0          36m   10.244.0.6   kind-control-plane   <none>           <none>
tidb-scheduler-86f68bd7cf-w4czj            2/2     Running   0          36m   10.244.0.5   kind-control-plane   <none>           <none>
```

**What did you do?**
I would like to run tidb cluster in a non-default kubernetes cluster domain `mydomain.internal`. 
The main reason is that I have a dns name constraint in my CA certificate. This certificate can only generate a leaf certificate with DNS ending with `mydomain.internal`. 

So I tried to run TiDB and modify the internal DNS usage such that it append `mydomain.internal` to all the URL.

I have edited kubernetes CoreDNS config file to handle `mydomain.internal` similarly to `cluster.local`

```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes mydomain.internal cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
```

I then create tidb cluster. The only different I made is I set `tidbcluster.spec.clusterDomain` to `mydomain.internal`.

```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  <omit>
spec:
  clusterDomain: mydomain.internal
```

This allows PD to start up with correct URL that contains `svc.mydomain.internal`
```
starting pd-server ...
/pd-server --data-dir=/var/lib/pd --name=tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-0.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-peer.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4.svc.mydomain.internal --peer-urls=https://0.0.0.0:2380 --advertise-peer-urls=https://tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-0.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-peer.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4.svc.mydomain.internal:2380 --client-urls=https://0.0.0.0:2379 --advertise-client-urls=https://tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-0.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-peer.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4.svc.mydomain.internal:2379 --config=/etc/pd/pd.toml --initial-cluster=tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-0.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-peer.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4.svc.mydomain.internal=https://tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-0.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-peer.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4.svc.mydomain.internal:2380
2023-11-08 00:53:32.158996 W | pkg/fileutil: check file permission: directory "/var/lib/pd" exist, but the permission is "drwxrwxrwx". The recommended permission is "-rwx------" to prevent possible unprivileged access to the data.
```

**What did you expect to see?**

Tidb cluster is able to use non default cluster domain and able to start up correctly.

**What did you see instead?**

Tidb-operator has failure. 
```
E1108 00:53:20.579094       1 pd_member_manager.go:195] failed to sync TidbCluster: [tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4/tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4]'s status, error: Get "https://tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4:2379/pd/api/v1/health": dial tcp 10.96.176.167:2379: connect: connection refused
I1108 00:53:20.585004       1 tidb_cluster_controller.go:141] TidbCluster: tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4/tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4, still need sync: TidbCluster: [tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4/tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4], waiting for PD cluster running, requeuing
E1108 00:53:34.697055       1 pd_member_manager.go:195] failed to sync TidbCluster: [tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4/tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4]'s status, error: Get "https://tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4:2379/pd/api/v1/health": tls: failed to verify certificate: x509: certificate is valid for tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd.mydomain.internal, tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4.mydomain.internal, tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4.svc.mydomain.internal, tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-peer.mydomain.internal, tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-peer.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4.mydomain.internal, tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-peer.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4.svc.mydomain.internal, *.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-peer.mydomain.internal, *.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-peer.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4.mydomain.internal, *.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-peer.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4.svc.mydomain.internal, *.mydomain.internal, *.*.mydomain.internal, *.*.*.mydomain.internal, *.*.*.*.mydomain.internal, not tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4
I1108 00:53:34.703689       1 tidb_cluster_controller.go:141] TidbCluster: tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4/tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4, still need sync: TidbCluster: [tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4/tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4], waiting for PD cluster running, requeuing
```

I think it is because when tidb-opertor constructed PDClient URL, it does not use include the cluster domain. 

`https://tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4:2379/pd/api/v1/health`

I think it might be related to this code. It looks like we only use `clusterdomain` when it is a Heterogeneous cluster. However, this is not a heterogenous cluster. 
https://github.com/pingcap/tidb-operator/blob/b7170fa/pkg/controller/pd_control.go#L30

Can we fix this so that tidb operator is able to operate in a non-default kubernetes domain?

**Comment by csuzhangxc** [comment]
TiDB Operator doesn't append the `clusterdomain` part when accessing service within the current Kubernetes, and this should work well if the CA can issue a cert for `*.${ns}.svc`.

But as you reported, your CA can't issue such a cert. So do you suggest appending the `clusterdomain` if it's non-default kubernetes domain?

**Comment by jarupatjdbr** [comment]
Yes that is my suggestion. Because the code in pd can already start with correct domain

starting pd-server ...
/pd-server --data-dir=/var/lib/pd --name=tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-0.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4-pd-peer.tidb-2b938dad-e7d9-4ee1-bc36-4cea1c439fd4.**svc.mydomain.internal**

**Comment by csuzhangxc** [comment]
OK. Cloud you try to append the `clusterdomain` and verify if are there more problems that exist.

**Comment by jarupatjdbr** [comment]
Are you asking me to to make the change to tidb-operator? I think it might be easier for you to do it. I have explain my setup in the bug. You just need to set `tidbcluster.spec.clusterDomain` and update CoreDNS config.

**Comment by csuzhangxc** [comment]
@jarupatjdbr Hi, I tested this case. I found other components (TiKV, TiDB, TiCDC, ...) are using `${cluster-name}-pd` (without any suffix) to connect to PD. If we append the suffix in the start script, any existing clusters with `clusterDomain` configured will be restarted.

So, I want to know, is it possible in your case to disable mTLS or update the CA to issue a cert without the `clusterDomain`.

**Comment by jarupatjdbr** [comment]
> I found other components (TiKV, TiDB, TiCDC, ...) are using ${cluster-name}-pd (without any suffix) to connect to PD.  f we append the suffix in the start script, any existing clusters with clusterDomain configured will be restarted.

I don't quite understand. If it is a newly created cluster, restarting should not be an issue, right? For existing cluster, we probably do not want to change the `clusterdomain` anyway.

**Comment by csuzhangxc** [comment]
> > I found other components (TiKV, TiDB, TiCDC, ...) are using ${cluster-name}-pd (without any suffix) to connect to PD.  f we append the suffix in the start script, any existing clusters with clusterDomain configured will be restarted.
> 
> I don't quite understand. If it is a newly created cluster, restarting should not be an issue, right? For existing cluster, we probably do not want to change the `clusterdomain` anyway.

I mean, this may affect existing clusters for other users. Do you mind if we add another command feature flag to enable this update?

**Comment by jarupatjdbr** [comment]
It is OK if you add another field in the CRD to enable this.

**Comment by csuzhangxc** [comment]
@jarupatjdbr in #5561, I improved the `StartScriptV2FeatureFlagPreferPDAddressesOverDiscovery` feature introduced in #5400, then TidbClusters with TLS enabled and customized K8s cluster domain should work.

```yaml
spec:
  clusterDomain: mydomain.internal
  startScriptVersion: v2
  startScriptV2FeatureFlags:
  - PreferPDAddressesOverDiscovery
  pdAddresses:
    - https://basic-pd.tls.svc.mydomain.internal:2379
  tlsCluster:
    enabled: true
```

**Comment by csuzhangxc** [comment]
close via #5561

**Comment by jarupatjdbr** [comment]
@csuzhangxc what version of tidb or tidb-operator will the fix be in?

**Comment by csuzhangxc** [comment]
@jarupatjdbr v1.5.3, which may be released in the next month.
