### ISSUE TITLE
Pod disaster tolerance bug

### ISSUE THREAD

**Issue by shuijing198799** [pingcap/tidb-operator#539]
## Bug Report

**What version of Kubernetes are you using?**

1.2.5
**What version of TiDB Operator are you using?**

pingcap/tidb-operator:latest in e2e test
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

local storage
**What's the status of the TiDB cluster pods?**

e2e-cluster1-discovery-574887d886-9prjh         1/1       Running     0          21m       10.244.2.127   kube-node-5
e2e-cluster1-monitor-7c9cd78fc9-66qwz           2/2       Running     0          21m       10.244.4.142   kube-node-4
e2e-cluster1-other-discovery-5d64c7bb5c-4nlw5   1/1       Running     0          1h        10.244.3.121   kube-node-3
e2e-cluster1-other-monitor-f44d88599-z5t45      2/2       Running     0          1h        10.244.5.112   kube-node-2
e2e-cluster1-other-pd-0                         1/1       Running     2          1h        10.244.2.118   kube-node-5
e2e-cluster1-other-pd-1                         1/1       Running     0          1h        10.244.6.100   kube-node-1
e2e-cluster1-other-pd-2                         1/1       Running     0          1h        10.244.3.122   kube-node-3
e2e-cluster1-other-tidb-0                       1/1       Running     0          1h        10.244.3.124   kube-node-3
e2e-cluster1-other-tidb-initializer-cncsf       0/1       Completed   4          1h        10.244.5.111   kube-node-2
e2e-cluster1-other-tikv-0                       1/1       Running     0          1h        10.244.3.123   kube-node-3
e2e-cluster1-other-tikv-1                       1/1       Running     0          1h        10.244.1.112   kube-node-6
e2e-cluster1-other-tikv-2                       1/1       Running     0          1h        10.244.5.113   kube-node-2
e2e-cluster1-pd-0                               1/1       Running     0          21m       10.244.4.143   kube-node-4
e2e-cluster1-pd-1                               1/1       Running     1          21m       10.244.1.122   kube-node-6
e2e-cluster1-pd-2                               1/1       Running     0          21m       10.244.2.128   kube-node-5
e2e-cluster1-tidb-0                             1/1       Running     0          20m       10.244.2.131   kube-node-5
e2e-cluster1-tidb-1                             1/1       Running     0          20m       10.244.4.147   kube-node-4
e2e-cluster1-tidb-initializer-bz6kl             0/1       Completed   4          21m       10.244.4.141   kube-node-4
**e2e-cluster1-tikv-0                             1/1       Running     0          20m       10.244.4.146   kube-node-4
e2e-cluster1-tikv-1                             1/1       Running     0          20m       10.244.2.130   kube-node-5
e2e-cluster1-tikv-2                             1/1       Running     0          20m       10.244.6.113   kube-node-1**
**What did you do?**

I have 7 nodes, master and node 1 - 6, and I assigned the seven nodes to 3 racks. Master is rack-0 node1 is rack-1 and so on. From the cluster distribution above, we can see that among the three KV nodes, e2e-cluster1-tikv-0  and e2e-cluster1-tikv-2 are in the same rack and do not meet the definition of disaster tolerance.
**What did you expect to see?**
Hope that all components meet the standards of disaster tolerance
**What did you see instead?**
as <what did you do>

**Comment by weekface** [comment]
@xiaojingchen ptal

**Comment by xiaojingchen** [comment]
what is the operator and charts' version

**Comment by xiaojingchen** [comment]
did you set affinity setting

**Comment by shuijing198799** [comment]
> did you set affinity setting?

I meet the problem in e2e test, so the operator and chart is the newest, Does the affinity setting is default to open or close ?

**Comment by shuijing198799** [comment]
affinity:
   podAntiAffinity:
     preferredDuringSchedulingIgnoredDuringExecution:
     - podAffinityTerm:
         labelSelector:
           matchLabels:
             app.kubernetes.io/component: tikv
             app.kubernetes.io/instance: e2e-cluster1
         namespaces:
         - e2e-cluster1
         topologyKey: rack
       weight: 10
