### ISSUE TITLE
[EBS BR] Invalid phase during WarmupStarted

### ISSUE THREAD

**Issue by nkg-** [pingcap/tidb-operator#5415]
## Bug Report

**What version of Kubernetes are you using?**
NA

**What version of TiDB Operator are you using?**
1.5.1

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
NA

**What's the status of the TiDB cluster pods?**
NA

**What did you do?**
Ran VolumeRestore. [CR](https://gist.github.com/oliviachenairbnb/b4101408272b654b9f6deac75798a2eb)

**What did you see instead?**
When Warmup is started for data plane (ie WarmupStarted), the phase is still VolumeComplete. 

**What did you expect to see?**
We expect to see the phase as WarmupStarted.

**Comment by BornChanger** [comment]
The problem should be fixe by PR https://github.com/pingcap/tidb-operator/pull/5370

**Comment by nkg-** [comment]
Sounds great.
