### ISSUE TITLE
`Restore` does not start restore job

### ISSUE THREAD

**Issue by emchristiansen** [pingcap/tidb-operator#5484]
## Bug Report

If I follow [the commands here](https://docs.pingcap.com/tidb-in-kubernetes/stable/restore-from-aws-s3-using-br) and run `kubectl apply -f restore-full-s3.yaml`, a Restore job is not actually created.

I _do_ see that the controller sees the Restore job:

<img width="1719" alt="Screenshot 2023-12-21 at 20 00 58" src="https://github.com/pingcap/tidb-operator/assets/225668/d1146358-6a1a-498e-b078-8d487e8b295a">

But, no restore job is created.

These are my versions:

```
KUBECTL_VERSION = "1.27.8"
# Find latest release here:
# https://github.com/k0sproject/k0s
K0S_VERSION = "1.27.8+k0s.0"
# https://github.com/pingcap/tidb-operator/releases
TIDB_OPERATOR_VERSION = "v1.5.1"
# https://docs.pingcap.com/tidb/stable/release-notes
TIDB_VERSION = "v7.5.0"
TIDB_MONITOR_INITIALIZER_VERSION = "v7.5.0"
TIDB_NG_MONITOR_VERSION = "v7.5.0"
TIDB_MONITOR_RELOADER_VERSION = "v1.0.1"
ALPINE_VERSION = "3.16.0"
PROMETHEUS_VERSION = "v2.27.1"
GRAFANA_VERSION = "7.5.11"
PROMETHEUS_RELOADER_VERSION = "v0.49.0"
NVIDIA_DEVICE_PLUGIN_VERSION = "0.14.3"
```

**Comment by csuzhangxc** [comment]
what's the current status of this restore CR?

**Comment by emchristiansen** [comment]
Digging a bit more, if I run `kubectl describe job restore-restore -n tidb-cluster` I see:

```
Error creating: pods "restore-restore-" is forbidden: error looking up service account tidb-cluster/tidb-backup-manager: serviceaccount "tidb-backup-manager" not found
```

**Comment by emchristiansen** [comment]
So, the `tidb-backup-manager` SA was created, but in the default namespace, not `tidb-cluster` where it was needed.

I fixed the problem by modifying [this template](https://raw.githubusercontent.com/pingcap/tidb-operator/1.5.1/manifests/backup/backup-rbac.yaml) to specify the namespace.

Also, it's weird that this worked before but not now - I did upgrade K8s so perhaps that changed some SA namespace semantics.

**Comment by csuzhangxc** [comment]
[in the document you mentioned above](https://docs.pingcap.com/tidb-in-kubernetes/stable/restore-from-aws-s3-using-br), 

`Step 1: Prepare the restore environment`

`2. Download backup-rbac.yaml, and execute the following command to create the role-based access control (RBAC) resources in the restore-test namespace:`

**Comment by emchristiansen** [comment]
Ah, you're correct!

Still don't know why this worked in my old setup and not the new one though.
