### ISSUE TITLE
volumebackup failed when backup restored cluster

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5537]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volumebackup
2. do volumerestore
3. do backup on restored cluster
**What did you expect to see?**
1. backup success
**What did you see instead?**
1. backup failed

**Comment by BornChanger** [comment]
also track in https://github.com/pingcap/tidb/issues/50878

**Comment by BornChanger** [comment]
pr is merged.
