### ISSUE TITLE
volumebackup will failed when there is more than 50 tags specified in snapshot

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5540]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. Repeat volume backup and volume restore 5 times

**What did you expect to see?**
1. The sixth backup was successful

**What did you see instead?**
1. volumebackup failed
2. 
![img_v3_027l_edc8d6f7-f894-44d6-812c-157f2b9850bg](https://github.com/pingcap/tidb-operator/assets/81375082/145fa754-81eb-40f9-bd9f-9595998c5431)

**Comment by BornChanger** [comment]
closed by https://github.com/pingcap/tidb/pull/50941
