### ISSUE TITLE
More stability tests

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#555]
- [x] stop kube-apiserver
  - https://github.com/pingcap/tidb-operator/issues/541 fix the cluster first, use the load balancer for the kube-apiserver
  - https://github.com/pingcap/tidb-operator/pull/896/files#diff-8f8eafaeec65b7926966885b1c103ca8R298
- [x] stop kube-scheduler https://github.com/pingcap/tidb-operator/pull/583
- [x] stop kube-controller-manager https://github.com/pingcap/tidb-operator/pull/583
- [x] stop kubelet https://github.com/pingcap/tidb-operator/pull/665
- [x] stop kube-proxy
  - ~~https://github.com/pingcap/tidb-operator/pull/503~~ https://github.com/pingcap/tidb-operator/pull/556

**Comment by aylei** [comment]
@cofyc https://github.com/pingcap/tidb-operator/pull/896/files#diff-8f8eafaeec65b7926966885b1c103ca8R298 has added the case
