### ISSUE TITLE
Invalid chart during install

### ISSUE THREAD

**Issue by luyomo** [pingcap/tidb-operator#5562]
## Bug Report

**What version of Kubernetes are you using?**
workstation$ kubectl version 
Client Version: v1.29.0-eks-5e0fdde
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0-eks-c417bb3

**What version of TiDB Operator are you using?**
workstation$ kubectl exec -n tidb-admin tidb-controller-manager-86bb89ddd-6j5w5 -- tidb-controller-manager -V
TiDB Operator Version: version.Info{GitVersion:"v1.5.2", GitCommit:"456a0273f67ac61212da78956f49f0a4a07e21d8", GitTreeState:"clean", BuildDate:"2024-01-19T03:50:22Z", GoVersion:"go1.21.5", Compiler:"gc", Platform:"linux/amd64"}

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
Not installed

**What's the status of the TiDB cluster pods?**
Not installed

**What did you do?**
helm install --namespace tidb-admin tidb-operator pingcap/tidb-operator --version v1.5.2

**What did you expect to see?**
Install without such unexpected messages. 

**What did you see instead?**
admin@ip-172-81-31-113:~/aws$ helm install --namespace tidb-admin tidb-operator pingcap/tidb-operator --version v1.5.2
index.go:370: skipping loading invalid entry for chart "tidb-drainer" "ms-alpha.3" from /home/admin/.cache/helm/repository/pingcap-index.yaml: validation: chart.metadata.version "ms-alpha.3" is invalid
index.go:370: skipping loading invalid entry for chart "tidb-drainer" "ms-alpha.3" from /home/admin/.cache/helm/repository/pingcap-index.yaml: validation: chart.metadata.version "ms-alpha.3" is invalid
index.go:370: skipping loading invalid entry for chart "tidb-drainer" "ms-alpha.1" from /home/admin/.cache/helm/repository/pingcap-index.yaml: validation: chart.metadata.version "ms-alpha.1" is invalid
index.go:370: skipping loading invalid entry for chart "tidb-drainer" "ms-alpha.4" from /home/admin/.cache/helm/repository/pingcap-index.yaml: validation: chart.metadata.version "ms-alpha.4" is invalid
index.go:370: skipping loading invalid entry for chart "tidb-lightning" "ms-alpha.1" from /home/admin/.cache/helm/repository/pingcap-index.yaml: validation: chart.metadata.version "ms-alpha.1" is invalid
index.go:370: skipping loading invalid entry for chart "tidb-lightning" "ms-alpha.3" from /home/admin/.cache/helm/repository/pingcap-index.yaml: validation: chart.metadata.version "ms-alpha.3" is invalid
index.go:370: skipping loading invalid entry for chart "tidb-lightning" "ms-alpha.3" from /home/admin/.cache/helm/repository/pingcap-index.yaml: validation: chart.metadata.version "ms-alpha.3" is invalid
index.go:370: skipping loading invalid entry for chart "tidb-lightning" "ms-alpha.4" from /home/admin/.cache/helm/repository/pingcap-index.yaml: validation: chart.metadata.version "ms-alpha.4" is invalid
index.go:370: skipping loading invalid entry for chart "tidb-operator" "ms-alpha.3" from /home/admin/.cache/helm/repository/pingcap-index.yaml: validation: chart.metadata.version "ms-alpha.3" is invalid
index.go:370: skipping loading invalid entry for chart "tidb-operator" "ms-alpha.4" from /home/admin/.cache/helm/repository/pingcap-index.yaml: validation: chart.metadata.version "ms-alpha.4" is invalid
index.go:370: skipping loading invalid entry for chart "tidb-operator" "ms-alpha.1" from /home/admin/.cache/helm/repository/pingcap-index.yaml: validation: chart.metadata.version "ms-alpha.1" is invalid
index.go:370: skipping loading invalid entry for chart "tidb-operator" "ms-alpha.3" from /home/admin/.cache/helm/repository/pingcap-index.yaml: validation: chart.metadata.version "ms-alpha.3" is invalid

**Comment by csuzhangxc** [comment]
some internal versions of the Helm Chart with invalid version format were pushed to the Helm index, this is harmless, and we'll clear them in the future.

**Comment by csuzhangxc** [comment]
invalid charts have been removed
