### ISSUE TITLE
tikv crash during volumerestore

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5577]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volumebackup
2. do volumerestore

**What did you expect to see?**
1. volumerestore success

**What did you see instead?**
1. volumerestore failed
2. Confirmed corruption is likely in rocksdb layer, rather than EBS snapshots. Corrupt log file was generated (and last fsynced as per manifest), 15 seconds before ebs snapshots started. 
There is some unknown write path which does partial writes to wal file, without updating the manifest.

**Comment by BornChanger** [comment]
duplicate
