### ISSUE TITLE
A TiKV was restarted before it was stopped for scheduling, and BR did not exit in a timely manner and set the status to failed, resulting in the cluster remaining in the pause schedule state

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5583]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do rolling restart
2. do volumebackup

**What did you expect to see?**
1. volumebackup success
2. The pause schedule lasts for a short period of time

**What did you see instead?**
1. volumebackup is stuck, when exceed Volume Backup Init Job Max Active Seconds, volumebackup is set to failed
2. 
![img_v3_0295_c15d2c9e-311b-4186-81b8-366bd787a74g](https://github.com/pingcap/tidb-operator/assets/81375082/eb7dbed4-cf70-4a76-bc2d-7b4d09305ae3)

![img_v3_0295_7667b5b9-b3a4-4a11-8b60-5cc8996adeeg](https://github.com/pingcap/tidb-operator/assets/81375082/2bf80c5a-d56e-4159-833f-36e57833fc3d)
![img_v3_0294_5b2d712b-d82b-4941-8cdd-1424aa0e540g](https://github.com/pingcap/tidb-operator/assets/81375082/809a1e6f-e9f1-4eb4-9826-6eecf89e86b0)
![image](https://github.com/pingcap/tidb-operator/assets/81375082/c9e0252e-601c-43dc-b9ac-62259ded7a22)

**Comment by BornChanger** [comment]
track and closed in tidb repo https://github.com/pingcap/tidb/issues/52243
