### ISSUE TITLE
How to remove a failed TiKV store when using local storage

### ISSUE THREAD

**Issue by healthwaite** [pingcap/tidb-operator#5642]
## Question

How do I cleanly remove a failed TiKV store when using local storage? Here's the scenario: I start with 5 TiKV pods and 5-way replication enabled. The TiKV pods are selected to run on nodes which have the label `node-role.kubernetes.io/tikv=true`. The TiKV pods are using local storage. I simulate one of the nodes failing by removing the `node-role.kubernetes.io/tikv=true` label and killing one of the tikv pods: `basic-tikv-2`:

```
>>>>>>>> $ kubectl -n tidb-cluster get pods -l app.kubernetes.io/component=tikv
NAME           READY   STATUS    RESTARTS   AGE
basic-tikv-0   1/1     Running   0          112s
basic-tikv-1   1/1     Running   0          111s
basic-tikv-2   0/1     Pending   0          33s
basic-tikv-3   1/1     Running   0          111s
basic-tikv-4   1/1     Running   0          111s
```

After `controllerManager.tikvFailoverPeriod + pd.max-store-down-time` a new store, `basic-tikv-5` is created. Leaving me with 5 running TiKV pods and the old failed pod:

```
$ kubectl -n tidb-cluster get pods -l app.kubernetes.io/component=tikv
NAME           READY   STATUS    RESTARTS   AGE
basic-tikv-0   1/1     Running   0          3m34s
basic-tikv-1   1/1     Running   0          3m33s
basic-tikv-2   0/1     Pending   0          2m15s
basic-tikv-3   1/1     Running   0          3m33s
basic-tikv-4   1/1     Running   0          3m33s
basic-tikv-5   1/1     Running   0          32s

```

As expected basic-tikv-2 can't start because it can't access the local storage because the node is dead. As it stands I have 5 replicas and the cluster is healthy. However, if I try and update the `TidbCluster` custom resource it will successfully restart pods basic-tikv-5, basic-tikv-4 and basic-tikv-3 and then fail on pod basic-tikv-2 because it is stuck in the pending state.

It seems the only way to proceed is to get basic-tikv-2 healthy and running? I can do this by removing the PVC for tikv-2, removing the store using pd-ctl unsafe remove-failed-stores and then restarting basic-tikv-2.

**My question:** what is the correct way to keep pods basic-tikv-0, basic-tikv-1, basic-tikv-3, basic-tikv-4 and basic-tikv-5 and removing the old failed pod basic-tikv-2? 

Things I have tried:

Attempt 1: removing the store from the TidbCluster CR as specified [here](https://docs-archive.pingcap.com/tidb-in-kubernetes/v1.0/use-auto-failover#failover-with-tikv). This doesn't work it just removes `basic-tikv-5` rather than the previously failed store basic-tikv-2.

Attempt 2: Installing the AdvancedStateful set and setting an annotation to remove `[2]`. This doesn't work either again it just removes basic-tikv-5.

Any help would be greatly appreciated! Thank you

**Comment by healthwaite** [comment]
After playing around it looks like the correct way to handle this scenario is to:
1. Enable the advanced statefulset when installing the operator
2. To remove basic-tikv-2, edit the `TidbCluster` CR and change tikv.statefulset.replicas to the desired number (5) and set the `annotations.tikv.tidb.pingcap.com/delete-slots: '[2]'`.

Note the documentation [here](https://docs.pingcap.com/tidb-in-kubernetes/stable/advanced-statefulset) says to set `tikv.replicas` to the 5, which doesn't help in this scenario.

Would someone be able to confirm what I've just written? I think it would be useful to update the documentation to detail how to remove a failed pods.

**Comment by csuzhangxc** [comment]
To remove a failed TiKV, if you don't want to use Advanced StatefulSet, the correct way is:

> I can do this by removing the PVC for tikv-2, removing the store using pd-ctl unsafe remove-failed-stores and then restarting basic-tikv-2.

If you want to use Advanced StatefulSet, the correct way is:

> Enable the advanced statefulset when installing the operator;  set the annotations.tikv.tidb.pingcap.com/delete-slots: '[2]'

There is no need to change the `tikv.replicas`.

---

> Note the documentation [here](https://docs.pingcap.com/tidb-in-kubernetes/stable/advanced-statefulset) says to set tikv.replicas to the 5, which doesn't help in this scenario.

Do you have any details about this?

**Comment by healthwaite** [comment]
> To remove a failed TiKV, if you don't want to use Advanced StatefulSet, the correct way is...:
Apologies! I've just retried this and setting the annotation does seem to do the correct thing. Maybe I didn't wait long enough.

One further question. If I am using TiKV with local storage and I remove a failed TiKV via the Advanced StatefulSet annotation should I also use `pd-ctl unsafe remove-failed-stores` to remove the store? If so is it better to use `remove-failed-store` before or after setting the statefulset annotation?

Thanks.

**Comment by csuzhangxc** [comment]
> `emove-failed-stores` to rem

You can use remove-failed-store after setting the statefulset annotation
