### ISSUE TITLE
[Documentation] A guide on how to safely remove nodes.

### ISSUE THREAD

**Issue by kkimdev** [pingcap/tidb-operator#566]
[The current operation guide](https://github.com/pingcap/tidb-operator/blob/master/docs/operation-guide.md) doesn't explain how to safely downscale TIDB.  I suspect that it's not as simple as just draining the nodes to remove as it the data migration can take more than the default pod termination grace period(30sec) https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods .  But in any case, it will be great to have it documented.

**Comment by tennix** [comment]
@kkimdev Scale in TiDB cluster is as simple as changing the component replicas and run `helm upgrade` as documented in the [operation guide](https://github.com/pingcap/tidb-operator/blob/master/docs/operation-guide.md#horizontal-scaling).

As for removing k8s nodes, there are some extra steps. We'll add the document soon. But if you are familiar with k8s, then after the component replica count is decreased, removing the k8s node can simply be achieved by `kubectl drain node` command.

**Comment by weekface** [comment]
https://github.com/pingcap/docs-cn/pull/1417
