### ISSUE TITLE
Support customized values file for helm in the terraform scripts

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#574]
## Feature Request

**Is your feature request related to a problem? Please describe:**

This issue is related to #494 , but they are concentrate on the different use case.

**Describe the feature you'd like:**

When I try to explain some helm operations for tidb cluster managed by terraform to our users, I find I have to guide the user to modify the template file of `values.yaml`, which is informal and hard to maintain. 

We will totally separate the management of TiDB cluster and infrastructure when we can automatically provision node by Cluster Autoscaler or a customized node controller. However, it is necessary to provide a decent (and easy to implement) solution for now.

I propose adding a new terraform variable `helm_values` to enable full customization of tidb cluster in terraform:

```
variable "helm_values" {
    description = "The hem values file passed to `helm upgrade` and `helm install`, which helps customizing the TiDB cluster"
    default = ""
}
```

The default value is `empty-string`, which has no effect. 

An example usage:
```
TF_VAR_HELM_VALUES=values.yaml terraform apply
```

Another consideration is that user may accidentally edit the fields managed by terraform (e.g. `tikv.replicas`). To tackle with this,  we can change the render process: instead of rendering the `values.yaml`, we render the helm arguments, for example:

```
--set-string tikv.replicas=3,pd.replicas=3,tidb.replicas=2 -f values.yaml
```

The arguments passed by `--set` or `--set-string` takes higher priority to the values file, which helps avoiding the mis-configuration.

Then the template file of `values.yaml` can be removed.

**Teachability, Documentation, Adoption, Migration Strategy:**

This change is backward compatible, we can document how terraform and helm are integrated more clearly when we implemented this.

@gregwebs @tennix @jlerche @AstroProfundis PTAL

**Comment by gregwebs** [comment]
With the current arrangement the approach is a big improvement: do not template a values.yaml, instead generate `--set` arguments.
This fixes the biggest issue that the current setup does no have any extensibility.
Also, this change is easy to make. Therefore I would recommend making it immediately.

However, keep in mind that although this fixes the extensibility problem it doesn't fix the architectural problem. Terraform is still the source of truth for the tidb operator deployment that must be the one running helm. Instead terraform should setup infrastructure and be refreshed from the information provided by the tidbcluster CRD.
