### ISSUE TITLE
Terraform should use released helm charts

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#575]
## Feature Request

**Describe the feature you'd like:**

Currently, the terraform scripts using the chart inside this repository, which is may not stable. We should use the release chart instead and add a new terraform variable to specify the chart version:

```
variable "helm_chart_version" {
    default = "v1.0.0-beta.3"
}
```

- [x] AWS (merged): #616 
- [x] Alibaba Cloud: #658 
- [x] GKE #717 

@gregwebs @jlerche @tennix @weekface PTAL

**Comment by jlerche** [comment]
I think that's a good idea :+1:

**Comment by jlerche** [comment]
Closing now that #717 has been merged.
