### ISSUE TITLE
local-kind-tutorial

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#587]
## Feature Request

[kind](https://github.com/kubernetes-sigs/kind) is a more active project than [kubeadm-dind-cluster](https://github.com/kubernetes-sigs/kubeadm-dind-cluster).

Both of them support running a multiple-node cluster locally.

**Comment by gregwebs** [comment]
DinD has not been completely reliable for me. Before having a goal of a tutorial we should try testing out tidb-operator with kind.

**Comment by cofyc** [comment]
Closed via https://github.com/pingcap/tidb-operator/pull/791.
