### ISSUE TITLE
Replace backup/restore script with rclone

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#589]
## Feature Request

**Is your feature request related to a problem? Please describe:**

None

**Describe the feature you'd like:**

[rclone](https://github.com/ncw/rclone) is an `rsync` tool for cloud storage. It supports many (almost all) cloud storage backend. It's an ideal tool for cloud backup/restore scenario. Our current backup/restore is based on a tool written with [go-cloud](https://github.com/google/go-cloud). It only supports GCP, AWS, and Azure, so very limited.

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

When replacing with rclone, we should keep the values.yaml as before to keep backward compatible.

**Comment by gregwebs** [comment]
does rclone help us stream to object storage? Streaming without large intermediate disk needs to be a requirement.

**Comment by onlymellb** [comment]
The new backup solution #747  uses rclone to upload backup data.
