### ISSUE TITLE
tidb spec support loadBalancerClass

### ISSUE THREAD

**Issue by xiaozhuang-a** [pingcap/tidb-operator#5952]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When deploying TiDB and configuring the cluster entry, I selected loadBalancer, but the default loadBalancerClass of Alibaba Cloud is clb, which has a QPS limit of 50,000. I am considering using nlb instead, but nlb requires configuring service.spec.loadBalancerClass.

**Describe the feature you'd like:**

tidb-cluster tidb.service support loadBalancerClass

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by csuzhangxc** [comment]
we recommend to create an extra customized `Service` for LoadBalancer, also ref #5543
