### ISSUE TITLE
Enable scheduled backup to Amazon S3

### ISSUE THREAD

**Issue by shinnosuke-okada** [pingcap/tidb-operator#604]
## Feature Request

**Is your feature request related to a problem? Please describe:**
With current set of helm charts and terraform scripts, mydumper backup data cannot be uploaded to Amazon S3.

**Describe the feature you'd like:**
Enable the option to upload backup data to Amazon S3 using `scheduledBackup`.

**Describe alternatives you've considered:**
N/A

**Teachability, Documentation, Adoption, Migration Strategy:**
N/A

**Comment by gregwebs** [comment]
Have you tried using the [ceph configuration](https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-backup/templates/backup-job.yaml#L49)? ceph uses the AWS API.

**Comment by shinnosuke-okada** [comment]
`uploader` uses a ceph specific code:
https://github.com/pingcap/tidb-cloud-backup/blob/master/pkg/setup.go#L108
Made changes on my end to get it to work:
https://github.com/shinnosuke-okada/tidb-operator/tree/support-s3-backup

**Comment by gregwebs** [comment]
It looks like you added support for specifying the region. Can you open a pull request?

**Comment by shinnosuke-okada** [comment]
Will do once I pass all your test suites. Currently struggling to get tidb-operator-e2e to work locally.

**Comment by gregwebs** [comment]
I don't think the existing test suite will execute this new template code, although I don't have much familiarity with the e2e testing.

**Comment by shinnosuke-okada** [comment]
Okay. In that case, I'll perform a basic manual test tomorrow, and open a PR. Thanks :)

**Comment by shinnosuke-okada** [comment]
PR merged. Closing the issue.
