### ISSUE TITLE
Closer errors are ignored.

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#614]
## Bug Report

In [this commit](https://github.com/pingcap/tidb-operator/commit/44fff7a3e33ecf1e363af3e511749d95f2bec2e4#diff-1939da385d8e9a47974ec2acfd561c0c) the errors from `DeferClose` were all ignored. Its possible that we might decide we want to ignore all Closer errors (one option would be just to log them), but then we should have a different function that doesn't pass in an error param.

Note that I currently have PRs #581 #618  open that moves this file (so changes to this file will have merge conflicts with it).

**Comment by xiaojingchen** [comment]
@gregwebs  you mean add a new function like follow
``` golang 
func DeferClose(c io.Closer) {
	if err := c.Close(); err != nil {
		// log err
	}
}
```
is it right?

**Comment by gregwebs** [comment]
Yes.

**Comment by xiaojingchen** [comment]
At present, there is no need for this method. I will add it when needs it.

**Comment by gregwebs** [comment]
The code doesn't make sense right now since it passes in a pointer to an error and then doesn't use the error. I would suggest putting a link to this issue at the current DeferClose function so that the code can be understood.

**Comment by xiaojingchen** [comment]
I would like to remove the error pointer, directly to print error log when failed to close. the closing error should not expose to outside.
