### ISSUE TITLE
AWS terraform default to multiple environments

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#628]
Our terraform should default to a setup in which one can make multiple instantiations (environments). One just needs to use it as a module instead of changing the terraform directly. The layout change is outlined here, along with some additional discussion:

https://github.com/pingcap/tidb-operator/pull/616#issuecomment-507914194

**Comment by aylei** [comment]
I will do this along with the alibaba cloud multiple cluster refactoring, because I realize that the reusing of `tidb-operator` helm release and `tidb-cluster` helm release across different cloud providers is necessary.
