### ISSUE TITLE
No design and implementing document of TiDB Operator

### ISSUE THREAD

**Issue by jason4wy** [pingcap/tidb-operator#63]
Maybe should provide the design and implement document of TiDB operator .

**Comment by tennix** [comment]
Thanks for your suggestions! Currently, we don't have enough manpower to maintain formal design documentation. But for future features, we'll discuss on GitHub issues, so everyone can join and discuss with us on GitHub.

**Comment by gregwebs** [comment]
We do have some existing internal documentation on the original design direction and also some potential talks we will give at conferences that will touch on this subject. Between the two we should probably be able to create a document to describe some aspects of the architecture and implementation.

**Comment by jason4wy** [comment]
we can amplify this topic，  it is a big topic that is how to extend K8S...

**Comment by aylei** [comment]
closed via #651 , feel free to reopen if the current document don't meet your needs @jason4wy
