### ISSUE TITLE
tidb-controller-manager crashed over and over

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#630]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
**What version of TiDB Operator are you using?**

TiDB Operator Version: version.Info{TiDBVersion:"2.1.0", GitVersion:"v1.0.0-beta.3.24+5bf7fc1a672a55-dirty", GitCommit:"5bf7fc1a672a550983aca3a827738cda28df5c5d", GitTreeState:"dirty", BuildDate:"2019-07-04T02:35:04Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**What's the status of the TiDB operator pods?**

tidb-controller-manager-7fcfbf7779-zqt28   1/1   Running   0     52s   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   0/1   Error   0     6m32s   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   1/1   Running   1     6m59s   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   0/1   Error   1     7m22s   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   0/1   CrashLoopBackOff   1     7m32s   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   1/1   Running   2     7m52s   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   0/1   Error   2     8m19s   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   0/1   CrashLoopBackOff   2     8m31s   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   1/1   Running   3     9m10s   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   0/1   Error   3     10m   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   0/1   CrashLoopBackOff   3     10m   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   1/1   Running   4     11m   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   0/1   Error   4     12m   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   0/1   CrashLoopBackOff   4     12m   10.233.79.76   172.16.4.155   <none>
tidb-controller-manager-7fcfbf7779-zqt28   1/1   Running   5     14m   10.233.79.76   172.16.4.155   <none>
**What did you do?**

Just install and upgrade TiDB cluster with helm
**What did you expect to see?**
TiDB Operator keeps running stablely
**What did you see instead?**
TiDB Operator goes down over and over agin

Here are the logs:
I0704 03:33:48.399646       1 leaderelection.go:249] failed to renew lease tidb-admin/tidb-controller-manager: failed to tryAcquireOrRenew context deadline exceeded
F0704 03:33:48.698611       1 main.go:142] leader election lost

**Comment by weekface** [comment]
etcd logs:
```
7月 04 11:33:50 172.16.4.155 etcd[13779]: read-only range request "key:\"/registry/controllerrevisions\" range_end:\"/registry/controllerrevisiont\" count_only:true " with result "range_response_count:0 size:9" took too long (102.784224ms) to execute
7月 04 11:34:03 172.16.4.155 etcd[13779]: read-only range request "key:\"/registry/persistentvolumeclaims/dan3/tikv-dan3-tikv-0\" " with result "range_response_count:1 size:783" took too long (158.328374ms) to execute
7月 04 11:34:04 172.16.4.155 etcd[13779]: request "header:<ID:15788330935575962974 username:\"etcd-node-172\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/minions/172.16.4.159\" mod_revision:3102509 > success:<request_put:<key:\"/registry/minions/172.16.4.159\" value_size:8076 >> failure:<>>" with result "size:20" took too long (117.537927ms) to execute
7月 04 11:35:17 172.16.4.155 etcd[13779]: store.index: compact 3101952
7月 04 11:35:17 172.16.4.155 etcd[13779]: finished scheduled compaction at 3101952 (took 15.95545ms)
7月 04 11:40:17 172.16.4.155 etcd[13779]: store.index: compact 3102717
7月 04 11:40:17 172.16.4.155 etcd[13779]: finished scheduled compaction at 3102717 (took 12.324439ms)
7月 04 11:40:38 172.16.4.155 etcd[13779]: request "header:<ID:14091318300993196612 username:\"etcd-node-172\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/services/endpoints/kube-system/kube-controller-manager\" mod_revision:3103614 > success:<request_put:<key:\"/registry/services/endpoints/kube-system/kube-controller-manager\" value_size:365 >> failure:<request_range:<key:\"/registry/services/endpoints/kube-system/kube-controller-manager\" > >>" with result "size:20" took too long (151.205997ms) to execute
7月 04 11:41:54 172.16.4.155 etcd[13779]: request "header:<ID:14091318300993197014 username:\"etcd-node-172\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/minions/172.16.4.155\" mod_revision:3103772 > success:<request_put:<key:\"/registry/minions/172.16.4.155\" value_size:7602 >> failure:<request_range:<key:\"/registry/minions/172.16.4.155\" > >>" with result "size:20" took too long (117.31808ms) to execute
7月 04 11:43:53 172.16.4.155 etcd[13779]: read-only range request "key:\"/registry/events\" range_end:\"/registry/eventt\" count_only:true " with result "range_response_count:0 size:10" took too long (140.853561ms) to execute
```

**Comment by weekface** [comment]
duplicated with #472
