### ISSUE TITLE
add e2e test for force upgrade

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#637]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Add e2e test for force upgrade https://github.com/pingcap/tidb-operator/pull/631

**Comment by aylei** [comment]
ping @DanielZhangQD

**Comment by DanielZhangQD** [comment]
@cofyc is going to adjust the e2e framework, I will add the case when it's done.
