### ISSUE TITLE
Too many aruguments for glog.Infof

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#64]
`nodeName` is not used 

https://github.com/pingcap/tidb-operator/blob/9a2c5385c3bcac20d435383023238535cc1efad1/pkg/manager/member/tikv_member_manager.go#L557

**Comment by gregwebs** [comment]
The linters catch these automatically if you can start running them.

**Comment by gregwebs** [comment]
actually, I guess this won't catch issues with glog, just with the standard formatters
