### ISSUE TITLE
AWS terraform manifest and chart version selection is hard-coded

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#640]
## Feature Request

AWS terraform hardcodes the beta 3 release in a few places. We should have one variable to set the version of charts & manifests.

We also need the ability to specify using a version that is not released as a helm chart. This includes both
* A specific git version
* The (dirty) local copy for development or otherwise making local changes

Specifying a git version may possibly this be satisfied by using a local copy since one can checkout the repo at that git version.

**Comment by aylei** [comment]
Actually the version is configurable: https://github.com/pingcap/tidb-operator/blob/7fc6aacf36744483bc4a6d774e09c5c678e5b9a1/deploy/aws/tidb-cluster/variables.tf#L101

**Comment by gregwebs** [comment]
The tidb-operator module also needs to also have a variable: https://github.com/pingcap/tidb-operator/blob/7fc6aacf36744483bc4a6d774e09c5c678e5b9a1/deploy/aws/tidb-operator/main.tf#L52

**Comment by aylei** [comment]
Yes, I will fix this.
