### ISSUE TITLE
External Access to TiKV

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#641]
In #267 it was stated: 

But TiKV client currently has to talk to both PD and TiKV, and to use a stable network ID for the stateful app PD and TiKV on Kubernetes, tidb-operator uses DNS domain name instead of Pod IP address as the advertise address. And the domain name is non-routable outside of the cluster. So we can't simply deploy TiKV clients outside of the Kubernetes cluter right now.

However there is another approach which allows to deploy tikv client application outside of the Kubernetes cluster:
Deploy a kv proxy inside the Kubernetes cluster. The proxy connects to both PD and TiKV pods and exposes a kv service. And the application just talks to the exposed kv service.

**Comment by tennix** [comment]
Here is the TiKV proxy design proposal https://docs.google.com/document/d/1tDW9IqvcgY2IAR1IAPihM0W6Vqdh6UTkmWjRT7uED-g/edit#heading=h.ciwhnpkq8uqo

**Comment by gregwebs** [comment]
We already have clients that expect direct access to PD & TiKV, so I don't know how creating a new proxy that is an abstraction could work. Alternatively we can probably find a way to set up a proxy that will pass through to the DNS names.

Another approach would be to create a separate service for each pod that needs to be contacted externally.

**Comment by aylei** [comment]
Yes, the TiKV proxy is to address a different problem. 

Current clients like tispark requires to access the PD service and access the TiKV Pod via headless service name I suppose.

**Comment by tennix** [comment]
For those services accessing PD & TiKV directly, I think they should be deployed into the same k8s cluster. And I don't think it's a good idea to expose PD service to outside world since PD doesn't have readonly API, exposing PD service introduces risks of losing control of the whole cluster.

**Comment by aylei** [comment]
> For those services accessing PD & TiKV directly, I think they should be deployed into the same k8s cluster. And I don't think it's a good idea to expose PD service to outside world since PD doesn't have readonly API, exposing PD service introduces risks of losing control of the whole cluster.

Exposing the PD service externally does not mean expose to the internet, it is possible that users may can not or don't want to manage clients like TiSpark on Kubernetes, and this is unresolvable now because we don't provide our own solution.
