### ISSUE TITLE
Fail to create tidb-cluster

### ISSUE THREAD

**Issue by sayume** [pingcap/tidb-operator#655]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**What version of TiDB Operator are you using?**

TiDB Operator Version: version.Info{TiDBVersion:"2.1.0", GitVersion:"v1.0.0-beta.3", GitCommit:"6257dfaad68f55f745f20f6f5d19b10bea2b0bea", GitTreeState:"clean", BuildDate:"2019-06-06T09:51:04Z", GoVersion:"go1.12", Compiler:"gc", Platform:"linux/amd64"}

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

helm install pingcap/tidb-cluster --name=demo --namespace=kube-system --version=v1.0.0-beta.3
Error: validation failed: unable to recognize "": no matches for kind "TidbCluster" in version "pingcap.com/v1alpha1"

**What did you expect to see?**

**What did you see instead?**

**Comment by weekface** [comment]
@sayume Which guide are you using to setup the TiDB cluster?

This error shows that there is no CRD in k8s cluster. You can create one:

```
kubectl apply -f https://raw.githubusercontent.com/pingcap/tidb-operator/master/manifests/crd.yaml
```

**Comment by sayume** [comment]
Resolved, Thanks.
