### ISSUE TITLE
label's key names are not uniform between monitor and pd/tidb/tikv

### ISSUE THREAD

**Issue by xiaojingchen** [pingcap/tidb-operator#66]
the monitor's deployments and pods create by helm, their label keys is difference with pd/tikv/tidb's label keys.  

monitor's labels:
```app=tidb-cluster,chart=tidb-cluster-0.1.0,component=monitor,heritage=Tiller,release=tidb-cluster-e2e```
pd's labels:
```cluster.pingcap.com/app=pd,cluster.pingcap.com/owner=tidbCluster,cluster.pingcap.com/tidbCluster=demo-cluster```

we need to unify their label keys naming conventions for management and query.
1. should decide whether to use long or short names
long name: ```cluster.pingcap.com/app```
short name: ```app```
2. should define the unified label key names
```owner=tidb-operator```
```cluster=tidb cluster name```
```app=pd/tidb/tikv/monitor```
3.  limited only use lowercase characters and ‘-’

The above content needs to be discussed，please makes your suggestions

**Comment by weekface** [comment]
According to k8s documentation on [label key](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set): 

_Labels are key/value pairs. Valid label keys have two segments: an optional prefix and name, separated by a slash (/). The name segment is required and must be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between. The prefix is optional. If specified, the prefix must be a DNS subdomain: a series of DNS labels separated by dots (.), not longer than 253 characters in total, followed by a slash (/). If the prefix is omitted, the label Key is presumed to be private to the user. **Automated system components (e.g. kube-scheduler, kube-controller-manager, kube-apiserver, kubectl, or other third-party automation) which add labels to end-user objects must specify a prefix.** The kubernetes.io/ prefix is reserved for Kubernetes core components._

We should use the long names:  an prefix and name, separated by a slash (/).

**Comment by tennix** [comment]
I agree that label keys should contain a prefix. So it can be selected by label selector without conflict with other apps.
But for annotations, it's usually used internally and can't be queried by keys. So shorter keys are fine enough and we can source the annotations in our scripts without errors.
