### ISSUE TITLE
Document allocation of IP resources in EKS

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#664]
EKS CNI plugin pre-allocates many IPs for Pods on each Node by default, causing IP resources being worn out.

We should document this issue and guide users to provision subnet CIDR that large enough (which is now configured by default) or adjust the setting of EKS CNI plugin.

**Comment by george24601** [comment]
If you mind, what is considered large enough?

**Comment by aylei** [comment]
@george24601 Recommendation is `/20` subnet mask (4093 available IPs), and this is the default of our AWS tf scripts now.

**Comment by gregwebs** [comment]
This same issue occurs on GCP which may have more tools to deal with this. I set [max-pods-per-node](https://cloud.google.com/kubernetes-engine/docs/how-to/flexible-pod-cidr#configuring_maximum_pods_per_node) to 32.

**Comment by george24601** [comment]
What I got from AWS support is that they recommend subnets with CIDR /18 or /19

**Comment by aylei** [comment]
https://github.com/pingcap/docs/pull/1348

**Comment by aylei** [comment]
closed

**Comment by knightXun** [comment]
maybe we can hint users to use calico instead of aws-cni
