### ISSUE TITLE
migrate data to local PVs on another node when draining a node

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#669]
## Motivation

It's often slow to migrate data in TiKV cluster. We can try to sync raw data by using `rsync` when TiKV id is not changed and old PV is available to use.

**Comment by gregwebs** [comment]
Is there an API in PD/TiKV to speed up the transfer?

**Comment by tennix** [comment]
The logical transfer is too slow, it has to go through raft and rocksdb. One of our customers usually scp the to-be-drained node TiKV data to another node, and start a TiKV on that data directory. This is especially useful when the data is too large,  it will reduce a lot of time.

**Comment by gregwebs** [comment]
Okay, so we would have to wait for physical backup capabilities.
