### ISSUE TITLE
add e2e test to ensure tidbcluster's status is properly synchronized

### ISSUE THREAD

**Issue by xiaojingchen** [pingcap/tidb-operator#69]
At present, the synchronization of tidbcluster status involves the processing of pd/tikv/tidb members. The correctness of the status is the basis for the execution of all functions. It is necessary to add the test logic to ensure that the status is correct.
check points
-  pd/tikv/tidb statefulSet status sync to tidbcluster
- whether to get the real status information of pd and tikv through pdclient

the tidbcluster status struct is defined at
https://github.com/pingcap/tidb-operator/blob/master/pkg/apis/pingcap.com/v1alpha1/types.go#L102
should add test logic at
https://github.com/pingcap/tidb-operator/blob/master/tests/e2e/create.go#L72

#158

**Comment by mathspanda** [comment]
Is there anyone working on this issue? I would like to resolve this issue.

**Comment by weekface** [comment]
Great! If you have any questions about this issue, please feel free to ask.

**Comment by xiaojingchen** [comment]
@mathspanda Is this issue still work in progress?

**Comment by mathspanda** [comment]
Sorry, i am busy with work and not working on this. You could take it.

**Comment by weekface** [comment]
I will take it.

**Comment by weekface** [comment]
#158

**Comment by weekface** [comment]
I think these logics had been covered on unit tests, for example:
https://github.com/weekface/tidb-operator/blob/58a5ab000438aba44d7aa14c75eb6f0b9c9aa777/pkg/manager/member/pd_member_manager_test.go#L298
https://github.com/weekface/tidb-operator/blob/58a5ab000438aba44d7aa14c75eb6f0b9c9aa777/pkg/manager/member/tidb_member_manager_test.go#L176
https://github.com/weekface/tidb-operator/blob/58a5ab000438aba44d7aa14c75eb6f0b9c9aa777/pkg/manager/member/tikv_member_manager_test.go#L275
...

**Comment by weekface** [comment]
@xiaojingchen

**Comment by tennix** [comment]
Closed because unit tests already cover this.
