### ISSUE TITLE
e2e test resources requirement

### ISSUE THREAD

**Issue by shonge** [pingcap/tidb-operator#700]
4 vCPU
8G Memory
Can't run e2e test.

**Comment by weekface** [comment]
In the e2e tests, we create [three](https://github.com/pingcap/tidb-operator/blob/master/tests/cmd/e2e/main.go#L79) TiDB clusters and [insert](https://github.com/pingcap/tidb-operator/blob/master/tests/cmd/e2e/main.go#L110-L115) real data into them. Now the e2e tests need a lot of resources: **6C** and **25G**.

I think this is a bit too much. We must reduce it. Thank you for your feedback. @shonge
