### ISSUE TITLE
Repeated creation of namespace tidb-operator-e2e when following CONTRIBUTING.md

### ISSUE THREAD

**Issue by mathspanda** [pingcap/tidb-operator#72]
I am told to create namespace tidb-operator-e2e in CONTRIBUTING.md (https://github.com/pingcap/tidb-operator/blob/master/docs/CONTRIBUTING.md#run-e2e-tests), while the namespace tidb-operator-e2e has been created in dind-cluster-v1.10.sh before (https://github.com/pingcap/tidb-operator/blob/master/manifests/local-dind/dind-cluster-v1.10.sh#L1885), so manual creation may report AlreadyExistsError.
The namespace creation is redundant. Is it necessary to remove one of them?

**Comment by weekface** [comment]
Yes, i think we can remove the one in `dind-cluster-v1.10.sh`. @onlymellb @tennix

**Comment by onlymellb** [comment]
@mathspanda  Thanks for your feedback, our documentation is based on the DinD environment, so I think it would be reasonable to delete the statement that creates namespace tidb-operator-e2e in CONTRIBUTING.md.

**Comment by weekface** [comment]
I am fine with both solutions.
@tennix PTAL

**Comment by tennix** [comment]
Updating *CONTRIBUTING.md* is OK to me.
@mathspanda Any update?
