### ISSUE TITLE
tkctl does not work in GKE

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#721]
## Bug Report

**What version of Kubernetes are you using?**
`1.12`

**What version of TiDB Operator are you using?**
`1.0.0`

**What did you do?**

**What did you expect to see?**
Use `tkctl` in GKE smoothly
**What did you see instead?**
`tkctl` cannot work and report that:

```shell
$ tkctl version
error: No Auth Provider found for name "gcp"
```

**Comment by yeya24** [comment]
Seems like this can be solved by https://github.com/kubernetes/client-go/issues/242.
Can I open a PR for it? @aylei

**Comment by aylei** [comment]
@yeya24 of course, thanks!

**Comment by cofyc** [comment]
Closed via https://github.com/pingcap/tidb-operator/pull/756.
Thanks! @yeya24
