### ISSUE TITLE
terraform does not allow for password initialization

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#728]
## Bug Report

Our password initialization is documented [here](https://pingcap.com/docs/v3.0/tidb-in-kubernetes/initialize-cluster/). Initialization is accomplished by setting a secret in the K8s cluster to the desired password. However, if one uses the terraform to create a K8s cluster, there isn't an opportunity to set the secret.

This is why I still recommend we take the approach of separating out provisioning infrastructure from deploying software.

With the current modularization of our terraform, it is already possible for one to add TiDB to an existing cluster. In this case it should be easy enough to create the secret ahead of time.

@jlerche 
@aylei

**Comment by tennix** [comment]
Yes, this can be done in `modules/share/tidb-cluster-release`.

**Comment by gregwebs** [comment]
Terraform saves all values in clear text in the state file, so I don't think it is possible to do this in terraform (once someone wants to share their state file) unless additional tools are used to secure the password.
