### ISSUE TITLE
status of tidbcluster CR always updated

### ISSUE THREAD

**Issue by mathspanda** [pingcap/tidb-operator#73]
https://github.com/pingcap/tidb-operator/blob/master/pkg/controller/tidbcluster/tidb_cluster_control.go#L80

Variable `oldStatus` is a pointer type, while `tc.Status` is not. According to the comment of function `reflect.DeepEqual`, values of distinct types are never deeply equal. So maybe the result of `DeepEqual` in this line is always false, and then status of tidbcluster CR  is always updated?

**Comment by weekface** [comment]
Good Catch! Thank you.

Further moreover:
1. Replace `reflect.DeepEqual` with `apiequality.Semantic.DeepEqual` which is supplied by K8s.
https://github.com/pingcap/tidb-operator/blob/fe1792b2e8fbbc6728c204900529d07f2eb34b54/pkg/manager/member/utils.go#L174
2. Add unit test to cover this situation

Would you like to resolve this problem?

**Comment by mathspanda** [comment]
Sure.

**Comment by weekface** [comment]
Thank you for your feedback.
