### ISSUE TITLE
Need update uhub.ucloud.cn/pingcap/local-volume-provisioner:v2.3.2 image.

### ISSUE THREAD

**Issue by shonge** [pingcap/tidb-operator#736]
## Bug Report

**What version of Kubernetes are you using?**

1.12

**What version of TiDB Operator are you using?**

v1.0.0

**What did you do?**

KUBE_REPO_PREFIX=uhub.ucloud.cn/pingcap manifests/local-dind/dind-cluster-v1.12.sh up 

**What did you expect to see?**

**What did you see instead?**
Failed to pull image "uhub.ucloud.cn/pingcap/local-volume-provisioner:v2.3.2": rpc error: code = Unknown desc = Error response from daemon: manifest for uhub.ucloud.cn/pingcap/local-volume-provisioner:v2.3.2 not found

**Comment by weekface** [comment]
@tennix PTAL

**Comment by tennix** [comment]
The image is synced to ucloud registry.
