### ISSUE TITLE
is local persistent volumes supported? 

### ISSUE THREAD

**Issue by tkalanick** [pingcap/tidb-operator#740]
## Question

i am just wondering if local persistent volumes are supported
https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/

the above article seems to indicate that some work has to be done in the operator in order to prevent a few failure scenarios. 

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/pingcap/tidb-operator/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [TiDB Operator Readme](https://github.com/pingcap/tidb-operator)
  - [TiDB Operator Doc](https://github.com/pingcap/tidb-operator/tree/master/docs)

**Comment by gregwebs** [comment]
Yes, this is what we use. Did you have difficulty finding [the documentation](https://pingcap.com/docs/v3.0/tidb-in-kubernetes/reference/configuration/local-pv/)? I see there are some problems with the organization still.

**Comment by gregwebs** [comment]
BTW, you can join our [community Slack](https://pingcap.com/tidbslack/) to ask more questions.
