### ISSUE TITLE
Able to run TiDB components in host network

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#759]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In GKE TiDB sysbench benchmark, performance in the host network is slightly better (10%) than the pod network (GKE cluster network is VPC-native).

**Describe the feature you'd like:**

Able to run TiDB components (pd/tidb/tikv) in host network.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

One issue to run pods in host network is hostname is not pod name anymore. In Kubernetes, the hostname is set to the host hostname when the pod is running in host network (xref: https://github.com/kubernetes/kubernetes/issues/12893). We need to update our start scripts to use pod name to construct the component address.

**Comment by tennix** [comment]
Currently, TiDB Operator uses domain names for each component. I think this should be still available when in host network mode.

**Comment by cofyc** [comment]
yes, it resolves to node IP address.
