### ISSUE TITLE
Integrate all components into one binary

### ISSUE THREAD

**Issue by onlymellb** [pingcap/tidb-operator#780]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Currently, there are several independent components related to the tidb operator, which may add more components in the future, too many binaries is not convenient to package and software delivery, on the other hand, it is also inconvenient to add some self-explanatory functional descriptions for these components.

**Describe the feature you'd like:**

Compile all components into a single binary, just like [rook](https://github.com/rook/rook/blob/master/cmd/rook/main.go) does. Then start different components with different commands

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by gregwebs** [comment]
The goal of this is to reduce the total size of all the binaries (the tidb-operator docker image)?
