### ISSUE TITLE
Use Helm chart dependencies for Tidb-cluster

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#832]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For now, the `values.yaml` and `templates folder` for `tidb-cluster` helm chart includes both core components and add-on components install configuration which can make `tidb-cluster` helm chart more and more complex and hard to be managed.

**Describe the feature you'd like:**

I think `helm chart dependency` can be a good choice. Each components will be managed by the `tidb-cluster` global chart as an independent child chart which the child chart will be placed into `charts folder`. And the global `values.yaml` will be responsible for the common install customization like `time-zone` and choice for which add-on components will be installed.
 
**Describe alternatives you've considered:**

`monitor` and `scheduled backup` can be considered as two independent add-on components and can be managed as child charts in `charts` folder. It also need to update the document for `tidb-cluster` custom install.

**Teachability, Documentation, Adoption, Migration Strategy:**

The `values.yaml` will be hard to manage and a giant configuration if we put all the configuration for all the components in there. 

And if you think it's necessary or helpful,I'd like to make a PR for this issue.

**Comment by aylei** [comment]
Do you mean manage the add-on components in the `requirements.yaml`? or Could you please elaborate your proposal with a simple example?

**Comment by Yisaer** [comment]
yep, `requirements.yaml` is exactly what I want to say.

**Comment by weekface** [comment]
Divide `values.yaml` to multiple files may be a breaking change.

**Comment by aylei** [comment]
IIUC, `helm dependency` is used to reference other charts and the `values.yaml` of the user interface (think the `values.yaml` of the `tidb-cluster` chart) will not be changed. So the key question is: do we want to move the add-on components to separate charts (modularization)?

I suppose no, because currently the add-on components only make sense inside the `tidb-cluster` chart, we won't have chance to reuse them. What do you think?

**Comment by Yisaer** [comment]
In my view, separate components into each chart in `tidb-cluster` is not for reusing but for dividing configuration in each component. It might be more components (mainly add-on) and more detailed configuraition (both core and add-on components) for `tidb-cluster` helm in future and the global `values.yaml` could be complex if we put all the configuraition in it. I think `isito` might be a good example to show how large chart inculdes both core and add-on components be managed.

However,I agree separating charts not necessary for now but it might be a good choice in future.

**Comment by aylei** [comment]
I believe `istio` did this for maintainability and developer experience. On the user side, they still have to write a big `values.yaml` if they want to customize the add-on components.

Back to the topic, I think whether separating charts benefits to maintainability is debatable. @weekface @tennix How do you think?

**Comment by aylei** [comment]
closing in favor of #1121 
feel free to reopen if more discussions are needed
