### ISSUE TITLE
Support file and tidb as destDBType for drainer

### ISSUE THREAD

**Issue by shinnosuke-okada** [pingcap/tidb-operator#838]
## Bug Report

**What version of Kubernetes are you using?**
N/A

**What version of TiDB Operator are you using?**
N/A

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
N/A

**What's the status of the TiDB cluster pods?**
N/A

**What did you do?**
Deploy TiDB cluster with `db-type = tidb`.

**What did you expect to see?**
Functional drainer with ts mapping in the downstream TiDB

**What did you see instead?**
Drainer can't connect to the downstream TiDB

**Comment by aylei** [comment]
closed via #839
