### ISSUE TITLE
Scheduled backup - immediate clean up upon successful upload

### ISSUE THREAD

**Issue by shinnosuke-okada** [pingcap/tidb-operator#841]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Same as https://github.com/pingcap/tidb-operator/issues/840

**Describe the feature you'd like:**

Feature to immediately delete the backup data upon successful upload to CEPH/S3/GCP would be nice to have especially when we don't have the retention policy (https://github.com/pingcap/tidb-operator/issues/840)

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

Need a boolean flag to enable the feature

**Comment by aylei** [comment]
closed via #902 , thanks @shinnosuke-okada
