### ISSUE TITLE
Failover recovery and rolling-update may cause deadlock

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#865]
## Bug Report

**What version of Kubernetes are you using?**
`1.12`

**What version of TiDB Operator are you using?**
`1.1.0-alpha.1`

**What did you do?**

Say we have 6 TiKV pods with the largest ordinla 5:

1. rolling-update TiKV to a bad configuration, `tikv-5` go to `CrashLoopBackoff`
2. wait for 35 minutes
3. the tidb-controller-manager does failover, `tikv-6` added
4. due to resources constrain, `tikv-6` is `Pending`
5. I notice that and correct the bad configuration
6. current `partition` is 5, statefulset rollover, `tikv-6` recreated in new revision but still in `Pending` state
7. `tikv-5` cannot be updated because `tikv-6` is not `Ready`, which makes sense
8. I delete the `.status.tikv.failureStores` field of `TidbCluster`, try to fix this problem by scaling-in `tikv-6`
9. `tikv-6` does not get scaled-in, because tidb-operator has a constrain that scaling cannot be performed during upgrading...
10. ...and upgrading cannot proceed on because `tikv-6` is not `Ready`, deadlock

Workaround:
- force scaling via manual intervention: edit the tikv statefulset and change the `replicas`, then delete the PVC of `tikv-6` to release the the scheduling lock 
- or add more resources and get `tikv-6` ready

**What did you expect to see?**

Not pretty sure but maybe:

- We shouldn't perform failover if the predecessors are `CrashLoopBackoff`, which often indicates a configuration error. Failover can hardly help in such case
- We shouldn't perform failover when upgrading, because tidb-operator reject scaling during upgrading to avoid race condition but failover is actually a kind of scaling which is not get rejected

**Comment by aylei** [comment]
cc @weekface @tennix

**Comment by weekface** [comment]
I prefer: don't failover when upgrading.

**Comment by aylei** [comment]
New case of this deadlock:

- tidb failover, the new Pod is pending because there is no enough compute resources
- user upgrade the tidb-servers without recovering the failover first
- upgrade cannot make progress because the Pod with largest ordinal is pending
- user recover the tidb-servers, but the Pod with largest ordinal cannot be scaled-in because the upgrading is in progress

This scenario reveals that we cannot address this issue by not doing failover in certain cases, the real issue is that we should think twice about the "cannot scale when upgrade" constrain.

**Comment by weekface** [comment]
If we use the raw statefulset, not operator, we should be able to upgrade or scale in onto the failed pod and stop at that ordinal, after recovering that pod the upgrade or scale in should continue.

**Comment by aylei** [comment]
Likely this will be addressed in #992 , re-assigned to @Yisaer

**Comment by aylei** [comment]
@Yisaer Could you verify if this has been addressed by webhook? Thanks!
