### ISSUE TITLE
Unable to mount /boot and /lib/modules in Mac environment

### ISSUE THREAD

**Issue by kissmydb** [pingcap/tidb-operator#867]
# ## Bug Report

**What version of Kubernetes are you using?**
v1.14.3

**What version of TiDB Operator are you using?**
v1.0.0

**What did you do?**
When I execute 'manifests/local-dind/dind-cluster-v1.12.sh up',report a error:

```
docker: Error response from daemon: Mounts denied:
The path /boot
is not shared from OS X and is not known to Docker.
```

**What did you expect to see?**
The dind-cluster-v1.12.sh can automatically identify the system, if it is macOS, skip this part of the execution:

```
  if [[ ! ${using_linuxkit} ]]; then
    sys_volume_args=()
    if [[ -d /boot ]]; then
      sys_volume_args+=(-v /boot:/boot)
    fi
    if [[ -d /lib/modules ]]; then
      sys_volume_args+=(-v /lib/modules:/lib/modules)
    fi
    return 0
  fi
```

**Comment by cofyc** [comment]
dind is deprecated, try kind, see https://github.com/pingcap/tidb-operator/blob/master/docs/CONTRIBUTING.md#run-e2e-tests-in-kind

cc @xiaojingchen remove dind part?

**Comment by kissmydb** [comment]
I was follow the official documentation,  https://pingcap.com/docs-cn/v3.0/tidb-in-kubernetes/get-started/deploy-tidb-from-kubernetes-dind/

if dind is deprecated,why not change the documentation?

**Comment by Yisaer** [comment]
I'm also trying tidb-operator in my local kubernetes in Mac by `Docker Desktop` with its own single node Kubernetes. I changed the `StorageClass` in the `values.yaml` each helm chart I need into `hostpath` (the default storageclass for local kubernetes) and everything runs fine.

I think you can try this way. @kissmydb

**Comment by cofyc** [comment]
@Yisaer can you write a "quick-started" document using kind? kind is more stable than kubeadm-dind-cluster.

**Comment by Yisaer** [comment]
> @Yisaer can you write a "quick-started" document using kind? kind is more stable than kubeadm-dind-cluster.

sure

**Comment by tennix** [comment]
@kissmydb @Yisaer @cofyc  Can we close this issue if we won't fix the DinD environment?

**Comment by Yisaer** [comment]
> @kissmydb @Yisaer @cofyc Can we close this issue if we won't fix the DinD environment?

sure.
