### ISSUE TITLE
Can terraform deployment support Reserved Instances 

### ISSUE THREAD

**Issue by iamxy** [pingcap/tidb-operator#874]
## Feature Request

**Is your feature request related to a problem? Please describe:**
User cost can be greatly reduced by using Reserved Instances (包年包月). 

**Describe the feature you'd like:**
Users can select the billing type for the cluster instances in the configuration file.

**Describe alternatives you've considered:**
It can be created first and modified in the console, but it's not a good experience.

**Teachability, Documentation, Adoption, Migration Strategy:**
To make terraform's public cloud providers support the configuration of billing types for node instances of managed Kubernetes.

**Comment by gregwebs** [comment]
Which cloud provider? Cloud providers are moving towards making RI essentially like a billing credit and this is not something that would need to be configured anywhere.

**Comment by iamxy** [comment]
This is a user who uses Terraform to create TiDB clusters in Aliyun and thinks the cost of on-demand instances is high for him.

**Comment by gregwebs** [comment]
I am not familiar with Aliyun but, AFAICT from looking at their [docs](https://www.alibabacloud.com/help/doc-detail/100370.htm?spm=a2c63.p38356.b99.98.78751d9aZWX2MY) it works the same way: "A reserved instance is a discount coupon that can be applied automatically to one or more pay-as-you-go instances that belong to your account".

So I don't know what we could possibly do here to help the user.

**Comment by gregwebs** [comment]
@iamxy I would like to get a clearer description from the user about what we can do or close this issue out.

**Comment by aylei** [comment]
Seems like the reserved instance coupon is what the customer want.
