### ISSUE TITLE
gcp load balancer severs active MySQL client connections to tidb-server

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb-operator#877]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.24", GitCommit:"2ce02ef1754a457ba464ab87dba9090d90cf0468", GitTreeState:"clean", BuildDate:"2019-08-12T22:05:28Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}

**What version of TiDB Operator are you using?**

TiDB Operator Version: version.Info{GitVersion:"v1.0.0", GitCommit:"0214ddab80dc07616f86102733fb6c69a0137429", GitTreeState:"clean", BuildDate:"2019-07-30T09:09:59Z", GoVersion:"go1.12", Compiler:"gc", Platform:"linux/amd64"}

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

```
NAME                                      READY   STATUS    RESTARTS   AGE    IP          NODE                                                  NOMINATED NODE   READINESS GATES
tidb-cluster-discovery-787cf87b74-nffs8   1/1     Running   0          5d6h   10.0.3.17   gke-tidb-cluster-tidb-cluster-monitor-87e9d987-42tj   <none>           <none>
tidb-cluster-monitor-745654489b-kmprw     3/3     Running   0          5d6h   10.0.3.18   gke-tidb-cluster-tidb-cluster-monitor-87e9d987-42tj   <none>           <none>
tidb-cluster-pd-0                         1/1     Running   0          5d6h   10.0.4.2    gke-tidb-cluster-tidb-cluster-pd-pool-84a7b422-4h51   <none>           <none>
tidb-cluster-tidb-0                       2/2     Running   0          5d6h   10.0.6.2    gke-tidb-cluster-tidb-cluster-tidb-po-3fe3ab4a-xrxx   <none>           <none>
tidb-cluster-tidb-1                       2/2     Running   0          5d6h   10.0.5.2    gke-tidb-cluster-tidb-cluster-tidb-po-3fe3ab4a-pw76   <none>           <none>
tidb-cluster-tikv-0                       1/1     Running   0          5d6h   10.0.0.3    gke-tidb-cluster-tidb-cluster-tikv-po-b85cc272-qhj0   <none>           <none>
tidb-cluster-tikv-1                       1/1     Running   0          5d6h   10.0.2.3    gke-tidb-cluster-tidb-cluster-tikv-po-b85cc272-c9zh   <none>           <none>
tidb-cluster-tikv-2                       1/1     Running   0          5d6h   10.0.1.3    gke-tidb-cluster-tidb-cluster-tikv-po-b85cc272-s5gz   <none>           <none>
```

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

SQL statements that run longer than about 10 minutes seem to be cut off by the load balancer and the client doesn't return until its internal timeout is triggered.

I see this behavior only when connecting to the internal load balancer, *not* when connecting to a backend tidb-server instance via a kubectl port-forward, so I think it's something to do with the configuration of the load balancer rather than an issue with the configuration of tidb-server.

**Comment by aylei** [comment]
Tracked in #880
