### ISSUE TITLE
externalTrafficPolicy of tidb service should default to local in terraform deployment 

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#879]
## Bug Report

When the `externalTrafficPolicy` is set to cluster (the default value), every Kubernetes node is a valid backend for the load balancer, a single machine failure will impact part of new connections. More seriously, for immature clients that has a 0 connect-timeout (no timeout), the new connections that routed to the failure machine hangs forever.

With `externalTrafficPolicy` set to `local`, the nodes without backend pods route the traffic to blackhole, therefore, LB can mark these nodes as unhealthy when performs the initial check. `local` mode may cause [unbalanced traffic](https://www.asykim.com/blog/deep-dive-into-kubernetes-external-traffic-policies), but not for our terraform deployment which uses dedicated node.   

**What did you do?**

1. Deploy TiDB cluster via the AWS terraform scripts
2. Simulate inserts using mysqlcli
3. Terminate a PD instance from the AWS console

**What did you expect to see?**
No impact on the workload

**What did you see instead?**
mysqlcli hangs forever

cc @tennix @weekface 

ref:
https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/
https://www.asykim.com/blog/deep-dive-into-kubernetes-external-traffic-policies

**Comment by shinnosuke-okada** [comment]
I'll quickly fix this one as it's related to our use case.

**Comment by shinnosuke-okada** [comment]
@aylei i can't close the ticket - can you?

**Comment by aylei** [comment]
Yes.
closed via #947
