### ISSUE TITLE
Terraform: TiDB nodes should configure tcp_keepalive_time

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#880]
## Feature Request

Progress:

- [x] AWS
- [ ] GCP
- [ ] Alibaba Cloud

**Edit:**

**Because the `net.*` kernel parameters are namespaced and will not inherit from parent namespace, we have to change the keepalive parameters in the Pod level, which requires change to the `TidbCluster` CRD definition (a `securityContext` filed of TiKV/TiDB/PD pods will be introduced). This will be addressed in #795. Also note that much of the parameters are considered unsafe and should be enabled via the kubelet args explicitly, this issue will track the kubelet one.** 

Typically, the load balancers provided by public cloud have a fixed idle-timeout or a limited configurable range:

* AWS ELB: 1~4000s
* AWS NLB: 350s
* GCP TCP load balancer: 600s ([ref](https://cloud.google.com/load-balancing/docs/https/))
* Alibaba Cloud SLB: not verified yet

When the idle-timeout reaches, the LB either explicitly close the connection (send `FIN` to both sides, e.g. AWS ELB) or close the connection silently (response `RST` when the client send packets again). Both cases cause long time queries to fail.

One can simulate an idle timeout by the following command:

```
mysql -u <user> -p -e "select sleep(400); select tidb_version();"
``` 
Where 400 should be adjusted to more than the idle-timeout of LB.

To tackle this problem, one can enable tcp_keepalive in the client-side or the server-side, can a the `tcp_keepalive_time` that shorter than the LB idle-timeout.

I propose to enable tcp_keepalive for the TiDB servers ~~and adjust the `tcp_alive_time` kernel parameter of **TiDB nodes** in our terraform deployment.~~  Because:

* Generally speaking, we know the infracture provisioned by our scripts better than the users. Tackling this problem in scripts is more user-friendly than warning this in docs;
* We provision dedicated nodes for TiDB Pods, so the scope of influence is controllable;

cc @tennix @cofyc @AstroProfundis @jlerche @gregwebs @kolbe 

ref:
The tidb tcp_keepalive configuration: https://pingcap.com/docs/v3.0/reference/configuration/tidb-server/configuration-file/#performance
tcp keep alive: http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html

**Comment by cofyc** [comment]
why?

**Comment by aylei** [comment]
@cofyc Sorry for lacking detailed description, I've update the description to explain why we want to do this.

**Comment by aylei** [comment]
After some experiments, I found that changing the `net.*` sysctls of the host's network namespace do not affect the containers' one. 

There are two possible ways to set tcp_keepalive_time for TiDB container:

* Use `hostNetwork` and configure sysctls of the host
* Specify sysctls via k8s container spec: https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#setting-sysctls-for-a-pod

This SO answer explains why: https://stackoverflow.com/questions/54552379/tcp-keepalive-time-in-docker-container

**Comment by AstroProfundis** [comment]
Is it necessary to change kernel parameters when TiDB's `tcp-keep-alive = true`?

**Comment by aylei** [comment]
@AstroProfundis  Yes, the default `tcp-keepalive-time` is 7200s, which is much longer than the idle-timeout of common LBs.
