### ISSUE TITLE
Graceful upgrade TiDB pod

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#89]
When upgrading TiDB, we should make sure there's no DDL job running on the current pod. TiDB has an [API to evict DDL owner](https://github.com/pingcap/tidb/pull/7649). We should evict DDL owner before upgrading.

**Comment by winkyao** [comment]
This API just start a new election, not evict.

**Comment by winkyao** [comment]
What you need is some method to "stop the ddl" and "start the ddl"?

**Comment by tennix** [comment]
Can we resign the ddl owner to other tidb-server using the API?
