### ISSUE TITLE
Zone labels and kubelet reserved memories for GCP and Alibaba Cloud

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#891]
## Feature Request
#848 #845 add zone label and customization of kubelet args support for AWS, these should also be implemented for the GCP and Alibaba Cloud.

This issue is created to track the progress:

- [ ] Alibaba Cloud
- [ ] GCP
 
**Is your feature request related to a problem? Please describe:**

see original issues for detail.

**Comment by gregwebs** [comment]
can tidb-operator do some translation on the slash? Or add the label as an annotation? Then we can solve this in the operator once without having to figure out this setup for every K8s.

**Comment by aylei** [comment]
@gregwebs Yes, I suggested these methods before and we thought it's better to tolerate the slash on the PD side to avoid adding indirections and this fix has landed in the new versions of PD (https://github.com/pingcap/pd/commit/d91268eca6a52dff5c48dae843b0eda60bcf0ab1). 

So this is a workaround for old versions.
