### ISSUE TITLE
[WIP]Able to specify the replicas of components(tidb/pd/tikv) for each availability zone

### ISSUE THREAD

**Issue by LinuxGit** [pingcap/tidb-operator#894]
## Feature Request

**Describe the feature you'd like:**

For example, I want to create a TiDB Cluster across three availability zone（zone A, zone B and zone C). There's no business application in zone C. And TiKV's replication factor（max-replicas） is 3. In order to achieve the data disaster recovery, PD's location-labels settings is set to [ "zone", "host"].
For TiDB, I don't want to deploy tidb pods in zone C, I may deploy two tidb pods in zone A, and two in zone B.
For PD, if I set pd's replicas to 3, each zone should run a pd pod. If I set pd's replicas to 5, zone A and zone B could run 2 pd pods, zone C could run 1 pd pod.
For TiKV, each zone should have the same number of tikv pods. In some scenarios, I might expect more tikv pods in zone A to relieve CPU pressure.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by gregwebs** [comment]
Will the business application failover (perhaps by manual deployment) to zone C if there is a failure in zone A (or in both A & B)?
