### ISSUE TITLE
Tool or feature to aggregate TiDB metadata (e.g. running queries)

### ISSUE THREAD

**Issue by shinnosuke-okada** [pingcap/tidb-operator#897]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, if you have multiple TiDB pods, you'll have to port-forward and connect to every single TiDB pod to collect TiDB metadata (e.g. `show processlist`).

**Describe the feature you'd like:**

A tool or feature that helps end-users and/or TiDB admins to efficiently collect and understand the current status of TiDB _as a service_.

**Describe alternatives you've considered:**

Scripting the aforementioned aggregation with port-forwarding.

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

**Comment by tennix** [comment]
Good point! Some session or server level SQL statements are hard to check if TiDB service is exposed by a load balancer. For example:
- Show processlist
- Find slow queries using SQL command
- Check server level variables like slow log threshold

We may implement this via `tkctl` subcommands.

**Comment by gregwebs** [comment]
I think this issue effects any TiDB user to some extent and we should review ways to solve this outside of tidb-operator tools.

**Comment by tennix** [comment]
This affects users on public cloud with a load balancer the most. In other environment, users can just connect the tidb-server they want. So not a big problem to those users.

**Comment by gregwebs** [comment]
@tennix one can already connect to an individual pod with `kubectl port-forward`, are you trying to make a mechanism that doesn't use `kubectl`?

However, that seems like a separate issue from the one outlined here which is to aggregate information across multiple TiDB SQL servers. Perhaps you should open a new issue for that?

The lack of aggregation would affect every TiDB user in any environment.

**Comment by tennix** [comment]
Yes, `kubectl port-forward` works.

I agree that tidb-server should support this aggregation and we should file an feature request in tidb repo. But before tidb support this, I think we may provide some helper scripts to do this task.

**Comment by shinnosuke-okada** [comment]
@gregwebs we could - what's the user scenario in your mind with k8s job? Another helm chart?

**Comment by gregwebs** [comment]
I think the goal is to work towards removing the need to use kubectl port-forward and a locally installed mysql. kubectl port-forward access weakens security and also complicates the script by being ran in the background. I think the smallest way forward would probably be to change the script to use `kubectl run`. Also, I would avoid argument parsing and pass the options through to mysql.

A helm chart has a lot of overhead, and helm isn't very good for running one-off jobs like this..

**Comment by aylei** [comment]
In favor of the operation in other platforms, I think it is better to be done in the TiDB side. For example, `SHOW GLOBAL PROCESSLIST` https://github.com/pingcap/tidb/issues/8854

**Comment by aylei** [comment]
TiDB RFC: https://github.com/pingcap/tidb/pull/13481/files

**Comment by tennix** [comment]
As TiDB is going to support this feature itself. We don't have to add a wrapper for this in tidb-operator. So close this issue.
