### ISSUE TITLE
initSQL from configMap

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#899]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Some users think it's hard to maintain multiple and complex SQL statements in `values.yaml` file.

**Describe the feature you'd like:**

They want to write multiple SQL statements in a file and let the job to read the file and execute SQL statements.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

The job pod needs to mount the file into the container. We can use ConfigMap. In `tidb-cluster` chart, we can add a new field, e.g. `initSQlFromConfigMap`, which is like `envFromConfigMap`.

In the deploy process, the user creates a ConfigMap first (`kubectl create configmap my-config --from-file=path/to/bar`) and then configures it in the values.yaml.

**Comment by Yisaer** [comment]
How about the initSql in `values.yaml` when we support this feature?

**Comment by cofyc** [comment]
mutually exclusive with each other. because there is no validation, we can give one of them a higher priority.

**Comment by Yisaer** [comment]
supported in https://github.com/pingcap/tidb-operator/pull/917

**Comment by cofyc** [comment]
closed via #917
