### ISSUE TITLE
Current rolling-update process may leave the pod with ordinal 0 in old version

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#901]
## Bug Report

**What version of Kubernetes are you using?**
`v1.12`

**What version of TiDB Operator are you using?**

`1.1.0-alpha.1`
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

All the Pods is running except `pd-0` is in `ContainerCreating` status.
**What did you do?**

1. Enable ConfigMap Rollout feature, say the current PD configuration version is **v0**
2. Apply a new PD config (say **v1**)
3. Apply another new PD config (say **v2**) while the previous upgrading is in progress

**What did you expect to see?**
Eventually all the PD pods are running in v2 configuration.

**What did you see instead?**
pd-1 and pd-2 are running in v1 configuration, pd-0 is stuck in container creating status.

**Some conclusions**
After some investigations, the problem is caused by the rolling-update logic in tidb-operator:

1. The user rolling updates from **v0** -> **v1**: 
  1. pd-2 and pd-1 are deleted and re-created in **v1**
  2. pd-0 is deleted
2. The user rolling updates from **v1** -> **v2**, however, the previous rolling updating is not completed, so for the statefulset, it is upgraded from **v0** -> **v2**:
  1. `tidb-controller-manager` set the partition of PD statefulset to 3
  2. `kube-controller-manager` is going to re-create pd-0, because the partition is 3, so it create pd-0 in the old version, **v0**
  3. because the **v0** configmap has been deleted by helm, pd-0 is stuck in `ContainerCreating` status 
  4. `tidb-controller-manager` tries to safely rolling-update the PD statefulset, so it transfer the PD leader to pd-0 first and waits the transfering complete.
  5. The transfering will never complete because pd-0 is not started
  6. cluster is stuck in this status forever 

We can tell that if the pod with zero ordinal is recreated after the partition is set to 3 by the tidb-controller-manager, it will be created in an old version, which violates the semantics of rolling upgrades and may cause unexpected behavior.

Actually, the partition based rolling-update control logic is quite complicated and may suffers race conditions like the one I describe above, I'd suggest raising the priority of gracefully rolling update refactoring (maybe via webhook)

**Comment by gregwebs** [comment]
Can we block rolling upgrade until the previous is finished?

**Comment by aylei** [comment]
@gregwebs With that, if there's any error in the new version which blocks rolling-update, user will have no way to recover the statefulset.
