### ISSUE TITLE
Add more flexibility to the scheduled backup job

### ISSUE THREAD

**Issue by shinnosuke-okada** [pingcap/tidb-operator#903]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Scheduled backup jobs are currently:
1. Hard to debug; and
2. Doesn't have a deadline so long backup jobs can potentially overlap with the traffic during the day.

**Describe the feature you'd like:**

Voting to make the following configurable for the scheduled backup job:
1. .spec.activeDeadlineSeconds
2. spec.backoffLimit
3. .spec.template.spec.restartPolicy

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

**Comment by gregwebs** [comment]
Any setting which is already inherent to the underlying K8s job could potentially be passed through here. You can run `helm template` right now to get the underlying k8s job to configure.

**Comment by shinnosuke-okada** [comment]
Thanks. Yes, we're currently manually modifying these, and would be good to have them configurable out-of-box in the helm chart.

**Comment by aylei** [comment]
closed via #904 , thanks @shinnosuke-okada
