### ISSUE TITLE
SSD with AWS EKS Kubernetes

### ISSUE THREAD

**Issue by liufuyang** [pingcap/tidb-operator#91]
Hi there,

I am trying to following this [guide](https://github.com/pingcap/tidb-operator/blob/master/docs/google-kubernetes-tutorial.md) to setup tidb, while working with a Kubernetes cloud started via an AWS EKS service (via Terraform). (You may see more info here as I am trying to note down the steps here: https://github.com/pingcap/tidb-operator/pull/71)

However when onto the steps of `Deploy your first TiDB cluster`, with command`helm install ./charts/tidb-cluster -n tidb --namespace=tidb --set pd.storageClassName=pd-ssd,tikv.storageClassName=pd-ssd
 `

I get error from Kube Dashboard showing me the pd pods are not started successfully:

`0/2 nodes are available: 2 node(s) didn't find available persistent volumes to bind.`

Questions:
For demo purpose, I guess I can get it over with `--set pd.storageClassName=pd,tikv.storageClassName=pd` ?

And more importantly, if I would like to setup tidb to use ssd with AWS, do you have some guide on how to achieve that? Thanks :)

**Comment by tennix** [comment]
What storage classes are there in EKS?
```
kubectl get storageclass
```
The tutorial in GKE uses `pd-ssd` storage class which is provided by GKE. Different cloud providers have different storage classes, users should adopt `storageClassName` to the cloud providers provide.
The default storage class on GKE is `standard`, but I haven't tested it on EKS. So I've no idea what the default storage class is on EKS.

**Comment by gregwebs** [comment]
Certainly the GKE tutorial will not work at the point of trying to use storage classes. EKS does not support local SSD (which is required for good TiDB performance). You can, however, use a [networked ssd](https://docs.aws.amazon.com/eks/latest/userguide/storage-classes.html).

**Comment by liufuyang** [comment]
I see. Will try it again some days later. To save some money, I have deleted all my AWS resources... Will get back to you when I try it out.

**Comment by gregwebs** [comment]
With terraform you should be able to destroy the cluster (and bring it back up when needed) to save money. You can also use much smaller instance types (particularly if you decrease the resource requirements in values.yml).

**Comment by liufuyang** [comment]
Hey there again @tennix 
I tired to set up a storage class `gp2` as @gregwebs suggested above, and tried to continue with the guide, I could see the PD works but tikv gives some error.

The command I used to deploy TiDB:
````
helm install ./charts/tidb-cluster -n tidb --namespace=tidb --set pd.storageClassName=gp2,tikv.storageClassName=gp2
```

```
kubectl get storageclass
NAME      PROVISIONER             AGE
gp2       kubernetes.io/aws-ebs   15m
pd-ssd    kubernetes.io/gce-pd    13m
```

![image](https://user-images.githubusercontent.com/161689/45915839-5d83fd80-be5c-11e8-9457-4f0ad5c6691e.png)

Steps to repeat to see is more or less in the PR:
https://github.com/pingcap/tidb-operator/blob/f497ddc37983cd92801bee2fe73987601c5239f4/docs/aws-eks-tutorial.md

**Comment by liufuyang** [comment]
The logs on tikv showing:
`2018/09/22 09:44:14.779 tikv-server.rs:84: [ERROR] Limit("the maximum number of open file descriptors is too small, got 65536, expect greater or equal to 82920")`

Perhaps I need to rebase onto current master or?

**Comment by tennix** [comment]
Oh, the `ulimit` on EKS is too small. To make TiKV run on your current cluster, you have to lower `max-open-files` setting for TiKV in `tidb-cluster/templates/tikv-configmap.yaml`. `1024` should be OK. But for a production deployment, it is recommended to adjust the host machine `ulimit` to `unlimited`. So the cloudformation template for EKS node should be modified to auto set `ulimit`

**Comment by liufuyang** [comment]
@tennix Thanks for the fast reply. I changed two settings in the configmap.yaml and it seems working now. all pods are up and green.

However, I seem don't get the `demo-tidb` svc as described in the google kube tutorial doc, but I do have `demo-tidb-peer`. Is this supposed to happen? I can just use `demo-tidb-peer` instead of `demo-tidb` to follow the doc [at here](https://github.com/pingcap/tidb-operator/blob/master/docs/google-kubernetes-tutorial.md) ? 
```
kubectl get svc -n tidb
NAME              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
demo-grafana      NodePort    172.20.199.125   <none>        3000:31105/TCP   2m
demo-pd           ClusterIP   172.20.162.181   <none>        2379/TCP         2m
demo-pd-peer      ClusterIP   None             <none>        2380/TCP         2m
demo-prometheus   NodePort    172.20.155.162   <none>        9090:31637/TCP   2m
demo-tidb-peer    ClusterIP   None             <none>        10080/TCP        42s
demo-tikv-peer    ClusterIP   None             <none>        20160/TCP        1m
```

**Comment by liufuyang** [comment]
Oh cool, and thanks. I think it's more or less working now. Will try to find some time finish the doc and test everything again before ping you another time. Have a nice weekend :)
