### ISSUE TITLE
Error: This command needs 1 argument: chart name

### ISSUE THREAD

**Issue by chenjianxin** [pingcap/tidb-operator#918]
helm install pingcap/tidb-cluster --name demo --set schedulerName=default-scheduler,pd.storageClassName=standard,tikv.storageClassName=standard,pd.replicas=1,tikv.replicas=1,tidb.replicas=1 --version=v1.0.0-beta.3

**Error: This command needs 1 argument: chart name**

**Comment by gregwebs** [comment]
@chenjianxin can you create a clear description for this issue, for example where the command came from?

**Comment by aylei** [comment]
@chenjianxin 
Have you add the `pingcap` helm repository first?
