### ISSUE TITLE
Some operations may cause the pd pod of the new cluster to be in the pending state forever.

### ISSUE THREAD

**Issue by onlymellb** [pingcap/tidb-operator#934]
## Bug Report

**What version of TiDB Operator are you using?**

All versions of tidb-operator have this problem

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

This has nothing to do with which storage class to use.

**What did you do?**

1. Use helm install tidb-cluster, set release name to `pd-test-re1`, the tidb cluster name set to 
`lhy1024`
```
helm install tidb-cluster --name=pd-test-re1  --namespace=lhy1024 --set clusterName=lhy1024 
```
2. When the pd cluster above the tidb cluster is started then use helm delete this tidb cluster release `pd-test-re1`
```
helm delete pd-test-re1 --purge
```
3. Reinstall the tidb cluster with helm, set release name to `pd-test-re2`, keep the `clusterName` setting unchanged, Still set to `lhy1024`
```
helm install tidb-cluster --name=pd-test-re2 --namespace=lhy1024 --set clusterName=lhy1024 
```

**What did you expect to see?**
The new tidb-cluster with release name `pd-test-re2` will start normally

**What did you see instead?**
The pd pod of the new tidb cluster is always in the `pending` state, and the log of the tidb-operator as follows:
```
I0903 09:33:23.840908       1 scheduler.go:105] scheduling pod: lhy1024/lhy1024-pd-0
E0903 09:33:23.843833       1 mux.go:107] unable to filter nodes: can't find current Pod lhy1024/lhy1024-pd-0's PVC
```

**Root Cause Analysis(RCA)**
Here we mainly analyze the situation of the first pd pod in the above two tidb clusters, we use the term first cluster instead of tidb cluster with the release name `pd-test-re1`, and use the term second cluster instead of tidb cluster with the release name `pd-test-re2`.

first cluster:
-  The first pd pod name is `lhy1024-pd-0`, the corresponding PVC name is `pd-lhy1024-pd-0`, their names are determined by clusterName `lhy1024`
- The PVC  `pd-lhy1024-pd-0` has label `app.kubernetes.io/instance=pd-test-re1`, this label value is determined by release name `pd-test-re1`

second cluster:
- The first pd pod name of second cluster has the same pod name and PVC name with the first cluster(both clusters have the same clusterName `lhy1024`)
- So the pd sts will create the first pd pod `lhy1024-pd-0` directly(the PVC `pd-lhy1024-pd-0` 
 already exists, but the PVC label `app.kubernetes.io/instance` value is `pd-test-re1` )
- When this pd pod `pd-test-re2` is created by pd sts, then scheduled by our custom scheduler `tidb-scheduler`, our scheduler will look up the corresponding PVC based on the information of this pd pod. The code as follows:

https://github.com/pingcap/tidb-operator/blob/084d181197d88759fa854eb0a5834c6cf6594bb6/pkg/scheduler/predicates/ha.go#L230-L255

find pd pod's `lhy1024-pd-0` PVC by `label app.kubernetes.io/instance=pd-test-re2`, but the
already exists PVC `pd-lhy1024-pd-0` has label `label app.kubernetes.io/instance=pd-test-re1`, so our custom scheduler will report the error :  `can't find current Pod lhy1024/lhy1024-pd-0's PVC`, but the pd sts think the PVC of this pd pod already exists(the pd sts only check the PVC name).

**Some Solutions**
Solution 1:
-  After deleting the first cluster with helm, delete all PVCs of the first cluster manually. Then install the second cluster. 

Solution 2:
- Make sure `clusterName` and `releaseName` are consistent and cannot set different values

Solution 3:
- Now we use `releaseName` as the instance name and then use `clusterName` to name the pd name and PVC name, which causes this problem to occur. Therefore, my opinion is to use the instance as the main object of our operation. The naming of all resources are determined by `releaseName`. `clusterName` is only used as the name of tc CRD. When installing the tidb cluster, as long as `releaseName` is the same, we think it is the same tidb cluster instance, the previous PVCs of tidb cluster instance will be reused, even if the specified `clusterName` is different from the previous tidb cluster instance. In this case, the `ownerReferences` of the resources under tc CRD may reference multiple tc CRDs object. Similar to multiple hard links to a file in the file system.

@weekface @tennix @xiaojingchen @cofyc @aylei  PTAL

**Comment by weekface** [comment]
Vote for Solution 3.

**Comment by DanielZhangQD** [comment]
Why not just use `releaseName` and discard `clusterName`?

**Comment by Yisaer** [comment]
> Why not just use `releaseName` and discard `clusterName`?

I agreed.

**Comment by onlymellb** [comment]
> Why not just use `releaseName` and discard `clusterName`?

This is solution 2 I listed above. IIRC, when using the helm to install the tidb cluster in GCP's marketplace, `releaseName` is a long random string that cannot be specified. When we use `releaseName` assembling other resource names in k8s will result in truncation (more than 63 characters and random strings will not make sense).

@tennix PTAL
