### ISSUE TITLE
Do not set --capacity to tikv-server if resources.limits.storage is not given

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#944]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, we cannot set `raftstore.capacity` in TiKV configuration.

https://github.com/pingcap/tidb-operator/blob/761daab5900d98959cd58762690bdfcce2432193/charts/tidb-cluster/values.yaml#L209

**Describe the feature you'd like:**

Do not pass TiKV default value if `resources.limits.storage` is absent. This will make it possible for users to set capacity in TiKV configuration.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

xref: https://github.com/pingcap/tidb-operator/pull/868 https://github.com/pingcap/tidb-operator/pull/942

**Comment by cofyc** [comment]
cc @weekface @tennix what do you think?

**Comment by weekface** [comment]
It's fine with me.
