### ISSUE TITLE
TidbCluster: able to restart all Pods of TidbCluster and single Pod of component

### ISSUE THREAD

**Issue by LinuxGit** [pingcap/tidb-operator#980]
## Feature Request

**Describe the feature you'd like:**

1. Able to restart all pods of tidb cluster's component sequentially
- Restart Pod of TiDB/TiKV/PD one by one, like rolling update
- Allow setting forced restart or graceful restart
- If graceful restart is set, we need to transfer PD leader、TiKV region leader and TiDB DDL Owner before restart

2. Able to restart single Pod of tidb cluster's component
- need graceful restart, we need to transfer PD leader、TiKV region leader and TiDB DDL Owner before restart

**Comment by cofyc** [comment]
@Yisaer has this been addressed?

**Comment by Yisaer** [comment]
@cofyc Mostly,yes. But I'm not familiar with the first feature request @aylei Could you give some details about the first one?

**Comment by aylei** [comment]
Yes, This has been addressed @Yisaer
