### ISSUE TITLE
Refactor controller with admission webhook

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#992]
## Feature Request

The controller uses a single thread to process an object, but the TiDB cluster operation is complicated.

For example, when upgrading TiKV, the controller needs to:
1. issue evict leader scheduler to PD,
2. wait until the to-be-upgraded TiKV leaders drop to zero or timeout,
3. upgrade the TiKV pod,
4. issue end evict leader scheduler to PD

Currently, all these logic are in the upgrader interface, this makes the controller code hard to read and maintain, especially when adding new features to the controller.

With admission webhook, the controller logic can be greatly simplified:
* the controller only needs to upgrade the TiKV statefulset
* the statefulset controller tries to delete old pod
* the webhook issue the scheduler to PD and check if leaders drop to zero or timeout
* the webhook permits the pod deletion
* when the next TiKV pod is to deleted, the webhook issues end evict leader for the previous TiKV.

The parts need to be refactored:
- [ ] TiDB upgrader
- [x] TiKV upgrader
- [x] PD upgrader
- [x] TiKV scaler
- [x] PD scaler

**Comment by Yisaer** [comment]
I would like to separete this issue into multi child tasks for each compoment(PD TiKV TiDB). For now, I'd like to assign PD task to myself.

**Comment by tennix** [comment]
Sure, just go ahead. This issue just tracks all the refactor progress.

**Comment by Yisaer** [comment]
The webhook refactor was finished by https://github.com/pingcap/tidb-operator/pull/1389 at last.
And this feature would be enabled in default in release 1.1.0. https://github.com/pingcap/tidb-operator/issues/1428
