### ISSUE TITLE
add aws cdk support

### ISSUE THREAD

**Issue by yuananf** [pingcap/tidb-operator#998]
## Feature Request

**Is your feature request related to a problem? Please describe:
aws has released its own ```code as infrastructure```: AWS Cloud Development Kit
https://github.com/aws/aws-cdk

**Describe the feature you'd like:
using aws cdk to deploy tidb cluster in aws
we have used cdk to deploy our infrastructure for months and we really love it. no exprience in eks, but it should not be hard.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:
https://github.com/aws/aws-cdk
https://github.com/aws-samples/amazon-eks-refarch-cloudformation/tree/master/cdk

**Comment by tennix** [comment]
@yuananf Hi, thank you for your suggestion! I'm not familiar with aws-cdk, but from the README it states that it generates cloud formation to provision infrastructure. The cloud formation can only be used on AWS.

We use Terraform to provision the infrastructure as code. The Terraform is a cross-cloud platform provision tool of which I think is widely used in many companies. I'm sorry that we don't have enough manpower to maintain another provisioning tool.

**Comment by gregwebs** [comment]
@yuananf if you make something here, let us know and we can look into how to share it with other users.
