### ISSUE TITLE
Generate deployment plan before creating the real resources

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#999]
## Feature Request

Terraform has an execution plan before modifying the real resources. This is a great help for ops, it can avoid dangerous actions to be executed.

However, with Kubernetes, all the APIs are asynchronous, users won't know the result until the modification is applied to Kubernetes. For example, if users create 10 Pods, they may all fail if there are not enough resources, also users won't know where the pod will be scheduled.

We can check the resources and generate the deployment plan to tell users if the deployment will be succeeded or only part of them will be succeeded. And what will be changed to the current cluster.

*ref*: [apiserver dry run](https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff/)

**Comment by gregwebs** [comment]
This can also help a lot with testing.
